import { STATS_COPY_EN, type StatsCopy } from './en';

export const STATS_COPY_UK: StatsCopy = {
  ...STATS_COPY_EN,
  title: "Пам'ять",
  subtitle: 'Сигнали, нитки й місячні форми з твого локального архіву снів.',
  monthLabel: 'Поточний локальний стан',
  rangeLabel: 'Період',
  rangeAll: 'Увесь час',
  range30Days: '30 днів',
  range7Days: '7 днів',
  memoryModeLabel: 'Розділ',
  memoryModeOverview: 'Огляд',
  memoryModeThreads: 'Повтори',
  memoryModeMonthly: 'Місяць',
  compareLabel: 'Режим',
  compareSnapshot: 'Зріз',
  compareMode: 'Порівняти',
  compareUnavailable: 'Порівняння працює для 7 або 30 днів.',
  compareCurrentPeriod: 'Поточний період',
  comparePreviousPeriod: 'Попередній період',
  compareDeltaLabel: 'до попереднього періоду',
  monthlyReportOpenButton: 'Місячний звіт',
  monthlyReportBackButton: 'Назад',
  monthlyReportEyebrow: 'Місячна рефлексія',
  monthlyReportTitle: 'Місячний звіт',
  monthlyReportSubtitle:
    'Спокійніше повернення до місяця, зібране з локального архіву без відчуття dashboard.',
  monthlyReportEmptyTitle: 'Місячного звіту ще немає',
  monthlyReportEmptyDescription:
    'Збережи кілька снів в одному місяці, і перший локальний звіт почне складатися.',
  monthlyReportLoadingTitle: 'Збираємо місячний звіт',
  monthlyReportLoadingDescription: 'Оновлюємо локальний архів за цей місяць.',
  monthlyReportMonthStripLabel: 'Місяці',
  monthlyReportSaveAction: 'Зберегти на потім',
  monthlyReportSavedAction: 'Збережено',
  monthlyReportShareAction: 'Поділитися',
  monthlyReportShareTitle: 'Місячний звіт про сни',
  monthlyReportCoverTitle: 'Цей місяць відчувався як',
  monthlyReportCoverEmpty: 'Його форма ще не встигла проявитися.',
  monthlyReportHighlightsTitle: 'Місяць у моментах',
  monthlyReportHighlightsDescription:
    'Найсильніші числа, які варто зберегти з цього місяця.',
  monthlyReportSignalsTitle: 'Що поверталося',
  monthlyReportSignalsDescription:
    'Повторювані деталі, які дали цьому місяцю власну текстуру.',
  monthlyReportGentleTitle: 'Що поглибило архів',
  monthlyReportGentleDescription:
    'Тиха структура, яка зробила цей місяць легшим для повернення.',
  monthlyReportEntriesLabel: 'Записи',
  monthlyReportWordsLabel: 'Слова',
  monthlyReportVoiceLabel: 'Голос',
  monthlyReportTranscriptLabel: 'Транскрипти',
  monthlyReportTagsLabel: 'Теги',
  monthlyReportContextLabel: 'Контекст',
  monthlyReportWakeLabel: 'Після пробудження',
  monthlyReportPreSleepLabel: 'Перед сном',
  monthlyReportThemeLabel: 'Тема',
  monthlyReportSymbolLabel: 'Символ',
  monthlyReportWordLabel: 'Фраза',
  monthlyReportRevisitTitle: 'Варто відкрити знову',
  monthlyReportRevisitDescription:
    'Один сон з цього місяця саме зараз потрапляє у вікно повернення.',
  monthlyReportOpenThreadAction: 'Відкрити нитку',
  monthlyReportSavedThreadsTitle: 'Збережені нитки',
  monthlyReportSavedThreadsDescription:
    'Нитки, які ти зберіг раніше і які все ще торкаються цього місяця.',
  monthlyReportNoSignal: 'Ще формується',
  overviewActivityTitle: 'Остання активність',
  overviewActivityDescription: 'Як часто останнім часом зберігалися сни.',
  nightmareFrequencyTitle: 'Частота кошмарів',
  nightmareFrequencyDescription:
    'Мʼякий зріз того, як часто в цьому періоді зʼявляються сни з кошмарним патерном.',
  nightmareFrequencyCountLabel: 'Записи з кошмарним патерном',
  nightmareFrequencyCountHint:
    'Сюди входять позначені кошмари та записи з виразним дистресом після пробудження.',
  nightmareFrequencyCountEmptyHint:
    'У цьому періоді немає записів з кошмарним патерном.',
  nightmareFrequencyShareLabel: 'Частка цього періоду',
  nightmareFrequencyShareHintPrefix: 'Приблизно один із ',
  nightmareFrequencyShareHintSuffix: ' снів у цьому періоді.',
  nightmareFrequencyShareEmptyHint: 'Зараз тут нічого не повторюється.',
  nightmareFrequencyLatestLabel: 'Найсвіжіший',
  nightmareFrequencyLatestHint:
    'Останній запис з кошмарним патерном у цьому періоді.',
  nightmareFrequencyLatestEmptyValue: 'Немає',
  nightmareFrequencyLatestEmptyHint:
    'У цьому періоді не було запису з кошмарним патерном.',
  lucidFrequencyTitle: 'Частота усвідомлених снів',
  lucidFrequencyDescription:
    'Як часто в цьому зрізі зʼявляється усвідомленість і який слід вона лишає в недавній історії.',
  lucidFrequencyCountLabel: 'Усвідомлені записи',
  lucidFrequencyCountHint:
    'Сюди входить коротка ясність, усвідомлені сни та записи з відчуттям контролю.',
  lucidFrequencyCountEmptyHint: 'У цьому періоді немає усвідомлених записів.',
  lucidFrequencyShareLabel: 'Частка цього періоду',
  lucidFrequencyShareHintPrefix: 'Приблизно один із ',
  lucidFrequencyShareHintSuffix: ' снів у цьому періоді.',
  lucidFrequencyShareEmptyHint:
    'У цьому періоді усвідомленість ще не повторюється.',
  lucidFrequencyLatestLabel: 'Найсвіжіший',
  lucidFrequencyLatestHint: 'Останній усвідомлений запис у цьому періоді.',
  lucidFrequencyLatestEmptyValue: 'Немає',
  lucidFrequencyLatestEmptyHint:
    'У цьому періоді не було усвідомленого запису.',
  lucidHistoryTitle: 'Недавня історія усвідомленості',
  lucidHistoryDescription:
    'Відкрий усвідомлений запис і звір, який рівень ясності там зʼявився.',
  lucidHistoryEmpty: 'У цьому зрізі ще немає усвідомлених записів.',
  lucidAwareLabel: 'Усвідомлені',
  lucidControlledLabel: 'З контролем',
  lucidTopTechniqueLabel: 'Головна техніка',
  lucidDreamSignsLabel: 'Головний dream sign',
  lucidTechniqueEmptyValue: 'Ще немає',
  lucidDreamSignsEmptyValue: 'Ще формується',
  nightmareRecurringLabel: 'Повторювані',
  nightmareHighDistressLabel: 'Високий дистрес',
  nightmareRescriptedLabel: 'Переписані',
  nightmareDerivedLabel: 'Похідні сигнали',
  nightmareDerivedHint:
    'Обережне fallback-визначення з дистресу після пробудження.',
  weeklyPatternsTitle: 'Патерни тижня',
  weeklyPatternsDescription:
    'Спокійний зріз того, що виділилося за останні сім днів.',
  overviewTopSignalLabel: 'Головний сигнал',
  overviewTopSignalEmpty: 'Ще формується',
  overviewNextStepLabel: 'Наступний крок',
  overviewNextStepEmpty: 'Нічого термінового зараз немає.',
  weeklyPatternRhythmLabel: 'Ритм',
  weeklyPatternSignalLabel: 'Свіжий сигнал',
  weeklyPatternToneLabel: 'Тон',
  weeklyPatternContextLabel: 'Контекст',
  weeklyPatternCaptureLabel: 'Запис',
  weeklyPatternQuietWeekTitle: 'Тихий тиждень',
  weeklyPatternQuietWeekHint: 'За останні сім днів нових снів не було.',
  weeklyPatternStillFormingTitle: 'Ще формується',
  weeklyPatternStillFormingHint:
    'Ще один детальніший запис зробить тиждень читабельнішим.',
  weeklyPatternContextTitle: 'Контекст зʼявлявся',
  weeklyPatternVoiceTitle: 'Тиждень схилявся до голосу',
  weeklyPatternThisWeekSuffix: 'цього тижня',
  weeklyPatternVsPreviousLabel: 'проти попередніх 7 днів',
  weeklyPatternVsPreviousFlat: 'Так само, як у попередні 7 днів',
  fingerprintTitle: 'Відбиток снів',
  fingerprintDescription:
    'Швидкий портрет сигналів, які знову повертаються в цьому зрізі.',
  fingerprintLeadLabel: 'Головні ноти',
  fingerprintEmpty:
    'Збережи ще кілька змістовніших снів, щоб відбиток усталився.',
  fingerprintThemeLabel: 'Тема',
  fingerprintSymbolLabel: 'Символ',
  fingerprintWakeLabel: 'Після пробудження',
  fingerprintPreSleepLabel: 'Перед сном',
  detailsTitle: 'Більше деталей',
  detailsDescription: 'Відкривай глибші цифри тільки коли це потрібно.',
  detailsShow: 'Показати деталі',
  detailsHide: 'Сховати деталі',
  snapshotTitle: 'Зріз архіву',
  snapshotDescription: 'Компактний зріз цієї частини архіву.',
  spotlightTitle: 'Фокус',
  spotlightDescription:
    'Найшвидший спосіб побачити, що тут найбільше виділяється.',
  memoryNudgeLabel: 'Відкрити зараз',
  memoryNudgeThemeReasonPrefix: 'Тема все ще тягне увагу: ',
  memoryNudgeThemeReasonSuffix:
    '. Відкрий один сон і звір, що досі відчувається правдою.',
  memoryNudgeWordReasonPrefix: 'Це слово знову повертається: ',
  memoryNudgeWordReasonSuffix:
    '. Відкрий один сон і подивись, що навколо нього змінилося.',
  memoryNudgeSymbolReasonPrefix: 'Цей символ знову виринає: ',
  memoryNudgeSymbolReasonSuffix:
    '. Відкрий один сон і перевір, яка деталь досі тримається.',
  memoryNudgeTimeReasonPrefix: 'Цей сон знову виринає з ',
  memoryNudgeTimeReasonSuffix:
    '. Відкрий його ще раз і подивись, яка деталь досі тримається.',
  memoryNudgeTranscriptReason:
    'Одна голосова нотатка ще чекає, щоб стати придатним текстом, поки спогад свіжий.',
  memoryNudgeThemeBadge: 'Тема',
  memoryNudgeWordBadge: 'Слово',
  memoryNudgeSymbolBadge: 'Символ',
  memoryNudgeTimeBadge: 'Час',
  memoryNudgeTranscriptBadge: 'Транскрипт',
  memoryNudgeTimeWeek: 'приблизно тижневої давності',
  memoryNudgeTimeMonth: 'приблизно місячної давності',
  memoryNudgeTimeQuarter: 'приблизно тримісячної давності',
  memoryNudgeTimeHalfYear: 'приблизно піврічної давності',
  memoryNudgeTimeYear: 'приблизно річної давності',
  memoryNudgeActionReflection: 'Відкрити сон',
  memoryNudgeActionTime: 'Повернути спогад',
  memoryNudgeActionTranscript: 'Попрацювати з транскриптом',
  takeawaysTitle: 'Швидкі висновки',
  takeawaysDescription:
    'Короткі сигнали, які можна зчитати без довгого перегляду архіву.',
  coverageTitle: 'Вже добре збережено',
  coverageDescription: 'Що тут уже легко знайти або переглянути пізніше.',
  coverageTranscriptsLabel: 'Є текст для пошуку',
  coverageTagsLabel: 'Додані теги',
  coverageContextLabel: 'Доданий контекст сну',
  coverageTranscriptsHint: 'сни вже мають транскрипт або текст',
  coverageTagsHint: 'сни вже мають прикріплені теги',
  coverageContextHint: 'сни вже мають контекст перед сном',
  attentionTitle: 'Що варто додати',
  attentionDescription: 'Невеликі кроки, які зроблять цей зріз змістовнішим.',
  attentionAudioLabel: 'Транскрибувати аудіо',
  attentionMoodLabel: 'Додати настрій',
  attentionContextLabel: 'Додати контекст',
  attentionAudioHint: 'голосові сни ще сирі',
  attentionMoodHint: 'у снах бракує настрою після пробудження',
  attentionContextHint: 'у снах бракує контексту перед сном',
  attentionAllSetHint: 'Тут зараз усе виглядає добре.',
  workQueueTitle: 'Продовжити локально',
  workQueueDescription:
    'У цьому зрізі вже є кілька конкретних наступних кроків.',
  reviewShelfTitle: 'Полиця для ревʼю',
  reviewShelfDescription:
    'Одне місце, щоб повертатися до важливих снів, збережених місяців, ниток і наступних локальних кроків.',
  reviewWorkspaceTitle: 'Простір ревʼю',
  reviewWorkspaceSubtitle:
    'Повернення до наступного локального кроку, важливого сну, збереженого місяця чи нитки в одному спокійнішому місці.',
  reviewWorkspaceOpenAction: 'Відкрити ревʼю',
  reviewWorkspaceContinueTitle: 'Продовжити локально',
  reviewWorkspaceImportantTitle: 'Важливі сни',
  reviewWorkspaceImportantDescription:
    'Позначені як важливі сни залишаються поруч, щоб задавати тон наступному колу рефлексії.',
  reviewWorkspaceSavedSetsTitle: 'Збережені набори',
  reviewWorkspaceSavedSetsDescription:
    'Збережені місяці й нитки живуть тут разом як один спокійніший шар ревʼю.',
  reviewWorkspaceSavedMonthsTitle: 'Збережені місяці',
  reviewWorkspaceSavedThreadsTitle: 'Збережені нитки',
  reviewWorkspaceSummaryContinueLabel: 'Локальні кроки',
  reviewWorkspaceSummaryImportantLabel: 'Важливі сни',
  reviewWorkspaceSummarySavedSetsLabel: 'Збережені набори',
  reviewWorkspaceEmptyTitle: 'Для ревʼю ще нічого не збережено',
  reviewWorkspaceEmptyDescription:
    'Важливі сни, збережені набори й локальні наступні кроки зʼявляться тут, коли архів трохи виросте.',
  reviewWorkspaceDreamFallbackTitle: 'Сон без назви',
  reviewShelfImportantDreamEyebrow: 'Важливий сон',
  reviewShelfContinueEyebrow: 'Продовжити локально',
  reviewShelfSavedMonthEyebrow: 'Збережений місяць',
  reviewShelfSavedThreadEyebrow: 'Збережена нитка',
  workQueueTranscriptGenerateReason:
    'Ця голосова нотатка ще чекає, щоб стати текстом для пошуку.',
  workQueueTranscriptRetryReason: 'Остання спроба транскрипції не завершилась.',
  workQueueTranscriptEditReason:
    'Згенерований транскрипт уже готовий до швидкої доробки.',
  workQueueTranscriptActionGenerate: 'Транскрибувати аудіо',
  workQueueTranscriptActionRetry: 'Повторити транскрипцію',
  workQueueTranscriptActionEdit: 'Редагувати транскрипт',
  workQueueAnalysisReason:
    'У цьому сні вже достатньо матеріалу для короткої локальної рефлексії.',
  workQueueAnalysisRetryReason:
    'Локальний аналіз минулого разу не вдався. Відкрий і спробуй ще раз.',
  workQueueAnalysisBadge: 'Аналіз',
  workQueueAnalysisActionGenerate: 'Згенерувати аналіз',
  workQueueAnalysisActionRetry: 'Оновити аналіз',
  voiceArchiveTitle: 'Голосовий архів',
  voiceArchiveDescription:
    'Скільки в архіві ще сирого аудіо, а скільки вже стало придатним текстом.',
  sleepSignalsTitle: 'Сон і настрій',
  sleepSignalsDescription:
    'Настрій, контекст перед сном і повторювані емоції в межах вибраного періоду.',
  patternsTitle: 'Повторювані сигнали',
  patternsDescription:
    'Символи, теми й повторювані фрази, відсортовані за тим, як часто вони повертаються і де саме зʼявляються.',
  patternsTrackedLabel: 'відстежуються',
  memoryThreadTitle: 'Поточна нитка',
  memoryThreadDescription:
    'Залишайся на цьому екрані й переглядай сни, пов’язані з вибраним повторюваним сигналом.',
  memoryThreadOpenAction: 'Відкрити всю нитку',
  memoryThreadClearAction: 'Закрити нитку',
  savedThreadsTitle: 'Збережені нитки',
  savedThreadsDescription:
    'Закріплені нитки лишаються тут, щоб їх можна було відкрити знову без пошуку по сигналах.',
  threadSaveAction: 'Зберегти нитку',
  threadSavedAction: 'Збережено',
  patternsTopLabel: 'Головний сигнал',
  patternsMoreLabel: 'Ще повторюються',
  recurringWordsDescription: 'У назвах, нотатках і транскриптах.',
  recurringThemesDescription: 'З тегів і мови транскриптів.',
  recurringSymbolsDescription: 'Лише з мови транскриптів.',
  preSleepEmotionsDescription:
    'Емоції, які ти найчастіше відмічаєш перед сном.',
  progressOpenButton: 'Відкрити прогрес',
  progressBackButton: 'Назад',
  progressScreenTitle: 'Прогрес',
  progressScreenSubtitle:
    'Тут видно тижневий ритм, відкриті майлстоуни і наступну ціль запису.',
  progressLoadingTitle: 'Завантажуємо прогрес',
  progressLoadingDescription: 'Оновлюємо локальні майлстоуни й тижневий ритм.',
  progressFocusTitle: 'Наступне відкриття',
  progressFocusDoneTitle: 'Усі базові майлстоуни відкриті',
  progressFocusDoneDescription:
    'Звичка запису вже зібрана. Тепер нові записи головно поглиблюють архів.',
  milestonesToggleShow: 'Показати майлстоуни',
  milestonesToggleHide: 'Сховати майлстоуни',
  currentStreak: 'Поточний стрік',
  lastSevenDays: 'Останні 7 днів',
  emptyTitle: "Пам'ять ще формується",
  emptyDescription:
    "Спочатку збережи кілька снів. Пам'ять почне автоматично пов'язувати повторювані сигнали з локального архіву.",
  readinessTitle: 'Готовність аналітики',
  readinessDescription:
    'Що більше ти додаєш настрою, тегів і контексту перед сном, то кориснішими стають ці патерни.',
  entriesWithMood: 'Записи з настроєм',
  entriesWithTags: 'Записи з тегами',
  readinessHint:
    'На малому обсязі даних патерни легко коливаються. Сприймай ранні сигнали як орієнтир, а не як висновок.',
  milestonesTitle: 'Усі майлстоуни',
  milestonesDescription:
    'Простий зріз того, що вже відкрито і що ще добудовується.',
  milestonesUnlockedLabel: 'Відкрито',
  milestonesCompleteTitle: 'Майлстоуни закрито',
  milestonesCompleteDescription:
    'Усі базові майлстоуни запису відкриті. Архів уже достатньо насичений для глибшої рефлексії.',
  milestoneHighlightLabel: 'Фокус',
  milestoneUnlocked: 'Відкрито',
  milestoneInProgress: 'У процесі',
  milestoneProgressLabel: 'Виконано / ціль',
  milestoneFirstDreamTitle: 'Перший сон збережено',
  milestoneFirstDreamDescription:
    'Збережи перший сон, щоб почати будувати корисний архів.',
  milestoneThreeDayStreakTitle: 'Три дні поспіль',
  milestoneThreeDayStreakDescription:
    'Записуй сни три дні підряд, щоб закріпити звичку.',
  milestoneTenDreamsTitle: '10 збережених снів',
  milestoneTenDreamsDescription:
    'Дійди до десяти збережених снів, щоб тренди й повторювані теми стали помітнішими.',
  milestoneFirstVoiceDreamTitle: 'Перший голосовий сон',
  milestoneFirstVoiceDreamDescription:
    'Збережи хоча б один сон з аудіо, щоб не втратити оригінальний спогад.',
  weeklyGoalTitle: 'Ціль на тиждень',
  weeklyGoalDescription:
    'Спробуй дійти до трьох записів за останні сім днів, щоб не втрачати ритм.',
  weeklyGoalStatusDone: 'Рух хороший',
  weeklyGoalStatusPending: 'Продовжуй',
  weeklyGoalProgressLabel: 'Записів за тиждень',
  weeklyGoalTargetLabel: 'Ціль',
  journalVolume: 'Обсяг щоденника',
  entries: 'Записи',
  wordsSaved: 'Збережено слів',
  averageWords: 'Середньо слів',
  averageWordsShort: 'Сер. слів',
  entryStructure: 'Структура записів',
  voiceNotes: 'Голосові нотатки',
  transcribedDreams: 'Транскрибовані сни',
  generatedTranscripts: 'Згенеровані транскрипти',
  editedTranscripts: 'Відредаговані транскрипти',
  audioOnlyDreams: 'Сни лише з аудіо',
  taggedDreams: 'Записи з тегами',
  emotionPatterns: 'Патерни емоцій',
  wakeEmotions: 'Після пробудження',
  preSleepEmotions: 'Перед сном',
  emotionPatternsEmpty:
    'Додай емоції після пробудження і перед сном, щоб бачити, які відчуття повторюються.',
  moodBreakdown: 'Розподіл настрою',
  moodBreakdownEmpty:
    'Додай настрій після пробудження, щоб тут зʼявився розподіл.',
  sleepContextBreakdown: 'Фактори перед сном',
  sleepContextEmpty:
    'Додай контекст перед сном, щоб тут порівнювати стрес, кофеїн та інші сигнали.',
  entriesWithContext: 'Записи з контекстом',
  entriesWithoutMood: 'Записи без настрою',
  entriesWithoutContext: 'Записи без контексту',
  averageStressLevel: 'Середній стрес',
  alcoholBeforeSleep: 'Алкоголь перед сном',
  lateCaffeine: 'Пізній кофеїн',
  medicationsNoted: 'Вказані препарати',
  importantEventsNoted: 'Вказані важливі події',
  healthNotesNoted: 'Нотатки про здоровʼя',
  moodSignalTitle: 'Сигнали настрою (експериментально)',
  moodSignalEmpty:
    'Сигнали настрою зʼявляться, коли ти поєднаєш настрій і контекст перед сном у тих самих записах.',
  negativeMoodRate: 'Частка негативного настрою',
  negativeWithAlcohol: 'Негатив після алкоголю',
  negativeWithoutAlcohol: 'Негатив без алкоголю',
  negativeWithLateCaffeine: 'Негатив після пізнього кофеїну',
  negativeWithoutLateCaffeine: 'Негатив без пізнього кофеїну',
  negativeWithHighStress: 'Негатив при високому стресі',
  negativeWithLowStress: 'Негатив при низькому стресі',
  noData: 'Немає даних',
  recurringThemes: 'Теми',
  recurringThemesEmpty: 'Додай теги, щоб тут зʼявлялися повторювані теми.',
  recurringWords: 'Слова',
  recurringWordsEmpty:
    'Збережи кілька змістовніших нотаток або транскриптів, щоб тут зʼявились повторювані слова.',
  recurringSymbols: 'Символи',
  recurringSymbolsEmpty:
    'Транскрибуй кілька голосових снів, щоб тут зʼявилися повторювані символи з тексту транскриптів.',
  patternDetailEyebrow: 'Деталь патерну',
  patternDetailMatchesTitle: 'Сни зі збігом',
  patternDetailMatchesSingle: 'сон',
  patternDetailMatchesPlural: 'снів',
  patternDetailMatchedIn: 'Збіг у',
  patternDetailWordLabel: 'Повторюване слово',
  patternDetailThemeLabel: 'Повторювана тема',
  patternDetailSymbolLabel: 'Повторюваний символ',
  patternDetailWordDescription:
    'Це слово знову зʼявляється в заголовках, нотатках або транскриптах.',
  patternDetailThemeDescription:
    'Цей сигнал повертається через теги або мову транскриптів.',
  patternDetailSymbolDescription:
    'Цей символ повторюється всередині збережених транскриптів.',
  threadDetailEyebrow: 'Нитка сну',
  threadDetailCountLabel: 'Збіги',
  threadDetailFirstSeenLabel: 'Вперше',
  threadDetailLatestSeenLabel: 'Останній',
  threadDetailSourceLabel: 'Головне джерело',
  threadDetailTimelineTitle: 'Послідовність',
  threadDetailEntryFirst: 'Початок',
  threadDetailEntryLatest: 'Останній',
  threadDetailEntryOnly: 'Єдиний збіг',
  threadDetailMentionSingle: 'згадка',
  threadDetailMentionPlural: 'згадок',
  threadDetailMentionPluralUkFew: 'згадки',
  patternDetailSourceTag: 'Тег',
  patternDetailSourceTitle: 'Заголовок',
  patternDetailSourceText: 'Нотатки',
  patternDetailSourceTranscript: 'Транскрипт',
  patternDetailEmptyTitle: 'Збігів не знайдено',
  patternDetailEmptyDescription:
    'Цей сигнал більше не присутній у поточному зрізі архіву.',
  takeawayWordsLabel: 'Слова',
  takeawayThemesLabel: 'Теми',
  takeawayGapsLabel: 'Що ще доповнити',
  takeawayWordsEmpty: 'Поки замало повторюваних слів.',
  takeawayThemesEmpty: 'Тегів ще недостатньо для чіткої теми.',
  takeawayGapsEmpty: 'Цей зріз уже заповнений досить добре.',
  takeawayGapAudioOnly: 'Аудіо без транскрипту',
  takeawayGapMood: 'Записи без настрою',
  takeawayGapContext: 'Записи без контексту',
  localReflectionTitle: 'Локальна рефлексія',
  localReflectionDescription:
    'Повторювані сигнали витягуються лише з твоїх збережених тегів і транскриптів на пристрої.',
  reflectionThemeCountLabel: 'снів',
  reflectionSourceTag: 'Тег',
  reflectionSourceTranscript: 'Транскрипт',
  reflectionSourceMixed: 'Тег + транскрипт',
  bright: 'Світлий',
  calm: 'Спокійний',
  heavy: 'Важкий',
  milestoneFiftyDreamsTitle: '50 збережених снів',
  milestoneFiftyDreamsDescription:
    'Пʼятдесят записів в архіві. Патерни поглиблюються.',
  milestoneHundredDreamsTitle: '100 збережених снів',
  milestoneHundredDreamsDescription:
    'Сотня запамʼятованих ночей. Справжній архів.',
  streakMilestoneThreeDaysTitle: 'Три дні поспіль',
  streakMilestoneThreeDaysSubtitle:
    'Звичка починає формуватися. Підтримуй тепло.',
  streakMilestoneSevenDaysTitle: 'Сім днів снів',
  streakMilestoneSevenDaysSubtitle:
    'Повний тиждень. Архів вже починає памʼятати.',
  streakMilestoneFourteenDaysTitle: 'Два тижні',
  streakMilestoneFourteenDaysSubtitle:
    'Чотирнадцять днів. Щось справжнє будується.',
  streakMilestoneThirtyDaysTitle: 'Тридцять ночей',
  streakMilestoneThirtyDaysSubtitle:
    'Повний місяць снів. Патерни починають проявлятися.',
  emotionalTrendTitle: 'Емоційна дуга',
  emotionalTrendDescription: 'Як настрій твоїх снів змінювався з часом.',
  emotionalTrendEmptyLabel:
    'Додай настрій до кількох снів, щоб дуга почала проявлятися.',
  emotionalTrendArcPositive: 'Переважно спокійний і світлий за цей період.',
  emotionalTrendArcNeutral: 'Рівний, збалансований рух — без різких перепадів.',
  emotionalTrendArcNegative: 'Важчий відрізок. Варто побути з ним трохи довше.',
  emotionalTrendArcMixed: 'Змішана дуга — коливається між світлим і важким.',
  patternGroupHighFrequencyLabel: 'Повторюваний',
};
