export const DREAM_COPY_EN = {
  homeTitle: 'Dream log',
  homeSubtitle: 'Capture quickly. Revisit patterns later.',
  homeGreeting: 'Good morning',
  homeGreetingMorning: 'Good morning',
  homeGreetingAfternoon: 'Good afternoon',
  homeGreetingEvening: 'Good evening',
  homeGreetingNight: 'Still awake?',
  homeRecordNow: 'Record now',
  homeContinueDraft: 'Continue draft',
  homeDraftShortcutHint: 'Your unfinished capture is waiting.',
  homeLastDreamLabel: 'Return to last dream',
  homeLastDreamMetaPrefix: 'Last open',
  homeSectionLabel: 'Recent dreams',
  homeCustomizeAction: 'Customize',
  homeCustomizeTitle: 'Customize Home',
  homeCustomizeDone: 'Done',
  homeCustomizeReset: 'Reset',
  homeCustomizePresetLabel: 'Emphasis',
  homeCustomizePresetHint:
    'Choose a calmer or more insight-heavy Home without changing anything outside this screen.',
  homeCustomizePresetBalanced: 'Balanced',
  homeCustomizePresetCalm: 'Calm',
  homeCustomizePresetInsight: 'Insight',
  homeCustomizeSectionsLabel: 'Visible sections',
  homeCustomizeSectionsHint:
    'Show or hide the modules above your recent dreams.',
  homeCustomizeOrderLabel: 'Section order',
  homeCustomizeOrderHint: 'Move the modules you want to notice first.',
  homeCustomizeSectionShortcuts: 'Shortcuts',
  homeCustomizeSectionSpotlight: 'In focus',
  homeCustomizeSectionWeeklyPatterns: 'Weekly patterns',
  homeCustomizeVisibleLabel: 'Visible',
  homeCustomizeHiddenLabel: 'Hidden',
  homeOpenArchive: 'Archive',
  homeRecentLimitHint:
    'Home stays focused on the latest dreams. Switch to the Archive tab for the full history.',
  homeSpotlightTitle: 'In focus',
  homeSpotlightPatternLabel: 'Pattern',
  homeSpotlightWeeklyLabel: 'This week',
  homeSpotlightAttentionLabel: 'Needs attention',
  homeSpotlightNoPattern: 'Still forming',
  homeSpotlightAttentionClear: 'All clear',
  homeSpotlightWeeklyOnTrack: 'Warm streak',
  homeSpotlightWeeklyOffTrack: 'One more helps',
  homeSpotlightAttentionAudioSingle: '1 voice note',
  homeSpotlightAttentionAudioPlural: 'voice notes',
  homeSpotlightAttentionMoodSingle: '1 dream missing mood',
  homeSpotlightAttentionMoodPlural: 'dreams missing mood',
  homeSpotlightAttentionAudioHint:
    'Transcripts would make them easier to revisit.',
  homeSpotlightAttentionMoodHint:
    'A quick wake mood would make patterns clearer later.',
  homeSpotlightAttentionClearHint: 'Nothing obvious needs cleanup right now.',
  homeSpotlightRevisitLabel: 'Revisit now',
  homeSpotlightRevisitAction: 'Open dream',
  homeSpotlightRevisitActionThread: 'Open thread',
  homeSpotlightRevisitActionAnalysis: 'Review reflection',
  homeSpotlightRevisitActionTranscript: 'Clean transcript',
  homeSpotlightRevisitActionTime: 'Reopen memory',
  homeSpotlightRevisitEmpty: 'No older dream is asking for attention yet.',
  homeSpotlightRevisitContextThread: 'Thread nearby',
  homeSpotlightRevisitContextAnalysis: 'Reflection ready',
  homeSpotlightRevisitContextTranscript: 'Transcript ready',
  homeSpotlightRevisitContextTime: 'Time marker',
  homeSpotlightRevisitContextSignal: 'Signal worth naming',
  homeSpotlightRevisitReasonThreadPrefix: 'Thread with ',
  homeSpotlightRevisitReasonThreadSuffix: ' nearby dreams',
  homeSpotlightRevisitReasonAnalysis: 'Has a saved reflection to test again',
  homeSpotlightRevisitReasonTranscript: 'Transcript is ready for cleanup',
  homeSpotlightRevisitReasonTimePrefix: 'Resurfacing from ',
  homeSpotlightRevisitReasonTimeSuffix:
    ' and worth reopening before it fades again.',
  homeSpotlightRevisitTimeWeek: 'about a week ago',
  homeSpotlightRevisitTimeMonth: 'about a month ago',
  homeSpotlightRevisitTimeQuarter: 'about three months ago',
  homeSpotlightRevisitTimeHalfYear: 'about six months ago',
  homeSpotlightRevisitTimeYear: 'about a year ago',
  homeSpotlightRevisitReasonSignal: 'Still carries a clear signal worth naming',
  homeSpotlightShowDetails: 'More details',
  homeSpotlightHideDetails: 'Less details',
  homeWeeklyPatternsTitle: 'Weekly patterns',
  homeStreakLabel: 'Streak',
  homeTotalLabel: 'Total',
  homeAverageLabel: 'Avg words',
  weeklyPatternRhythmLabel: 'Rhythm',
  weeklyPatternSignalLabel: 'Recent signal',
  weeklyPatternToneLabel: 'Tone',
  weeklyPatternContextLabel: 'Context',
  weeklyPatternCaptureLabel: 'Capture',
  weeklyPatternQuietWeekTitle: 'Quiet week',
  weeklyPatternQuietWeekHint: 'No dreams landed in the last seven days.',
  weeklyPatternStillFormingTitle: 'Still forming',
  weeklyPatternStillFormingHint:
    'One more detailed entry will make the week easier to read.',
  weeklyPatternContextTitle: 'Context showed up',
  weeklyPatternVoiceTitle: 'Voice leaning',
  weeklyPatternThisWeekSuffix: 'this week',
  weeklyPatternVsPreviousLabel: 'vs previous 7 days',
  weeklyPatternVsPreviousFlat: 'Same as previous 7 days',
  homeDaysUnit: 'days',
  homeFilterAll: 'All',
  homeFilterActive: 'Current',
  homeFilterArchived: 'Archived',
  homeFilterStarred: 'Important',
  homeArchiveFilterLabel: 'Status',
  homeSearchLabel: 'Search dreams',
  homeSearchPlaceholder: 'Title, notes, transcript, or tag',
  homeSaveSearchPreset: 'Save search',
  homeSearchShowDetails: 'Saved searches',
  homeSearchHideDetails: 'Hide saved',
  homeSavedSearchesLabel: 'Saved searches',
  homeSearchPresetFallback: 'Quick search',
  homeSearchPresetRemove: 'Remove saved search',
  homeSearchPresetDeleteTitle: 'Remove this saved search?',
  homeSearchPresetDeleteDescription:
    'This removes the saved filter combination, but your dreams stay untouched.',
  homeSearchMatchTitle: 'Title',
  homeSearchMatchNotes: 'Notes',
  homeSearchMatchTranscript: 'Transcript',
  homeSearchMatchTag: 'Tag',
  homeSearchMatchContext: 'Context',
  homeClearSearch: 'Clear search',
  homeRefineLabel: 'Refine timeline',
  homeQuickFiltersLabel: 'Quick filters',
  homeAllFilters: 'All filters',
  homeMoreFilters: 'More filters',
  homeLessFilters: 'Less filters',
  homeShowFilters: 'Filters',
  homeHideFilters: 'Hide filters',
  homeMoodFilterLabel: 'Mood',
  homeMoodFilterAll: 'Any mood',
  homeTypeFilterLabel: 'Entry type',
  homeTypeFilterAll: 'Any type',
  homeTypeFilterText: 'Text',
  homeTypeFilterAudio: 'Audio',
  homeTypeFilterMixed: 'Mixed',
  homeTranscriptFilterLabel: 'Transcript',
  homeTranscriptFilterAll: 'Any transcript state',
  homeTranscriptFilterWithTranscript: 'Has transcript',
  homeTranscriptFilterAudioOnly: 'Audio only',
  homeTranscriptFilterEdited: 'Edited transcript',
  homeDateRangeFilterLabel: 'Date range',
  homeDateRangeAll: 'Any time',
  homeDateRange7d: 'Last 7 days',
  homeDateRange30d: 'Last 30 days',
  homeDateRange90d: 'Last 90 days',
  homeSortFilterLabel: 'Sort',
  homeSortFilterNewest: 'Newest first',
  homeSortFilterOldest: 'Oldest first',
  homeTagFilterLabel: 'Tags',
  homeTagSearchPlaceholder: 'Search tags',
  homeTagSelectedLabel: 'Selected tags',
  homeTagsShowMore: 'Show all tags',
  homeTagsShowLess: 'Show fewer',
  homeTagsEmpty: 'No tags match this search.',
  homeClearFilters: 'Clear filters',
  homeResultsSingle: 'entry',
  homeResultsPlural: 'entries',
  homeSearchEmptyTitle: 'Nothing matches these filters',
  homeSearchEmptyDescription:
    'Try a simpler phrase, switch filters, or clear them to see more dreams.',
  homeQuickOpen: 'Open',
  actionRetry: 'Retry',
  clearErrorAction: 'Dismiss',
  timelineLoadingTitle: 'Loading timeline',
  timelineLoadingDescription: 'Refreshing local entries...',
  timelineErrorTitle: 'Could not load timeline',
  timelineErrorDescription:
    'Try again. Local storage may be temporarily unavailable.',
  openDreamHint: 'Tap to open. Hold for quick actions.',
  swipeEdit: 'Edit',
  swipeDelete: 'Delete',
  swipeArchive: 'Archive',
  swipeUnarchive: 'Unarchive',
  emptyTitle: 'Your first dream is waiting',
  emptyDescription:
    'Write it before it fades — a fragment, a feeling, or a single image is enough.',
  emptyActiveTitle: 'No active dreams',
  emptyActiveDescription:
    'All entries are archived right now. Switch filter or record a new dream.',
  emptyArchivedTitle: 'No archived dreams',
  emptyArchivedDescription:
    'Archive older entries to keep the timeline focused.',
  archiveTitle: 'Archive',
  archiveSubtitle: 'Browse past dreams month by month.',
  archiveSearchPlaceholder: 'Search current month',
  archiveSearchScopeHint: 'Search applies only to the current month.',
  archiveResetView: 'Reset view',
  archiveCalendarTitle: 'Calendar',
  archiveCalendarSubtitle: 'Jump by month or tap a day with dreams.',
  archiveCalendarShowGrid: 'Show days',
  archiveCalendarHideGrid: 'Hide days',
  archiveBrowseLabel: 'View',
  archiveMonthEntriesLabel: 'entries',
  archiveMonthActiveDaysLabel: 'active days',
  archivePreviousMonth: 'Older',
  archiveNextMonth: 'Newer',
  archiveAllDates: 'All dates',
  archiveSelectedDatePrefix: 'Selected',
  archiveWeekdaySun: 'Su',
  archiveWeekdayMon: 'Mo',
  archiveWeekdayTue: 'Tu',
  archiveWeekdayWed: 'We',
  archiveWeekdayThu: 'Th',
  archiveWeekdayFri: 'Fr',
  archiveWeekdaySat: 'Sa',
  archiveEmptyTitle: 'Archive is empty',
  archiveEmptyDescription:
    'Save a few dreams first, then the archive will start grouping them here.',
  archiveEmptyCurrentTitle: 'No open dreams',
  archiveEmptyCurrentDescription:
    'Everything in this month is already filed away or filtered out.',
  archiveEmptyArchivedTitle: 'Nothing filed away yet',
  archiveEmptyArchivedDescription:
    'Archive a few older dreams and they will start showing up here.',
  archiveEmptyImportantTitle: 'No important dreams yet',
  archiveEmptyImportantDescription:
    'Mark a few dreams as important to keep them easy to revisit later.',
  archiveNoResultsTitle: 'Nothing matches this archive view',
  archiveNoResultsDescription:
    'Try another month, clear the day, or reset the current search and filters.',
  archiveFilterAll: 'Everything',
  archiveFilterActive: 'Open',
  archiveFilterArchived: 'Past',
  archiveFilterStarred: 'Important',
  archiveTagsLabel: 'Symbols',
  untitled: 'Untitled dream',
  archivedTag: 'Archived',
  starredTag: 'Important',
  audioTag: 'Audio',
  transcriptTag: 'Transcript',
  editedTranscriptTag: 'Edited',
  transcriptPreviewPrefix: 'Transcript',
  editedTranscriptPreviewPrefix: 'Edited transcript',
  audioOnlyPreview: 'Voice note saved. Transcript can be added later.',
  noDetailsPreview: 'No written details yet.',
  detailBack: 'Back',
  detailEdit: 'Edit dream',
  detailStar: 'Mark important',
  detailUnstar: 'Remove important',
  detailArchive: 'Archive dream',
  detailUnarchive: 'Unarchive dream',
  detailDelete: 'Delete dream',
  detailDeleteTitle: 'Delete this dream?',
  detailDeleteDescription:
    'This action removes the entry from local storage and cannot be undone.',
  detailDeleteCancel: 'Cancel',
  detailDeleteConfirm: 'Delete',
  detailMissingTitle: 'Dream not found',
  detailMissingDescription:
    'This entry is no longer available in local storage.',
  detailMetaTitle: 'At a glance',
  detailCapturedLabel: 'Captured',
  detailPreviewLabel: 'Preview',
  detailActionEdit: 'Edit',
  detailActionImportant: 'Important',
  detailActionArchive: 'Archive',
  detailActionRestore: 'Restore',
  detailActionDelete: 'Delete',
  detailSavedTitle: 'Dream captured',
  detailSavedDescription: 'The raw note is safe. Refine it later if needed.',
  detailSavedPatternLabel: 'Strongest signal',
  detailSavedRelatedLabel: 'Related dreams',
  detailReflectionTitle: 'Revisit now',
  detailReflectionSignalTitle: 'Name the signal',
  detailReflectionSignalPrefix: 'This dream keeps pointing to ',
  detailReflectionSignalSuffix:
    '. Add one line about why that signal matters right now.',
  detailReflectionEmotionTitle: 'Catch the feeling',
  detailReflectionEmotionWithMoodPrefix:
    'The emotional tone still leans toward ',
  detailReflectionEmotionWithMoodSuffix:
    '. Write what stayed in your body after waking.',
  detailReflectionEmotionBody:
    'Write what feeling stayed in your body after waking, even if it only lasted a few seconds.',
  detailReflectionThreadTitle: 'Follow the thread',
  detailReflectionThreadPrefix: 'This dream already touches ',
  detailReflectionThreadSuffix:
    '. Open one nearby dream and note what repeats or shifts.',
  detailReflectionAnalysisTitle: 'Test the meaning',
  detailReflectionAnalysisPrefix: 'Your saved summary points to: ',
  detailReflectionAnalysisSuffix: ' Decide whether that still feels true.',
  detailReflectionTranscriptTitle: 'Make the transcript usable',
  detailReflectionTranscriptBody:
    'One quick cleanup pass will make this voice memory easier to search and revisit later.',
  detailReflectionResurfaceTitle: 'What still holds now',
  detailReflectionResurfacePrefix: 'This dream is resurfacing from ',
  detailReflectionResurfaceSuffix:
    '. Add one line about what still feels true now.',
  detailReflectionCaptureTitle: 'Keep one vivid detail',
  detailReflectionCaptureBody:
    'Add one concrete image, place, or sentence that your future self will still understand in a week.',
  detailReflectionFallbackTitle: 'Leave a trace for later',
  detailReflectionFallbackBody:
    'Add one short note your future self would thank you for.',
  detailReflectionActionEdit: 'Add detail',
  detailReflectionActionRelated: 'Open thread',
  detailReflectionActionAnalysis: 'Review analysis',
  detailCaptureTitle: 'Capture',
  detailCaptureEmpty: 'This dream has not been filled with text or audio yet.',
  detailTranscriptTitle: 'Written notes',
  detailTranscriptEmpty: 'No written notes saved for this dream yet.',
  detailGlanceCaptureLabel: 'Entry',
  detailGlanceTranscriptLabel: 'Transcript',
  detailGlanceAnalysisLabel: 'Analysis',
  detailGlanceRelatedLabel: 'Related',
  detailCaptureModeText: 'Note',
  detailCaptureModeVoice: 'Voice',
  detailCaptureModeMixed: 'Mixed',
  detailTranscriptSummaryIdle: 'None',
  detailTranscriptSummaryReady: 'Ready',
  detailTranscriptSummaryEdited: 'Edited',
  detailTranscriptSummaryProcessing: 'Working',
  detailTranscriptSummaryError: 'Retry',
  detailGeneratedTranscriptTitle: 'Generated transcript',
  detailGeneratedTranscriptEmpty:
    'No transcript has been generated from this voice note yet.',
  detailGeneratedTranscriptHint:
    'Transcription runs on device and keeps the original voice note untouched.',
  detailGeneratedTranscriptProcessing:
    'Transcription is running locally on this device. Keep the app open until it finishes.',
  detailGeneratedTranscriptError:
    'The last transcription attempt did not finish. The original voice note is still saved.',
  detailGeneratedTranscriptReplaceError:
    'The latest replace attempt failed. The previous transcript is still saved locally.',
  detailGeneratedTranscriptSourceLabel: 'Source',
  detailGeneratedTranscriptSourceGenerated: 'Generated from audio',
  detailGeneratedTranscriptSourceEdited: 'Edited by hand',
  detailGeneratedTranscriptUpdatedLabel: 'Updated',
  detailGeneratedTranscriptEdit: 'Edit transcript',
  detailGeneratedTranscriptSave: 'Save transcript',
  detailGeneratedTranscriptCancel: 'Cancel editing',
  detailGeneratedTranscriptClear: 'Clear transcript',
  detailGeneratedTranscriptReplace: 'Replace transcript',
  detailGeneratedTranscriptEmptyErrorTitle: 'Transcript is empty',
  detailGeneratedTranscriptEmptyErrorDescription:
    'Write at least one line before saving, or clear the transcript instead.',
  detailGeneratedTranscriptSaveSuccessTitle: 'Transcript updated',
  detailGeneratedTranscriptSaveSuccessDescription:
    'The edited transcript is saved locally and remains searchable.',
  detailGeneratedTranscriptClearTitle: 'Clear transcript?',
  detailGeneratedTranscriptClearDescription:
    'This removes the saved transcript but keeps the original voice note on device.',
  detailAnalysisTitle: 'Dream analysis',
  detailAnalysisEmpty:
    'No analysis is saved for this dream yet. Generate one to turn this entry into a short local reflection.',
  detailAnalysisDisabled:
    'The analysis layer is disabled in Settings, so this dream stays as raw capture only.',
  detailAnalysisSummaryLabel: 'Summary',
  detailAnalysisThemesLabel: 'Themes',
  detailAnalysisStateLabel: 'Analysis mode',
  detailAnalysisStateLocalReady:
    'Local analysis is on and ready for this dream.',
  detailAnalysisStateDisabled:
    'Analysis is off. Enable it in Settings when you want summaries and themes.',
  detailAnalysisStateOpenAiPlanned:
    'OpenAI is selected in Settings, but network analysis is still a planned path in this release.',
  detailAnalysisStateManual:
    'This dream can generate a local summary from saved text, transcript, tags, and context.',
  detailAnalysisProviderLabel: 'Provider',
  detailAnalysisUpdatedLabel: 'Updated',
  detailAnalysisStatusLabel: 'Status',
  detailAnalysisStatusReady: 'Ready',
  detailAnalysisStatusError: 'Error',
  detailAnalysisStatusIdle: 'Not generated',
  detailAnalysisSummaryReady: 'Ready',
  detailAnalysisSummaryIdle: 'None',
  detailAnalysisSummaryDisabled: 'Off',
  detailAnalysisSummaryPlanned: 'Plan',
  detailAnalysisProviderManual: 'Local',
  detailAnalysisProviderOpenAi: 'OpenAI (planned)',
  detailAnalysisGenerate: 'Generate analysis',
  detailAnalysisRegenerate: 'Regenerate analysis',
  detailAnalysisClear: 'Clear analysis',
  detailAnalysisGenerating: 'Generating local analysis...',
  detailAnalysisOpenSettings: 'Open Settings',
  detailAnalysisOpenAiUnavailable:
    'The OpenAI provider is configured in Settings, but it is still a planned path in this release.',
  detailAnalysisErrorTitle: 'Analysis failed',
  detailAnalysisGenerateErrorDescription:
    'The dream is still saved locally. Try the manual provider or keep this slot empty for now.',
  detailTranscribeAudio: 'Transcribe audio',
  detailTranscribeRetry: 'Retry transcription',
  detailTranscribePreparingModel: 'Preparing offline model',
  detailTranscribeInProgress: 'Transcribing on device',
  detailTranscriptionErrorTitle: 'Transcription failed',
  detailTranscriptionErrorDescription:
    'The voice note is still saved locally. Try again in a quieter moment or after the model finishes downloading.',
  detailTranscriptSyncLocal:
    'This saved transcript is newer on this device and may not have reached your other device yet.',
  detailTranscriptSyncing:
    'This saved transcript is still moving through sync. Give it a moment before checking another device.',
  detailTranscriptSyncError:
    'This saved transcript is still safe on this device, but the last sync did not finish.',
  detailAudioSyncLocal:
    'This voice note is still saved only on this device until backup catches up.',
  detailAudioSyncing:
    'This voice note is still moving through backup. Give it a moment before checking another device.',
  detailAudioSyncError:
    'This voice note is still safe on this device, but the last backup sync did not finish.',
  detailTagsEmpty: 'No tags attached yet.',
  detailRelatedTitle: 'Nearby dreams',
  detailRelatedDescription:
    'Earlier dreams linked by shared signals, repeated words, and emotional echoes.',
  detailRelatedEmpty:
    'Save a few more dreams and the first clear thread will start taking shape.',
  detailRelatedSummaryEmpty: 'None',
  detailRelatedMatchSingular: 'match',
  detailRelatedMatchPlural: 'matches',
  detailRelatedSharedLabel: 'Thread signals',
  detailRelatedRecurringLabel: 'Seen before',
  detailStateTitle: 'Dream state',
  detailStateEmpty:
    'No lucid state, wake-up emotions, or pre-sleep context were saved for this dream.',
  detailLucidPracticeEmpty: 'No lucid practice was logged for this dream.',
  detailLucidityLabel: 'Lucid state',
  detailAudioDescription: 'An original voice note is attached to this dream.',
  detailAudioPathLabel: 'Local file',
  detailAudioPlay: 'Play voice note',
  detailAudioStop: 'Stop playback',
  detailAudioPlaybackHint:
    'Listen back to verify the original capture is still usable.',
  detailAudioPlaybackErrorTitle: 'Playback error',
  detailAudioAttachedMeta: 'Attached',
  detailAudioCloudOnlyHint:
    'This voice note is stored in the cloud. Download it to play it back on this device.',
  detailAudioDownload: 'Download voice note',
  detailAudioDownloading: 'Downloading…',
  detailAudioDownloadErrorTitle: 'Download failed',
  createTitle: 'Capture a dream',
  createSubtitle: 'Capture the shape now. Sort the details later.',
  quickAddKicker: 'Quick add',
  quickAddWakeAction: 'Wake capture',
  quickAddWakeHint:
    'Open the compressed morning flow for a quick voice or text capture.',
  quickAddVoiceAction: 'Voice note',
  quickAddVoiceHint:
    'Open the composer in voice-first mode and start recording fast.',
  quickAddTextAction: 'Write note',
  quickAddTextHint: 'Open the composer and type what is still there.',
  quickAddContinueHint:
    'Pick up the saved local draft exactly where you left it.',
  wakeEntryKicker: 'Wake flow',
  wakeEntryTitle: 'Before it slips away',
  wakeEntryDescription:
    'One calm screen after the reminder. Tap the center to write, or choose voice below.',
  wakeEntryOrbAction: 'Write',
  wakeEntryOrbHint: 'Tap the center and start with raw lines.',
  wakeEntryWriteAction: 'Write now',
  wakeEntryAlternateTitle: 'Other ways to capture',
  wakeEntrySpeakAction: 'Speak instead',
  wakeEntrySpeakHint: 'Start with voice if speaking is faster than typing.',
  wakeEntryDraftAction: 'Continue draft',
  wakeEntryDraftHint: 'Pick up the unfinished capture already saved locally.',
  wakeModeChip: 'Wake mode',
  wakeHeroTitle: 'Catch the first shape',
  wakeHeroDescription:
    'Voice first, raw lines second. Title, tags, and context can wait.',
  wakeCaptureTitle: 'Voice or raw lines',
  wakeCaptureDescription:
    'Start with the fastest thing that is still alive: a voice note, a few words, or both.',
  wakeCaptureAlternateTitle: 'Or record instead',
  wakeCaptureVoiceHint:
    'Use voice if speaking is faster than typing right now.',
  wakeVoiceDescription: 'Start recording now or drop a few raw lines below.',
  wakeCoreTitle: 'Raw memory',
  wakeCoreDescription:
    'Keep only what is still vivid. Structure can come later.',
  wakeTextLabel: 'What is still here?',
  wakeTextPlaceholder: 'A place, a face, a feeling, a line...',
  wakeRefineTitle: 'Add later if it helps',
  wakeRefineDescription:
    'Keep wake capture light. Title, tags, and before-sleep context are still here when you need them.',
  wakeRefineMetaAction: 'Title + date',
  wakeMetaTitle: 'Title and sleep date',
  wakeMetaDescription: 'Only add these now if they help anchor the memory.',
  wakeReadyHint:
    'A voice note, a few raw lines, and a waking feeling are enough to save.',
  createHeroTitle: 'Capture before it fades',
  createHeroDescription: 'Start with voice or a few raw lines.',
  recordEmptyTitle: 'Start with a quick capture',
  recordEmptyDescription: 'Start with text or voice. Everything else can wait.',
  recordDraftRestoredTitle: 'Draft restored',
  recordDraftRestoredDescription:
    'Your unfinished capture is still here. Keep writing or save it when ready.',
  recordDraftStartFreshAction: 'Start fresh',
  recordLoadingTitle: 'Working on it',
  recordLoadingDescription: 'Please wait while the action is completing.',
  recordErrorTitle: 'Action failed',
  recordErrorDescription:
    'Try again or continue with text-only capture for now.',
  refineTitle: 'Refine later',
  refineDescription:
    'Mood, context, and tags can stay lightweight. Add them only if they help.',
  refineReadyHint: 'A raw text or voice capture is enough to save.',
  refineMoodAction: 'Mood',
  refineContextAction: 'Before sleep',
  refineTagsAction: 'Tags',
  refineHideAction: 'Hide',
  editTitle: 'Edit dream',
  editSubtitle: 'Refine the memory without losing the original entry.',
  editHeroTitle: 'Polish the memory',
  editHeroDescription:
    'Update details while the dream is still meaningful, without losing the original entry.',
  coreTitle: 'Core details',
  coreDescription: 'Title is optional. Capture the core memory first.',
  titleLabel: 'Dream title',
  titlePlaceholder: 'Flying over old rooftops',
  sleepDateLabel: 'Sleep date',
  sleepDatePlaceholder: 'YYYY-MM-DD',
  sleepDateInvalidTitle: 'Invalid sleep date',
  sleepDateInvalidDescription:
    'Use format YYYY-MM-DD and a real calendar date.',
  textLabel: 'What do you remember?',
  textPlaceholder: 'Write the dream while it is still fresh...',
  wordsUnit: 'words',
  moodTitle: 'Mood after waking',
  moodDescription: 'What tone did the dream leave behind?',
  moodIntensityLabel: 'Vividness',
  moodIntensityHint: 'How vivid or intense was this dream?',
  lucidityLabel: 'Lucidity',
  lucidityHint: 'Did you realize you were dreaming, even for a moment?',
  lucidityNoneLabel: 'Not lucid',
  lucidityBriefLabel: 'Briefly aware',
  lucidityAwareLabel: 'Lucid',
  lucidityControlLabel: 'Lucid + in control',
  wakeEmotionsTitle: 'Emotions after waking',
  wakeEmotionsDescription:
    'Quick signals from the first minute after waking, before the dream starts to flatten out.',
  sleepContextTitle: 'Before sleep context',
  sleepContextDescription:
    'Small signals before sleep that may explain the dream.',
  preSleepEmotionsLabel: 'Emotions before sleep',
  stressLabel: 'Stress level',
  alcoholLabel: 'Alcohol before sleep',
  caffeineLabel: 'Late caffeine',
  medicationsLabel: 'Medications or supplements',
  medicationsPlaceholder: 'e.g. melatonin 3mg',
  eventsLabel: 'Important events',
  eventsPlaceholder: 'e.g. exams, conflict, celebration',
  healthNotesLabel: 'Health notes',
  healthNotesPlaceholder: 'e.g. headache, anxiety, low mood',
  boolYes: 'Yes',
  boolNo: 'No',
  detailEmotionTitle: 'Emotional snapshot',
  detailEmotionEmpty:
    'No wake-up or pre-sleep emotions were saved for this dream.',
  detailWakeEmotionsLabel: 'After waking',
  detailPreSleepEmotionsLabel: 'Before sleep',
  detailContextTitle: 'Pre-sleep context',
  detailContextEmpty: 'No pre-sleep context was saved for this dream.',
  tagsTitle: 'Tags',
  tagsDescription: 'Symbols, people, places, recurring fragments.',
  tagsPlaceholder: 'ocean',
  tagsEmpty: 'No tags yet. Tap add to save your first one.',
  voiceTitle: 'Voice note',
  voiceDescription: 'Start fast. Refine later.',
  voiceIdleHint: 'One tap starts a raw voice capture.',
  startRecording: 'Start recording',
  stopRecording: 'Stop recording',
  recordingHint: 'Recording in progress. Stop when you are done.',
  attachedAudioTitle: 'Voice note attached',
  audioPlayAction: 'Play voice note',
  audioPauseAction: 'Pause voice note',
  removeAudio: 'Remove voice note',
  addTag: 'Add',
  saveDream: 'Save dream',
  updateDream: 'Update dream',
  saveErrorTitle: 'Nothing to save',
  saveErrorDescription:
    'Write what you remember or attach a voice note first. Title alone is not enough.',
  saveSuccessTitle: 'Saved',
  saveSuccessDescription: 'Your dream was saved locally.',
  postSaveTitle: 'Capture saved',
  postSaveDescription:
    'It is safe locally now. Keep capturing, or open this dream if you want to refine it.',
  postSaveSavedLabel: 'Saved entry',
  postSaveNextStepLabel: 'Next step',
  postSaveFollowUpReflectionTitle: 'Revisit while it is still vivid',
  postSaveFollowUpReflectionDescription:
    'Open this dream and use the reflection prompts to keep one sharp detail alive.',
  postSaveFollowUpReflectionAction: 'Open revisit prompts',
  postSaveFollowUpRefineTitle: 'Add one concrete detail',
  postSaveFollowUpRefineDescription:
    'Open the capture and write one image, place, or line your future self will still understand.',
  postSaveFollowUpRefineAction: 'Refine this dream',
  postSaveFollowUpTranscriptTitle: 'Turn the voice note into usable text',
  postSaveFollowUpTranscriptDescription:
    'Open this dream and clean up the transcript while the memory is still close.',
  postSaveFollowUpTranscriptAction: 'Work on transcript',
  postSaveThenLabel: 'Then',
  postSaveCaptureAnother: 'Keep capturing',
  postSaveRecordAnother: 'Record another',
  postSaveOpenDetail: 'Open this dream',
  postSaveContinueLater: 'Continue later',
  postSaveFooterHint: 'You can switch tabs anytime.',
  updateSuccessTitle: 'Updated',
  updateSuccessDescription: 'Your dream was updated locally.',
  audioErrorTitle: 'Audio error',
  audioSimulatorHint:
    'Voice capture may be unavailable on the iOS Simulator. Use text here or test recording on a real device.',
  audioPermissionDenied:
    'Microphone access was denied. Turn on microphone permission in system settings to record voice notes.',
  audioPermissionUnavailable:
    'Microphone permission could not be requested. Check system settings.',
  audioInterruptedSaved:
    'Something interrupted the recording. What you said up to then was kept.',
  audioInterruptedLost:
    'Something interrupted the recording before it could be saved.',
  templateSectionHint: 'Quick type',
  templateLucidLabel: 'Lucid',
  templateNightmareLabel: 'Nightmare',
  templateVividLabel: 'Vivid',
  templateRecurringLabel: 'Recurring',
  templateFragmentLabel: 'Fragment',
  templatePeacefulLabel: 'Peaceful',
  dreamCardShareAction: 'Share dream',
  dreamCardShareTitle: 'Kaleidoscope of Dreams',
  dreamCardWatermark: 'Kaleidoscope of Dreams',
  dreamCardShareMessage: 'Shared from my dream journal.',
};

export type DreamCopy = typeof DREAM_COPY_EN;
