import { DREAM_COPY_EN, type DreamCopy } from './en';

export const DREAM_COPY_UK: DreamCopy = {
  ...DREAM_COPY_EN,
  homeTitle: 'Щоденник снів',
  homeSubtitle: 'Записуй швидко. До патернів повернешся пізніше.',
  homeGreeting: 'Доброго ранку',
  homeGreetingMorning: 'Доброго ранку',
  homeGreetingAfternoon: 'Доброго дня',
  homeGreetingEvening: 'Доброго вечора',
  homeGreetingNight: 'Ще не спиш?',
  homeRecordNow: 'Записати зараз',
  homeContinueDraft: 'Продовжити чернетку',
  homeDraftShortcutHint: 'Незавершений запис чекає на тебе.',
  homeLastDreamLabel: 'Повернутись до останнього сну',
  homeLastDreamMetaPrefix: 'Останнє відкриття',
  homeSectionLabel: 'Останні сни',
  homeCustomizeAction: 'Налаштувати',
  homeCustomizeTitle: 'Налаштувати Home',
  homeCustomizeDone: 'Готово',
  homeCustomizeReset: 'Скинути',
  homeCustomizePresetLabel: 'Акцент',
  homeCustomizePresetHint:
    'Спокійніша або аналітичніша стрічка. Інші екрани не зміняться.',
  homeCustomizePresetBalanced: 'Баланс',
  homeCustomizePresetCalm: 'Спокій',
  homeCustomizePresetInsight: 'Інсайти',
  homeCustomizeSectionsLabel: 'Видимі секції',
  homeCustomizeSectionsHint: 'Покажи або сховай блоки над останніми снами.',
  homeCustomizeOrderLabel: 'Порядок секцій',
  homeCustomizeOrderHint: 'Підніміть вище те, що хочете помічати першим.',
  homeCustomizeSectionShortcuts: 'Швидкі дії',
  homeCustomizeSectionSpotlight: 'У фокусі',
  homeCustomizeSectionWeeklyPatterns: 'Тижневі патерни',
  homeCustomizeVisibleLabel: 'Видимо',
  homeCustomizeHiddenLabel: 'Сховано',
  homeOpenArchive: 'Архів',
  homeRecentLimitHint:
    'Головний екран тримає фокус на останніх записах. Для повної історії перемкнись на вкладку Архів.',
  homeSpotlightTitle: 'У фокусі',
  homeSpotlightPatternLabel: 'Патерн',
  homeSpotlightWeeklyLabel: 'Цей тиждень',
  homeSpotlightAttentionLabel: 'Потребує уваги',
  homeSpotlightNoPattern: 'Ще формується',
  homeSpotlightAttentionClear: 'Все чисто',
  homeSpotlightWeeklyOnTrack: 'Ритм теплий',
  homeSpotlightWeeklyOffTrack: 'Ще один запис допоможе',
  homeSpotlightAttentionAudioSingle: '1 голосовий запис',
  homeSpotlightAttentionAudioPlural: 'голосових записів',
  homeSpotlightAttentionMoodSingle: '1 сон без настрою',
  homeSpotlightAttentionMoodPlural: 'снів без настрою',
  homeSpotlightAttentionAudioHint:
    'Транскрипт зробить їх легшими для повернення.',
  homeSpotlightAttentionMoodHint:
    'Швидкий настрій після пробудження зробить патерни яснішими.',
  homeSpotlightAttentionClearHint:
    'Зараз нічого очевидного не потребує cleanup.',
  homeSpotlightRevisitLabel: 'Повернутись зараз',
  homeSpotlightRevisitAction: 'Відкрити сон',
  homeSpotlightRevisitActionThread: 'Відкрити нитку',
  homeSpotlightRevisitActionAnalysis: 'Звірити рефлексію',
  homeSpotlightRevisitActionTranscript: 'Доробити транскрипт',
  homeSpotlightRevisitActionTime: 'Повернути спогад',
  homeSpotlightRevisitEmpty: 'Ще немає старішого сну, який явно просить уваги.',
  homeSpotlightRevisitContextThread: 'Поруч є нитка',
  homeSpotlightRevisitContextAnalysis: 'Рефлексія готова',
  homeSpotlightRevisitContextTranscript: 'Транскрипт готовий',
  homeSpotlightRevisitContextTime: 'Часовий слід',
  homeSpotlightRevisitContextSignal: 'Сигнал варто назвати',
  homeSpotlightRevisitReasonThreadPrefix: 'Нитка з ',
  homeSpotlightRevisitReasonThreadSuffix: ' близькими снами',
  homeSpotlightRevisitReasonAnalysis:
    'Тут уже є збережена рефлексія, яку варто звірити знову',
  homeSpotlightRevisitReasonTranscript: 'Транскрипт уже готовий до доробки',
  homeSpotlightRevisitReasonTimePrefix: 'Цей сон повертається з ',
  homeSpotlightRevisitReasonTimeSuffix:
    ' і його варто знову відкрити, поки деталь не стерлась.',
  homeSpotlightRevisitTimeWeek: 'приблизно тижневої давності',
  homeSpotlightRevisitTimeMonth: 'приблизно місячної давності',
  homeSpotlightRevisitTimeQuarter: 'приблизно тримісячної давності',
  homeSpotlightRevisitTimeHalfYear: 'приблизно піврічної давності',
  homeSpotlightRevisitTimeYear: 'приблизно річної давності',
  homeSpotlightRevisitReasonSignal:
    'Тут усе ще є виразний сигнал, який варто назвати',
  homeSpotlightShowDetails: 'Більше деталей',
  homeSpotlightHideDetails: 'Менше деталей',
  homeWeeklyPatternsTitle: 'Патерни тижня',
  homeStreakLabel: 'Серія',
  homeTotalLabel: 'Всього',
  homeAverageLabel: 'Сер. слів',
  weeklyPatternRhythmLabel: 'Ритм',
  weeklyPatternSignalLabel: 'Свіжий сигнал',
  weeklyPatternToneLabel: 'Тон',
  weeklyPatternContextLabel: 'Контекст',
  weeklyPatternCaptureLabel: 'Запис',
  weeklyPatternQuietWeekTitle: 'Тихий тиждень',
  weeklyPatternQuietWeekHint: 'За останні сім днів нових снів не було.',
  weeklyPatternStillFormingTitle: 'Ще формується',
  weeklyPatternStillFormingHint:
    'Ще один детальніший запис зробить тиждень читабельнішим.',
  weeklyPatternContextTitle: 'Контекст зʼявлявся',
  weeklyPatternVoiceTitle: 'Тиждень схилявся до голосу',
  weeklyPatternThisWeekSuffix: 'цього тижня',
  weeklyPatternVsPreviousLabel: 'проти попередніх 7 днів',
  weeklyPatternVsPreviousFlat: 'Так само, як у попередні 7 днів',
  homeDaysUnit: 'днів',
  homeFilterAll: 'Усі',
  homeFilterActive: 'Поточні',
  homeFilterArchived: 'Архів',
  homeFilterStarred: 'Важливі',
  homeArchiveFilterLabel: 'Статус',
  homeSearchLabel: 'Пошук снів',
  homeSearchPlaceholder: 'Назва, нотатки, транскрипт або тег',
  homeSaveSearchPreset: 'Зберегти пошук',
  homeSearchShowDetails: 'Збережені пошуки',
  homeSearchHideDetails: 'Сховати збережені',
  homeSavedSearchesLabel: 'Збережені пошуки',
  homeSearchPresetFallback: 'Швидкий пошук',
  homeSearchPresetRemove: 'Видалити збережений пошук',
  homeSearchPresetDeleteTitle: 'Видалити цей пошук?',
  homeSearchPresetDeleteDescription:
    'Це прибере лише збережену комбінацію фільтрів. Самі сни не зміняться.',
  homeSearchMatchTitle: 'Назва',
  homeSearchMatchNotes: 'Нотатки',
  homeSearchMatchTranscript: 'Транскрипт',
  homeSearchMatchTag: 'Тег',
  homeSearchMatchContext: 'Контекст',
  homeClearSearch: 'Очистити пошук',
  homeRefineLabel: 'Уточнення таймлайну',
  homeQuickFiltersLabel: 'Швидкі фільтри',
  homeAllFilters: 'Усі фільтри',
  homeMoreFilters: 'Більше фільтрів',
  homeLessFilters: 'Менше фільтрів',
  homeShowFilters: 'Фільтри',
  homeHideFilters: 'Сховати',
  homeMoodFilterLabel: 'Настрій',
  homeMoodFilterAll: 'Будь-який',
  homeTypeFilterLabel: 'Тип запису',
  homeTypeFilterAll: 'Будь-який тип',
  homeTypeFilterText: 'Текст',
  homeTypeFilterAudio: 'Аудіо',
  homeTypeFilterMixed: 'Змішаний',
  homeTranscriptFilterLabel: 'Транскрипт',
  homeTranscriptFilterAll: 'Будь-який стан транскрипту',
  homeTranscriptFilterWithTranscript: 'Є транскрипт',
  homeTranscriptFilterAudioOnly: 'Лише аудіо',
  homeTranscriptFilterEdited: 'Редагований транскрипт',
  homeDateRangeFilterLabel: 'Період',
  homeDateRangeAll: 'Будь-коли',
  homeDateRange7d: 'Останні 7 днів',
  homeDateRange30d: 'Останні 30 днів',
  homeDateRange90d: 'Останні 90 днів',
  homeSortFilterLabel: 'Сортування',
  homeSortFilterNewest: 'Спочатку нові',
  homeSortFilterOldest: 'Спочатку старі',
  homeTagFilterLabel: 'Теги',
  homeTagSearchPlaceholder: 'Пошук тегів',
  homeTagSelectedLabel: 'Вибрані теги',
  homeTagsShowMore: 'Показати всі теги',
  homeTagsShowLess: 'Показати менше',
  homeTagsEmpty: 'За цим пошуком тегів немає.',
  homeClearFilters: 'Очистити фільтри',
  homeResultsSingle: 'запис',
  homeResultsPlural: 'записів',
  homeSearchEmptyTitle: 'Нічого не знайдено за цими фільтрами',
  homeSearchEmptyDescription:
    'Спробуй простіший запит, зміни фільтри або очисть їх, щоб побачити більше записів.',
  homeQuickOpen: 'Відкрити',
  actionRetry: 'Повторити',
  clearErrorAction: 'Закрити',
  timelineLoadingTitle: 'Завантаження таймлайну',
  timelineLoadingDescription: 'Оновлюємо локальні записи...',
  timelineErrorTitle: 'Не вдалося завантажити таймлайн',
  timelineErrorDescription:
    'Спробуй ще раз. Локальне сховище може бути тимчасово недоступне.',
  openDreamHint: 'Натисни, щоб відкрити. Затисни для швидких дій.',
  swipeEdit: 'Змінити',
  swipeDelete: 'Видалити',
  swipeArchive: 'Архів',
  swipeUnarchive: 'Розархівувати',
  emptyTitle: 'Перший сон уже чекає',
  emptyDescription:
    'Запиши до того, як він зникне — фрагмент, відчуття чи один образ — цього достатньо.',
  emptyActiveTitle: 'Немає активних снів',
  emptyActiveDescription:
    'Усі записи в архіві. Зміни фільтр або створи новий сон.',
  emptyArchivedTitle: 'Архів порожній',
  emptyArchivedDescription: 'Архівуй старі записи, щоб сфокусувати таймлайн.',
  archiveTitle: 'Архів',
  archiveSubtitle: 'Переглядай минулі сни по місяцях.',
  archiveSearchPlaceholder: 'Пошук у поточному місяці',
  archiveSearchScopeHint: 'Пошук працює тільки в межах поточного місяця.',
  archiveResetView: 'Скинути вигляд',
  archiveCalendarTitle: 'Календар',
  archiveCalendarSubtitle: 'Перемикай місяць або натискай день, де є сни.',
  archiveCalendarShowGrid: 'Показати дні',
  archiveCalendarHideGrid: 'Сховати дні',
  archiveBrowseLabel: 'Вигляд',
  archiveMonthEntriesLabel: 'записів',
  archiveMonthActiveDaysLabel: 'активних днів',
  archivePreviousMonth: 'Раніше',
  archiveNextMonth: 'Новіше',
  archiveAllDates: 'Усі дати',
  archiveSelectedDatePrefix: 'Вибрано',
  archiveWeekdaySun: 'Нд',
  archiveWeekdayMon: 'Пн',
  archiveWeekdayTue: 'Вт',
  archiveWeekdayWed: 'Ср',
  archiveWeekdayThu: 'Чт',
  archiveWeekdayFri: 'Пт',
  archiveWeekdaySat: 'Сб',
  archiveEmptyTitle: 'Архів порожній',
  archiveEmptyDescription:
    'Спочатку збережи кілька снів, і вони почнуть групуватись тут.',
  archiveEmptyCurrentTitle: 'Немає активних снів',
  archiveEmptyCurrentDescription:
    'Усе в цьому місяці вже в архіві або відфільтроване.',
  archiveEmptyArchivedTitle: 'Поки немає архівних снів',
  archiveEmptyArchivedDescription:
    'Перемісти кілька старіших снів в архів, і вони зʼявляться тут.',
  archiveEmptyImportantTitle: 'Поки немає важливих снів',
  archiveEmptyImportantDescription:
    'Познач кілька снів як важливі, щоб до них було легше повертатись.',
  archiveNoResultsTitle: 'Нічого не знайдено в цьому вигляді архіву',
  archiveNoResultsDescription:
    'Спробуй інший місяць, очисть день або скинь поточний пошук і фільтри.',
  archiveFilterAll: 'Усі',
  archiveFilterActive: 'Активні',
  archiveFilterArchived: 'Архівні',
  archiveFilterStarred: 'Важливі',
  archiveTagsLabel: 'Символи',
  untitled: 'Сон без назви',
  archivedTag: 'Архів',
  starredTag: 'Важливе',
  audioTag: 'Аудіо',
  transcriptTag: 'Транскрипт',
  editedTranscriptTag: 'Редаговано',
  transcriptPreviewPrefix: 'Транскрипт',
  editedTranscriptPreviewPrefix: 'Редагований транскрипт',
  audioOnlyPreview: 'Голосову нотатку збережено. Текст можна додати пізніше.',
  noDetailsPreview: 'Поки без текстового опису.',
  detailBack: 'Назад',
  detailEdit: 'Редагувати сон',
  detailStar: 'Додати у важливі',
  detailUnstar: 'Прибрати з важливих',
  detailArchive: 'В архів',
  detailUnarchive: 'З архіву',
  detailDelete: 'Видалити сон',
  detailDeleteTitle: 'Видалити цей сон?',
  detailDeleteDescription:
    'Запис буде видалено з локального сховища без можливості відновлення.',
  detailDeleteCancel: 'Скасувати',
  detailDeleteConfirm: 'Видалити',
  detailMissingTitle: 'Сон не знайдено',
  detailMissingDescription:
    'Цей запис більше недоступний у локальному сховищі.',
  detailMetaTitle: 'Коротко',
  detailCapturedLabel: 'Збережено',
  detailPreviewLabel: 'Фрагмент',
  detailActionEdit: 'Редагувати',
  detailActionImportant: 'Важливе',
  detailActionArchive: 'В архів',
  detailActionRestore: 'Повернути',
  detailActionDelete: 'Видалити',
  detailSavedTitle: 'Сон збережено',
  detailSavedDescription:
    'Сирий спогад уже в безпеці. Деталі можна доробити пізніше.',
  detailSavedPatternLabel: 'Найсильніший сигнал',
  detailSavedRelatedLabel: 'Схожі сни',
  detailReflectionTitle: 'Повернись до цього зараз',
  detailReflectionSignalTitle: 'Назви сигнал',
  detailReflectionSignalPrefix: 'У цьому сні найсильніше звучить ',
  detailReflectionSignalSuffix:
    '. Додай один рядок про те, чому цей сигнал важливий саме зараз.',
  detailReflectionEmotionTitle: 'Впіймай відчуття',
  detailReflectionEmotionWithMoodPrefix:
    'Емоційний тон цього сну все ще тягнеться до ',
  detailReflectionEmotionWithMoodSuffix:
    '. Запиши, що залишилося в тілі після пробудження.',
  detailReflectionEmotionBody:
    'Запиши, яке відчуття залишилося в тілі після пробудження, навіть якщо воно тривало лише кілька секунд.',
  detailReflectionThreadTitle: 'Потягни за нитку',
  detailReflectionThreadPrefix: 'Цей сон уже торкається ',
  detailReflectionThreadSuffix:
    '. Відкрий один близький сон і відміть, що повторюється або змінюється.',
  detailReflectionAnalysisTitle: 'Перевір зміст',
  detailReflectionAnalysisPrefix: 'Збережений summary підказує: ',
  detailReflectionAnalysisSuffix: ' Виріши, чи це все ще відчувається правдою.',
  detailReflectionTranscriptTitle: 'Зроби транскрипт придатним',
  detailReflectionTranscriptBody:
    'Одного швидкого проходу вистачить, щоб цей голосовий спогад було легше шукати й відкривати пізніше.',
  detailReflectionResurfaceTitle: 'Що досі тримається',
  detailReflectionResurfacePrefix: 'Цей сон знову виринає з ',
  detailReflectionResurfaceSuffix:
    '. Додай один рядок про те, що все ще відчувається правдою зараз.',
  detailReflectionCaptureTitle: 'Залиши одну яскраву деталь',
  detailReflectionCaptureBody:
    'Додай один конкретний образ, місце або рядок, який твій майбутній ти все ще зрозуміє через тиждень.',
  detailReflectionFallbackTitle: 'Залиши слід на потім',
  detailReflectionFallbackBody:
    'Додай одну коротку нотатку, за яку майбутній ти буде вдячний.',
  detailReflectionActionEdit: 'Додати деталь',
  detailReflectionActionRelated: 'Відкрити нитку',
  detailReflectionActionAnalysis: 'Переглянути аналіз',
  detailCaptureTitle: 'Запис',
  detailCaptureEmpty: 'Для цього сну ще немає ні тексту, ні аудіо.',
  detailTranscriptTitle: 'Текстові нотатки',
  detailTranscriptEmpty: 'Для цього сну ще немає збережених текстових нотаток.',
  detailGlanceCaptureLabel: 'Формат',
  detailGlanceTranscriptLabel: 'Транскрипт',
  detailGlanceAnalysisLabel: 'Аналіз',
  detailGlanceRelatedLabel: 'Схожі',
  detailCaptureModeText: 'Нотатка',
  detailCaptureModeVoice: 'Голос',
  detailCaptureModeMixed: 'Змішано',
  detailTranscriptSummaryIdle: 'Немає',
  detailTranscriptSummaryReady: 'Готово',
  detailTranscriptSummaryEdited: 'Змінено',
  detailTranscriptSummaryProcessing: 'У роботі',
  detailTranscriptSummaryError: 'Повтор',
  detailGeneratedTranscriptTitle: 'Згенерований транскрипт',
  detailGeneratedTranscriptEmpty:
    'Для цієї голосової нотатки ще не створено транскрипт.',
  detailGeneratedTranscriptHint:
    'Транскрипція виконується на пристрої й не змінює оригінальну голосову нотатку.',
  detailGeneratedTranscriptProcessing:
    'Транскрипція виконується локально на цьому пристрої. Не закривай застосунок, доки вона не завершиться.',
  detailGeneratedTranscriptError:
    'Остання спроба транскрипції не завершилась. Оригінальна голосова нотатка все ще збережена.',
  detailGeneratedTranscriptReplaceError:
    'Остання спроба заміни транскрипту не завершилась. Попередній транскрипт усе ще збережений локально.',
  detailGeneratedTranscriptSourceLabel: 'Джерело',
  detailGeneratedTranscriptSourceGenerated: 'Згенеровано з аудіо',
  detailGeneratedTranscriptSourceEdited: 'Відредаговано вручну',
  detailGeneratedTranscriptUpdatedLabel: 'Оновлено',
  detailGeneratedTranscriptEdit: 'Редагувати транскрипт',
  detailGeneratedTranscriptSave: 'Зберегти транскрипт',
  detailGeneratedTranscriptCancel: 'Скасувати редагування',
  detailGeneratedTranscriptClear: 'Очистити транскрипт',
  detailGeneratedTranscriptReplace: 'Замінити транскрипт',
  detailGeneratedTranscriptEmptyErrorTitle: 'Порожній транскрипт',
  detailGeneratedTranscriptEmptyErrorDescription:
    'Додай хоча б один рядок перед збереженням або очисти транскрипт окремо.',
  detailGeneratedTranscriptSaveSuccessTitle: 'Транскрипт оновлено',
  detailGeneratedTranscriptSaveSuccessDescription:
    'Відредагований транскрипт збережено локально і він лишається доступним для пошуку.',
  detailGeneratedTranscriptClearTitle: 'Очистити транскрипт?',
  detailGeneratedTranscriptClearDescription:
    'Це видалить збережений транскрипт, але залишить оригінальну голосову нотатку на пристрої.',
  detailAnalysisTitle: 'Аналіз сну',
  detailAnalysisEmpty:
    'Для цього сну ще не збережено аналіз. Згенеруй його, щоб перетворити запис на коротку локальну рефлексію.',
  detailAnalysisDisabled:
    'Шар аналізу вимкнений у Settings, тому цей сон поки лишається сирим записом без summary і themes.',
  detailAnalysisSummaryLabel: 'Підсумок',
  detailAnalysisThemesLabel: 'Теми',
  detailAnalysisStateLabel: 'Режим аналізу',
  detailAnalysisStateLocalReady:
    'Локальний аналіз увімкнений і готовий для цього сну.',
  detailAnalysisStateDisabled:
    'Аналіз вимкнений. Увімкни його в Settings, коли захочеш summary і themes.',
  detailAnalysisStateOpenAiPlanned:
    'У Settings обрано OpenAI, але мережевий аналіз у цьому релізі ще лишається запланованим шляхом.',
  detailAnalysisStateManual:
    'Для цього сну можна згенерувати локальний summary зі збереженого тексту, транскрипту, тегів і context.',
  detailAnalysisProviderLabel: 'Провайдер',
  detailAnalysisUpdatedLabel: 'Оновлено',
  detailAnalysisStatusLabel: 'Статус',
  detailAnalysisStatusReady: 'Готово',
  detailAnalysisStatusError: 'Помилка',
  detailAnalysisStatusIdle: 'Не згенеровано',
  detailAnalysisSummaryReady: 'Готово',
  detailAnalysisSummaryIdle: 'Немає',
  detailAnalysisSummaryDisabled: 'Вимкнено',
  detailAnalysisSummaryPlanned: 'План',
  detailAnalysisProviderManual: 'Локально',
  detailAnalysisProviderOpenAi: 'OpenAI (заплановано)',
  detailAnalysisGenerate: 'Згенерувати аналіз',
  detailAnalysisRegenerate: 'Оновити аналіз',
  detailAnalysisClear: 'Очистити аналіз',
  detailAnalysisGenerating: 'Генерується локальний аналіз...',
  detailAnalysisOpenSettings: 'Відкрити Settings',
  detailAnalysisOpenAiUnavailable:
    'Провайдер OpenAI уже обраний у Settings, але в цьому релізі це ще лише запланований шлях.',
  detailAnalysisErrorTitle: 'Помилка аналізу',
  detailAnalysisGenerateErrorDescription:
    'Сон усе ще збережений локально. Спробуй manual provider або залиш цей слот порожнім.',
  detailTranscribeAudio: 'Транскрибувати аудіо',
  detailTranscribeRetry: 'Повторити транскрипцію',
  detailTranscribePreparingModel: 'Підготовка офлайн-моделі',
  detailTranscribeInProgress: 'Транскрипція на пристрої',
  detailTranscriptionErrorTitle: 'Помилка транскрипції',
  detailTranscriptionErrorDescription:
    'Голосова нотатка все ще збережена локально. Спробуй ще раз у тихішому середовищі або після завершення завантаження моделі.',
  detailTranscriptSyncLocal:
    'Цей збережений транскрипт новіший на цьому пристрої й може ще не дійти до іншого.',
  detailTranscriptSyncing:
    'Цей збережений транскрипт ще проходить через sync. Дай йому трохи часу, перш ніж перевіряти інший пристрій.',
  detailTranscriptSyncError:
    'Цей збережений транскрипт у безпеці на цьому пристрої, але останній sync не завершився.',
  detailAudioSyncLocal:
    'Ця голосова нотатка поки збережена лише на цьому пристрої, доки backup не наздожене.',
  detailAudioSyncing:
    'Ця голосова нотатка ще проходить через backup. Дай їй трохи часу, перш ніж перевіряти інший пристрій.',
  detailAudioSyncError:
    'Ця голосова нотатка у безпеці на цьому пристрої, але останній backup sync не завершився.',
  detailTagsEmpty: 'Теги ще не додані.',
  detailRelatedTitle: 'Поруч сни',
  detailRelatedDescription:
    'Раніші сни, пов’язані спільними сигналами, повторюваними словами та емоційними відлуннями.',
  detailRelatedEmpty:
    'Збережи ще кілька снів, і перша виразна нитка почне формуватися.',
  detailRelatedSummaryEmpty: 'Немає',
  detailRelatedMatchSingular: 'збіг',
  detailRelatedMatchPlural: 'збіги',
  detailRelatedSharedLabel: 'Сигнали нитки',
  detailRelatedRecurringLabel: 'Вже траплялось',
  detailStateTitle: 'Стан сну',
  detailStateEmpty:
    'Для цього сну не збережено усвідомленість, емоції після пробудження чи контекст перед сном.',
  detailLucidPracticeEmpty:
    'Для цього сну не записано практику усвідомлених снів.',
  detailLucidityLabel: 'Усвідомленість',
  detailAudioDescription:
    'До цього сну прикріплена оригінальна голосова нотатка.',
  detailAudioPathLabel: 'Локальний файл',
  detailAudioPlay: 'Відтворити голос',
  detailAudioStop: 'Зупинити відтворення',
  detailAudioPlaybackHint:
    'Прослухай запис, щоб перевірити, що початкове захоплення збереглося.',
  detailAudioPlaybackErrorTitle: 'Помилка відтворення',
  detailAudioAttachedMeta: 'Є запис',
  detailAudioCloudOnlyHint:
    'Ця голосова нотатка зберігається в хмарі. Завантаж її, щоб прослухати на цьому пристрої.',
  detailAudioDownload: 'Завантажити голосову нотатку',
  detailAudioDownloading: 'Завантаження…',
  detailAudioDownloadErrorTitle: 'Помилка завантаження',
  createTitle: 'Запис сну',
  createSubtitle: 'Злови форму сну зараз. Деталі відсортуєш пізніше.',
  quickAddKicker: 'Швидке додавання',
  quickAddWakeAction: 'Ранковий запис',
  quickAddWakeHint:
    'Відкрий стислий ранковий режим для швидкого голосового або текстового запису.',
  quickAddVoiceAction: 'Голосова нотатка',
  quickAddVoiceHint:
    'Відкрий редактор у голосовому режимі й швидко почни запис.',
  quickAddTextAction: 'Текстова нотатка',
  quickAddTextHint: 'Відкрий редактор і зафіксуй те, що ще памʼятаєш.',
  quickAddContinueHint:
    'Продовж із локально збереженої чернетки з того місця, де зупинився.',
  wakeEntryKicker: 'Ранковий потік',
  wakeEntryTitle: 'Поки не вислизнуло',
  wakeEntryDescription:
    'Один спокійний екран після нагадування. Натисни в центр, щоб писати, або нижче обери голос.',
  wakeEntryOrbAction: 'Писати',
  wakeEntryOrbHint: 'Натисни в центр і почни з сирих рядків.',
  wakeEntryWriteAction: 'Писати зараз',
  wakeEntryAlternateTitle: 'Інші способи запису',
  wakeEntrySpeakAction: 'Говорити замість цього',
  wakeEntrySpeakHint: 'Почни з голосу, якщо це швидше, ніж друкувати.',
  wakeEntryDraftAction: 'Продовжити чернетку',
  wakeEntryDraftHint:
    'Повернись до незавершеного запису, який уже збережено локально.',
  wakeModeChip: 'Ранковий режим',
  wakeHeroTitle: 'Злови першу форму',
  wakeHeroDescription:
    'Спочатку голос, потім сирі рядки. Назва, теги й контекст можуть зачекати.',
  wakeCaptureTitle: 'Голос або сирі рядки',
  wakeCaptureDescription:
    'Почни з найшвидшого, що ще живе: голосова нотатка, кілька слів або обидва варіанти разом.',
  wakeCaptureAlternateTitle: 'Або запиши голосом',
  wakeCaptureVoiceHint:
    'Обери голос, якщо зараз говорити швидше, ніж друкувати.',
  wakeVoiceDescription:
    'Почни запис зараз або одразу впиши кілька сирих рядків нижче.',
  wakeCoreTitle: 'Сирий спогад',
  wakeCoreDescription: 'Залиши лише те, що ще живе. Структуру додаси пізніше.',
  wakeTextLabel: 'Що ще лишилося?',
  wakeTextPlaceholder: 'Місце, обличчя, відчуття, один рядок...',
  wakeRefineTitle: 'Додаси пізніше, якщо треба',
  wakeRefineDescription:
    'Ранковий запис має лишатися легким. Назва, теги і контекст перед сном усе ще доступні пізніше.',
  wakeRefineMetaAction: 'Назва + дата',
  wakeMetaTitle: 'Назва і дата сну',
  wakeMetaDescription:
    'Додавай це зараз лише якщо воно справді допомагає заякорити спогад.',
  wakeReadyHint:
    'Голосу, кількох сирих рядків і відчуття після пробудження достатньо для збереження.',
  createHeroTitle: 'Запиши, поки не зникло',
  createHeroDescription: 'Почни з голосу або кількох сирих рядків.',
  recordEmptyTitle: 'Почни з короткого запису',
  recordEmptyDescription: 'Почни з тексту або голосу. Усе інше може зачекати.',
  recordDraftRestoredTitle: 'Чернетку відновлено',
  recordDraftRestoredDescription:
    'Незавершений запис збережено локально. Продовжуй редагування або збережи, коли будеш готовий.',
  recordDraftStartFreshAction: 'Почати заново',
  recordLoadingTitle: 'Виконується дія',
  recordLoadingDescription: 'Зачекай, поки операція завершиться.',
  recordErrorTitle: 'Дія не виконалась',
  recordErrorDescription: 'Спробуй ще раз або продовж запис текстом.',
  refineTitle: 'Уточниш пізніше',
  refineDescription:
    'Настрій, контекст і теги не обовʼязкові одразу. Додавай їх лише якщо вони справді допомагають.',
  refineReadyHint: 'Щоб зберегти, достатньо сирого тексту або голосу.',
  refineMoodAction: 'Настрій',
  refineContextAction: 'Перед сном',
  refineTagsAction: 'Теги',
  refineHideAction: 'Сховати',
  editTitle: 'Редагування сну',
  editSubtitle: 'Уточни спогад, не втрачаючи оригінальний запис.',
  editHeroTitle: 'Уточни спогад',
  editHeroDescription: 'Онови деталі, поки сон ще свіжий і важливий.',
  coreTitle: 'Основне',
  coreDescription: 'Назва необовʼязкова. Спершу зафіксуй сам спогад.',
  titleLabel: 'Назва сну',
  titlePlaceholder: 'Політ над старими дахами',
  sleepDateLabel: 'Дата сну',
  sleepDateInvalidTitle: 'Некоректна дата сну',
  sleepDateInvalidDescription:
    'Використовуй формат YYYY-MM-DD і реальну календарну дату.',
  textLabel: 'Що ти памʼятаєш?',
  textPlaceholder: 'Запиши сон, поки він ще свіжий...',
  wordsUnit: 'слів',
  moodTitle: 'Настрій після пробудження',
  moodDescription: 'Який тон залишив сон?',
  moodIntensityLabel: 'Яскравість',
  moodIntensityHint: 'Наскільки яскравим або насиченим був цей сон?',
  lucidityLabel: 'Усвідомленість',
  lucidityHint: 'Чи було відчуття, що це сон — хоча б на мить?',
  lucidityNoneLabel: 'Неусвідомлений',
  lucidityBriefLabel: 'Коротка ясність',
  lucidityAwareLabel: 'Усвідомлений',
  lucidityControlLabel: 'Усвідомлений + контроль',
  wakeEmotionsTitle: 'Емоції після пробудження',
  wakeEmotionsDescription:
    'Швидкі сигнали з першої хвилини після пробудження, поки сон ще не встиг згладитися.',
  sleepContextTitle: 'Контекст перед сном',
  sleepContextDescription:
    'Невеликі сигнали перед сном, які можуть пояснити сон.',
  preSleepEmotionsLabel: 'Емоції перед сном',
  stressLabel: 'Рівень стресу',
  alcoholLabel: 'Алкоголь перед сном',
  caffeineLabel: 'Пізній кофеїн',
  medicationsLabel: 'Препарати або добавки',
  medicationsPlaceholder: 'напр. мелатонін 3мг',
  eventsLabel: 'Важливі події',
  eventsPlaceholder: 'напр. іспит, конфлікт, святкування',
  healthNotesLabel: 'Нотатки про здоровʼя',
  healthNotesPlaceholder: 'напр. головний біль, тривожність, низький настрій',
  boolYes: 'Так',
  boolNo: 'Ні',
  detailEmotionTitle: 'Емоційний зріз',
  detailEmotionEmpty:
    'Для цього сну не збережено емоцій ні після пробудження, ні перед сном.',
  detailWakeEmotionsLabel: 'Після пробудження',
  detailPreSleepEmotionsLabel: 'Перед сном',
  detailContextTitle: 'Контекст перед сном',
  detailContextEmpty: 'Для цього сну контекст перед сном не збережено.',
  tagsTitle: 'Теги',
  tagsDescription: 'Символи, люди, місця, повторювані фрагменти.',
  tagsPlaceholder: 'океан',
  tagsEmpty: 'Тегів ще немає. Додай перший.',
  voiceTitle: 'Голосова нотатка',
  voiceDescription: 'Почни швидко. Уточниш пізніше.',
  voiceIdleHint: 'Один тап запускає запис голосу.',
  startRecording: 'Почати запис',
  stopRecording: 'Зупинити запис',
  recordingHint: 'Йде запис. Зупини, коли завершиш.',
  attachedAudioTitle: 'Голосову нотатку додано',
  audioPlayAction: 'Відтворити голосову нотатку',
  audioPauseAction: 'Зупинити голосову нотатку',
  removeAudio: 'Видалити голос',
  addTag: 'Додати',
  saveDream: 'Зберегти сон',
  updateDream: 'Оновити сон',
  saveErrorTitle: 'Немає що зберігати',
  saveErrorDescription:
    'Додай текст або голосову нотатку. Однієї назви недостатньо.',
  saveSuccessTitle: 'Збережено',
  saveSuccessDescription: 'Сон збережено локально.',
  postSaveTitle: 'Запис збережено',
  postSaveDescription:
    'Тепер він безпечно лежить локально. Продовж записувати далі або відкрий цей сон, якщо хочеш одразу щось уточнити.',
  postSaveSavedLabel: 'Збережений запис',
  postSaveNextStepLabel: 'Наступний крок',
  postSaveFollowUpReflectionTitle: 'Повернись, поки сон ще живий',
  postSaveFollowUpReflectionDescription:
    'Відкрий цей сон і пройди короткі reflection prompts, щоб не втратити найважливішу деталь.',
  postSaveFollowUpReflectionAction: 'Відкрити prompts',
  postSaveFollowUpRefineTitle: 'Додай одну конкретну деталь',
  postSaveFollowUpRefineDescription:
    'Відкрий запис і додай один образ, місце або рядок, який твій майбутній ти ще зрозуміє.',
  postSaveFollowUpRefineAction: 'Доробити цей сон',
  postSaveFollowUpTranscriptTitle: 'Перетвори голос у корисний текст',
  postSaveFollowUpTranscriptDescription:
    'Відкрий цей сон і дороби транскрипт, поки спогад ще близько.',
  postSaveFollowUpTranscriptAction: 'Попрацювати з транскриптом',
  postSaveThenLabel: 'Потім',
  postSaveCaptureAnother: 'Продовжити запис',
  postSaveRecordAnother: 'Записати голос ще раз',
  postSaveOpenDetail: 'Відкрити цей сон',
  postSaveContinueLater: 'Повернутись пізніше',
  postSaveFooterHint: 'На інші вкладки можна перейти будь-коли.',
  updateSuccessTitle: 'Оновлено',
  updateSuccessDescription: 'Сон оновлено локально.',
  audioErrorTitle: 'Помилка аудіо',
  audioSimulatorHint:
    'Голосовий запис може не працювати в iOS Simulator. Тут краще тестувати текст, а запис перевіряти на реальному пристрої.',
  audioPermissionDenied:
    'Доступ до мікрофона заборонено. Увімкни дозвіл у системних налаштуваннях, щоб записувати голосові нотатки.',
  audioPermissionUnavailable:
    'Не вдалося запитати дозвіл мікрофона. Перевір налаштування системи.',
  audioInterruptedSaved: 'Запис перервало. Те, що ти встиг сказати, збережено.',
  audioInterruptedLost: 'Запис перервало, і зберегти його не вдалося.',
  templateSectionHint: 'Тип сну',
  templateLucidLabel: 'Усвідомлений',
  templateNightmareLabel: 'Кошмар',
  templateVividLabel: 'Яскравий',
  templateRecurringLabel: 'Повторюваний',
  templateFragmentLabel: 'Фрагмент',
  templatePeacefulLabel: 'Спокійний',
  dreamCardShareAction: 'Поділитись сном',
  dreamCardShareTitle: 'Kaleidoscope of Dreams',
  dreamCardWatermark: 'Kaleidoscope of Dreams',
  dreamCardShareMessage: 'Поділено з мого щоденника снів.',
};
