export const SETTINGS_COPY_EN = {
  title: 'Settings',
  subtitle:
    'Local-first controls for reminders, privacy, backups, and analysis.',
  toggleShow: 'Show',
  toggleHide: 'Hide',
  // The hub. Every row below opens one screen; the value on the right is what
  // that screen currently says, so the list answers most questions without
  // being opened at all.
  hubAppearanceTitle: 'Appearance and language',
  hubAppearanceMeta: 'Palette, and the language the app speaks',
  hubRemindersTitle: 'Reminders',
  hubRemindersMeta: 'When to ask you about last night',
  hubRemindersOff: 'Off',
  hubBackupTitle: 'Backup and sync',
  hubSecurityTitle: 'Privacy and lock',
  hubSecurityMeta: 'Where dreams live, and who can open them',
  hubSecurityLocked: 'Locked',
  hubSecurityUnlocked: 'No lock',
  hubAnalysisTitle: 'Analysis and transcription',
  hubAnalysisMeta: 'Reading patterns, and turning voice into text',
  hubAboutTitle: 'About',
  hubAboutMeta: 'Version, storage, and export',
  footerBuildLabel: 'Kaleidoskop',
  footerStorageMetaPrefix: 'Schema',
  footerExportMetaPrefix: 'Export',
  reminderTitle: 'Dream reminder',
  reminderDescription:
    'One daily nudge after waking so you capture dreams faster.',
  reminderPermissionLabel: 'Notifications',
  reminderPermissionBlocked: 'Blocked',
  reminderCurrentScheduleLabel: 'Current schedule',
  reminderEnableHint: 'Turn it on to choose a daily reminder time.',
  reminderOffValue: 'Off',
  reminderTimeLabel: 'Reminder time',
  reminderTimeHint: 'Tap to change.',
  reminderSmartSuggestionLabel: 'Based on your recording patterns',
  reminderSmartSuggestionApply: 'Set to',
  reminderStyleTitle: 'Reminder style',
  reminderStyleDescription:
    'Changes the tone only. Timing and delivery stay the same.',
  reminderStyleBalancedLabel: 'Steady',
  reminderStyleBalancedDescription: 'Clear and neutral.',
  reminderStyleGentleLabel: 'Gentle',
  reminderStyleGentleDescription: 'Softer and more reflective.',
  reminderStyleDirectLabel: 'Direct',
  reminderStyleDirectDescription: 'Short and more immediate.',
  reminderStylePreviewLabel: 'Notification preview',
  reminderStyleFootnote:
    'You can choose the tone now even if reminders are off.',
  reminderPreviewWakeAction: 'Preview wake flow',
  reminderPreviewWakeMeta:
    'Open the reminder entry screen without waiting for the next notification.',
  devPreviewMonthlyReport: 'Preview monthly report',
  devPreviewBackupOnboarding: 'Preview backup onboarding',
  devPreviewBackupOnboardingMeta:
    'Open the one-time modal preview and reset its seen state.',
  devPreviewSyncDiagnostics: 'Preview sync diagnostics',
  devPreviewSyncDiagnosticsMeta:
    'Open the debug-only screen with the latest sync snapshot and recent sync attempts.',
  actionCancel: 'Cancel',
  reminderPermissionDeniedTitle: 'Notifications disabled',
  reminderPermissionDeniedDescription:
    'Allow notifications in system settings to enable dream reminders.',
  reminderSaveErrorTitle: 'Reminder error',
  reminderNotificationTitle: 'Record your dream',
  reminderNotificationBody: 'Capture it while details are still fresh.',
  reminderStyleGentleNotificationTitle: 'Keep the dream close',
  reminderStyleGentleNotificationBody:
    'A few calm words now can save the feeling before the day gets loud.',
  reminderStyleDirectNotificationTitle: 'Write it down now',
  reminderStyleDirectNotificationBody: 'Catch the key images before they slip.',
  languageTitle: 'Language',
  languageDescription: 'Choose your app language.',
  languageEnglish: 'EN',
  languageUkrainian: 'UA',
  calmModeTitle: 'Calm mode',
  calmModeHint:
    'Hides the explanations under headings and fields. Values, counts and errors stay.',
  nightCaptureTitle: 'Night capture',
  nightCaptureHint:
    'Between 22:00 and 07:00 the capture screen goes warm and dark, whichever theme is set.',
  themeTitle: 'Appearance',
  themeDescription: 'Choose the palette used across the app.',
  themeFootnote: 'Kaleido keeps the current look stable as the default theme.',
  themeOptionKaleido: 'Kaleido',
  themeOptionEmber: 'Ember',
  themeOptionMoss: 'Moss',
  themeOptionDaylight: 'Daylight',
  appIconTitle: 'App icon',
  appIconDescription: 'Pick the icon shown on your home screen.',
  appIconOptionDefault: 'Forest Gold',
  appIconOptionIvory: 'Ivory',
  appIconOptionSage: 'Sage',
  appIconOptionNight: 'Night',
  appIconOptionMono: 'Mono',
  appIconErrorTitle: 'Icon not changed',
  appIconErrorDescription: 'The app icon could not be changed on this device.',
  privacyTitle: 'Privacy and storage',
  privacyDescription:
    'Dream data stays on your device by default. Cloud stays optional and does not block first capture.',
  privacyStorageLabel: 'Dream data',
  privacyStorageValue: 'On this device',
  privacyReminderLabel: 'Reminders',
  privacyReminderValue: 'Local notifications only',
  privacyFootnote:
    'If you delete the app, local entries, downloaded transcription model, and drafts may be removed with it until export or sync exists.',
  privacyOpenAction: 'How your data is handled',
  privacyScreenTitle: 'Your data',
  privacyScreenIntro:
    'Your dreams are stored on this device. Nothing is sent anywhere unless you turn on a feature that sends it, and each of those starts off.',
  privacyLocalTitle: 'Stays on this device',
  privacyLocalBody:
    'Dream text, titles, tags, moods, voice recordings and transcripts. Patterns, streaks and statistics are worked out here too, never on a server.',
  privacyLeavesTitle: 'What can leave, and when',
  privacyCloudTitle: 'Cloud backup, if you turn it on',
  privacyCloudBody:
    'Uploads your dream text, transcripts and recordings, encrypted on this device with a key the server never receives. The server can see how many dreams you have and when you last changed one — nothing about what is in them. The key travels to your other devices through iCloud Keychain or Android backup, and a recovery code is in these settings if you ever need it.',
  privacyCrashTitle: 'Crash reports, in builds set up for them',
  privacyCrashBody:
    'Sends the error, the app version and which screen was open. Dream text, titles, transcripts, tags and your identity are stripped out before anything is sent.',
  privacyAnalyticsTitle: 'Usage counts',
  privacyAnalyticsBody:
    'Counts of which screens and actions are used, so the app can be improved where it is actually failing people. Never your dreams, transcripts, titles, tags, symbols, searches or moods — the search event carries how long the query was and how many results it found, never what you typed. Not tied to your account.',
  privacyAnalyticsToggleLabel: 'Share usage counts',
  privacyModelTitle: 'The speech model, once',
  privacyModelBody:
    'Transcription runs on this device, but the model is downloaded the first time you use it. That request carries no dream data. Afterwards transcription works offline.',
  privacyLockTitle: 'The lock',
  privacyLockBody:
    'Biometrics are checked by the system; the app only learns whether it was accepted. The lock hides the screens — it does not encrypt the stored files.',
  privacyDeleteTitle: 'Deleting everything',
  privacyDeleteBody:
    'Removing the app deletes what is stored here, including recordings and drafts. Export first if you want to keep them. Anything already uploaded stays until you delete those dreams while backup is on.',
  privacyNoAccountNote:
    'There is no account, no profile and no analytics service. Offline, the app is complete.',
  archiveKeyTitle: 'The key to your archive',
  archiveKeyDescription:
    'Your dreams are encrypted before they are uploaded. This is the key that opens them.',
  archiveKeyTravelsIcloud:
    'Carried to your other Apple devices by iCloud Keychain. Nothing for you to do.',
  archiveKeyTravelsAndroid:
    'Carried to your next Android device by Google backup. Nothing for you to do.',
  archiveKeyStranded:
    'This key cannot leave this phone on its own — device backup is off. Save the recovery code, or the archive will only ever open here.',
  archiveKeyMissingForArchive:
    'The archive in the cloud was encrypted with a different key. Enter its recovery code to read it here. Nothing on this phone has been changed or deleted.',
  archiveKeyNotYetCreated:
    'The key is created the first time you sync. Until then there is nothing to keep.',
  archiveKeyRevealAction: 'Show recovery code',
  archiveKeyHideAction: 'Hide recovery code',
  archiveKeyCodeIntro:
    'Twenty-four words, in this order. They are the key itself — anyone who has them can read your archive. You need them only to move between iPhone and Android, or to restore a phone that had no backup.',
  archiveKeyEntryLabel: 'Recovery code',
  archiveKeyEntryPlaceholder: 'Paste or type the twenty-four words',
  archiveKeyEntryAction: 'Use this code',
  archiveKeyEntryInvalid:
    'That is not a complete code. Check for a missing or mistyped word — the code carries a checksum, so it can tell.',
  archiveKeyEntryAccepted: 'Key accepted. Sync again to read the archive.',
  archiveKeyStrandedDisclosureTitle:
    'This key cannot leave this phone on its own',
  archiveKeyStrandedDisclosureAction: 'Got it',
  cloudTitle: 'Cloud backup',
  cloudDescription: 'Optional device-to-device sync for one archive.',
  cloudConfigLabel: 'Runtime config',
  cloudConfigReady: 'Ready',
  cloudConfigMissing: 'Missing',
  cloudConfigUrlLabel: 'Supabase URL',
  cloudConfigUrlHint: 'Project URL, usually *.supabase.co.',
  cloudConfigAnonKeyLabel: 'Anon key',
  cloudConfigAnonKeyHint: 'Public anon key used by the mobile client.',
  cloudSessionLabel: 'Backup',
  cloudSessionSignedOut: 'Off',
  cloudSessionSignedIn: 'On',
  cloudAccountLabel: 'Account',
  cloudAccountDisconnected: 'Not linked yet',
  cloudAccountAnonymous: 'Needs email account',
  cloudPathTitle: 'What do you need on this device?',
  cloudPathDescription:
    'Choose whether this is the device where backup starts or one that should open an existing archive.',
  cloudPathThisDevice: 'Start here',
  cloudPathAnotherDevice: 'Open existing',
  cloudFirstDeviceTitle: 'Start backup on this device',
  cloudFirstDeviceDescription:
    'Create the backup on this device first, then save it under an email account if you want another device to open the same archive.',
  cloudGuideTitle: 'How backup works',
  cloudGuideStepOne: 'Turn on backup on your first device.',
  cloudGuideStepTwo:
    'Save it under an email account if you want the same archive on another device.',
  cloudGuideStepThree: 'Open that same backup on another device and run sync.',
  cloudGuideExistingStepOne:
    'Enter the same email and password you used for this backup before.',
  cloudGuideExistingStepTwo:
    'Open that archive on this device and let sync pull the latest changes.',
  cloudGuideExistingStepThree:
    'Keep sync on so edits and deletes continue moving between devices.',
  cloudGuideAnonymousStepOne: 'This device is already connected to backup.',
  cloudGuideAnonymousStepTwo: 'Save this backup under an email account next.',
  cloudGuideAnonymousStepThree: 'Then open the same backup on another device.',
  cloudGuideNamedStepOne: 'This backup is already linked to your account.',
  cloudGuideNamedStepTwo:
    'Open the same backup with this email on another device.',
  cloudGuideNamedStepThree: 'Keep sync on so changes move between devices.',
  cloudSuccessTitle: 'Next step',
  cloudConnectedSuccessTitle: 'Backup is on for this device',
  cloudConnectedSuccessDescription:
    'Save this backup under an email account next if you want another device to open the same archive.',
  cloudSignedInSuccessTitle: 'Existing backup opened',
  cloudSignedInSuccessDescription:
    'This device is now linked to your backup. Run sync now to pull the latest archive changes.',
  cloudUpgradedSuccessTitle: 'Backup account saved',
  cloudUpgradedSuccessDescription:
    'This backup is now linked to your email account. Open the same backup on another device with these credentials.',
  cloudResetSuccessTitle: 'Check your inbox',
  cloudResetSuccessDescription:
    'Open the reset link from that email, then come back and sign in with the new password.',
  backupCueOpenAction: 'Open backup',
  backupCueConnectTitle: 'Back up this archive',
  backupCueConnectDescription:
    'Keep this archive available on another device before more local-only changes pile up.',
  backupCueSyncOffTitle: 'Backup is connected, but sync is off',
  backupCueSyncOffDescription:
    'Turn sync back on before switching devices so newer local changes do not stay behind.',
  backupCueReviewPendingTitle: 'Saved review sets are newer on this device',
  backupCueReviewPendingDescription:
    'Saved months and threads changed locally. Open backup and run sync before switching devices.',
  backupOnboardingEyebrow: 'Archive started',
  backupOnboardingDismissAction: 'Close',
  backupOnboardingTitle: 'You already have dreams worth keeping',
  backupOnboardingDescription:
    'After a few entries, backup starts paying off. Save this archive before it becomes device-bound.',
  backupOnboardingDreamsLabel: 'Saved dreams',
  backupOnboardingThresholdLabel: 'Prompt threshold',
  backupOnboardingValueTitle: 'Why now',
  backupOnboardingValueDescription:
    'Backup keeps this archive restorable and makes saved review sets useful across devices once they start to accumulate.',
  backupOnboardingPrimaryAction: 'Open backup',
  backupOnboardingLaterAction: 'Later',
  backupOnboardingPreviewTitle: 'Backup onboarding preview',
  backupOnboardingPreviewDescription:
    'Debug the one-time backup prompt without waiting for a fresh account.',
  backupOnboardingPreviewSeenTitle: 'Seen state',
  backupOnboardingPreviewSeenValue: 'Seen',
  backupOnboardingPreviewUnseenValue: 'Unseen',
  backupOnboardingPreviewEligibilityTitle: 'Production gate',
  backupOnboardingPreviewEligibilityReady: 'Would open on Home now.',
  backupOnboardingPreviewEligibilityWaiting:
    'Needs 3 saved dreams and an unseen state.',
  backupOnboardingPreviewEligibilityReadyValue: 'Ready',
  backupOnboardingPreviewEligibilityWaitingValue: 'Waiting',
  backupOnboardingPreviewOpenAction: 'Open modal preview',
  backupOnboardingPreviewResetAction: 'Reset seen state',
  backupOnboardingPreviewMarkSeenAction: 'Mark as seen',
  backupOnboardingPreviewFootnote:
    'In production this modal opens once after the archive reaches 3 saved dreams.',
  reminderOnboardingEyebrow: 'Build the habit',
  reminderOnboardingTitle: 'A nightly nudge to write it down',
  reminderOnboardingDescription:
    'A gentle reminder before your usual wake time — never demanding, and easy to turn off.',
  reminderOnboardingPrimaryAction: 'Enable reminders',
  reminderOnboardingLaterAction: 'Not now',
  backupScreenTitle: 'Backup & sync',
  backupScreenSubtitle:
    'Restore backups bring data back into the app. Markdown, text, and PDFs are for reading or moving elsewhere. Cloud backup stays optional.',
  backupSummaryDescription:
    'Restore files, Markdown/text exports, PDFs, and optional cloud backup live here.',
  backupSummaryOpenTitle: 'Open backup workspace',
  backupLocalSectionTitle: 'Local files',
  backupLocalSectionDescription:
    'Create a restore backup, export readable Markdown or text, restore from backup, or export a PDF.',
  backupCloudSectionTitle: 'Cloud backup',
  backupCloudSectionDescription:
    'Optional sync for one archive across devices.',
  backupStatusTitle: 'Status details',
  backupStatusDescription:
    'Open this only when you need sync state or local-only details.',
  backupStatusToggleTitle: 'Cloud sync and local-only status',
  backupStatusToggleMetaCollapsed:
    'Hidden by default so the screen stays focused on backup, restore, and PDF actions.',
  backupStatusToggleMetaExpanded:
    'Shows recent sync state, latest restore backup, and what is still only on this device.',
  backupFlowGuideTitle: 'Choose the right file',
  backupFlowGuideDescription:
    'Each action creates or uses a different kind of file.',
  backupFlowBackupTitle: 'Backup export',
  backupFlowBackupMeta:
    'Creates a JSON restore file for this app. Use it later in Local restore or save it somewhere else.',
  backupFlowBackupValue: 'Restore file',
  backupFlowPortableTitle: 'Markdown / text export',
  backupFlowPortableMeta:
    'Creates readable .md or .txt files with stable structure and dream metadata. They are not restore files.',
  backupFlowPortableValue: 'Portable file',
  backupFlowPdfTitle: 'PDF export',
  backupFlowPdfMeta:
    'Creates a readable snapshot for reading or sharing. It is not a restore file.',
  backupFlowPdfValue: 'Readable file',
  backupFlowRestoreTitle: 'Restore',
  backupFlowRestoreMeta:
    'Applies a backup export to this device after preview. PDFs never appear here.',
  backupFlowRestoreValue: 'Applies backup',
  backupTimelineTitle: 'Cloud sync activity',
  backupTimelineDescription:
    'See the last cloud sync, latest restore backup, and this device state.',
  backupTimelineSyncTitle: 'Last successful sync',
  backupTimelineSnapshotTitle: 'Latest restore backup',
  backupTimelineDeviceTitle: 'This device',
  backupTimelineDeviceFreshnessLabel: 'Freshest local change',
  backupTimelineSnapshotMissing: 'No restore backup yet',
  backupTimelineSnapshotMissingMeta:
    'Create one restore backup and the latest preview will appear here.',
  backupTimelineDeviceLocalOnly: 'Local only',
  backupTimelineDeviceNeedsAttention: 'Needs attention',
  backupTimelineDeviceAheadSingle: '1 change ahead',
  backupTimelineDeviceAheadPlural: '{count} changes ahead',
  backupTimelineDeviceReviewAhead: 'Review sets ahead',
  backupTimelineDeviceCaughtUp: 'Caught up',
  backupTimelineDeviceWaitingFirstSync: 'Waiting for first sync',
  backupTimelineDeviceNoLocalChanges: 'No local changes yet',
  backupTimelineReviewSetsLabel: 'Review sets',
  backupTimelineReviewSetsPending: 'Review sets waiting for sync',
  backupContentTrustTitle: 'What is still only on this device',
  backupContentTrustDescription:
    'These counts show what has not reached cloud backup yet. Local backup files and PDFs are separate from this.',
  backupContentTrustAudioTitle: 'Voice notes',
  backupContentTrustAudioMeta: '{total} saved • {synced} already in cloud',
  backupContentTrustAudioEmpty: 'No voice notes yet',
  backupContentTrustAudioEmptyMeta:
    'Audio trust will appear here once a dream includes a voice note.',
  backupContentTrustAudioAllBackedUp: 'In cloud backup',
  backupContentTrustAudioStillLocalSingle: '1 still local',
  backupContentTrustAudioStillLocalPlural: '{count} still local',
  backupContentTrustTranscriptTitle: 'Saved transcripts',
  backupContentTrustTranscriptMeta: '{total} saved • {edited} edited',
  backupContentTrustTranscriptEmpty: 'No saved transcripts',
  backupContentTrustTranscriptEmptyMeta:
    'Transcript trust will appear here once a dream includes saved transcript text.',
  backupContentTrustTranscriptCaughtUp: 'Up to date in cloud',
  backupContentTrustTranscriptStillLocalSingle: '1 newer locally',
  backupContentTrustTranscriptStillLocalPlural: '{count} newer locally',
  backupContentTrustReviewTitle: 'Saved review sets',
  backupContentTrustReviewMeta:
    '{total} saved • {months} months • {threads} threads',
  backupContentTrustReviewEmpty: 'No saved sets yet',
  backupContentTrustReviewEmptyMeta:
    'Saved months and threads will appear here once you start curating review work.',
  backupContentTrustReviewCaughtUp: 'Up to date in cloud',
  backupContentTrustReviewStillLocal: 'Newer locally',
  backupContentTrustLocalOnly: 'Local only',
  cloudExistingBackupTitle: 'Open existing backup',
  cloudSaveBackupTitle: 'Save this backup',
  cloudIdentityTitle: 'Named account',
  cloudIdentityDescriptionSignedOut:
    'Sign in with the same email and password on another device to open the same archive.',
  cloudIdentityDescriptionAnonymous:
    'Save this backup under an email account so another device can open it.',
  cloudIdentityEmailLabel: 'Email',
  cloudIdentityEmailHint: 'Used for the same cloud account across devices.',
  cloudIdentityPasswordLabel: 'Password',
  cloudIdentityPasswordHint: 'Use at least 6 characters.',
  cloudCredentialsMissingTitle: 'Missing credentials',
  cloudCredentialsMissingDescription:
    'Enter an email and password before continuing.',
  cloudEmailMissingTitle: 'Missing email',
  cloudEmailMissingDescription: 'Enter the email for the backup account first.',
  cloudSyncToggleLabel: 'Auto sync',
  cloudSyncToggleHint:
    'Auto sync can be enabled only after cloud backup is connected.',
  cloudSyncDisabled: 'Off',
  cloudSyncEnabled: 'On',
  cloudPendingLabel: 'Pending',
  cloudSyncedLabel: 'Synced',
  cloudPulledLabel: 'Pulled',
  cloudSkippedLabel: 'Skipped',
  cloudConflictsLabel: 'Conflicts',
  cloudLocalWinsLabel: 'Local wins',
  cloudRemoteWinsLabel: 'Remote wins',
  cloudErrorsLabel: 'Errors',
  cloudSaveConfigButton: 'Save config',
  cloudClearConfigButton: 'Clear config',
  cloudConnectButton: 'Turn on backup',
  cloudConnectButtonBusy: 'Connecting...',
  cloudSignInExistingButton: 'Open existing backup',
  cloudSignInExistingButtonBusy: 'Signing in...',
  cloudResetPasswordButton: 'Send reset email',
  cloudResetPasswordButtonBusy: 'Sending email...',
  cloudUpgradeAccountButton: 'Save backup account',
  cloudUpgradeAccountButtonBusy: 'Saving account...',
  cloudDisconnectButton: 'Turn off backup',
  cloudDisconnectButtonBusy: 'Disconnecting...',
  cloudSyncNowButton: 'Sync now',
  cloudSyncNowButtonBusy: 'Syncing...',
  cloudLastSyncLabel: 'Last sync',
  cloudLastSyncNever: 'Never',
  cloudSyncStateIdle: 'Idle',
  cloudSyncStateSyncing: 'Syncing',
  cloudSyncStateSuccess: 'Synced',
  cloudSyncStateError: 'Needs attention',
  cloudSyncManualErrorTitle: 'Backup sync failed',
  cloudConfigMissingTitle: 'Supabase config missing',
  cloudConfigMissingDescription:
    'Add a valid project URL and anon key before connecting cloud.',
  cloudConfigErrorTitle: 'Cloud config error',
  cloudConnectErrorTitle: 'Backup connect failed',
  cloudAccountSignInErrorTitle: 'Account sign-in failed',
  cloudPasswordResetErrorTitle: 'Password reset failed',
  cloudPasswordResetSuccessTitle: 'Reset email sent',
  cloudPasswordResetSuccessDescription:
    'If this backup account exists, check that inbox for the password reset link.',
  cloudAccountUpgradeErrorTitle: 'Account upgrade failed',
  cloudDisconnectErrorTitle: 'Backup disconnect failed',
  cloudFootnote:
    'Cloud backup is optional sync between connected devices. Restore backups and PDFs are separate files, and this app does not add end-to-end encryption to them.',
  backupExportTitle: 'Backup export',
  backupExportDescription:
    'Create a JSON backup file for restore on this or another device.',
  backupExportFootnote:
    'Backup exports are plain files. Anyone with the file can read or import it. This app does not encrypt the file.',
  portableExportTitle: 'Markdown and text export',
  portableExportDescription:
    'Create a readable Markdown or plain-text file for portability. These files are not restore backups.',
  portableExportFootnote:
    'Markdown and text exports are plain files for reading, saving, or importing elsewhere. They stay separate from restore backups and PDFs.',
  pdfExportTitle: 'PDF export',
  pdfExportDescription:
    'Create a readable PDF for reference, printing, or sharing. It cannot be restored into the app.',
  pdfExportFootnote:
    'PDF exports are plain files for reading or sharing. This app does not encrypt the file.',
  exportTitle: 'Local export',
  exportDescription: 'Create a restore backup or a readable PDF snapshot.',
  exportLatestPathLabel: 'Latest file',
  exportFootnote: 'Backup is for restore later. PDF is for reading or sharing.',
  exportButton: 'Create backup',
  exportButtonBusy: 'Creating backup...',
  exportMarkdownButton: 'Create Markdown',
  exportMarkdownButtonBusy: 'Creating Markdown...',
  exportPdfButton: 'Create PDF',
  exportPdfButtonBusy: 'Rendering PDF...',
  exportTextButton: 'Create text',
  exportTextButtonBusy: 'Creating text...',
  exportOpenMarkdownButton: 'Open Markdown',
  exportOpenPdfButton: 'Open PDF',
  exportOpenTextButton: 'Open text',
  exportShareBackupButton: 'Share backup',
  exportShareMarkdownButton: 'Share Markdown',
  exportSharePdfButton: 'Share PDF',
  exportShareTextButton: 'Share text',
  exportBackupReadyTitle: 'Backup ready',
  exportBackupReadyDescription:
    'Use it later in Local restore, or share it to save a copy elsewhere.',
  exportMarkdownReadyTitle: 'Markdown export ready',
  exportMarkdownReadyDescription:
    'Open it to read now, or share it to keep a portable copy with stable structure.',
  exportPdfReadyTitle: 'PDF snapshot ready',
  exportPdfReadyDescription:
    'Open it now to read, or share it when you want to send it somewhere.',
  exportTextReadyTitle: 'Text export ready',
  exportTextReadyDescription:
    'Open it to read now, or share it to save a plain-text copy anywhere.',
  exportPdfOpenErrorTitle: 'Could not open PDF',
  exportPdfOpenErrorDescription:
    'Open failed on this device. Use Share PDF instead.',
  exportReadableOpenErrorTitle: 'Could not open export',
  exportReadableOpenErrorDescription:
    'Open failed on this device. Use Share instead.',
  exportErrorTitle: 'Export failed',
  exportPdfErrorTitle: 'PDF export failed',
  restoreTitle: 'Local restore',
  restoreDescription:
    'Choose a backup export, review it, then restore it on this device. PDFs cannot be restored.',
  restoreAvailableLabel: 'Available restore backups',
  restoreLoading: 'Loading restore backups...',
  restoreEmptyTitle: 'No restore backups yet',
  restoreEmptyDescription:
    'Create a backup export first, then it will appear here for preview and restore.',
  restorePreviewTitle: 'Restore preview',
  restoreSelectedValue: 'Selected',
  restoreModeLabel: 'Mode',
  restoreModeReplace: 'Replace',
  restoreModeMerge: 'Merge',
  restoreModeReplaceHint:
    'Replace local dreams, draft, locale, reminders, and analysis settings.',
  restoreModeMergeHint:
    'Add backup dreams, keep current settings, and import the backup draft only if the local draft is empty.',
  restoreNoBackupAction: 'Create a restore backup first',
  restoreSelectBackupAction: 'Choose a restore backup first',
  restoreLoadingAction: 'Preparing restore preview...',
  restoreReplaceWarning: 'Replace overwrites the local archive on this device.',
  restoreMergeGuidance:
    'Merge keeps current settings and adds dreams from the backup.',
  restoreFileLabel: 'File',
  restoreVersionLabel: 'Backup',
  restoreLocaleLabel: 'Locale',
  restoreDreamCountLabel: 'Dreams',
  restoreCurrentCountLabel: 'Now',
  restoreIncomingCountLabel: 'From backup',
  restoreNewCountLabel: 'New',
  restoreResultCountLabel: 'Result',
  restoreOverlapCountLabel: 'Overlap',
  restoreDraftLabel: 'Draft',
  restoreDraftPresent: 'Included',
  restoreDraftMissing: 'None',
  restoreSettingsLabel: 'Settings',
  restoreSettingsReplace: 'Backup settings replace local',
  restoreSettingsKeepCurrent: 'Current settings stay as they are',
  restoreDraftActionLabel: 'Draft',
  restoreDraftActionReplace: 'Backup draft replaces local draft',
  restoreDraftActionImportIfEmpty:
    'Backup draft imports only if local draft is empty',
  restoreExportedAtLabel: 'Exported',
  restoreAppVersionLabel: 'App',
  restoreRestoreButton: 'Replace with this backup',
  restoreMergeButton: 'Merge from this backup',
  restoreRestoreButtonBusy: 'Restoring...',
  restoreConfirmTitle: 'Replace local data?',
  restoreConfirmDescription:
    'This will replace local dreams, draft, locale, reminder settings, and analysis settings with the selected backup.',
  restoreMergeConfirmTitle: 'Merge backup into local data?',
  restoreMergeConfirmDescription:
    'This will add backup dreams to the current archive, keep current settings, and import the backup draft only if the local draft is empty.',
  restoreSuccessTitle: 'Backup restored',
  restoreSuccessDescription: 'Local data was replaced from:',
  restoreSuccessModeLabel: 'Applied mode',
  restoreSuccessCountLabel: 'Dreams now on device',
  restoreErrorTitle: 'Restore failed',
  transcriptionTitle: 'Offline transcription',
  transcriptionDescription:
    'Transcribe voice notes on device after one model download.',
  transcriptionStatusLabel: 'Model',
  transcriptionStatusInstalled: 'Downloaded',
  transcriptionStatusMissing: 'Not downloaded yet',
  transcriptionSizeLabel: 'Size',
  transcriptionPathLabel: 'Local file',
  transcriptionDownloadButton: 'Download offline model',
  transcriptionDownloadButtonBusy: 'Downloading model...',
  transcriptionDownloadSuccessTitle: 'Model ready',
  transcriptionDownloadSuccessDescription:
    'The offline transcription model is now stored locally on this device.',
  transcriptionDownloadErrorTitle: 'Could not download model',
  transcriptionDeleteButton: 'Delete local model',
  transcriptionDeleteButtonBusy: 'Deleting model...',
  transcriptionMissingHint:
    'Download the model once to enable offline transcription.',
  transcriptionDeleteSuccessTitle: 'Model removed',
  transcriptionDeleteSuccessDescription:
    'The offline transcription model was removed from local storage.',
  transcriptionDeleteErrorTitle: 'Could not remove model',
  scaleTestTitle: 'Scale test',
  scaleTestDescription: 'Generate sample dreams for stress testing.',
  developerToolsTitle: 'Developer tools',
  developerToolsDescription:
    'Debug-only tools for previews, seed data, and stress testing.',
  devSyncHistoryTitle: 'Recent sync attempts',
  devSyncHistoryDescription:
    'Debug-only history of the latest cloud sync outcomes on this device.',
  devSyncReasonManual: 'Manual',
  devSyncReasonLaunch: 'Launch',
  devSyncSnapshotTitle: 'Latest sync snapshot',
  devSyncSnapshotDescription:
    'Debug-only view of the latest stored sync result on this device.',
  devSyncSnapshotStatusTitle: 'Status',
  devSyncSnapshotReasonTitle: 'Reason',
  devSyncSnapshotPendingTitle: 'Pending changes',
  devSyncSnapshotPendingDreamsTitle: 'Pending dreams',
  devSyncSnapshotPendingDeletesTitle: 'Pending deletions',
  devSyncSnapshotPendingReviewTitle: 'Pending review sets',
  devSyncSnapshotUploadsTitle: 'Uploaded',
  devSyncSnapshotPullsTitle: 'Pulled',
  devSyncSnapshotConflictsTitle: 'Conflicts',
  devSyncSnapshotErrorsTitle: 'Last error',
  devSyncHistoryEmptyTitle: 'No sync attempts yet',
  devSyncHistoryEmptyDescription:
    'Run backup sync once and the latest debug history will appear here.',
  scaleTestSeededLabel: 'Sample dreams',
  scaleTestAdd250: 'Add 250',
  scaleTestAdd1000: 'Add 1000',
  scaleTestClear: 'Clear samples',
  scaleTestBusy: 'Working...',
  scaleTestClearTitle: 'Clear sample dreams?',
  scaleTestClearDescription:
    'This removes only generated sample dreams. Your own entries stay untouched.',
  scaleTestSeededTitle: 'Sample dreams ready',
  scaleTestSeededDescription:
    'The archive was filled with generated dreams for scale testing.',
  scaleTestErrorTitle: 'Could not prepare sample dreams',
  biometricLockTitle: 'App lock',
  biometricLockDescription:
    'Require Face ID, Touch ID, or fingerprint when opening the app.',
  biometricLockEnabledValue: 'On',
  biometricLockDisabledValue: 'Off',
  biometricLockNotSupportedValue: 'Not supported',
  biometricLockNotEnrolledValue: 'Not enrolled',
  biometricLockPrompt: 'Unlock Kaleidoscope',
  biometricLockUnlockLabel: 'Unlock',
  biometricLockScreenSubtitle: 'Your dreams are protected.',
  biometricLockAppName: 'Kaleidoscope',
  biometricLockEnableErrorTitle: 'Could not enable app lock',
  biometricLockEnableErrorUnsupported:
    'Your device does not support biometric authentication.',
  biometricLockEnableErrorNotEnrolled:
    'No biometrics are set up on this device. Enable Face ID or fingerprint in system settings first.',
  biometricLockEnableErrorFailed:
    'Biometric check failed. App lock was not enabled.',
  biometricOnboardingEyebrow: 'Keep it private',
  biometricOnboardingTitle: 'Add a lock to your dreams',
  biometricOnboardingDescription:
    'Face ID, Touch ID, or a fingerprint keeps entries private if someone else picks up your phone — easy to turn off anytime.',
  biometricOnboardingPrimaryAction: 'Enable app lock',
  biometricOnboardingLaterAction: 'Not now',
  analysisTitle: 'Dream analysis',
  analysisDescription: 'Generate a local reflection from saved dream data.',
  analysisProviderLabel: 'Provider',
  analysisProviderManual: 'Local manual',
  analysisProviderOpenAi: 'OpenAI (planned)',
  analysisNetworkLabel: 'Network',
  analysisNetworkAllowed: 'Allowed',
  analysisNetworkBlocked: 'Blocked',
  analysisLocalNetworkHint: 'Local analysis does not need network access.',
};

export type SettingsCopy = typeof SETTINGS_COPY_EN;
