import { AppLocale } from '../../i18n/types';
import {
  Mood,
  PreSleepEmotion,
  StressLevel,
  WakeEmotion,
} from '../../features/dreams/model/dream';

const DREAM_COPY_EN = {
  homeTitle: 'Dream log',
  homeSubtitle: 'Capture quickly. Revisit patterns later.',
  homeGreeting: 'Good morning',
  homeGreetingMorning: 'Good morning',
  homeGreetingAfternoon: 'Good afternoon',
  homeGreetingEvening: 'Good evening',
  homeGreetingNight: 'Still awake?',
  homeRecordNow: 'Record now',
  homeContinueDraft: 'Continue draft',
  homeDraftShortcutHint: 'Your unfinished capture is waiting.',
  homeLastDreamLabel: 'Return to last dream',
  homeLastDreamMetaPrefix: 'Last open',
  homeSectionLabel: 'Recent dreams',
  homeOpenArchive: 'Archive',
  homeRecentLimitHint: 'Home stays focused on the latest dreams. Switch to the Archive tab for the full history.',
  homeSpotlightTitle: 'In focus',
  homeSpotlightSubtitle: 'One recurring signal and one thing worth cleaning up.',
  homeSpotlightPatternLabel: 'Pattern',
  homeSpotlightWeeklyLabel: 'This week',
  homeSpotlightAttentionLabel: 'Needs attention',
  homeSpotlightNoPattern: 'Still forming',
  homeSpotlightAttentionClear: 'All clear',
  homeSpotlightWeeklyOnTrack: 'Warm streak',
  homeSpotlightWeeklyOffTrack: 'One more helps',
  homeSpotlightAttentionAudioSingle: '1 voice note',
  homeSpotlightAttentionAudioPlural: 'voice notes',
  homeSpotlightAttentionMoodSingle: '1 dream missing mood',
  homeSpotlightAttentionMoodPlural: 'dreams missing mood',
  homeSpotlightAttentionAudioHint: 'Transcripts would make them easier to revisit.',
  homeSpotlightAttentionMoodHint: 'A quick wake mood would make patterns clearer later.',
  homeSpotlightAttentionClearHint: 'Nothing obvious needs cleanup right now.',
  homeSpotlightRevisitLabel: 'Revisit now',
  homeSpotlightRevisitAction: 'Open dream',
  homeSpotlightRevisitActionThread: 'Open thread',
  homeSpotlightRevisitActionAnalysis: 'Review reflection',
  homeSpotlightRevisitActionTranscript: 'Clean transcript',
  homeSpotlightRevisitActionTime: 'Reopen memory',
  homeSpotlightRevisitEmpty: 'No older dream is asking for attention yet.',
  homeSpotlightRevisitContextThread: 'Thread nearby',
  homeSpotlightRevisitContextAnalysis: 'Reflection ready',
  homeSpotlightRevisitContextTranscript: 'Transcript ready',
  homeSpotlightRevisitContextTime: 'Time marker',
  homeSpotlightRevisitContextSignal: 'Signal worth naming',
  homeSpotlightRevisitReasonThreadPrefix: 'Thread with ',
  homeSpotlightRevisitReasonThreadSuffix: ' nearby dreams',
  homeSpotlightRevisitReasonAnalysis: 'Has a saved reflection to test again',
  homeSpotlightRevisitReasonTranscript: 'Transcript is ready for cleanup',
  homeSpotlightRevisitReasonTimePrefix: 'Resurfacing from ',
  homeSpotlightRevisitReasonTimeSuffix: ' and worth reopening before it fades again.',
  homeSpotlightRevisitTimeWeek: 'about a week ago',
  homeSpotlightRevisitTimeMonth: 'about a month ago',
  homeSpotlightRevisitTimeQuarter: 'about three months ago',
  homeSpotlightRevisitTimeHalfYear: 'about six months ago',
  homeSpotlightRevisitTimeYear: 'about a year ago',
  homeSpotlightRevisitReasonSignal: 'Still carries a clear signal worth naming',
  homeSpotlightShowDetails: 'More details',
  homeSpotlightHideDetails: 'Less details',
  homeStreakLabel: 'Streak',
  homeTotalLabel: 'Total',
  homeAverageLabel: 'Avg words',
  homeDaysUnit: 'days',
  homeFilterAll: 'All',
  homeFilterActive: 'Current',
  homeFilterArchived: 'Archived',
  homeFilterStarred: 'Important',
  homeArchiveFilterLabel: 'Status',
  homeSearchLabel: 'Search dreams',
  homeSearchPlaceholder: 'Title, notes, transcript, or tag',
  homeSaveSearchPreset: 'Save search',
  homeSearchShowDetails: 'Saved searches',
  homeSearchHideDetails: 'Hide saved',
  homeSavedSearchesLabel: 'Saved searches',
  homeSearchPresetFallback: 'Quick search',
  homeSearchPresetRemove: 'Remove saved search',
  homeSearchPresetDeleteTitle: 'Remove this saved search?',
  homeSearchPresetDeleteDescription:
    'This removes the saved filter combination, but your dreams stay untouched.',
  homeSearchMatchTitle: 'Title',
  homeSearchMatchNotes: 'Notes',
  homeSearchMatchTranscript: 'Transcript',
  homeSearchMatchTag: 'Tag',
  homeSearchMatchContext: 'Context',
  homeClearSearch: 'Clear search',
  homeRefineLabel: 'Refine timeline',
  homeShowFilters: 'Filters',
  homeHideFilters: 'Hide filters',
  homeMoodFilterLabel: 'Mood',
  homeMoodFilterAll: 'Any mood',
  homeTypeFilterLabel: 'Entry type',
  homeTypeFilterAll: 'Any type',
  homeTypeFilterText: 'Text',
  homeTypeFilterAudio: 'Audio',
  homeTypeFilterMixed: 'Mixed',
  homeTranscriptFilterLabel: 'Transcript',
  homeTranscriptFilterAll: 'Any transcript state',
  homeTranscriptFilterWithTranscript: 'Has transcript',
  homeTranscriptFilterAudioOnly: 'Audio only',
  homeTranscriptFilterEdited: 'Edited transcript',
  homeDateRangeFilterLabel: 'Date range',
  homeDateRangeAll: 'Any time',
  homeDateRange7d: 'Last 7 days',
  homeDateRange30d: 'Last 30 days',
  homeDateRange90d: 'Last 90 days',
  homeSortFilterLabel: 'Sort',
  homeSortFilterNewest: 'Newest first',
  homeSortFilterOldest: 'Oldest first',
  homeTagFilterLabel: 'Tags',
  homeTagSearchPlaceholder: 'Search tags',
  homeTagSelectedLabel: 'Selected tags',
  homeTagsShowMore: 'Show all tags',
  homeTagsShowLess: 'Show fewer',
  homeTagsEmpty: 'No tags match this search.',
  homeClearFilters: 'Clear filters',
  homeResultsSingle: 'entry',
  homeResultsPlural: 'entries',
  homeSearchEmptyTitle: 'Nothing matches these filters',
  homeSearchEmptyDescription:
    'Try a simpler phrase, switch filters, or clear them to see more dreams.',
  homeQuickOpen: 'Open',
  actionRetry: 'Retry',
  clearErrorAction: 'Dismiss',
  timelineLoadingTitle: 'Loading timeline',
  timelineLoadingDescription: 'Refreshing local entries...',
  timelineErrorTitle: 'Could not load timeline',
  timelineErrorDescription: 'Try again. Local storage may be temporarily unavailable.',
  openDreamHint: 'Tap to open. Hold for quick actions.',
  swipeEdit: 'Edit',
  swipeDelete: 'Delete',
  swipeArchive: 'Archive',
  swipeUnarchive: 'Unarchive',
  emptyTitle: 'No dreams yet',
  emptyDescription:
    'Capture the first one from the + button. Keep it fast: title, voice note, or a few raw lines are enough.',
  emptyActiveTitle: 'No active dreams',
  emptyActiveDescription:
    'All entries are archived right now. Switch filter or record a new dream.',
  emptyArchivedTitle: 'No archived dreams',
  emptyArchivedDescription:
    'Archive older entries to keep the timeline focused.',
  archiveTitle: 'Archive',
  archiveSubtitle:
    'Browse past dreams month by month.',
  archiveSearchPlaceholder: 'Search current month',
  archiveSearchScopeHint: 'Search applies only to the current month.',
  archiveResetView: 'Reset view',
  archiveCalendarTitle: 'Calendar',
  archiveCalendarSubtitle: 'Jump by month or tap a day with dreams.',
  archiveCalendarShowGrid: 'Show days',
  archiveCalendarHideGrid: 'Hide days',
  archiveBrowseLabel: 'View',
  archiveBrowseComfortable: 'Cards',
  archiveBrowseCompact: 'List',
  archiveMonthEntriesLabel: 'entries',
  archiveMonthActiveDaysLabel: 'active days',
  archivePreviousMonth: 'Older',
  archiveNextMonth: 'Newer',
  archiveAllDates: 'All dates',
  archiveSelectedDatePrefix: 'Selected',
  archiveWeekdaySun: 'Su',
  archiveWeekdayMon: 'Mo',
  archiveWeekdayTue: 'Tu',
  archiveWeekdayWed: 'We',
  archiveWeekdayThu: 'Th',
  archiveWeekdayFri: 'Fr',
  archiveWeekdaySat: 'Sa',
  archiveRevisitLabel: 'Reopen from this month',
  archiveRevisitAction: 'Open detail',
  archiveRevisitActionAnalysis: 'Review reflection',
  archiveRevisitActionTranscript: 'Clean transcript',
  archiveRevisitEmpty: 'No strong revisit cue in this archive slice yet.',
  archiveRevisitContextImportant: 'Important',
  archiveRevisitContextAnalysis: 'Reflection ready',
  archiveRevisitContextTranscript: 'Transcript ready',
  archiveRevisitContextArchived: 'Archived',
  archiveRevisitContextSignal: 'Detail to keep',
  archiveRevisitReasonImportant: 'Marked important and worth another look',
  archiveRevisitReasonAnalysis: 'Saved reflection is ready to revisit',
  archiveRevisitReasonTranscript: 'Transcript is ready for cleanup',
  archiveRevisitReasonArchived: 'Older archived dream worth reopening',
  archiveRevisitReasonSignal: 'Still carries a detail worth keeping alive',
  archiveEmptyTitle: 'Archive is empty',
  archiveEmptyDescription: 'Save a few dreams first, then the archive will start grouping them here.',
  archiveEmptyCurrentTitle: 'No open dreams',
  archiveEmptyCurrentDescription: 'Everything in this month is already filed away or filtered out.',
  archiveEmptyArchivedTitle: 'Nothing filed away yet',
  archiveEmptyArchivedDescription: 'Archive a few older dreams and they will start showing up here.',
  archiveEmptyImportantTitle: 'No important dreams yet',
  archiveEmptyImportantDescription: 'Mark a few dreams as important to keep them easy to revisit later.',
  archiveNoResultsTitle: 'Nothing matches this archive view',
  archiveNoResultsDescription:
    'Try another month, clear the day, or reset the current search and filters.',
  archiveFilterAll: 'Everything',
  archiveFilterActive: 'Open',
  archiveFilterArchived: 'Past',
  archiveFilterStarred: 'Important',
  untitled: 'Untitled dream',
  archivedTag: 'Archived',
  starredTag: 'Important',
  audioTag: 'Audio',
  transcriptTag: 'Transcript',
  editedTranscriptTag: 'Edited',
  transcriptPreviewPrefix: 'Transcript',
  editedTranscriptPreviewPrefix: 'Edited transcript',
  audioOnlyPreview: 'Voice note saved. Transcript can be added later.',
  noDetailsPreview: 'No written details yet.',
  detailBack: 'Back',
  detailEdit: 'Edit dream',
  detailStar: 'Mark important',
  detailUnstar: 'Remove important',
  detailArchive: 'Archive dream',
  detailUnarchive: 'Unarchive dream',
  detailDelete: 'Delete dream',
  detailDeleteTitle: 'Delete this dream?',
  detailDeleteDescription:
    'This action removes the entry from local storage and cannot be undone.',
  detailDeleteCancel: 'Cancel',
  detailDeleteConfirm: 'Delete',
  detailMissingTitle: 'Dream not found',
  detailMissingDescription:
    'This entry is no longer available in local storage.',
  detailMetaTitle: 'At a glance',
  detailCapturedLabel: 'Captured',
  detailPreviewLabel: 'Preview',
  detailActionEdit: 'Edit',
  detailActionImportant: 'Important',
  detailActionArchive: 'Archive',
  detailActionRestore: 'Restore',
  detailActionDelete: 'Delete',
  detailSavedTitle: 'Dream captured',
  detailSavedDescription:
    'The raw note is safe. Refine it later if needed.',
  detailSavedPatternLabel: 'Strongest signal',
  detailSavedRelatedLabel: 'Related dreams',
  detailReflectionTitle: 'Revisit now',
  detailReflectionSignalTitle: 'Name the signal',
  detailReflectionSignalPrefix: 'This dream keeps pointing to ',
  detailReflectionSignalSuffix:
    '. Add one line about why that signal matters right now.',
  detailReflectionEmotionTitle: 'Catch the feeling',
  detailReflectionEmotionWithMoodPrefix: 'The emotional tone still leans toward ',
  detailReflectionEmotionWithMoodSuffix:
    '. Write what stayed in your body after waking.',
  detailReflectionEmotionBody:
    'Write what feeling stayed in your body after waking, even if it only lasted a few seconds.',
  detailReflectionThreadTitle: 'Follow the thread',
  detailReflectionThreadPrefix: 'This dream already touches ',
  detailReflectionThreadSuffix:
    '. Open one nearby dream and note what repeats or shifts.',
  detailReflectionAnalysisTitle: 'Test the meaning',
  detailReflectionAnalysisPrefix: 'Your saved summary points to: ',
  detailReflectionAnalysisSuffix:
    ' Decide whether that still feels true.',
  detailReflectionTranscriptTitle: 'Make the transcript usable',
  detailReflectionTranscriptBody:
    'One quick cleanup pass will make this voice memory easier to search and revisit later.',
  detailReflectionResurfaceTitle: 'What still holds now',
  detailReflectionResurfacePrefix: 'This dream is resurfacing from ',
  detailReflectionResurfaceSuffix:
    '. Add one line about what still feels true now.',
  detailReflectionCaptureTitle: 'Keep one vivid detail',
  detailReflectionCaptureBody:
    'Add one concrete image, place, or sentence that your future self will still understand in a week.',
  detailReflectionFallbackTitle: 'Leave a trace for later',
  detailReflectionFallbackBody:
    'Add one short note your future self would thank you for.',
  detailReflectionActionEdit: 'Add detail',
  detailReflectionActionRelated: 'Open thread',
  detailReflectionActionAnalysis: 'Review analysis',
  detailCaptureTitle: 'Capture',
  detailCaptureEmpty: 'This dream has not been filled with text or audio yet.',
  detailTranscriptTitle: 'Written notes',
  detailTranscriptEmpty: 'No written notes saved for this dream yet.',
  detailGlanceCaptureLabel: 'Entry',
  detailGlanceTranscriptLabel: 'Transcript',
  detailGlanceAnalysisLabel: 'Analysis',
  detailGlanceRelatedLabel: 'Related',
  detailCaptureModeText: 'Note',
  detailCaptureModeVoice: 'Voice',
  detailCaptureModeMixed: 'Mixed',
  detailTranscriptSummaryIdle: 'None',
  detailTranscriptSummaryReady: 'Ready',
  detailTranscriptSummaryEdited: 'Edited',
  detailTranscriptSummaryProcessing: 'Working',
  detailTranscriptSummaryError: 'Retry',
  detailGeneratedTranscriptTitle: 'Generated transcript',
  detailGeneratedTranscriptEmpty: 'No transcript has been generated from this voice note yet.',
  detailGeneratedTranscriptHint:
    'Transcription runs on device and keeps the original voice note untouched.',
  detailGeneratedTranscriptProcessing:
    'Transcription is running locally on this device. Keep the app open until it finishes.',
  detailGeneratedTranscriptError:
    'The last transcription attempt did not finish. The original voice note is still saved.',
  detailGeneratedTranscriptReplaceError:
    'The latest replace attempt failed. The previous transcript is still saved locally.',
  detailGeneratedTranscriptSourceLabel: 'Source',
  detailGeneratedTranscriptSourceGenerated: 'Generated from audio',
  detailGeneratedTranscriptSourceEdited: 'Edited by hand',
  detailGeneratedTranscriptUpdatedLabel: 'Updated',
  detailGeneratedTranscriptEdit: 'Edit transcript',
  detailGeneratedTranscriptSave: 'Save transcript',
  detailGeneratedTranscriptCancel: 'Cancel editing',
  detailGeneratedTranscriptClear: 'Clear transcript',
  detailGeneratedTranscriptReplace: 'Replace transcript',
  detailGeneratedTranscriptEmptyErrorTitle: 'Transcript is empty',
  detailGeneratedTranscriptEmptyErrorDescription:
    'Write at least one line before saving, or clear the transcript instead.',
  detailGeneratedTranscriptSaveSuccessTitle: 'Transcript updated',
  detailGeneratedTranscriptSaveSuccessDescription:
    'The edited transcript is saved locally and remains searchable.',
  detailGeneratedTranscriptClearTitle: 'Clear transcript?',
  detailGeneratedTranscriptClearDescription:
    'This removes the saved transcript but keeps the original voice note on device.',
  detailAnalysisTitle: 'Dream analysis',
  detailAnalysisEmpty:
    'No analysis is saved for this dream yet. Generate one to turn this entry into a short local reflection.',
  detailAnalysisDisabled:
    'The analysis layer is disabled in Settings, so this dream stays as raw capture only.',
  detailAnalysisSummaryLabel: 'Summary',
  detailAnalysisThemesLabel: 'Themes',
  detailAnalysisStateLabel: 'Analysis mode',
  detailAnalysisStateLocalReady: 'Local analysis is on and ready for this dream.',
  detailAnalysisStateDisabled: 'Analysis is off. Enable it in Settings when you want summaries and themes.',
  detailAnalysisStateOpenAiPlanned:
    'OpenAI is selected in Settings, but network analysis is still a planned path in this release.',
  detailAnalysisStateManual: 'This dream can generate a local summary from saved text, transcript, tags, and context.',
  detailAnalysisProviderLabel: 'Provider',
  detailAnalysisUpdatedLabel: 'Updated',
  detailAnalysisStatusLabel: 'Status',
  detailAnalysisStatusReady: 'Ready',
  detailAnalysisStatusError: 'Error',
  detailAnalysisStatusIdle: 'Not generated',
  detailAnalysisSummaryReady: 'Ready',
  detailAnalysisSummaryIdle: 'None',
  detailAnalysisSummaryDisabled: 'Off',
  detailAnalysisSummaryPlanned: 'Plan',
  detailAnalysisProviderManual: 'Local',
  detailAnalysisProviderOpenAi: 'OpenAI (planned)',
  detailAnalysisGenerate: 'Generate analysis',
  detailAnalysisRegenerate: 'Regenerate analysis',
  detailAnalysisClear: 'Clear analysis',
  detailAnalysisGenerating: 'Generating local analysis...',
  detailAnalysisOpenSettings: 'Open Settings',
  detailAnalysisOpenAiUnavailable:
    'The OpenAI provider is configured in Settings, but it is still a planned path in this release.',
  detailAnalysisErrorTitle: 'Analysis failed',
  detailAnalysisGenerateErrorDescription:
    'The dream is still saved locally. Try the manual provider or keep this slot empty for now.',
  detailTranscribeAudio: 'Transcribe audio',
  detailTranscribeRetry: 'Retry transcription',
  detailTranscribePreparingModel: 'Preparing offline model',
  detailTranscribeInProgress: 'Transcribing on device',
  detailTranscriptionErrorTitle: 'Transcription failed',
  detailTranscriptionErrorDescription:
    'The voice note is still saved locally. Try again in a quieter moment or after the model finishes downloading.',
  detailTagsEmpty: 'No tags attached yet.',
  detailRelatedTitle: 'Nearby dreams',
  detailRelatedDescription:
    'Earlier dreams linked by shared signals, repeated words, and emotional echoes.',
  detailRelatedEmpty:
    'Save a few more dreams and the first clear thread will start taking shape.',
  detailRelatedSummaryEmpty: 'None',
  detailRelatedMatchSingular: 'match',
  detailRelatedMatchPlural: 'matches',
  detailRelatedSharedLabel: 'Thread signals',
  detailRelatedRecurringLabel: 'Seen before',
  detailStateTitle: 'Sleep context',
  detailStateEmpty: 'No wake-up emotions or pre-sleep context were saved for this dream.',
  detailAudioDescription: 'An original voice note is attached to this dream.',
  detailAudioPathLabel: 'Local file',
  detailAudioPlay: 'Play voice note',
  detailAudioStop: 'Stop playback',
  detailAudioPlaybackHint: 'Listen back to verify the original capture is still usable.',
  detailAudioPlaybackErrorTitle: 'Playback error',
  detailAudioAttachedMeta: 'Attached',
  createTitle: 'Capture a dream',
  createSubtitle:
    'Capture the shape now. Sort the details later.',
  quickAddKicker: 'Quick add',
  quickAddWakeAction: 'Wake capture',
  quickAddWakeHint: 'Open the compressed morning flow for a quick voice or text capture.',
  quickAddVoiceAction: 'Voice note',
  quickAddVoiceHint: 'Open the composer in voice-first mode and start recording fast.',
  quickAddTextAction: 'Write note',
  quickAddTextHint: 'Open the composer and type what is still there.',
  quickAddContinueHint: 'Pick up the saved local draft exactly where you left it.',
  wakeEntryKicker: 'Wake flow',
  wakeEntryTitle: 'Before it slips away',
  wakeEntryDescription:
    'One calm screen after the reminder. Tap the center to write, or choose voice below.',
  wakeEntryOrbAction: 'Write',
  wakeEntryOrbHint: 'Tap the center and start with raw lines.',
  wakeEntryWriteAction: 'Write now',
  wakeEntryAlternateTitle: 'Other ways to capture',
  wakeEntrySpeakAction: 'Speak instead',
  wakeEntrySpeakHint: 'Start with voice if speaking is faster than typing.',
  wakeEntryDraftAction: 'Continue draft',
  wakeEntryDraftHint: 'Pick up the unfinished capture already saved locally.',
  wakeModeChip: 'Wake mode',
  wakeHeroTitle: 'Catch the first shape',
  wakeHeroDescription:
    'Voice first, raw lines second. Title, tags, and context can wait.',
  wakeCaptureTitle: 'Voice or raw lines',
  wakeCaptureDescription:
    'Start with the fastest thing that is still alive: a voice note, a few words, or both.',
  wakeCaptureAlternateTitle: 'Or record instead',
  wakeCaptureVoiceHint: 'Use voice if speaking is faster than typing right now.',
  wakeVoiceDescription: 'Start recording now or drop a few raw lines below.',
  wakeCoreTitle: 'Raw memory',
  wakeCoreDescription: 'Keep only what is still vivid. Structure can come later.',
  wakeTextLabel: 'What is still here?',
  wakeTextPlaceholder: 'A place, a face, a feeling, a line...',
  wakeRefineTitle: 'Add later if it helps',
  wakeRefineDescription:
    'Keep wake capture light. Title, tags, and before-sleep context are still here when you need them.',
  wakeRefineMetaAction: 'Title + date',
  wakeMetaTitle: 'Title and sleep date',
  wakeMetaDescription: 'Only add these now if they help anchor the memory.',
  wakeReadyHint: 'A voice note, a few raw lines, and a waking feeling are enough to save.',
  createHeroTitle: 'Capture before it fades',
  createHeroDescription:
    'Start with voice or a few raw lines.',
  recordEmptyTitle: 'Start with a quick capture',
  recordEmptyDescription:
    'Start with text or voice. Everything else can wait.',
  recordDraftRestoredTitle: 'Draft restored',
  recordDraftRestoredDescription:
    'Your unfinished capture is still here. Keep writing or save it when ready.',
  recordLoadingTitle: 'Working on it',
  recordLoadingDescription: 'Please wait while the action is completing.',
  recordErrorTitle: 'Action failed',
  recordErrorDescription: 'Try again or continue with text-only capture for now.',
  refineTitle: 'Refine later',
  refineDescription: 'Mood, context, and tags can stay lightweight. Add them only if they help.',
  refineReadyHint: 'A raw text or voice capture is enough to save.',
  refineMoodAction: 'Mood',
  refineContextAction: 'Before sleep',
  refineTagsAction: 'Tags',
  refineHideAction: 'Hide',
  editTitle: 'Edit dream',
  editSubtitle:
    'Refine the memory without losing the original entry.',
  editHeroTitle: 'Polish the memory',
  editHeroDescription:
    'Update details while the dream is still meaningful, without losing the original entry.',
  coreTitle: 'Core details',
  coreDescription: 'Title is optional. Capture the core memory first.',
  titleLabel: 'Dream title',
  titlePlaceholder: 'Flying over old rooftops',
  sleepDateLabel: 'Sleep date',
  sleepDatePlaceholder: 'YYYY-MM-DD',
  sleepDateInvalidTitle: 'Invalid sleep date',
  sleepDateInvalidDescription: 'Use format YYYY-MM-DD and a real calendar date.',
  textLabel: 'What do you remember?',
  textPlaceholder: 'Write the dream while it is still fresh...',
  wordsUnit: 'words',
  moodTitle: 'Mood after waking',
  moodDescription: 'Quick after-waking signals for later patterns.',
  wakeEmotionsTitle: 'Emotions after waking',
  wakeEmotionsDescription:
    'Quick signals from the first minute after waking, before the dream starts to flatten out.',
  sleepContextTitle: 'Before sleep context',
  sleepContextDescription:
    'Small signals before sleep that may explain the dream.',
  preSleepEmotionsLabel: 'Emotions before sleep',
  stressLabel: 'Stress level',
  alcoholLabel: 'Alcohol before sleep',
  caffeineLabel: 'Late caffeine',
  medicationsLabel: 'Medications or supplements',
  medicationsPlaceholder: 'e.g. melatonin 3mg',
  eventsLabel: 'Important events',
  eventsPlaceholder: 'e.g. exams, conflict, celebration',
  healthNotesLabel: 'Health notes',
  healthNotesPlaceholder: 'e.g. headache, anxiety, low mood',
  boolYes: 'Yes',
  boolNo: 'No',
  detailEmotionTitle: 'Emotional snapshot',
  detailEmotionEmpty: 'No wake-up or pre-sleep emotions were saved for this dream.',
  detailWakeEmotionsLabel: 'After waking',
  detailPreSleepEmotionsLabel: 'Before sleep',
  detailContextTitle: 'Pre-sleep context',
  detailContextEmpty: 'No pre-sleep context was saved for this dream.',
  tagsTitle: 'Tags',
  tagsDescription: 'Symbols, people, places, recurring fragments.',
  tagsPlaceholder: 'ocean',
  tagsEmpty: 'No tags yet. Tap add to save your first one.',
  voiceTitle: 'Voice note',
  voiceDescription: 'Start fast. Refine later.',
  voiceIdleHint: 'One tap starts a raw voice capture.',
  startRecording: 'Start recording',
  stopRecording: 'Stop recording',
  recordingHint: 'Recording in progress. Stop when you are done.',
  attachedAudioTitle: 'Voice note attached',
  removeAudio: 'Remove voice note',
  addTag: 'Add',
  saveDream: 'Save dream',
  updateDream: 'Update dream',
  saveErrorTitle: 'Nothing to save',
  saveErrorDescription:
    'Write what you remember or attach a voice note first. Title alone is not enough.',
  saveSuccessTitle: 'Saved',
  saveSuccessDescription: 'Your dream was saved locally.',
  postSaveTitle: 'Capture saved',
  postSaveDescription:
    'It is safe locally now. Keep capturing, or open this dream if you want to refine it.',
  postSaveSavedLabel: 'Saved entry',
  postSaveNextStepLabel: 'Next step',
  postSaveFollowUpReflectionTitle: 'Revisit while it is still vivid',
  postSaveFollowUpReflectionDescription:
    'Open this dream and use the reflection prompts to keep one sharp detail alive.',
  postSaveFollowUpReflectionAction: 'Open revisit prompts',
  postSaveFollowUpRefineTitle: 'Add one concrete detail',
  postSaveFollowUpRefineDescription:
    'Open the capture and write one image, place, or line your future self will still understand.',
  postSaveFollowUpRefineAction: 'Refine this dream',
  postSaveFollowUpTranscriptTitle: 'Turn the voice note into usable text',
  postSaveFollowUpTranscriptDescription:
    'Open this dream and clean up the transcript while the memory is still close.',
  postSaveFollowUpTranscriptAction: 'Work on transcript',
  postSaveCaptureAnother: 'Keep capturing',
  postSaveRecordAnother: 'Record another',
  postSaveOpenDetail: 'Open this dream',
  postSaveContinueLater: 'Continue later',
  postSaveFooterHint: 'You can switch tabs anytime.',
  updateSuccessTitle: 'Updated',
  updateSuccessDescription: 'Your dream was updated locally.',
  audioErrorTitle: 'Audio error',
  audioSimulatorHint:
    'Voice capture may be unavailable on the iOS Simulator. Use text here or test recording on a real device.',
};

const DREAM_COPY_UK: typeof DREAM_COPY_EN = {
  ...DREAM_COPY_EN,
  homeTitle: 'Щоденник снів',
  homeSubtitle: 'Записуй швидко. До патернів повернешся пізніше.',
  homeGreeting: 'Доброго ранку',
  homeGreetingMorning: 'Доброго ранку',
  homeGreetingAfternoon: 'Доброго дня',
  homeGreetingEvening: 'Доброго вечора',
  homeGreetingNight: 'Ще не спиш?',
  homeRecordNow: 'Записати зараз',
  homeContinueDraft: 'Продовжити чернетку',
  homeDraftShortcutHint: 'Незавершений запис чекає на тебе.',
  homeLastDreamLabel: 'Повернутись до останнього сну',
  homeLastDreamMetaPrefix: 'Останнє відкриття',
  homeSectionLabel: 'Останні сни',
  homeOpenArchive: 'Архів',
  homeRecentLimitHint: 'Головний екран тримає фокус на останніх записах. Для повної історії перемкнись на вкладку Архів.',
  homeSpotlightTitle: 'У фокусі',
  homeSpotlightSubtitle: 'Один повторюваний сигнал і одна річ, яку варто розчистити.',
  homeSpotlightPatternLabel: 'Патерн',
  homeSpotlightWeeklyLabel: 'Цей тиждень',
  homeSpotlightAttentionLabel: 'Потребує уваги',
  homeSpotlightNoPattern: 'Ще формується',
  homeSpotlightAttentionClear: 'Все чисто',
  homeSpotlightWeeklyOnTrack: 'Ритм теплий',
  homeSpotlightWeeklyOffTrack: 'Ще один запис допоможе',
  homeSpotlightAttentionAudioSingle: '1 голосовий запис',
  homeSpotlightAttentionAudioPlural: 'голосових записів',
  homeSpotlightAttentionMoodSingle: '1 сон без настрою',
  homeSpotlightAttentionMoodPlural: 'снів без настрою',
  homeSpotlightAttentionAudioHint: 'Транскрипт зробить їх легшими для повернення.',
  homeSpotlightAttentionMoodHint: 'Швидкий настрій після пробудження зробить патерни яснішими.',
  homeSpotlightAttentionClearHint: 'Зараз нічого очевидного не потребує cleanup.',
  homeSpotlightRevisitLabel: 'Повернутись зараз',
  homeSpotlightRevisitAction: 'Відкрити сон',
  homeSpotlightRevisitActionThread: 'Відкрити нитку',
  homeSpotlightRevisitActionAnalysis: 'Звірити рефлексію',
  homeSpotlightRevisitActionTranscript: 'Доробити транскрипт',
  homeSpotlightRevisitActionTime: 'Повернути спогад',
  homeSpotlightRevisitEmpty: 'Ще немає старішого сну, який явно просить уваги.',
  homeSpotlightRevisitContextThread: 'Поруч є нитка',
  homeSpotlightRevisitContextAnalysis: 'Рефлексія готова',
  homeSpotlightRevisitContextTranscript: 'Транскрипт готовий',
  homeSpotlightRevisitContextTime: 'Часовий слід',
  homeSpotlightRevisitContextSignal: 'Сигнал варто назвати',
  homeSpotlightRevisitReasonThreadPrefix: 'Нитка з ',
  homeSpotlightRevisitReasonThreadSuffix: ' близькими снами',
  homeSpotlightRevisitReasonAnalysis: 'Тут уже є збережена рефлексія, яку варто звірити знову',
  homeSpotlightRevisitReasonTranscript: 'Транскрипт уже готовий до доробки',
  homeSpotlightRevisitReasonTimePrefix: 'Цей сон повертається з ',
  homeSpotlightRevisitReasonTimeSuffix:
    ' і його варто знову відкрити, поки деталь не стерлась.',
  homeSpotlightRevisitTimeWeek: 'приблизно тижневої давності',
  homeSpotlightRevisitTimeMonth: 'приблизно місячної давності',
  homeSpotlightRevisitTimeQuarter: 'приблизно тримісячної давності',
  homeSpotlightRevisitTimeHalfYear: 'приблизно піврічної давності',
  homeSpotlightRevisitTimeYear: 'приблизно річної давності',
  homeSpotlightRevisitReasonSignal: 'Тут усе ще є виразний сигнал, який варто назвати',
  homeSpotlightShowDetails: 'Більше деталей',
  homeSpotlightHideDetails: 'Менше деталей',
  homeStreakLabel: 'Серія',
  homeTotalLabel: 'Всього',
  homeAverageLabel: 'Сер. слів',
  homeDaysUnit: 'днів',
  homeFilterAll: 'Усі',
  homeFilterActive: 'Поточні',
  homeFilterArchived: 'Архів',
  homeFilterStarred: 'Важливі',
  homeArchiveFilterLabel: 'Статус',
  homeSearchLabel: 'Пошук снів',
  homeSearchPlaceholder: 'Назва, нотатки, транскрипт або тег',
  homeSaveSearchPreset: 'Зберегти пошук',
  homeSearchShowDetails: 'Збережені пошуки',
  homeSearchHideDetails: 'Сховати збережені',
  homeSavedSearchesLabel: 'Збережені пошуки',
  homeSearchPresetFallback: 'Швидкий пошук',
  homeSearchPresetRemove: 'Видалити збережений пошук',
  homeSearchPresetDeleteTitle: 'Видалити цей пошук?',
  homeSearchPresetDeleteDescription:
    'Це прибере лише збережену комбінацію фільтрів. Самі сни не зміняться.',
  homeSearchMatchTitle: 'Назва',
  homeSearchMatchNotes: 'Нотатки',
  homeSearchMatchTranscript: 'Транскрипт',
  homeSearchMatchTag: 'Тег',
  homeSearchMatchContext: 'Контекст',
  homeClearSearch: 'Очистити пошук',
  homeRefineLabel: 'Уточнення таймлайну',
  homeShowFilters: 'Фільтри',
  homeHideFilters: 'Сховати',
  homeMoodFilterLabel: 'Настрій',
  homeMoodFilterAll: 'Будь-який',
  homeTypeFilterLabel: 'Тип запису',
  homeTypeFilterAll: 'Будь-який тип',
  homeTypeFilterText: 'Текст',
  homeTypeFilterAudio: 'Аудіо',
  homeTypeFilterMixed: 'Змішаний',
  homeTranscriptFilterLabel: 'Транскрипт',
  homeTranscriptFilterAll: 'Будь-який стан транскрипту',
  homeTranscriptFilterWithTranscript: 'Є транскрипт',
  homeTranscriptFilterAudioOnly: 'Лише аудіо',
  homeTranscriptFilterEdited: 'Редагований транскрипт',
  homeDateRangeFilterLabel: 'Період',
  homeDateRangeAll: 'Будь-коли',
  homeDateRange7d: 'Останні 7 днів',
  homeDateRange30d: 'Останні 30 днів',
  homeDateRange90d: 'Останні 90 днів',
  homeSortFilterLabel: 'Сортування',
  homeSortFilterNewest: 'Спочатку нові',
  homeSortFilterOldest: 'Спочатку старі',
  homeTagFilterLabel: 'Теги',
  homeTagSearchPlaceholder: 'Пошук тегів',
  homeTagSelectedLabel: 'Вибрані теги',
  homeTagsShowMore: 'Показати всі теги',
  homeTagsShowLess: 'Показати менше',
  homeTagsEmpty: 'За цим пошуком тегів немає.',
  homeClearFilters: 'Очистити фільтри',
  homeResultsSingle: 'запис',
  homeResultsPlural: 'записів',
  homeSearchEmptyTitle: 'Нічого не знайдено за цими фільтрами',
  homeSearchEmptyDescription:
    'Спробуй простіший запит, зміни фільтри або очисть їх, щоб побачити більше записів.',
  homeQuickOpen: 'Відкрити',
  actionRetry: 'Повторити',
  clearErrorAction: 'Закрити',
  timelineLoadingTitle: 'Завантаження таймлайну',
  timelineLoadingDescription: 'Оновлюємо локальні записи...',
  timelineErrorTitle: 'Не вдалося завантажити таймлайн',
  timelineErrorDescription:
    'Спробуй ще раз. Локальне сховище може бути тимчасово недоступне.',
  openDreamHint: 'Натисни, щоб відкрити. Затисни для швидких дій.',
  swipeEdit: 'Змінити',
  swipeDelete: 'Видалити',
  swipeArchive: 'Архів',
  swipeUnarchive: 'Розархівувати',
  emptyTitle: 'Поки немає снів',
  emptyDescription:
    'Додай перший запис через кнопку +. Достатньо назви, голосу або кількох рядків.',
  emptyActiveTitle: 'Немає активних снів',
  emptyActiveDescription: 'Усі записи в архіві. Зміни фільтр або створи новий сон.',
  emptyArchivedTitle: 'Архів порожній',
  emptyArchivedDescription: 'Архівуй старі записи, щоб сфокусувати таймлайн.',
  archiveTitle: 'Архів',
  archiveSubtitle:
    'Переглядай минулі сни по місяцях.',
  archiveSearchPlaceholder: 'Пошук у поточному місяці',
  archiveSearchScopeHint: 'Пошук працює тільки в межах поточного місяця.',
  archiveResetView: 'Скинути вигляд',
  archiveCalendarTitle: 'Календар',
  archiveCalendarSubtitle: 'Перемикай місяць або натискай день, де є сни.',
  archiveCalendarShowGrid: 'Показати дні',
  archiveCalendarHideGrid: 'Сховати дні',
  archiveBrowseLabel: 'Вигляд',
  archiveBrowseComfortable: 'Картки',
  archiveBrowseCompact: 'Список',
  archiveMonthEntriesLabel: 'записів',
  archiveMonthActiveDaysLabel: 'активних днів',
  archivePreviousMonth: 'Раніше',
  archiveNextMonth: 'Новіше',
  archiveAllDates: 'Усі дати',
  archiveSelectedDatePrefix: 'Вибрано',
  archiveWeekdaySun: 'Нд',
  archiveWeekdayMon: 'Пн',
  archiveWeekdayTue: 'Вт',
  archiveWeekdayWed: 'Ср',
  archiveWeekdayThu: 'Чт',
  archiveWeekdayFri: 'Пт',
  archiveWeekdaySat: 'Сб',
  archiveRevisitLabel: 'Відкрити знову в цьому місяці',
  archiveRevisitAction: 'Відкрити деталі',
  archiveRevisitActionAnalysis: 'Звірити рефлексію',
  archiveRevisitActionTranscript: 'Доробити транскрипт',
  archiveRevisitEmpty: 'У цьому зрізі архіву ще немає сильного приводу повернутись.',
  archiveRevisitContextImportant: 'Важливе',
  archiveRevisitContextAnalysis: 'Рефлексія готова',
  archiveRevisitContextTranscript: 'Транскрипт готовий',
  archiveRevisitContextArchived: 'В архіві',
  archiveRevisitContextSignal: 'Деталь варто втримати',
  archiveRevisitReasonImportant: 'Позначено як важливе і варте ще одного погляду',
  archiveRevisitReasonAnalysis: 'Тут уже є збережена рефлексія, до якої варто повернутись',
  archiveRevisitReasonTranscript: 'Транскрипт уже готовий до доробки',
  archiveRevisitReasonArchived: 'Старіший архівний сон, який варто відкрити знову',
  archiveRevisitReasonSignal: 'Тут усе ще є деталь, яку варто втримати живою',
  archiveEmptyTitle: 'Архів порожній',
  archiveEmptyDescription: 'Спочатку збережи кілька снів, і вони почнуть групуватись тут.',
  archiveEmptyCurrentTitle: 'Немає активних снів',
  archiveEmptyCurrentDescription: 'Усе в цьому місяці вже в архіві або відфільтроване.',
  archiveEmptyArchivedTitle: 'Поки немає архівних снів',
  archiveEmptyArchivedDescription: 'Перемісти кілька старіших снів в архів, і вони зʼявляться тут.',
  archiveEmptyImportantTitle: 'Поки немає важливих снів',
  archiveEmptyImportantDescription: 'Познач кілька снів як важливі, щоб до них було легше повертатись.',
  archiveNoResultsTitle: 'Нічого не знайдено в цьому вигляді архіву',
  archiveNoResultsDescription:
    'Спробуй інший місяць, очисть день або скинь поточний пошук і фільтри.',
  archiveFilterAll: 'Усі',
  archiveFilterActive: 'Активні',
  archiveFilterArchived: 'Архівні',
  archiveFilterStarred: 'Важливі',
  untitled: 'Сон без назви',
  archivedTag: 'Архів',
  starredTag: 'Важливе',
  audioTag: 'Аудіо',
  transcriptTag: 'Транскрипт',
  editedTranscriptTag: 'Редаговано',
  transcriptPreviewPrefix: 'Транскрипт',
  editedTranscriptPreviewPrefix: 'Редагований транскрипт',
  audioOnlyPreview: 'Голосову нотатку збережено. Текст можна додати пізніше.',
  noDetailsPreview: 'Поки без текстового опису.',
  detailBack: 'Назад',
  detailEdit: 'Редагувати сон',
  detailStar: 'Додати у важливі',
  detailUnstar: 'Прибрати з важливих',
  detailArchive: 'В архів',
  detailUnarchive: 'З архіву',
  detailDelete: 'Видалити сон',
  detailDeleteTitle: 'Видалити цей сон?',
  detailDeleteDescription: 'Запис буде видалено з локального сховища без можливості відновлення.',
  detailDeleteCancel: 'Скасувати',
  detailDeleteConfirm: 'Видалити',
  detailMissingTitle: 'Сон не знайдено',
  detailMissingDescription: 'Цей запис більше недоступний у локальному сховищі.',
  detailMetaTitle: 'Коротко',
  detailCapturedLabel: 'Збережено',
  detailPreviewLabel: 'Фрагмент',
  detailActionEdit: 'Редагувати',
  detailActionImportant: 'Важливе',
  detailActionArchive: 'В архів',
  detailActionRestore: 'Повернути',
  detailActionDelete: 'Видалити',
  detailSavedTitle: 'Сон збережено',
  detailSavedDescription:
    'Сирий спогад уже в безпеці. Деталі можна доробити пізніше.',
  detailSavedPatternLabel: 'Найсильніший сигнал',
  detailSavedRelatedLabel: 'Схожі сни',
  detailReflectionTitle: 'Повернись до цього зараз',
  detailReflectionSignalTitle: 'Назви сигнал',
  detailReflectionSignalPrefix: 'У цьому сні найсильніше звучить ',
  detailReflectionSignalSuffix:
    '. Додай один рядок про те, чому цей сигнал важливий саме зараз.',
  detailReflectionEmotionTitle: 'Впіймай відчуття',
  detailReflectionEmotionWithMoodPrefix: 'Емоційний тон цього сну все ще тягнеться до ',
  detailReflectionEmotionWithMoodSuffix:
    '. Запиши, що залишилося в тілі після пробудження.',
  detailReflectionEmotionBody:
    'Запиши, яке відчуття залишилося в тілі після пробудження, навіть якщо воно тривало лише кілька секунд.',
  detailReflectionThreadTitle: 'Потягни за нитку',
  detailReflectionThreadPrefix: 'Цей сон уже торкається ',
  detailReflectionThreadSuffix:
    '. Відкрий один близький сон і відміть, що повторюється або змінюється.',
  detailReflectionAnalysisTitle: 'Перевір зміст',
  detailReflectionAnalysisPrefix: 'Збережений summary підказує: ',
  detailReflectionAnalysisSuffix:
    ' Виріши, чи це все ще відчувається правдою.',
  detailReflectionTranscriptTitle: 'Зроби транскрипт придатним',
  detailReflectionTranscriptBody:
    'Одного швидкого проходу вистачить, щоб цей голосовий спогад було легше шукати й відкривати пізніше.',
  detailReflectionResurfaceTitle: 'Що досі тримається',
  detailReflectionResurfacePrefix: 'Цей сон знову виринає з ',
  detailReflectionResurfaceSuffix:
    '. Додай один рядок про те, що все ще відчувається правдою зараз.',
  detailReflectionCaptureTitle: 'Залиши одну яскраву деталь',
  detailReflectionCaptureBody:
    'Додай один конкретний образ, місце або рядок, який твій майбутній ти все ще зрозуміє через тиждень.',
  detailReflectionFallbackTitle: 'Залиши слід на потім',
  detailReflectionFallbackBody:
    'Додай одну коротку нотатку, за яку майбутній ти буде вдячний.',
  detailReflectionActionEdit: 'Додати деталь',
  detailReflectionActionRelated: 'Відкрити нитку',
  detailReflectionActionAnalysis: 'Переглянути аналіз',
  detailCaptureTitle: 'Запис',
  detailCaptureEmpty: 'Для цього сну ще немає ні тексту, ні аудіо.',
  detailTranscriptTitle: 'Текстові нотатки',
  detailTranscriptEmpty: 'Для цього сну ще немає збережених текстових нотаток.',
  detailGlanceCaptureLabel: 'Формат',
  detailGlanceTranscriptLabel: 'Транскрипт',
  detailGlanceAnalysisLabel: 'Аналіз',
  detailGlanceRelatedLabel: 'Схожі',
  detailCaptureModeText: 'Нотатка',
  detailCaptureModeVoice: 'Голос',
  detailCaptureModeMixed: 'Змішано',
  detailTranscriptSummaryIdle: 'Немає',
  detailTranscriptSummaryReady: 'Готово',
  detailTranscriptSummaryEdited: 'Змінено',
  detailTranscriptSummaryProcessing: 'У роботі',
  detailTranscriptSummaryError: 'Повтор',
  detailGeneratedTranscriptTitle: 'Згенерований транскрипт',
  detailGeneratedTranscriptEmpty: 'Для цієї голосової нотатки ще не створено транскрипт.',
  detailGeneratedTranscriptHint:
    'Транскрипція виконується на пристрої й не змінює оригінальну голосову нотатку.',
  detailGeneratedTranscriptProcessing:
    'Транскрипція виконується локально на цьому пристрої. Не закривай застосунок, доки вона не завершиться.',
  detailGeneratedTranscriptError:
    'Остання спроба транскрипції не завершилась. Оригінальна голосова нотатка все ще збережена.',
  detailGeneratedTranscriptReplaceError:
    'Остання спроба заміни транскрипту не завершилась. Попередній транскрипт усе ще збережений локально.',
  detailGeneratedTranscriptSourceLabel: 'Джерело',
  detailGeneratedTranscriptSourceGenerated: 'Згенеровано з аудіо',
  detailGeneratedTranscriptSourceEdited: 'Відредаговано вручну',
  detailGeneratedTranscriptUpdatedLabel: 'Оновлено',
  detailGeneratedTranscriptEdit: 'Редагувати транскрипт',
  detailGeneratedTranscriptSave: 'Зберегти транскрипт',
  detailGeneratedTranscriptCancel: 'Скасувати редагування',
  detailGeneratedTranscriptClear: 'Очистити транскрипт',
  detailGeneratedTranscriptReplace: 'Замінити транскрипт',
  detailGeneratedTranscriptEmptyErrorTitle: 'Порожній транскрипт',
  detailGeneratedTranscriptEmptyErrorDescription:
    'Додай хоча б один рядок перед збереженням або очисти транскрипт окремо.',
  detailGeneratedTranscriptSaveSuccessTitle: 'Транскрипт оновлено',
  detailGeneratedTranscriptSaveSuccessDescription:
    'Відредагований транскрипт збережено локально і він лишається доступним для пошуку.',
  detailGeneratedTranscriptClearTitle: 'Очистити транскрипт?',
  detailGeneratedTranscriptClearDescription:
    'Це видалить збережений транскрипт, але залишить оригінальну голосову нотатку на пристрої.',
  detailAnalysisTitle: 'Аналіз сну',
  detailAnalysisEmpty:
    'Для цього сну ще не збережено аналіз. Згенеруй його, щоб перетворити запис на коротку локальну рефлексію.',
  detailAnalysisDisabled:
    'Шар аналізу вимкнений у Settings, тому цей сон поки лишається сирим записом без summary і themes.',
  detailAnalysisSummaryLabel: 'Summary',
  detailAnalysisThemesLabel: 'Themes',
  detailAnalysisStateLabel: 'Режим аналізу',
  detailAnalysisStateLocalReady: 'Локальний аналіз увімкнений і готовий для цього сну.',
  detailAnalysisStateDisabled: 'Аналіз вимкнений. Увімкни його в Settings, коли захочеш summary і themes.',
  detailAnalysisStateOpenAiPlanned:
    'У Settings обрано OpenAI, але мережевий аналіз у цьому релізі ще лишається запланованим шляхом.',
  detailAnalysisStateManual:
    'Для цього сну можна згенерувати локальний summary зі збереженого тексту, транскрипту, тегів і context.',
  detailAnalysisProviderLabel: 'Провайдер',
  detailAnalysisUpdatedLabel: 'Оновлено',
  detailAnalysisStatusLabel: 'Статус',
  detailAnalysisStatusReady: 'Готово',
  detailAnalysisStatusError: 'Помилка',
  detailAnalysisStatusIdle: 'Не згенеровано',
  detailAnalysisSummaryReady: 'Готово',
  detailAnalysisSummaryIdle: 'Немає',
  detailAnalysisSummaryDisabled: 'Вимкнено',
  detailAnalysisSummaryPlanned: 'План',
  detailAnalysisProviderManual: 'Локально',
  detailAnalysisProviderOpenAi: 'OpenAI (заплановано)',
  detailAnalysisGenerate: 'Згенерувати аналіз',
  detailAnalysisRegenerate: 'Оновити аналіз',
  detailAnalysisClear: 'Очистити аналіз',
  detailAnalysisGenerating: 'Генерується локальний аналіз...',
  detailAnalysisOpenSettings: 'Відкрити Settings',
  detailAnalysisOpenAiUnavailable:
    'Провайдер OpenAI уже обраний у Settings, але в цьому релізі це ще лише запланований шлях.',
  detailAnalysisErrorTitle: 'Помилка аналізу',
  detailAnalysisGenerateErrorDescription:
    'Сон усе ще збережений локально. Спробуй manual provider або залиш цей слот порожнім.',
  detailTranscribeAudio: 'Транскрибувати аудіо',
  detailTranscribeRetry: 'Повторити транскрипцію',
  detailTranscribePreparingModel: 'Підготовка офлайн-моделі',
  detailTranscribeInProgress: 'Транскрипція на пристрої',
  detailTranscriptionErrorTitle: 'Помилка транскрипції',
  detailTranscriptionErrorDescription:
    'Голосова нотатка все ще збережена локально. Спробуй ще раз у тихішому середовищі або після завершення завантаження моделі.',
  detailTagsEmpty: 'Теги ще не додані.',
  detailRelatedTitle: 'Поруч сни',
  detailRelatedDescription:
    'Раніші сни, пов’язані спільними сигналами, повторюваними словами та емоційними відлуннями.',
  detailRelatedEmpty:
    'Збережи ще кілька снів, і перша виразна нитка почне формуватися.',
  detailRelatedSummaryEmpty: 'Немає',
  detailRelatedMatchSingular: 'збіг',
  detailRelatedMatchPlural: 'збіги',
  detailRelatedSharedLabel: 'Сигнали нитки',
  detailRelatedRecurringLabel: 'Вже траплялось',
  detailStateTitle: 'Контекст сну',
  detailStateEmpty: 'Для цього сну не збережено емоцій після пробудження чи контексту перед сном.',
  detailAudioDescription: 'До цього сну прикріплена оригінальна голосова нотатка.',
  detailAudioPathLabel: 'Локальний файл',
  detailAudioPlay: 'Відтворити голос',
  detailAudioStop: 'Зупинити відтворення',
  detailAudioPlaybackHint: 'Прослухай запис, щоб перевірити, що початкове захоплення збереглося.',
  detailAudioPlaybackErrorTitle: 'Помилка відтворення',
  detailAudioAttachedMeta: 'Є запис',
  createTitle: 'Запис сну',
  createSubtitle:
    'Злови форму сну зараз. Деталі відсортуєш пізніше.',
  quickAddKicker: 'Швидке додавання',
  quickAddWakeAction: 'Ранковий запис',
  quickAddWakeHint: 'Відкрий стислий ранковий режим для швидкого голосового або текстового запису.',
  quickAddVoiceAction: 'Голосова нотатка',
  quickAddVoiceHint: 'Відкрий редактор у голосовому режимі й швидко почни запис.',
  quickAddTextAction: 'Текстова нотатка',
  quickAddTextHint: 'Відкрий редактор і зафіксуй те, що ще памʼятаєш.',
  quickAddContinueHint: 'Продовж із локально збереженої чернетки з того місця, де зупинився.',
  wakeEntryKicker: 'Ранковий потік',
  wakeEntryTitle: 'Поки не вислизнуло',
  wakeEntryDescription:
    'Один спокійний екран після нагадування. Натисни в центр, щоб писати, або нижче обери голос.',
  wakeEntryOrbAction: 'Писати',
  wakeEntryOrbHint: 'Натисни в центр і почни з сирих рядків.',
  wakeEntryWriteAction: 'Писати зараз',
  wakeEntryAlternateTitle: 'Інші способи запису',
  wakeEntrySpeakAction: 'Говорити замість цього',
  wakeEntrySpeakHint: 'Почни з голосу, якщо це швидше, ніж друкувати.',
  wakeEntryDraftAction: 'Продовжити чернетку',
  wakeEntryDraftHint: 'Повернись до незавершеного запису, який уже збережено локально.',
  wakeModeChip: 'Ранковий режим',
  wakeHeroTitle: 'Злови першу форму',
  wakeHeroDescription:
    'Спочатку голос, потім сирі рядки. Назва, теги й контекст можуть зачекати.',
  wakeCaptureTitle: 'Голос або сирі рядки',
  wakeCaptureDescription:
    'Почни з найшвидшого, що ще живе: голосова нотатка, кілька слів або обидва варіанти разом.',
  wakeCaptureAlternateTitle: 'Або запиши голосом',
  wakeCaptureVoiceHint: 'Обери голос, якщо зараз говорити швидше, ніж друкувати.',
  wakeVoiceDescription: 'Почни запис зараз або одразу впиши кілька сирих рядків нижче.',
  wakeCoreTitle: 'Сирий спогад',
  wakeCoreDescription: 'Залиши лише те, що ще живе. Структуру додаси пізніше.',
  wakeTextLabel: 'Що ще лишилося?',
  wakeTextPlaceholder: 'Місце, обличчя, відчуття, один рядок...',
  wakeRefineTitle: 'Додаси пізніше, якщо треба',
  wakeRefineDescription:
    'Ранковий запис має лишатися легким. Назва, теги і контекст перед сном усе ще доступні пізніше.',
  wakeRefineMetaAction: 'Назва + дата',
  wakeMetaTitle: 'Назва і дата сну',
  wakeMetaDescription: 'Додавай це зараз лише якщо воно справді допомагає заякорити спогад.',
  wakeReadyHint: 'Голосу, кількох сирих рядків і відчуття після пробудження достатньо для збереження.',
  createHeroTitle: 'Запиши, поки не зникло',
  createHeroDescription:
    'Почни з голосу або кількох сирих рядків.',
  recordEmptyTitle: 'Почни з короткого запису',
  recordEmptyDescription:
    'Почни з тексту або голосу. Усе інше може зачекати.',
  recordDraftRestoredTitle: 'Чернетку відновлено',
  recordDraftRestoredDescription:
    'Незавершений запис збережено локально. Продовжуй редагування або збережи, коли будеш готовий.',
  recordLoadingTitle: 'Виконується дія',
  recordLoadingDescription: 'Зачекай, поки операція завершиться.',
  recordErrorTitle: 'Дія не виконалась',
  recordErrorDescription: 'Спробуй ще раз або продовж запис текстом.',
  refineTitle: 'Уточниш пізніше',
  refineDescription: 'Настрій, контекст і теги не обовʼязкові одразу. Додавай їх лише якщо вони справді допомагають.',
  refineReadyHint: 'Щоб зберегти, достатньо сирого тексту або голосу.',
  refineMoodAction: 'Настрій',
  refineContextAction: 'Перед сном',
  refineTagsAction: 'Теги',
  refineHideAction: 'Сховати',
  editTitle: 'Редагування сну',
  editSubtitle: 'Уточни спогад, не втрачаючи оригінальний запис.',
  editHeroTitle: 'Уточни спогад',
  editHeroDescription: 'Онови деталі, поки сон ще свіжий і важливий.',
  coreTitle: 'Основне',
  coreDescription: 'Назва необовʼязкова. Спершу зафіксуй сам спогад.',
  titleLabel: 'Назва сну',
  titlePlaceholder: 'Політ над старими дахами',
  sleepDateLabel: 'Дата сну',
  sleepDateInvalidTitle: 'Некоректна дата сну',
  sleepDateInvalidDescription: 'Використовуй формат YYYY-MM-DD і реальну календарну дату.',
  textLabel: 'Що ти памʼятаєш?',
  textPlaceholder: 'Запиши сон, поки він ще свіжий...',
  wordsUnit: 'слів',
  moodTitle: 'Настрій після пробудження',
  moodDescription: 'Швидкі сигнали після пробудження для майбутніх патернів.',
  wakeEmotionsTitle: 'Емоції після пробудження',
  wakeEmotionsDescription:
    'Швидкі сигнали з першої хвилини після пробудження, поки сон ще не встиг згладитися.',
  sleepContextTitle: 'Контекст перед сном',
  sleepContextDescription:
    'Невеликі сигнали перед сном, які можуть пояснити сон.',
  preSleepEmotionsLabel: 'Емоції перед сном',
  stressLabel: 'Рівень стресу',
  alcoholLabel: 'Алкоголь перед сном',
  caffeineLabel: 'Пізній кофеїн',
  medicationsLabel: 'Препарати або добавки',
  medicationsPlaceholder: 'напр. мелатонін 3мг',
  eventsLabel: 'Важливі події',
  eventsPlaceholder: 'напр. іспит, конфлікт, святкування',
  healthNotesLabel: 'Нотатки про здоровʼя',
  healthNotesPlaceholder: 'напр. головний біль, тривожність, низький настрій',
  boolYes: 'Так',
  boolNo: 'Ні',
  detailEmotionTitle: 'Емоційний зріз',
  detailEmotionEmpty: 'Для цього сну не збережено емоцій ні після пробудження, ні перед сном.',
  detailWakeEmotionsLabel: 'Після пробудження',
  detailPreSleepEmotionsLabel: 'Перед сном',
  detailContextTitle: 'Контекст перед сном',
  detailContextEmpty: 'Для цього сну контекст перед сном не збережено.',
  tagsTitle: 'Теги',
  tagsDescription: 'Символи, люди, місця, повторювані фрагменти.',
  tagsPlaceholder: 'океан',
  tagsEmpty: 'Тегів ще немає. Додай перший.',
  voiceTitle: 'Голосова нотатка',
  voiceDescription: 'Почни швидко. Уточниш пізніше.',
  voiceIdleHint: 'Один тап запускає запис голосу.',
  startRecording: 'Почати запис',
  stopRecording: 'Зупинити запис',
  recordingHint: 'Йде запис. Зупини, коли завершиш.',
  attachedAudioTitle: 'Голосову нотатку додано',
  removeAudio: 'Видалити голос',
  addTag: 'Додати',
  saveDream: 'Зберегти сон',
  updateDream: 'Оновити сон',
  saveErrorTitle: 'Немає що зберігати',
  saveErrorDescription: 'Додай текст або голосову нотатку. Однієї назви недостатньо.',
  saveSuccessTitle: 'Збережено',
  saveSuccessDescription: 'Сон збережено локально.',
  postSaveTitle: 'Запис збережено',
  postSaveDescription:
    'Тепер він безпечно лежить локально. Продовж записувати далі або відкрий цей сон, якщо хочеш одразу щось уточнити.',
  postSaveSavedLabel: 'Збережений запис',
  postSaveNextStepLabel: 'Наступний крок',
  postSaveFollowUpReflectionTitle: 'Повернись, поки сон ще живий',
  postSaveFollowUpReflectionDescription:
    'Відкрий цей сон і пройди короткі reflection prompts, щоб не втратити найважливішу деталь.',
  postSaveFollowUpReflectionAction: 'Відкрити prompts',
  postSaveFollowUpRefineTitle: 'Додай одну конкретну деталь',
  postSaveFollowUpRefineDescription:
    'Відкрий запис і додай один образ, місце або рядок, який твій майбутній ти ще зрозуміє.',
  postSaveFollowUpRefineAction: 'Доробити цей сон',
  postSaveFollowUpTranscriptTitle: 'Перетвори голос у корисний текст',
  postSaveFollowUpTranscriptDescription:
    'Відкрий цей сон і дороби транскрипт, поки спогад ще близько.',
  postSaveFollowUpTranscriptAction: 'Попрацювати з транскриптом',
  postSaveCaptureAnother: 'Продовжити запис',
  postSaveRecordAnother: 'Записати голос ще раз',
  postSaveOpenDetail: 'Відкрити цей сон',
  postSaveContinueLater: 'Повернутись пізніше',
  postSaveFooterHint: 'На інші вкладки можна перейти будь-коли.',
  updateSuccessTitle: 'Оновлено',
  updateSuccessDescription: 'Сон оновлено локально.',
  audioErrorTitle: 'Помилка аудіо',
  audioSimulatorHint:
    'Голосовий запис може не працювати в iOS Simulator. Тут краще тестувати текст, а запис перевіряти на реальному пристрої.',
};

const DREAM_MOODS_EN: Array<{ label: string; value: Mood }> = [
  { label: 'Calm', value: 'neutral' },
  { label: 'Bright', value: 'positive' },
  { label: 'Heavy', value: 'negative' },
];

const DREAM_MOODS_UK: typeof DREAM_MOODS_EN = [
  { label: 'Спокійний', value: 'neutral' },
  { label: 'Світлий', value: 'positive' },
  { label: 'Важкий', value: 'negative' },
];

const DREAM_MOOD_LABELS_EN: Record<Mood, string> = {
  neutral: 'Calm',
  positive: 'Bright',
  negative: 'Heavy',
};

const DREAM_MOOD_LABELS_UK: typeof DREAM_MOOD_LABELS_EN = {
  neutral: 'Спокійний',
  positive: 'Світлий',
  negative: 'Важкий',
};

const DREAM_STRESS_LEVELS_EN: Array<{ label: string; value: StressLevel }> = [
  { label: 'Low', value: 0 },
  { label: 'Moderate', value: 1 },
  { label: 'High', value: 2 },
  { label: 'Overload', value: 3 },
];

const DREAM_STRESS_LEVELS_UK: typeof DREAM_STRESS_LEVELS_EN = [
  { label: 'Низький', value: 0 },
  { label: 'Помірний', value: 1 },
  { label: 'Високий', value: 2 },
  { label: 'Перевантаження', value: 3 },
];

const DREAM_STRESS_LABELS_EN: Record<StressLevel, string> = {
  0: 'Low',
  1: 'Moderate',
  2: 'High',
  3: 'Overload',
};

const DREAM_STRESS_LABELS_UK: typeof DREAM_STRESS_LABELS_EN = {
  0: 'Низький',
  1: 'Помірний',
  2: 'Високий',
  3: 'Перевантаження',
};

const DREAM_WAKE_EMOTIONS_EN: Array<{ label: string; value: WakeEmotion }> = [
  { label: 'Calm', value: 'calm' },
  { label: 'Uneasy', value: 'uneasy' },
  { label: 'Curious', value: 'curious' },
  { label: 'Heavy', value: 'heavy' },
  { label: 'Inspired', value: 'inspired' },
  { label: 'Disoriented', value: 'disoriented' },
];

const DREAM_WAKE_EMOTIONS_UK: typeof DREAM_WAKE_EMOTIONS_EN = [
  { label: 'Спокій', value: 'calm' },
  { label: 'Тривога', value: 'uneasy' },
  { label: 'Цікавість', value: 'curious' },
  { label: 'Важкість', value: 'heavy' },
  { label: 'Натхнення', value: 'inspired' },
  { label: 'Дезорієнтація', value: 'disoriented' },
];

const DREAM_PRE_SLEEP_EMOTIONS_EN: Array<{ label: string; value: PreSleepEmotion }> = [
  { label: 'Peaceful', value: 'peaceful' },
  { label: 'Anxious', value: 'anxious' },
  { label: 'Restless', value: 'restless' },
  { label: 'Hopeful', value: 'hopeful' },
  { label: 'Drained', value: 'drained' },
  { label: 'Lonely', value: 'lonely' },
];

const DREAM_PRE_SLEEP_EMOTIONS_UK: typeof DREAM_PRE_SLEEP_EMOTIONS_EN = [
  { label: 'Спокій', value: 'peaceful' },
  { label: 'Тривога', value: 'anxious' },
  { label: 'Неспокій', value: 'restless' },
  { label: 'Надія', value: 'hopeful' },
  { label: 'Виснаження', value: 'drained' },
  { label: 'Самотність', value: 'lonely' },
];

const DREAM_WAKE_EMOTION_LABELS_EN: Record<WakeEmotion, string> = Object.fromEntries(
  DREAM_WAKE_EMOTIONS_EN.map(option => [option.value, option.label]),
) as Record<WakeEmotion, string>;

const DREAM_WAKE_EMOTION_LABELS_UK: typeof DREAM_WAKE_EMOTION_LABELS_EN = Object.fromEntries(
  DREAM_WAKE_EMOTIONS_UK.map(option => [option.value, option.label]),
) as Record<WakeEmotion, string>;

const DREAM_PRE_SLEEP_EMOTION_LABELS_EN: Record<PreSleepEmotion, string> = Object.fromEntries(
  DREAM_PRE_SLEEP_EMOTIONS_EN.map(option => [option.value, option.label]),
) as Record<PreSleepEmotion, string>;

const DREAM_PRE_SLEEP_EMOTION_LABELS_UK: typeof DREAM_PRE_SLEEP_EMOTION_LABELS_EN =
  Object.fromEntries(
    DREAM_PRE_SLEEP_EMOTIONS_UK.map(option => [option.value, option.label]),
  ) as Record<PreSleepEmotion, string>;

export type DreamCopy = typeof DREAM_COPY_EN;

export function getDreamCopy(locale: AppLocale): DreamCopy {
  return locale === 'uk' ? DREAM_COPY_UK : DREAM_COPY_EN;
}

export function getDreamMoods(locale: AppLocale) {
  return locale === 'uk' ? DREAM_MOODS_UK : DREAM_MOODS_EN;
}

export function getDreamMoodLabels(locale: AppLocale) {
  return locale === 'uk' ? DREAM_MOOD_LABELS_UK : DREAM_MOOD_LABELS_EN;
}

export function getDreamStressLevels(locale: AppLocale) {
  return locale === 'uk' ? DREAM_STRESS_LEVELS_UK : DREAM_STRESS_LEVELS_EN;
}

export function getDreamStressLabels(locale: AppLocale) {
  return locale === 'uk' ? DREAM_STRESS_LABELS_UK : DREAM_STRESS_LABELS_EN;
}

export function getDreamWakeEmotions(locale: AppLocale) {
  return locale === 'uk' ? DREAM_WAKE_EMOTIONS_UK : DREAM_WAKE_EMOTIONS_EN;
}

export function getDreamWakeEmotionLabels(locale: AppLocale) {
  return locale === 'uk' ? DREAM_WAKE_EMOTION_LABELS_UK : DREAM_WAKE_EMOTION_LABELS_EN;
}

export function getDreamPreSleepEmotions(locale: AppLocale) {
  return locale === 'uk' ? DREAM_PRE_SLEEP_EMOTIONS_UK : DREAM_PRE_SLEEP_EMOTIONS_EN;
}

export function getDreamPreSleepEmotionLabels(locale: AppLocale) {
  return locale === 'uk'
    ? DREAM_PRE_SLEEP_EMOTION_LABELS_UK
    : DREAM_PRE_SLEEP_EMOTION_LABELS_EN;
}

export const DREAM_COPY = DREAM_COPY_EN;
export const DREAM_MOODS = DREAM_MOODS_EN;
export const DREAM_MOOD_LABELS = DREAM_MOOD_LABELS_EN;
export const DREAM_STRESS_LEVELS = DREAM_STRESS_LEVELS_EN;
export const DREAM_STRESS_LABELS = DREAM_STRESS_LABELS_EN;
export const DREAM_WAKE_EMOTIONS = DREAM_WAKE_EMOTIONS_EN;
export const DREAM_WAKE_EMOTION_LABELS = DREAM_WAKE_EMOTION_LABELS_EN;
export const DREAM_PRE_SLEEP_EMOTIONS = DREAM_PRE_SLEEP_EMOTIONS_EN;
export const DREAM_PRE_SLEEP_EMOTION_LABELS = DREAM_PRE_SLEEP_EMOTION_LABELS_EN;
