import { AppLocale } from '../../i18n/types';

const SETTINGS_COPY_EN = {
  title: 'Settings',
  subtitle: 'Architecture and product controls will grow here.',
  versionTitle: 'Current release',
  footerBuildLabel: 'Kaleidoskop',
  footerStorageMetaPrefix: 'Schema',
  footerExportMetaPrefix: 'Export',
  reminderTitle: 'Dream reminder',
  reminderDescription:
    'One daily nudge after waking so you capture dreams faster.',
  reminderStatusLabel: 'Status',
  reminderPermissionLabel: 'Notifications',
  reminderEnabled: 'Enabled',
  reminderDisabled: 'Disabled',
  reminderPermissionAllowed: 'Allowed',
  reminderPermissionBlocked: 'Blocked',
  reminderEnableButton: 'Enable reminder',
  reminderDisableButton: 'Disable reminder',
  reminderTimeLabel: 'Reminder time',
  reminderTimeHint: 'Tap to change.',
  actionCancel: 'Cancel',
  reminderPermissionDeniedTitle: 'Notifications disabled',
  reminderPermissionDeniedDescription:
    'Allow notifications in system settings to enable dream reminders.',
  reminderSaveErrorTitle: 'Reminder error',
  reminderStateHint:
    'Time is saved locally. If system notifications are blocked, the reminder stays off until permission is restored.',
  reminderNotificationTitle: 'Record your dream',
  reminderNotificationBody: 'Capture it while details are still fresh.',
  languageTitle: 'Language',
  languageDescription: 'Choose your app language.',
  languageEnglish: 'EN',
  languageUkrainian: 'UA',
  privacyTitle: 'Privacy and storage',
  privacyDescription:
    'Dream data stays on your device. Accounts and sync are still off.',
  privacyStorageLabel: 'Dream data',
  privacyStorageValue: 'Stored locally on device',
  privacySyncLabel: 'Cloud sync',
  privacySyncValue: 'Not enabled yet',
  privacyAccountLabel: 'Account',
  privacyAccountValue: 'No sign-in required',
  privacyReminderLabel: 'Reminders',
  privacyReminderValue: 'Scheduled as local notifications',
  privacyTranscriptionLabel: 'Audio transcription',
  privacyTranscriptionValue: 'Runs locally on device after model download',
  privacyFootnote:
    'If you delete the app, local entries, downloaded transcription model, and drafts may be removed with it until export or sync exists.',
  advancedTitle: 'Advanced',
  advancedDescription: 'Export and offline transcription stay here so the main screen stays lighter.',
  advancedShow: 'Show',
  advancedHide: 'Hide',
  exportTitle: 'Local export',
  exportDescription:
    'Create a local JSON snapshot when you want a backup.',
  exportIncludesLabel: 'Includes',
  exportIncludesValue:
    'Dreams, draft, locale, reminders, transcripts, and analysis metadata',
  exportFormatLabel: 'Format',
  exportFormatValue: 'JSON v5',
  exportLatestPathLabel: 'Latest file',
  exportFootnote:
    'Export writes a local file inside the app backup folder.',
  exportButton: 'Export JSON',
  exportButtonBusy: 'Exporting...',
  exportSuccessTitle: 'Export created',
  exportSuccessDescription: 'A local JSON snapshot was written to:',
  exportErrorTitle: 'Export failed',
  restoreTitle: 'Local restore',
  restoreDescription:
    'Review a saved backup before replacing local data on this device.',
  restoreAvailableLabel: 'Available backups',
  restoreLoading: 'Loading backups...',
  restoreEmptyTitle: 'No local backups yet',
  restoreEmptyDescription:
    'Create one export first, then it will appear here for preview and restore.',
  restorePreviewTitle: 'Backup preview',
  restoreSelectedValue: 'Selected',
  restoreModeLabel: 'Mode',
  restoreModeReplace: 'Replace',
  restoreModeMerge: 'Merge',
  restoreModeReplaceHint:
    'Use the backup as the new local source of truth.',
  restoreModeMergeHint:
    'Add backup dreams and keep current settings on this device.',
  restoreFileLabel: 'File',
  restoreVersionLabel: 'Backup',
  restoreLocaleLabel: 'Locale',
  restoreDreamCountLabel: 'Dreams',
  restoreCurrentCountLabel: 'Now',
  restoreIncomingCountLabel: 'From backup',
  restoreNewCountLabel: 'New',
  restoreResultCountLabel: 'Result',
  restoreOverlapCountLabel: 'Overlap',
  restoreDraftLabel: 'Draft',
  restoreDraftPresent: 'Included',
  restoreDraftMissing: 'None',
  restoreSettingsLabel: 'Settings',
  restoreSettingsReplace: 'Backup settings replace local',
  restoreSettingsKeepCurrent: 'Current settings stay as they are',
  restoreDraftActionLabel: 'Draft',
  restoreDraftActionReplace: 'Backup draft replaces local draft',
  restoreDraftActionImportIfEmpty: 'Backup draft imports only if local draft is empty',
  restoreExportedAtLabel: 'Exported',
  restoreAppVersionLabel: 'App',
  restoreRestoreButton: 'Replace with this backup',
  restoreMergeButton: 'Merge from this backup',
  restoreRestoreButtonBusy: 'Restoring...',
  restoreConfirmTitle: 'Replace local data?',
  restoreConfirmDescription:
    'This replaces dreams, draft, locale, reminder settings, and analysis settings with the selected backup.',
  restoreMergeConfirmTitle: 'Merge backup into local data?',
  restoreMergeConfirmDescription:
    'This adds backup dreams to the current archive, keeps current settings, and imports the backup draft only if your local draft is empty.',
  restoreSuccessTitle: 'Backup restored',
  restoreSuccessDescription: 'Local data was replaced from:',
  restoreSuccessModeLabel: 'Applied mode',
  restoreSuccessCountLabel: 'Dreams now on device',
  restoreErrorTitle: 'Restore failed',
  transcriptionTitle: 'Offline transcription',
  transcriptionDescription:
    'Voice notes can be transcribed on device after one model download.',
  transcriptionStatusLabel: 'Model',
  transcriptionStatusInstalled: 'Downloaded',
  transcriptionStatusMissing: 'Not downloaded yet',
  transcriptionSizeLabel: 'Size',
  transcriptionPathLabel: 'Local file',
  transcriptionDownloadButton: 'Download offline model',
  transcriptionDownloadButtonBusy: 'Downloading model...',
  transcriptionDownloadSuccessTitle: 'Model ready',
  transcriptionDownloadSuccessDescription:
    'The offline transcription model is now stored locally on this device.',
  transcriptionDownloadErrorTitle: 'Could not download model',
  transcriptionDeleteButton: 'Delete local model',
  transcriptionDeleteButtonBusy: 'Deleting model...',
  transcriptionDeleteSuccessTitle: 'Model removed',
  transcriptionDeleteSuccessDescription:
    'The offline transcription model was removed from local storage.',
  transcriptionDeleteErrorTitle: 'Could not remove model',
  scaleTestTitle: 'Scale test',
  scaleTestDescription: 'Generate sample dreams so you can stress-test Home, Archive, and Insights.',
  scaleTestSeededLabel: 'Sample dreams',
  scaleTestAdd250: 'Add 250',
  scaleTestAdd1000: 'Add 1000',
  scaleTestClear: 'Clear samples',
  scaleTestBusy: 'Working...',
  scaleTestClearTitle: 'Clear sample dreams?',
  scaleTestClearDescription: 'This removes only generated sample dreams. Your own entries stay untouched.',
  scaleTestSeededTitle: 'Sample dreams ready',
  scaleTestSeededDescription: 'The archive was filled with generated dreams for scale testing.',
  scaleTestErrorTitle: 'Could not prepare sample dreams',
  analysisTitle: 'Dream analysis',
  analysisDescription:
    'Generate a local reflection from saved text, transcript, tags, and sleep context. Network analysis stays optional and planned.',
  analysisEnabledLabel: 'Analysis layer',
  analysisEnabled: 'Enabled',
  analysisDisabled: 'Disabled',
  analysisProviderLabel: 'Provider',
  analysisProviderManual: 'Local manual',
  analysisProviderOpenAi: 'OpenAI (planned)',
  analysisNetworkLabel: 'Network',
  analysisNetworkAllowed: 'Allowed',
  analysisNetworkBlocked: 'Blocked',
  analysisEnableButton: 'Enable analysis layer',
  analysisDisableButton: 'Disable analysis layer',
  analysisUseManualButton: 'Use local analysis',
  analysisUseOpenAiButton: 'Keep OpenAI visible',
  analysisNetworkAllowButton: 'Allow network analysis later',
  analysisNetworkBlockButton: 'Keep network blocked',
  architectureTitle: 'Foundation status',
  architectureDescription:
    'Local-first data, feature-based structure, extracted styles, offline transcription, and an AI-ready analysis boundary.',
  plannedTitle: 'Planned controls',
  plannedDescription:
    'Notifications, privacy, export, AI preferences, and Health integrations should live here.',
};

const SETTINGS_COPY_UK: typeof SETTINGS_COPY_EN = {
  ...SETTINGS_COPY_EN,
  title: 'Налаштування',
  subtitle: 'Архітектура та керування продуктом будуть розширюватися тут.',
  versionTitle: 'Поточний реліз',
  footerBuildLabel: 'Kaleidoskop',
  footerStorageMetaPrefix: 'Схема',
  footerExportMetaPrefix: 'Експорт',
  reminderTitle: 'Нагадування про сон',
  reminderDescription:
    'Одне щоденне нагадування після пробудження, щоб швидше фіксувати сни.',
  reminderStatusLabel: 'Статус',
  reminderPermissionLabel: 'Сповіщення',
  reminderEnabled: 'Увімкнено',
  reminderDisabled: 'Вимкнено',
  reminderPermissionAllowed: 'Дозволені',
  reminderPermissionBlocked: 'Заблоковані',
  reminderEnableButton: 'Увімкнути нагадування',
  reminderDisableButton: 'Вимкнути нагадування',
  reminderTimeLabel: 'Час нагадування',
  reminderTimeHint: 'Натисни, щоб змінити.',
  actionCancel: 'Скасувати',
  reminderPermissionDeniedTitle: 'Сповіщення вимкнені',
  reminderPermissionDeniedDescription:
    'Дозволь сповіщення в системних налаштуваннях, щоб увімкнути нагадування.',
  reminderSaveErrorTitle: 'Помилка нагадування',
  reminderStateHint:
    'Час зберігається локально. Якщо системні сповіщення заблоковані, нагадування лишається вимкненим, доки дозвіл не повернеться.',
  reminderNotificationTitle: 'Запиши свій сон',
  reminderNotificationBody: 'Зафіксуй його, поки деталі ще свіжі.',
  languageTitle: 'Мова',
  languageDescription: 'Обери мову застосунку.',
  languageEnglish: 'EN',
  languageUkrainian: 'UA',
  architectureTitle: 'Стан фундаменту',
  privacyTitle: 'Приватність і зберігання',
  privacyDescription:
    'Дані про сни лишаються на пристрої. Акаунти і sync поки вимкнені.',
  privacyStorageLabel: 'Дані про сни',
  privacyStorageValue: 'Зберігаються локально на пристрої',
  privacySyncLabel: 'Хмарна синхронізація',
  privacySyncValue: 'Поки не ввімкнена',
  privacyAccountLabel: 'Акаунт',
  privacyAccountValue: 'Вхід не потрібен',
  privacyReminderLabel: 'Нагадування',
  privacyReminderValue: 'Працюють як локальні сповіщення',
  privacyTranscriptionLabel: 'Транскрипція аудіо',
  privacyTranscriptionValue: 'Працює локально на пристрої після завантаження моделі',
  privacyFootnote:
    'Якщо видалити застосунок, локальні записи, завантажена модель транскрипції і чернетки можуть зникнути, доки не зʼявиться експорт або синхронізація.',
  advancedTitle: 'Додатково',
  advancedDescription: 'Експорт і офлайн-транскрипція живуть тут, щоб основний екран лишався легшим.',
  advancedShow: 'Показати',
  advancedHide: 'Сховати',
  exportTitle: 'Локальний експорт',
  exportDescription:
    'Створи локальний JSON snapshot, коли потрібна резервна копія.',
  exportIncludesLabel: 'Що входить',
  exportIncludesValue:
    'Сни, чернетка, мова, нагадування, транскрипти й metadata аналізу',
  exportFormatLabel: 'Формат',
  exportFormatValue: 'JSON v5',
  exportLatestPathLabel: 'Останній файл',
  exportFootnote:
    'Експорт створює локальний файл у папці резервних копій застосунку.',
  exportButton: 'Експортувати JSON',
  exportButtonBusy: 'Експорт...',
  exportSuccessTitle: 'Експорт створено',
  exportSuccessDescription: 'Локальний JSON snapshot записано в:',
  exportErrorTitle: 'Помилка експорту',
  restoreTitle: 'Локальне відновлення',
  restoreDescription:
    'Переглянь збережену копію перед тим, як замінити локальні дані на цьому пристрої.',
  restoreAvailableLabel: 'Доступні копії',
  restoreLoading: 'Завантаження копій...',
  restoreEmptyTitle: 'Локальних копій ще немає',
  restoreEmptyDescription:
    'Спершу створи експорт, і він з’явиться тут для перегляду та відновлення.',
  restorePreviewTitle: 'Попередній перегляд копії',
  restoreSelectedValue: 'Вибрано',
  restoreModeLabel: 'Режим',
  restoreModeReplace: 'Замінити',
  restoreModeMerge: 'Об’єднати',
  restoreModeReplaceHint:
    'Використати backup як нове локальне джерело даних.',
  restoreModeMergeHint:
    'Додати сни з backup і лишити поточні налаштування цього пристрою.',
  restoreFileLabel: 'Файл',
  restoreVersionLabel: 'Копія',
  restoreLocaleLabel: 'Мова',
  restoreDreamCountLabel: 'Снів',
  restoreCurrentCountLabel: 'Зараз',
  restoreIncomingCountLabel: 'З backup',
  restoreNewCountLabel: 'Нових',
  restoreResultCountLabel: 'Результат',
  restoreOverlapCountLabel: 'Збігів',
  restoreDraftLabel: 'Чернетка',
  restoreDraftPresent: 'Є',
  restoreDraftMissing: 'Немає',
  restoreSettingsLabel: 'Налаштування',
  restoreSettingsReplace: 'Налаштування з backup замінять локальні',
  restoreSettingsKeepCurrent: 'Поточні налаштування лишаться як є',
  restoreDraftActionLabel: 'Чернетка',
  restoreDraftActionReplace: 'Чернетка з backup замінить локальну',
  restoreDraftActionImportIfEmpty: 'Чернетка з backup імпортується, лише якщо локальна порожня',
  restoreExportedAtLabel: 'Експортовано',
  restoreAppVersionLabel: 'Застосунок',
  restoreRestoreButton: 'Замінити цим backup',
  restoreMergeButton: 'Об’єднати з цього backup',
  restoreRestoreButtonBusy: 'Відновлення...',
  restoreConfirmTitle: 'Замінити локальні дані?',
  restoreConfirmDescription:
    'Це замінить сни, чернетку, мову, налаштування нагадувань і налаштування аналізу вибраною копією.',
  restoreMergeConfirmTitle: 'Об’єднати backup з локальними даними?',
  restoreMergeConfirmDescription:
    'Це додасть сни з backup у поточний архів, лишить поточні налаштування і імпортує чернетку з backup лише якщо локальна порожня.',
  restoreSuccessTitle: 'Копію відновлено',
  restoreSuccessDescription: 'Локальні дані замінено з:',
  restoreSuccessModeLabel: 'Застосований режим',
  restoreSuccessCountLabel: 'Снів тепер на пристрої',
  restoreErrorTitle: 'Помилка відновлення',
  transcriptionTitle: 'Офлайн-транскрипція',
  transcriptionDescription:
    'Голосові нотатки можна транскрибувати на пристрої після одного завантаження моделі.',
  transcriptionStatusLabel: 'Модель',
  transcriptionStatusInstalled: 'Завантажена',
  transcriptionStatusMissing: 'Ще не завантажена',
  transcriptionSizeLabel: 'Розмір',
  transcriptionPathLabel: 'Локальний файл',
  transcriptionDownloadButton: 'Завантажити офлайн-модель',
  transcriptionDownloadButtonBusy: 'Завантаження моделі...',
  transcriptionDownloadSuccessTitle: 'Модель готова',
  transcriptionDownloadSuccessDescription:
    'Офлайн-модель транскрипції тепер збережена локально на цьому пристрої.',
  transcriptionDownloadErrorTitle: 'Не вдалося завантажити модель',
  transcriptionDeleteButton: 'Видалити локальну модель',
  transcriptionDeleteButtonBusy: 'Видалення моделі...',
  transcriptionDeleteSuccessTitle: 'Модель видалено',
  transcriptionDeleteSuccessDescription:
    'Офлайн-модель транскрипції видалено з локального сховища.',
  transcriptionDeleteErrorTitle: 'Не вдалося видалити модель',
  scaleTestTitle: 'Перевірка масштабу',
  scaleTestDescription: 'Згенеруй тестові сни, щоб прогнати Home, Архів і Insights на великому обсязі.',
  scaleTestSeededLabel: 'Тестових снів',
  scaleTestAdd250: 'Додати 250',
  scaleTestAdd1000: 'Додати 1000',
  scaleTestClear: 'Очистити тести',
  scaleTestBusy: 'Працюю...',
  scaleTestClearTitle: 'Очистити тестові сни?',
  scaleTestClearDescription: 'Це видалить лише згенеровані тестові сни. Твої власні записи лишаться.',
  scaleTestSeededTitle: 'Тестові сни готові',
  scaleTestSeededDescription: 'Архів заповнено згенерованими снами для перевірки масштабу.',
  scaleTestErrorTitle: 'Не вдалося підготувати тестові сни',
  analysisTitle: 'Аналіз сну',
  analysisDescription:
    'Генеруй локальну рефлексію зі збереженого тексту, транскрипту, тегів і sleep context. Мережевий аналіз лишається опційним і запланованим.',
  analysisEnabledLabel: 'Шар аналізу',
  analysisEnabled: 'Увімкнений',
  analysisDisabled: 'Вимкнений',
  analysisProviderLabel: 'Провайдер',
  analysisProviderManual: 'Локальний manual',
  analysisProviderOpenAi: 'OpenAI (заплановано)',
  analysisNetworkLabel: 'Мережа',
  analysisNetworkAllowed: 'Дозволена',
  analysisNetworkBlocked: 'Заблокована',
  analysisEnableButton: 'Увімкнути шар аналізу',
  analysisDisableButton: 'Вимкнути шар аналізу',
  analysisUseManualButton: 'Увімкнути локальний аналіз',
  analysisUseOpenAiButton: 'Лишити OpenAI видимим',
  analysisNetworkAllowButton: 'Дозволити мережевий аналіз пізніше',
  analysisNetworkBlockButton: 'Тримати мережу заблокованою',
  architectureDescription:
    'Local-first дані, feature-структура, винесені стилі, офлайн-транскрипція і AI-ready межа аналізу.',
  plannedTitle: 'Заплановані розділи',
  plannedDescription:
    'Сповіщення, приватність, експорт, AI-параметри та інтеграції зі Здоров’ям.',
};

export type SettingsCopy = typeof SETTINGS_COPY_EN;

export function getSettingsCopy(locale: AppLocale): SettingsCopy {
  return locale === 'uk' ? SETTINGS_COPY_UK : SETTINGS_COPY_EN;
}
