import { AppLocale } from '../../i18n/types';

const SETTINGS_COPY_EN = {
  title: 'Settings',
  subtitle:
    'Local-first controls for reminders, privacy, backups, and analysis.',
  toggleShow: 'Show',
  toggleHide: 'Hide',
  footerBuildLabel: 'Kaleidoskop',
  footerStorageMetaPrefix: 'Schema',
  footerExportMetaPrefix: 'Export',
  reminderTitle: 'Dream reminder',
  reminderDescription:
    'One daily nudge after waking so you capture dreams faster.',
  reminderPermissionLabel: 'Notifications',
  reminderPermissionBlocked: 'Blocked',
  reminderTimeLabel: 'Reminder time',
  reminderTimeHint: 'Tap to change.',
  reminderPreviewWakeAction: 'Preview wake flow',
  reminderPreviewWakeMeta:
    'Open the reminder entry screen without waiting for the next notification.',
  devPreviewMonthlyReport: 'Preview monthly report',
  devPreviewBackupOnboarding: 'Preview backup onboarding',
  devPreviewBackupOnboardingMeta:
    'Open the one-time modal preview and reset its seen state.',
  devPreviewSyncDiagnostics: 'Preview sync diagnostics',
  devPreviewSyncDiagnosticsMeta:
    'Open the debug-only screen with the latest sync snapshot and recent sync attempts.',
  actionCancel: 'Cancel',
  reminderPermissionDeniedTitle: 'Notifications disabled',
  reminderPermissionDeniedDescription:
    'Allow notifications in system settings to enable dream reminders.',
  reminderSaveErrorTitle: 'Reminder error',
  reminderNotificationTitle: 'Record your dream',
  reminderNotificationBody: 'Capture it while details are still fresh.',
  languageTitle: 'Language',
  languageDescription: 'Choose your app language.',
  languageEnglish: 'EN',
  languageUkrainian: 'UA',
  privacyTitle: 'Privacy and storage',
  privacyDescription:
    'Dream data stays on your device by default. Cloud stays optional and does not block first capture.',
  privacyStorageLabel: 'Dream data',
  privacyStorageValue: 'On this device',
  privacyReminderLabel: 'Reminders',
  privacyReminderValue: 'Local notifications only',
  privacyFootnote:
    'If you delete the app, local entries, downloaded transcription model, and drafts may be removed with it until export or sync exists.',
  cloudTitle: 'Cloud backup',
  cloudDescription:
    'Keep one archive available across devices.',
  cloudConfigLabel: 'Runtime config',
  cloudConfigReady: 'Ready',
  cloudConfigMissing: 'Missing',
  cloudConfigUrlLabel: 'Supabase URL',
  cloudConfigUrlHint: 'Project URL, usually *.supabase.co.',
  cloudConfigAnonKeyLabel: 'Anon key',
  cloudConfigAnonKeyHint: 'Public anon key used by the mobile client.',
  cloudSessionLabel: 'Backup',
  cloudSessionSignedOut: 'Off',
  cloudSessionSignedIn: 'On',
  cloudAccountLabel: 'Account',
  cloudAccountDisconnected: 'Not linked yet',
  cloudAccountAnonymous: 'Needs email account',
  cloudPathTitle: 'What do you need on this device?',
  cloudPathDescription:
    'Choose whether this is the device where backup starts or one that should open an existing archive.',
  cloudPathThisDevice: 'Start here',
  cloudPathAnotherDevice: 'Open existing',
  cloudFirstDeviceTitle: 'Start backup on this device',
  cloudFirstDeviceDescription:
    'Create the backup on this device first, then save it under an email account if you want another device to open the same archive.',
  cloudGuideTitle: 'How backup works',
  cloudGuideStepOne: 'Turn on backup on your first device.',
  cloudGuideStepTwo: 'Save it under an email account if you want the same archive on another device.',
  cloudGuideStepThree: 'Open that same backup on another device and run sync.',
  cloudGuideExistingStepOne:
    'Enter the same email and password you used for this backup before.',
  cloudGuideExistingStepTwo:
    'Open that archive on this device and let sync pull the latest changes.',
  cloudGuideExistingStepThree:
    'Keep sync on so edits and deletes continue moving between devices.',
  cloudGuideAnonymousStepOne: 'This device is already connected to backup.',
  cloudGuideAnonymousStepTwo: 'Save this backup under an email account next.',
  cloudGuideAnonymousStepThree: 'Then open the same backup on another device.',
  cloudGuideNamedStepOne: 'This backup is already linked to your account.',
  cloudGuideNamedStepTwo: 'Open the same backup with this email on another device.',
  cloudGuideNamedStepThree: 'Keep sync on so changes move between devices.',
  cloudSuccessTitle: 'Next step',
  cloudConnectedSuccessTitle: 'Backup is on for this device',
  cloudConnectedSuccessDescription:
    'Save this backup under an email account next if you want another device to open the same archive.',
  cloudSignedInSuccessTitle: 'Existing backup opened',
  cloudSignedInSuccessDescription:
    'This device is now linked to your backup. Run sync now to pull the latest archive changes.',
  cloudUpgradedSuccessTitle: 'Backup account saved',
  cloudUpgradedSuccessDescription:
    'This backup is now linked to your email account. Open the same backup on another device with these credentials.',
  cloudResetSuccessTitle: 'Check your inbox',
  cloudResetSuccessDescription:
    'Open the reset link from that email, then come back and sign in with the new password.',
  backupCueOpenAction: 'Open backup',
  backupCueConnectTitle: 'Back up this archive',
  backupCueConnectDescription:
    'Keep this archive available on another device before more local-only changes pile up.',
  backupCueSyncOffTitle: 'Backup is connected, but sync is off',
  backupCueSyncOffDescription:
    'Turn sync back on before switching devices so newer local changes do not stay behind.',
  backupCueReviewPendingTitle: 'Saved review sets are newer on this device',
  backupCueReviewPendingDescription:
    'Saved months and threads changed locally. Open backup and run sync before switching devices.',
  backupOnboardingEyebrow: 'Archive started',
  backupOnboardingTitle: 'You already have dreams worth keeping',
  backupOnboardingDescription:
    'After a few entries, backup starts paying off. Save this archive before it becomes device-bound.',
  backupOnboardingDreamsLabel: 'Saved dreams',
  backupOnboardingThresholdLabel: 'Prompt threshold',
  backupOnboardingValueTitle: 'Why now',
  backupOnboardingValueDescription:
    'Backup keeps this archive restorable and makes saved review sets useful across devices once they start to accumulate.',
  backupOnboardingPrimaryAction: 'Open backup',
  backupOnboardingLaterAction: 'Later',
  backupOnboardingPreviewTitle: 'Backup onboarding preview',
  backupOnboardingPreviewDescription:
    'Debug the one-time backup prompt without waiting for a fresh account.',
  backupOnboardingPreviewSeenTitle: 'Seen state',
  backupOnboardingPreviewSeenValue: 'Seen',
  backupOnboardingPreviewUnseenValue: 'Unseen',
  backupOnboardingPreviewEligibilityTitle: 'Production gate',
  backupOnboardingPreviewEligibilityReady: 'Would open on Home now.',
  backupOnboardingPreviewEligibilityWaiting:
    'Needs 3 saved dreams and an unseen state.',
  backupOnboardingPreviewEligibilityReadyValue: 'Ready',
  backupOnboardingPreviewEligibilityWaitingValue: 'Waiting',
  backupOnboardingPreviewOpenAction: 'Open modal preview',
  backupOnboardingPreviewResetAction: 'Reset seen state',
  backupOnboardingPreviewMarkSeenAction: 'Mark as seen',
  backupOnboardingPreviewFootnote:
    'In production this modal opens once after the archive reaches 3 saved dreams.',
  backupScreenTitle: 'Backup & sync',
  backupScreenSubtitle:
    'Sync, export, and restore one archive.',
  backupTimelineTitle: 'Sync activity',
  backupTimelineDescription:
    'See the last sync, latest snapshot, and this device state.',
  backupTimelineSyncTitle: 'Last successful sync',
  backupTimelineSnapshotTitle: 'Latest backup snapshot',
  backupTimelineDeviceTitle: 'This device',
  backupTimelineDeviceFreshnessLabel: 'Freshest local change',
  backupTimelineSnapshotMissing: 'No local snapshot yet',
  backupTimelineSnapshotMissingMeta:
    'Export JSON once and the latest restore preview will appear here.',
  backupTimelineDeviceLocalOnly: 'Local only',
  backupTimelineDeviceNeedsAttention: 'Needs attention',
  backupTimelineDeviceAheadSingle: '1 change ahead',
  backupTimelineDeviceAheadPlural: '{count} changes ahead',
  backupTimelineDeviceReviewAhead: 'Review sets ahead',
  backupTimelineDeviceCaughtUp: 'Caught up',
  backupTimelineDeviceWaitingFirstSync: 'Waiting for first sync',
  backupTimelineDeviceNoLocalChanges: 'No local changes yet',
  backupTimelineReviewSetsLabel: 'Review sets',
  backupTimelineReviewSetsPending: 'Review sets waiting for sync',
  backupContentTrustTitle: 'What may still be local',
  backupContentTrustDescription:
    'Check what may still be local on this device.',
  backupContentTrustAudioTitle: 'Voice notes',
  backupContentTrustAudioMeta: '{total} saved • {synced} already in cloud',
  backupContentTrustAudioEmpty: 'No voice notes yet',
  backupContentTrustAudioEmptyMeta:
    'Audio trust will appear here once a dream includes a voice note.',
  backupContentTrustAudioAllBackedUp: 'All backed up',
  backupContentTrustAudioStillLocalSingle: '1 still local',
  backupContentTrustAudioStillLocalPlural: '{count} still local',
  backupContentTrustTranscriptTitle: 'Saved transcripts',
  backupContentTrustTranscriptMeta: '{total} saved • {edited} edited',
  backupContentTrustTranscriptEmpty: 'No saved transcripts',
  backupContentTrustTranscriptEmptyMeta:
    'Transcript trust will appear here once a dream includes saved transcript text.',
  backupContentTrustTranscriptCaughtUp: 'Caught up',
  backupContentTrustTranscriptStillLocalSingle: '1 newer locally',
  backupContentTrustTranscriptStillLocalPlural: '{count} newer locally',
  backupContentTrustReviewTitle: 'Saved review sets',
  backupContentTrustReviewMeta: '{total} saved • {months} months • {threads} threads',
  backupContentTrustReviewEmpty: 'No saved sets yet',
  backupContentTrustReviewEmptyMeta:
    'Saved months and threads will appear here once you start curating review work.',
  backupContentTrustReviewCaughtUp: 'Caught up',
  backupContentTrustReviewStillLocal: 'Newer locally',
  backupContentTrustLocalOnly: 'Local only',
  cloudExistingBackupTitle: 'Open existing backup',
  cloudSaveBackupTitle: 'Save this backup',
  cloudIdentityTitle: 'Named account',
  cloudIdentityDescriptionSignedOut:
    'Sign in with the same email and password on another device to open the same archive.',
  cloudIdentityDescriptionAnonymous:
    'Save this backup under an email account so another device can open it.',
  cloudIdentityEmailLabel: 'Email',
  cloudIdentityEmailHint: 'Used for the same cloud account across devices.',
  cloudIdentityPasswordLabel: 'Password',
  cloudIdentityPasswordHint: 'Use at least 6 characters.',
  cloudCredentialsMissingTitle: 'Missing credentials',
  cloudCredentialsMissingDescription:
    'Enter an email and password before continuing.',
  cloudEmailMissingTitle: 'Missing email',
  cloudEmailMissingDescription:
    'Enter the email for the backup account first.',
  cloudSyncToggleLabel: 'Auto sync',
  cloudSyncToggleHint:
    'Auto sync can be enabled only after cloud backup is connected.',
  cloudSyncDisabled: 'Off',
  cloudSyncEnabled: 'On',
  cloudPendingLabel: 'Pending',
  cloudSyncedLabel: 'Synced',
  cloudPulledLabel: 'Pulled',
  cloudSkippedLabel: 'Skipped',
  cloudConflictsLabel: 'Conflicts',
  cloudLocalWinsLabel: 'Local wins',
  cloudRemoteWinsLabel: 'Remote wins',
  cloudErrorsLabel: 'Errors',
  cloudSaveConfigButton: 'Save config',
  cloudClearConfigButton: 'Clear config',
  cloudConnectButton: 'Turn on backup',
  cloudConnectButtonBusy: 'Connecting...',
  cloudSignInExistingButton: 'Open existing backup',
  cloudSignInExistingButtonBusy: 'Signing in...',
  cloudResetPasswordButton: 'Send reset email',
  cloudResetPasswordButtonBusy: 'Sending email...',
  cloudUpgradeAccountButton: 'Save backup account',
  cloudUpgradeAccountButtonBusy: 'Saving account...',
  cloudDisconnectButton: 'Turn off backup',
  cloudDisconnectButtonBusy: 'Disconnecting...',
  cloudSyncNowButton: 'Sync now',
  cloudSyncNowButtonBusy: 'Syncing...',
  cloudLastSyncLabel: 'Last sync',
  cloudLastSyncNever: 'Never',
  cloudSyncStateIdle: 'Idle',
  cloudSyncStateSyncing: 'Syncing',
  cloudSyncStateSuccess: 'Synced',
  cloudSyncStateError: 'Needs attention',
  cloudSyncManualErrorTitle: 'Backup sync failed',
  cloudConfigMissingTitle: 'Supabase config missing',
  cloudConfigMissingDescription:
    'Add a valid project URL and anon key before connecting cloud.',
  cloudConfigErrorTitle: 'Cloud config error',
  cloudConnectErrorTitle: 'Backup connect failed',
  cloudAccountSignInErrorTitle: 'Account sign-in failed',
  cloudPasswordResetErrorTitle: 'Password reset failed',
  cloudPasswordResetSuccessTitle: 'Reset email sent',
  cloudPasswordResetSuccessDescription:
    'If this backup account exists, check that inbox for the password reset link.',
  cloudAccountUpgradeErrorTitle: 'Account upgrade failed',
  cloudDisconnectErrorTitle: 'Backup disconnect failed',
  cloudFootnote:
    'Your dreams stay local first. Cloud backup only adds sync and restore across devices when you choose to connect it.',
  exportTitle: 'Local export',
  exportDescription:
    'Create a JSON backup or a readable PDF snapshot.',
  exportIncludesLabel: 'Includes',
  exportIncludesValue:
    'Dreams, draft, locale, reminders, transcripts, and analysis metadata',
  exportFormatLabel: 'Format',
  exportFormatValue: 'JSON v7 + PDF snapshot',
  exportLatestPathLabel: 'Latest file',
  exportFootnote:
    'JSON works as a restore backup. PDF is a readable archive snapshot and does not replace restore.',
  exportButton: 'Export JSON',
  exportButtonBusy: 'Exporting...',
  exportPdfButton: 'Export PDF',
  exportPdfButtonBusy: 'Rendering PDF...',
  exportJsonGuidance: 'Use JSON if you may restore this archive later.',
  exportPdfGuidance: 'Use PDF only for reading or sharing.',
  exportSuccessTitle: 'Export created',
  exportSuccessDescription: 'A local JSON snapshot was written to:',
  exportPdfSuccessTitle: 'PDF created',
  exportPdfSuccessDescription: 'A local PDF snapshot was written to:',
  exportErrorTitle: 'Export failed',
  exportPdfErrorTitle: 'PDF export failed',
  restoreTitle: 'Local restore',
  restoreDescription:
    'Choose a backup, review it, then restore.',
  restoreAvailableLabel: 'Available backups',
  restoreLoading: 'Loading backups...',
  restoreEmptyTitle: 'No local backups yet',
  restoreEmptyDescription:
    'Create one export first, then it will appear here for preview and restore.',
  restorePreviewTitle: 'Backup preview',
  restoreSelectedValue: 'Selected',
  restoreModeLabel: 'Mode',
  restoreModeReplace: 'Replace',
  restoreModeMerge: 'Merge',
  restoreModeReplaceHint:
    'Replace local dreams, draft, locale, reminders, and analysis settings.',
  restoreModeMergeHint:
    'Add backup dreams, keep current settings, and import the backup draft only if the local draft is empty.',
  restoreNoBackupAction: 'Create JSON backup first',
  restoreSelectBackupAction: 'Choose a backup first',
  restoreLoadingAction: 'Preparing backup preview...',
  restoreReplaceWarning: 'Replace overwrites the local archive on this device.',
  restoreMergeGuidance:
    'Merge keeps current settings and adds dreams from the backup.',
  restoreFileLabel: 'File',
  restoreVersionLabel: 'Backup',
  restoreLocaleLabel: 'Locale',
  restoreDreamCountLabel: 'Dreams',
  restoreCurrentCountLabel: 'Now',
  restoreIncomingCountLabel: 'From backup',
  restoreNewCountLabel: 'New',
  restoreResultCountLabel: 'Result',
  restoreOverlapCountLabel: 'Overlap',
  restoreDraftLabel: 'Draft',
  restoreDraftPresent: 'Included',
  restoreDraftMissing: 'None',
  restoreSettingsLabel: 'Settings',
  restoreSettingsReplace: 'Backup settings replace local',
  restoreSettingsKeepCurrent: 'Current settings stay as they are',
  restoreDraftActionLabel: 'Draft',
  restoreDraftActionReplace: 'Backup draft replaces local draft',
  restoreDraftActionImportIfEmpty:
    'Backup draft imports only if local draft is empty',
  restoreExportedAtLabel: 'Exported',
  restoreAppVersionLabel: 'App',
  restoreRestoreButton: 'Replace with this backup',
  restoreMergeButton: 'Merge from this backup',
  restoreRestoreButtonBusy: 'Restoring...',
  restoreConfirmTitle: 'Replace local data?',
  restoreConfirmDescription:
    'This will replace local dreams, draft, locale, reminder settings, and analysis settings with the selected backup.',
  restoreMergeConfirmTitle: 'Merge backup into local data?',
  restoreMergeConfirmDescription:
    'This will add backup dreams to the current archive, keep current settings, and import the backup draft only if the local draft is empty.',
  restoreSuccessTitle: 'Backup restored',
  restoreSuccessDescription: 'Local data was replaced from:',
  restoreSuccessModeLabel: 'Applied mode',
  restoreSuccessCountLabel: 'Dreams now on device',
  restoreErrorTitle: 'Restore failed',
  transcriptionTitle: 'Offline transcription',
  transcriptionDescription:
    'Transcribe voice notes on device after one model download.',
  transcriptionStatusLabel: 'Model',
  transcriptionStatusInstalled: 'Downloaded',
  transcriptionStatusMissing: 'Not downloaded yet',
  transcriptionSizeLabel: 'Size',
  transcriptionPathLabel: 'Local file',
  transcriptionDownloadButton: 'Download offline model',
  transcriptionDownloadButtonBusy: 'Downloading model...',
  transcriptionDownloadSuccessTitle: 'Model ready',
  transcriptionDownloadSuccessDescription:
    'The offline transcription model is now stored locally on this device.',
  transcriptionDownloadErrorTitle: 'Could not download model',
  transcriptionDeleteButton: 'Delete local model',
  transcriptionDeleteButtonBusy: 'Deleting model...',
  transcriptionMissingHint: 'Download the model once to enable offline transcription.',
  transcriptionDeleteSuccessTitle: 'Model removed',
  transcriptionDeleteSuccessDescription:
    'The offline transcription model was removed from local storage.',
  transcriptionDeleteErrorTitle: 'Could not remove model',
  scaleTestTitle: 'Scale test',
  scaleTestDescription:
    'Generate sample dreams for stress testing.',
  developerToolsTitle: 'Developer tools',
  developerToolsDescription:
    'Debug-only tools for previews, seed data, and stress testing.',
  devSyncHistoryTitle: 'Recent sync attempts',
  devSyncHistoryDescription:
    'Debug-only history of the latest cloud sync outcomes on this device.',
  devSyncReasonManual: 'Manual',
  devSyncReasonLaunch: 'Launch',
  devSyncSnapshotTitle: 'Latest sync snapshot',
  devSyncSnapshotDescription:
    'Debug-only view of the latest stored sync result on this device.',
  devSyncSnapshotStatusTitle: 'Status',
  devSyncSnapshotReasonTitle: 'Reason',
  devSyncSnapshotPendingTitle: 'Pending changes',
  devSyncSnapshotUploadsTitle: 'Uploaded',
  devSyncSnapshotPullsTitle: 'Pulled',
  devSyncSnapshotConflictsTitle: 'Conflicts',
  devSyncSnapshotErrorsTitle: 'Last error',
  devSyncHistoryEmptyTitle: 'No sync attempts yet',
  devSyncHistoryEmptyDescription:
    'Run backup sync once and the latest debug history will appear here.',
  scaleTestSeededLabel: 'Sample dreams',
  scaleTestAdd250: 'Add 250',
  scaleTestAdd1000: 'Add 1000',
  scaleTestClear: 'Clear samples',
  scaleTestBusy: 'Working...',
  scaleTestClearTitle: 'Clear sample dreams?',
  scaleTestClearDescription:
    'This removes only generated sample dreams. Your own entries stay untouched.',
  scaleTestSeededTitle: 'Sample dreams ready',
  scaleTestSeededDescription:
    'The archive was filled with generated dreams for scale testing.',
  scaleTestErrorTitle: 'Could not prepare sample dreams',
  analysisTitle: 'Dream analysis',
  analysisDescription:
    'Generate a local reflection from saved dream data.',
  analysisProviderLabel: 'Provider',
  analysisProviderManual: 'Local manual',
  analysisProviderOpenAi: 'OpenAI (planned)',
  analysisNetworkLabel: 'Network',
  analysisNetworkAllowed: 'Allowed',
  analysisNetworkBlocked: 'Blocked',
  analysisLocalNetworkHint: 'Local analysis does not need network access.',
};

const SETTINGS_COPY_UK: typeof SETTINGS_COPY_EN = {
  ...SETTINGS_COPY_EN,
  title: 'Налаштування',
  subtitle:
    'Локальні керування нагадуваннями, приватністю, копіями й аналізом.',
  toggleShow: 'Показати',
  toggleHide: 'Сховати',
  footerBuildLabel: 'Kaleidoskop',
  footerStorageMetaPrefix: 'Схема',
  footerExportMetaPrefix: 'Експорт',
  reminderTitle: 'Нагадування про сон',
  reminderDescription:
    'Одне щоденне нагадування після пробудження, щоб швидше фіксувати сни.',
  reminderPermissionLabel: 'Сповіщення',
  reminderPermissionBlocked: 'Заблоковані',
  reminderTimeLabel: 'Час нагадування',
  reminderTimeHint: 'Натисни, щоб змінити.',
  reminderPreviewWakeAction: 'Переглянути ранковий режим',
  reminderPreviewWakeMeta:
    'Відкрий екран після нагадування без очікування наступного сповіщення.',
  devPreviewMonthlyReport: 'Переглянути місячний звіт',
  devPreviewBackupOnboarding: 'Переглянути backup onboarding',
  devPreviewBackupOnboardingMeta:
    'Відкрий preview одноразового modal і скинь його seen state.',
  devPreviewSyncDiagnostics: 'Переглянути sync diagnostics',
  devPreviewSyncDiagnosticsMeta:
    'Відкрий debug-only екран з останнім sync snapshot і недавніми sync спробами.',
  actionCancel: 'Скасувати',
  reminderPermissionDeniedTitle: 'Сповіщення вимкнені',
  reminderPermissionDeniedDescription:
    'Дозволь сповіщення в системних налаштуваннях, щоб увімкнути нагадування.',
  reminderSaveErrorTitle: 'Помилка нагадування',
  reminderNotificationTitle: 'Запиши свій сон',
  reminderNotificationBody: 'Зафіксуй його, поки деталі ще свіжі.',
  languageTitle: 'Мова',
  languageDescription: 'Обери мову застосунку.',
  languageEnglish: 'EN',
  languageUkrainian: 'UA',
  privacyTitle: 'Приватність і зберігання',
  privacyDescription:
    'Дані про сни лишаються на пристрої за замовчуванням. Хмара лишається опційною і не блокує перший запис.',
  privacyStorageLabel: 'Дані про сни',
  privacyStorageValue: 'Лише на цьому пристрої',
  privacyReminderLabel: 'Нагадування',
  privacyReminderValue: 'Локальні сповіщення',
  privacyFootnote:
    'Якщо видалити застосунок, локальні записи, завантажена модель транскрипції і чернетки можуть зникнути, доки не зʼявиться експорт або синхронізація.',
  cloudTitle: 'Хмарний backup',
  cloudDescription:
    'Тримай один архів доступним на кількох пристроях.',
  cloudConfigLabel: 'Runtime-конфіг',
  cloudConfigReady: 'Готово',
  cloudConfigMissing: 'Відсутній',
  cloudConfigUrlLabel: 'Supabase URL',
  cloudConfigUrlHint: 'URL проєкту, зазвичай *.supabase.co.',
  cloudConfigAnonKeyLabel: 'Anon key',
  cloudConfigAnonKeyHint: 'Публічний anon key для mobile-клієнта.',
  cloudSessionLabel: 'Backup',
  cloudSessionSignedOut: 'Вимкнено',
  cloudSessionSignedIn: 'Увімкнено',
  cloudAccountLabel: 'Акаунт',
  cloudAccountDisconnected: 'Ще не привʼязано',
  cloudAccountAnonymous: 'Потрібен email-акаунт',
  cloudPathTitle: 'Що тобі потрібно на цьому пристрої?',
  cloudPathDescription:
    'Обери, чи це пристрій, на якому backup починається, чи той, що має відкрити вже існуючий архів.',
  cloudPathThisDevice: 'Почати тут',
  cloudPathAnotherDevice: 'Відкрити існуючий',
  cloudFirstDeviceTitle: 'Почати backup на цьому пристрої',
  cloudFirstDeviceDescription:
    'Спершу створи backup на цьому пристрої, а потім збережи його під email-акаунтом, якщо хочеш відкрити той самий архів на іншому пристрої.',
  cloudGuideTitle: 'Як працює backup',
  cloudGuideStepOne: 'Увімкни backup на своєму першому пристрої.',
  cloudGuideStepTwo: 'Збережи його під email-акаунтом, якщо хочеш той самий архів на іншому пристрої.',
  cloudGuideStepThree: 'Відкрий той самий backup на іншому пристрої й запусти sync.',
  cloudGuideExistingStepOne:
    'Введи ту саму пошту і пароль, які вже використовуються для цього backup.',
  cloudGuideExistingStepTwo:
    'Відкрий цей архів на пристрої й дай sync підтягнути останні зміни.',
  cloudGuideExistingStepThree:
    'Тримай sync увімкненим, щоб редагування і видалення ходили між пристроями.',
  cloudGuideAnonymousStepOne: 'Цей пристрій уже підключений до backup.',
  cloudGuideAnonymousStepTwo: 'Тепер збережи цей backup під email-акаунтом.',
  cloudGuideAnonymousStepThree: 'Після цього відкрий той самий backup на іншому пристрої.',
  cloudGuideNamedStepOne: 'Цей backup уже привʼязаний до твого акаунта.',
  cloudGuideNamedStepTwo: 'Відкрий той самий backup з цією поштою на іншому пристрої.',
  cloudGuideNamedStepThree: 'Тримай sync увімкненим, щоб зміни ходили між пристроями.',
  cloudSuccessTitle: 'Що далі',
  cloudConnectedSuccessTitle: 'Backup увімкнено на цьому пристрої',
  cloudConnectedSuccessDescription:
    'Тепер збережи цей backup під email-акаунтом, якщо хочеш відкрити той самий архів на іншому пристрої.',
  cloudSignedInSuccessTitle: 'Існуючий backup відкрито',
  cloudSignedInSuccessDescription:
    'Цей пристрій уже підключений до твого backup. Тепер запусти sync, щоб підтягнути останні зміни архіву.',
  cloudUpgradedSuccessTitle: 'Backup-акаунт збережено',
  cloudUpgradedSuccessDescription:
    'Тепер цей backup привʼязаний до твоєї пошти. Відкрий той самий backup на іншому пристрої з цими даними.',
  cloudResetSuccessTitle: 'Перевір пошту',
  cloudResetSuccessDescription:
    'Відкрий посилання зі листа для скидання пароля, а потім повернись сюди й увійди з новим паролем.',
  backupCueOpenAction: 'Відкрити backup',
  backupCueConnectTitle: 'Збережи цей архів у backup',
  backupCueConnectDescription:
    'Зроби архів доступним на іншому пристрої, поки локальних змін не стало більше.',
  backupCueSyncOffTitle: 'Backup підключено, але sync вимкнений',
  backupCueSyncOffDescription:
    'Увімкни sync знову перед переходом на інший пристрій, щоб нові локальні зміни не лишилися тут.',
  backupCueReviewPendingTitle: 'Збережені набори ревʼю новіші на цьому пристрої',
  backupCueReviewPendingDescription:
    'Збережені місяці й нитки змінилися локально. Відкрий backup і запусти sync перед переходом на інший пристрій.',
  backupOnboardingEyebrow: 'Архів уже почався',
  backupOnboardingTitle: 'У тебе вже є сни, які варто зберегти',
  backupOnboardingDescription:
    'Після кількох записів backup уже має сенс. Збережи цей архів, поки він не лишився прив’язаним до одного пристрою.',
  backupOnboardingDreamsLabel: 'Збережених снів',
  backupOnboardingThresholdLabel: 'Поріг показу',
  backupOnboardingValueTitle: 'Чому саме зараз',
  backupOnboardingValueDescription:
    'Backup тримає архів придатним до відновлення і робить saved review sets корисними між пристроями, коли вони починають накопичуватись.',
  backupOnboardingPrimaryAction: 'Відкрити backup',
  backupOnboardingLaterAction: 'Пізніше',
  backupOnboardingPreviewTitle: 'Preview backup onboarding',
  backupOnboardingPreviewDescription:
    'Перевір одноразовий backup prompt без очікування нового акаунта.',
  backupOnboardingPreviewSeenTitle: 'Стан показу',
  backupOnboardingPreviewSeenValue: 'Вже показано',
  backupOnboardingPreviewUnseenValue: 'Ще не показано',
  backupOnboardingPreviewEligibilityTitle: 'Production gate',
  backupOnboardingPreviewEligibilityReady: 'На Home уже відкрився б.',
  backupOnboardingPreviewEligibilityWaiting:
    'Потрібно 3 збережені сни і unseen state.',
  backupOnboardingPreviewEligibilityReadyValue: 'Готово',
  backupOnboardingPreviewEligibilityWaitingValue: 'Очікує',
  backupOnboardingPreviewOpenAction: 'Відкрити modal preview',
  backupOnboardingPreviewResetAction: 'Скинути seen state',
  backupOnboardingPreviewMarkSeenAction: 'Позначити як показаний',
  backupOnboardingPreviewFootnote:
    'У production цей modal відкривається один раз після 3 збережених снів.',
  backupScreenTitle: 'Backup і sync',
  backupScreenSubtitle:
    'Синк, експорт і відновлення одного архіву.',
  backupTimelineTitle: 'Активність синку',
  backupTimelineDescription:
    'Подивись на останній синк, snapshot і стан цього пристрою.',
  backupTimelineSyncTitle: 'Останній успішний синк',
  backupTimelineSnapshotTitle: 'Останній backup snapshot',
  backupTimelineDeviceTitle: 'Цей пристрій',
  backupTimelineDeviceFreshnessLabel: 'Найсвіжіша локальна зміна',
  backupTimelineSnapshotMissing: 'Локального snapshot ще немає',
  backupTimelineSnapshotMissingMeta:
    'Зроби JSON export один раз, і тут з’явиться найновіший restore preview.',
  backupTimelineDeviceLocalOnly: 'Лише локально',
  backupTimelineDeviceNeedsAttention: 'Потрібна увага',
  backupTimelineDeviceAheadSingle: 'На 1 зміну попереду',
  backupTimelineDeviceAheadPlural: 'На {count} змін попереду',
  backupTimelineDeviceReviewAhead: 'Набори ревʼю попереду',
  backupTimelineDeviceCaughtUp: 'Актуально',
  backupTimelineDeviceWaitingFirstSync: 'Чекає на перший синк',
  backupTimelineDeviceNoLocalChanges: 'Локальних змін ще немає',
  backupTimelineReviewSetsLabel: 'Набори ревʼю',
  backupTimelineReviewSetsPending: 'Набори ревʼю чекають на синк',
  backupContentTrustTitle: 'Що ще може бути лише локально',
  backupContentTrustDescription:
    'Перевір, що ще може лишатися тільки на цьому пристрої.',
  backupContentTrustAudioTitle: 'Голосові нотатки',
  backupContentTrustAudioMeta: '{total} збережено • {synced} уже в хмарі',
  backupContentTrustAudioEmpty: 'Ще немає голосових нотаток',
  backupContentTrustAudioEmptyMeta:
    'Статус аудіо з’явиться тут, щойно якийсь сон матиме голосову нотатку.',
  backupContentTrustAudioAllBackedUp: 'Усе в backup',
  backupContentTrustAudioStillLocalSingle: '1 ще локально',
  backupContentTrustAudioStillLocalPlural: '{count} ще локально',
  backupContentTrustTranscriptTitle: 'Збережені транскрипти',
  backupContentTrustTranscriptMeta: '{total} збережено • {edited} відредаговано',
  backupContentTrustTranscriptEmpty: 'Ще немає збережених транскриптів',
  backupContentTrustTranscriptEmptyMeta:
    'Статус транскриптів з’явиться тут, щойно якийсь сон матиме збережений текст транскрипту.',
  backupContentTrustTranscriptCaughtUp: 'Актуально',
  backupContentTrustTranscriptStillLocalSingle: '1 новіший локально',
  backupContentTrustTranscriptStillLocalPlural: '{count} новіші локально',
  backupContentTrustReviewTitle: 'Збережені набори ревʼю',
  backupContentTrustReviewMeta: '{total} збережено • {months} місяців • {threads} ниток',
  backupContentTrustReviewEmpty: 'Ще немає збережених наборів',
  backupContentTrustReviewEmptyMeta:
    'Збережені місяці й нитки зʼявляться тут, щойно ти почнеш збирати ревʼю-набори.',
  backupContentTrustReviewCaughtUp: 'Актуально',
  backupContentTrustReviewStillLocal: 'Новіше локально',
  backupContentTrustLocalOnly: 'Лише локально',
  cloudExistingBackupTitle: 'Відкрити існуючий backup',
  cloudSaveBackupTitle: 'Зберегти цей backup',
  cloudIdentityTitle: 'Іменний акаунт',
  cloudIdentityDescriptionSignedOut:
    'Увійди з тією ж поштою і паролем на іншому пристрої, щоб відкрити той самий архів.',
  cloudIdentityDescriptionAnonymous:
    'Збережи цей backup під email-акаунтом, щоб інший пристрій міг відкрити його.',
  cloudIdentityEmailLabel: 'Email',
  cloudIdentityEmailHint: 'Використовується для того самого хмарного акаунта на різних пристроях.',
  cloudIdentityPasswordLabel: 'Пароль',
  cloudIdentityPasswordHint: 'Використай щонайменше 6 символів.',
  cloudCredentialsMissingTitle: 'Немає даних для входу',
  cloudCredentialsMissingDescription:
    'Введи email і пароль перед продовженням.',
  cloudEmailMissingTitle: 'Немає email',
  cloudEmailMissingDescription:
    'Спершу введи email для backup-акаунта.',
  cloudSyncToggleLabel: 'Автосинк',
  cloudSyncToggleHint:
    'Автосинк можна увімкнути лише після підключення backup.',
  cloudSyncDisabled: 'Вимкнено',
  cloudSyncEnabled: 'Увімкнено',
  cloudPendingLabel: 'У черзі',
  cloudSyncedLabel: 'Синхронізовано',
  cloudPulledLabel: 'Підтягнуто',
  cloudSkippedLabel: 'Пропущено',
  cloudConflictsLabel: 'Конфлікти',
  cloudLocalWinsLabel: 'Переміг локальний стан',
  cloudRemoteWinsLabel: 'Переміг remote стан',
  cloudErrorsLabel: 'Помилки',
  cloudSaveConfigButton: 'Зберегти конфіг',
  cloudClearConfigButton: 'Очистити конфіг',
  cloudConnectButton: 'Увімкнути backup',
  cloudConnectButtonBusy: 'Підключення...',
  cloudSignInExistingButton: 'Відкрити існуючий backup',
  cloudSignInExistingButtonBusy: 'Вхід...',
  cloudResetPasswordButton: 'Надіслати лист для скидання',
  cloudResetPasswordButtonBusy: 'Надсилаємо лист...',
  cloudUpgradeAccountButton: 'Зберегти backup-акаунт',
  cloudUpgradeAccountButtonBusy: 'Збереження акаунта...',
  cloudDisconnectButton: 'Вимкнути backup',
  cloudDisconnectButtonBusy: 'Відключення...',
  cloudSyncNowButton: 'Синхронізувати',
  cloudSyncNowButtonBusy: 'Синхронізація...',
  cloudLastSyncLabel: 'Останній синк',
  cloudLastSyncNever: 'Ще не було',
  cloudSyncStateIdle: 'Очікує',
  cloudSyncStateSyncing: 'Синхронізація',
  cloudSyncStateSuccess: 'Синхронізовано',
  cloudSyncStateError: 'Потрібна увага',
  cloudSyncManualErrorTitle: 'Помилка синхронізації backup',
  cloudConfigMissingTitle: 'Немає Supabase-конфігу',
  cloudConfigMissingDescription:
    'Додай валідний URL проєкту та anon key перед підключенням хмари.',
  cloudConfigErrorTitle: 'Помилка cloud-конфігу',
  cloudConnectErrorTitle: 'Не вдалося підключити backup',
  cloudAccountSignInErrorTitle: 'Не вдалося увійти в акаунт',
  cloudPasswordResetErrorTitle: 'Не вдалося надіслати лист для скидання',
  cloudPasswordResetSuccessTitle: 'Лист для скидання надіслано',
  cloudPasswordResetSuccessDescription:
    'Якщо такий backup-акаунт існує, перевір пошту й відкрий посилання для скидання пароля.',
  cloudAccountUpgradeErrorTitle: 'Не вдалося оновити акаунт',
  cloudDisconnectErrorTitle: 'Не вдалося вимкнути backup',
  cloudFootnote:
    'Твої сни лишаються локальними в першу чергу. Хмарний backup лише додає sync і restore між пристроями, коли ти сам цього хочеш.',
  exportTitle: 'Локальний експорт',
  exportDescription:
    'Створи JSON backup або читабельний PDF snapshot.',
  exportIncludesLabel: 'Що входить',
  exportIncludesValue:
    'Сни, чернетка, мова, нагадування, транскрипти й метадані аналізу',
  exportFormatLabel: 'Формат',
  exportFormatValue: 'JSON v7 + PDF-знімок',
  exportLatestPathLabel: 'Останній файл',
  exportFootnote:
    'JSON підходить для відновлення. PDF є читабельним знімком архіву і не замінює відновлення.',
  exportButton: 'Експортувати JSON',
  exportButtonBusy: 'Експорт...',
  exportPdfButton: 'Експортувати PDF',
  exportPdfButtonBusy: 'Створення PDF...',
  exportJsonGuidance: 'Використай JSON, якщо потім може знадобитися відновлення.',
  exportPdfGuidance: 'PDF потрібен лише для читання або поширення.',
  exportSuccessTitle: 'Експорт створено',
  exportSuccessDescription: 'Локальний JSON-файл записано в:',
  exportPdfSuccessTitle: 'PDF створено',
  exportPdfSuccessDescription: 'Локальний PDF-файл записано в:',
  exportErrorTitle: 'Помилка експорту',
  exportPdfErrorTitle: 'Помилка PDF-експорту',
  restoreTitle: 'Локальне відновлення',
  restoreDescription:
    'Обери backup, переглянь його і віднови.',
  restoreAvailableLabel: 'Доступні копії',
  restoreLoading: 'Завантаження копій...',
  restoreEmptyTitle: 'Локальних копій ще немає',
  restoreEmptyDescription:
    'Спершу створи експорт, і він з’явиться тут для перегляду та відновлення.',
  restorePreviewTitle: 'Попередній перегляд копії',
  restoreSelectedValue: 'Вибрано',
  restoreModeLabel: 'Режим',
  restoreModeReplace: 'Замінити',
  restoreModeMerge: 'Об’єднати',
  restoreModeReplaceHint:
    'Замінити локальні сни, чернетку, мову, нагадування й налаштування аналізу.',
  restoreModeMergeHint:
    'Додати сни з копії, лишити поточні налаштування і взяти чернетку з копії лише якщо локальна порожня.',
  restoreNoBackupAction: 'Спершу створи JSON backup',
  restoreSelectBackupAction: 'Спершу обери backup',
  restoreLoadingAction: 'Готуємо preview backup...',
  restoreReplaceWarning: 'Replace перезапише локальний архів на цьому пристрої.',
  restoreMergeGuidance:
    'Merge лишає поточні налаштування й додає сни з backup.',
  restoreFileLabel: 'Файл',
  restoreVersionLabel: 'Копія',
  restoreLocaleLabel: 'Мова',
  restoreDreamCountLabel: 'Снів',
  restoreCurrentCountLabel: 'Зараз',
  restoreIncomingCountLabel: 'З копії',
  restoreNewCountLabel: 'Нових',
  restoreResultCountLabel: 'Результат',
  restoreOverlapCountLabel: 'Збігів',
  restoreDraftLabel: 'Чернетка',
  restoreDraftPresent: 'Є',
  restoreDraftMissing: 'Немає',
  restoreSettingsLabel: 'Налаштування',
  restoreSettingsReplace: 'Налаштування з копії замінять локальні',
  restoreSettingsKeepCurrent: 'Поточні налаштування лишаться як є',
  restoreDraftActionLabel: 'Чернетка',
  restoreDraftActionReplace: 'Чернетка з копії замінить локальну',
  restoreDraftActionImportIfEmpty:
    'Чернетка з копії імпортується, лише якщо локальна порожня',
  restoreExportedAtLabel: 'Експортовано',
  restoreAppVersionLabel: 'Застосунок',
  restoreRestoreButton: 'Замінити цією копією',
  restoreMergeButton: 'Об’єднати з цієї копії',
  restoreRestoreButtonBusy: 'Відновлення...',
  restoreConfirmTitle: 'Замінити локальні дані?',
  restoreConfirmDescription:
    'Це замінить сни, чернетку, мову, налаштування нагадувань і налаштування аналізу вибраною копією.',
  restoreMergeConfirmTitle: 'Об’єднати копію з локальними даними?',
  restoreMergeConfirmDescription:
    'Це додасть сни з копії у поточний архів, лишить поточні налаштування і імпортує чернетку з копії лише якщо локальна порожня.',
  restoreSuccessTitle: 'Копію відновлено',
  restoreSuccessDescription: 'Локальні дані замінено з:',
  restoreSuccessModeLabel: 'Застосований режим',
  restoreSuccessCountLabel: 'Снів тепер на пристрої',
  restoreErrorTitle: 'Помилка відновлення',
  transcriptionTitle: 'Офлайн-транскрипція',
  transcriptionDescription:
    'Транскрибуй голосові нотатки локально після одного завантаження моделі.',
  transcriptionStatusLabel: 'Модель',
  transcriptionStatusInstalled: 'Завантажена',
  transcriptionStatusMissing: 'Ще не завантажена',
  transcriptionSizeLabel: 'Розмір',
  transcriptionPathLabel: 'Локальний файл',
  transcriptionDownloadButton: 'Завантажити офлайн-модель',
  transcriptionDownloadButtonBusy: 'Завантаження моделі...',
  transcriptionDownloadSuccessTitle: 'Модель готова',
  transcriptionDownloadSuccessDescription:
    'Офлайн-модель транскрипції тепер збережена локально на цьому пристрої.',
  transcriptionDownloadErrorTitle: 'Не вдалося завантажити модель',
  transcriptionDeleteButton: 'Видалити локальну модель',
  transcriptionDeleteButtonBusy: 'Видалення моделі...',
  transcriptionMissingHint: 'Завантаж модель один раз, щоб увімкнути офлайн-транскрипцію.',
  transcriptionDeleteSuccessTitle: 'Модель видалено',
  transcriptionDeleteSuccessDescription:
    'Офлайн-модель транскрипції видалено з локального сховища.',
  transcriptionDeleteErrorTitle: 'Не вдалося видалити модель',
  scaleTestTitle: 'Перевірка масштабу',
  scaleTestDescription:
    'Згенеруй тестові сни для stress test.',
  developerToolsTitle: 'Developer tools',
  developerToolsDescription:
    'Інструменти лише для debug: preview, seed data і stress test.',
  devSyncHistoryTitle: 'Останні sync спроби',
  devSyncHistoryDescription:
    'Історія лише для debug з останніми результатами cloud sync на цьому пристрої.',
  devSyncReasonManual: 'Вручну',
  devSyncReasonLaunch: 'При запуску',
  devSyncSnapshotTitle: 'Останній sync snapshot',
  devSyncSnapshotDescription:
    'Debug-only перегляд останнього збереженого результату sync на цьому пристрої.',
  devSyncSnapshotStatusTitle: 'Статус',
  devSyncSnapshotReasonTitle: 'Причина',
  devSyncSnapshotPendingTitle: 'Pending changes',
  devSyncSnapshotUploadsTitle: 'Uploaded',
  devSyncSnapshotPullsTitle: 'Pulled',
  devSyncSnapshotConflictsTitle: 'Conflicts',
  devSyncSnapshotErrorsTitle: 'Остання помилка',
  devSyncHistoryEmptyTitle: 'Ще не було sync спроб',
  devSyncHistoryEmptyDescription:
    'Запусти backup sync один раз, і тут зʼявиться debug history.',
  scaleTestSeededLabel: 'Тестових снів',
  scaleTestAdd250: 'Додати 250',
  scaleTestAdd1000: 'Додати 1000',
  scaleTestClear: 'Очистити тести',
  scaleTestBusy: 'Працюю...',
  scaleTestClearTitle: 'Очистити тестові сни?',
  scaleTestClearDescription:
    'Це видалить лише згенеровані тестові сни. Твої власні записи лишаться.',
  scaleTestSeededTitle: 'Тестові сни готові',
  scaleTestSeededDescription:
    'Архів заповнено згенерованими снами для перевірки масштабу.',
  scaleTestErrorTitle: 'Не вдалося підготувати тестові сни',
  analysisTitle: 'Аналіз сну',
  analysisDescription:
    'Генеруй локальну рефлексію зі збережених даних сну.',
  analysisProviderLabel: 'Провайдер',
  analysisProviderManual: 'Локальний',
  analysisProviderOpenAi: 'OpenAI (заплановано)',
  analysisNetworkLabel: 'Мережа',
  analysisNetworkAllowed: 'Дозволена',
  analysisNetworkBlocked: 'Заблокована',
  analysisLocalNetworkHint: 'Локальний аналіз не потребує доступу до мережі.',
};

export type SettingsCopy = typeof SETTINGS_COPY_EN;

export function getSettingsCopy(locale: AppLocale): SettingsCopy {
  return locale === 'uk' ? SETTINGS_COPY_UK : SETTINGS_COPY_EN;
}
