import { AppLocale } from '../../i18n/types';

const SETTINGS_COPY_EN = {
  title: 'Settings',
  subtitle:
    'Local-first controls for reminders, privacy, backups, and analysis.',
  sectionTitle: 'Workspace',
  sectionGeneral: 'General',
  sectionBackup: 'Backup',
  sectionTools: 'Tools',
  sectionGeneralHint: 'Language, reminder, and privacy basics.',
  sectionBackupHint:
    'Export snapshots and review restore before changing local data.',
  sectionToolsHint: 'Analysis, transcription, and developer tools.',
  toggleShow: 'Show',
  toggleHide: 'Hide',
  versionTitle: 'Current release',
  footerBuildLabel: 'Kaleidoskop',
  footerStorageMetaPrefix: 'Schema',
  footerExportMetaPrefix: 'Export',
  reminderTitle: 'Dream reminder',
  reminderDescription:
    'One daily nudge after waking so you capture dreams faster.',
  reminderStatusLabel: 'Status',
  reminderPermissionLabel: 'Notifications',
  reminderEnabled: 'Enabled',
  reminderDisabled: 'Disabled',
  reminderPermissionAllowed: 'Allowed',
  reminderPermissionBlocked: 'Blocked',
  reminderEnableButton: 'Enable reminder',
  reminderDisableButton: 'Disable reminder',
  reminderTimeLabel: 'Reminder time',
  reminderTimeHint: 'Tap to change.',
  reminderPreviewWakeAction: 'Preview wake flow',
  reminderPreviewWakeMeta:
    'Open the reminder entry screen without waiting for the next notification.',
  devPreviewMonthlyReport: 'Preview monthly report',
  actionCancel: 'Cancel',
  reminderPermissionDeniedTitle: 'Notifications disabled',
  reminderPermissionDeniedDescription:
    'Allow notifications in system settings to enable dream reminders.',
  reminderSaveErrorTitle: 'Reminder error',
  reminderStateHint:
    'Time is saved locally. If system notifications are blocked, the reminder stays off until permission is restored.',
  reminderNotificationTitle: 'Record your dream',
  reminderNotificationBody: 'Capture it while details are still fresh.',
  languageTitle: 'Language',
  languageDescription: 'Choose your app language.',
  languageEnglish: 'EN',
  languageUkrainian: 'UA',
  privacyTitle: 'Privacy and storage',
  privacyDescription:
    'Dream data stays on your device by default. Cloud stays optional and does not block first capture.',
  privacyStorageLabel: 'Dream data',
  privacyStorageValue: 'On this device',
  privacySyncLabel: 'Cloud sync',
  privacySyncValue: 'Optional after cloud connect',
  privacyAccountLabel: 'Account',
  privacyAccountValue: 'Optional Supabase session',
  privacyReminderLabel: 'Reminders',
  privacyReminderValue: 'Local notifications only',
  privacyTranscriptionLabel: 'Audio transcription',
  privacyTranscriptionValue: 'On-device after model download',
  privacyFootnote:
    'If you delete the app, local entries, downloaded transcription model, and drafts may be removed with it until export or sync exists.',
  cloudTitle: 'Cloud backup',
  cloudDescription:
    'Keep the same dream archive available across devices while offline capture stays primary.',
  cloudConfigLabel: 'Runtime config',
  cloudConfigReady: 'Ready',
  cloudConfigMissing: 'Missing',
  cloudConfigUrlLabel: 'Supabase URL',
  cloudConfigUrlHint: 'Project URL, usually *.supabase.co.',
  cloudConfigAnonKeyLabel: 'Anon key',
  cloudConfigAnonKeyHint: 'Public anon key used by the mobile client.',
  cloudSessionLabel: 'Backup',
  cloudSessionSignedOut: 'Off',
  cloudSessionSignedIn: 'On',
  cloudAccountLabel: 'Account',
  cloudAccountDisconnected: 'Not linked yet',
  cloudAccountAnonymous: 'Needs email account',
  cloudIdentityTitle: 'Named account',
  cloudIdentityDescriptionSignedOut:
    'Sign in with the same email and password on another device to open the same archive.',
  cloudIdentityDescriptionAnonymous:
    'Save this backup under an email account so another device can open it.',
  cloudIdentityEmailLabel: 'Email',
  cloudIdentityEmailHint: 'Used for the same cloud account across devices.',
  cloudIdentityPasswordLabel: 'Password',
  cloudIdentityPasswordHint: 'Use at least 6 characters.',
  cloudCredentialsMissingTitle: 'Missing credentials',
  cloudCredentialsMissingDescription:
    'Enter an email and password before continuing.',
  cloudSyncToggleLabel: 'Auto sync',
  cloudSyncToggleHint:
    'Auto sync can be enabled only after cloud backup is connected.',
  cloudSyncDisabled: 'Off',
  cloudSyncEnabled: 'On',
  cloudPendingLabel: 'Pending',
  cloudSyncedLabel: 'Synced',
  cloudPulledLabel: 'Pulled',
  cloudSkippedLabel: 'Skipped',
  cloudConflictsLabel: 'Conflicts',
  cloudLocalWinsLabel: 'Local wins',
  cloudRemoteWinsLabel: 'Remote wins',
  cloudErrorsLabel: 'Errors',
  cloudSaveConfigButton: 'Save config',
  cloudClearConfigButton: 'Clear config',
  cloudConnectButton: 'Turn on backup',
  cloudConnectButtonBusy: 'Connecting...',
  cloudSignInExistingButton: 'Open existing backup',
  cloudSignInExistingButtonBusy: 'Signing in...',
  cloudUpgradeAccountButton: 'Save backup account',
  cloudUpgradeAccountButtonBusy: 'Saving account...',
  cloudDisconnectButton: 'Turn off backup',
  cloudDisconnectButtonBusy: 'Disconnecting...',
  cloudSyncNowButton: 'Sync now',
  cloudSyncNowButtonBusy: 'Syncing...',
  cloudLastSyncLabel: 'Last sync',
  cloudLastSyncNever: 'Never',
  cloudSyncStateIdle: 'Idle',
  cloudSyncStateSyncing: 'Syncing',
  cloudSyncStateSuccess: 'Synced',
  cloudSyncStateError: 'Needs attention',
  cloudSyncManualErrorTitle: 'Backup sync failed',
  cloudConfigMissingTitle: 'Supabase config missing',
  cloudConfigMissingDescription:
    'Add a valid project URL and anon key before connecting cloud.',
  cloudConfigErrorTitle: 'Cloud config error',
  cloudConnectErrorTitle: 'Backup connect failed',
  cloudAccountSignInErrorTitle: 'Account sign-in failed',
  cloudAccountUpgradeErrorTitle: 'Account upgrade failed',
  cloudDisconnectErrorTitle: 'Backup disconnect failed',
  cloudFootnote:
    'Your dreams stay local first. Cloud backup only adds sync and restore across devices when you choose to connect it.',
  exportTitle: 'Local export',
  exportDescription:
    'Create a restore-safe JSON backup or a readable PDF snapshot of the archive.',
  exportIncludesLabel: 'Includes',
  exportIncludesValue:
    'Dreams, draft, locale, reminders, transcripts, and analysis metadata',
  exportFormatLabel: 'Format',
  exportFormatValue: 'JSON v5 + PDF snapshot',
  exportLatestPathLabel: 'Latest file',
  exportFootnote:
    'JSON works as a restore backup. PDF is a readable archive snapshot and does not replace restore.',
  exportButton: 'Export JSON',
  exportButtonBusy: 'Exporting...',
  exportPdfButton: 'Export PDF',
  exportPdfButtonBusy: 'Rendering PDF...',
  exportSuccessTitle: 'Export created',
  exportSuccessDescription: 'A local JSON snapshot was written to:',
  exportPdfSuccessTitle: 'PDF created',
  exportPdfSuccessDescription: 'A local PDF snapshot was written to:',
  exportErrorTitle: 'Export failed',
  exportPdfErrorTitle: 'PDF export failed',
  restoreTitle: 'Local restore',
  restoreDescription:
    'Review a saved backup before replacing local data on this device.',
  restoreAvailableLabel: 'Available backups',
  restoreLoading: 'Loading backups...',
  restoreEmptyTitle: 'No local backups yet',
  restoreEmptyDescription:
    'Create one export first, then it will appear here for preview and restore.',
  restorePreviewTitle: 'Backup preview',
  restoreSelectedValue: 'Selected',
  restoreModeLabel: 'Mode',
  restoreModeReplace: 'Replace',
  restoreModeMerge: 'Merge',
  restoreModeReplaceHint: 'Use the backup as the new local source of truth.',
  restoreModeMergeHint:
    'Add backup dreams and keep current settings on this device.',
  restoreFileLabel: 'File',
  restoreVersionLabel: 'Backup',
  restoreLocaleLabel: 'Locale',
  restoreDreamCountLabel: 'Dreams',
  restoreCurrentCountLabel: 'Now',
  restoreIncomingCountLabel: 'From backup',
  restoreNewCountLabel: 'New',
  restoreResultCountLabel: 'Result',
  restoreOverlapCountLabel: 'Overlap',
  restoreDraftLabel: 'Draft',
  restoreDraftPresent: 'Included',
  restoreDraftMissing: 'None',
  restoreSettingsLabel: 'Settings',
  restoreSettingsReplace: 'Backup settings replace local',
  restoreSettingsKeepCurrent: 'Current settings stay as they are',
  restoreDraftActionLabel: 'Draft',
  restoreDraftActionReplace: 'Backup draft replaces local draft',
  restoreDraftActionImportIfEmpty:
    'Backup draft imports only if local draft is empty',
  restoreExportedAtLabel: 'Exported',
  restoreAppVersionLabel: 'App',
  restoreRestoreButton: 'Replace with this backup',
  restoreMergeButton: 'Merge from this backup',
  restoreRestoreButtonBusy: 'Restoring...',
  restoreConfirmTitle: 'Replace local data?',
  restoreConfirmDescription:
    'This replaces dreams, draft, locale, reminder settings, and analysis settings with the selected backup.',
  restoreMergeConfirmTitle: 'Merge backup into local data?',
  restoreMergeConfirmDescription:
    'This adds backup dreams to the current archive, keeps current settings, and imports the backup draft only if your local draft is empty.',
  restoreSuccessTitle: 'Backup restored',
  restoreSuccessDescription: 'Local data was replaced from:',
  restoreSuccessModeLabel: 'Applied mode',
  restoreSuccessCountLabel: 'Dreams now on device',
  restoreErrorTitle: 'Restore failed',
  transcriptionTitle: 'Offline transcription',
  transcriptionDescription:
    'Voice notes can be transcribed on device after one model download.',
  transcriptionStatusLabel: 'Model',
  transcriptionStatusInstalled: 'Downloaded',
  transcriptionStatusMissing: 'Not downloaded yet',
  transcriptionSizeLabel: 'Size',
  transcriptionPathLabel: 'Local file',
  transcriptionDownloadButton: 'Download offline model',
  transcriptionDownloadButtonBusy: 'Downloading model...',
  transcriptionDownloadSuccessTitle: 'Model ready',
  transcriptionDownloadSuccessDescription:
    'The offline transcription model is now stored locally on this device.',
  transcriptionDownloadErrorTitle: 'Could not download model',
  transcriptionDeleteButton: 'Delete local model',
  transcriptionDeleteButtonBusy: 'Deleting model...',
  transcriptionDeleteSuccessTitle: 'Model removed',
  transcriptionDeleteSuccessDescription:
    'The offline transcription model was removed from local storage.',
  transcriptionDeleteErrorTitle: 'Could not remove model',
  scaleTestTitle: 'Scale test',
  scaleTestDescription:
    'Generate sample dreams so you can stress-test Home, Archive, and Memory.',
  scaleTestSeededLabel: 'Sample dreams',
  scaleTestAdd250: 'Add 250',
  scaleTestAdd1000: 'Add 1000',
  scaleTestClear: 'Clear samples',
  scaleTestBusy: 'Working...',
  scaleTestClearTitle: 'Clear sample dreams?',
  scaleTestClearDescription:
    'This removes only generated sample dreams. Your own entries stay untouched.',
  scaleTestSeededTitle: 'Sample dreams ready',
  scaleTestSeededDescription:
    'The archive was filled with generated dreams for scale testing.',
  scaleTestErrorTitle: 'Could not prepare sample dreams',
  analysisTitle: 'Dream analysis',
  analysisDescription:
    'Generate a local reflection from saved text, transcript, tags, and sleep context. Network analysis stays optional and planned.',
  analysisEnabledLabel: 'Analysis layer',
  analysisEnabled: 'Enabled',
  analysisDisabled: 'Disabled',
  analysisProviderLabel: 'Provider',
  analysisProviderManual: 'Local manual',
  analysisProviderOpenAi: 'OpenAI (planned)',
  analysisNetworkLabel: 'Network',
  analysisNetworkAllowed: 'Allowed',
  analysisNetworkBlocked: 'Blocked',
  analysisEnableButton: 'Enable analysis layer',
  analysisDisableButton: 'Disable analysis layer',
  analysisUseManualButton: 'Use local analysis',
  analysisUseOpenAiButton: 'Keep OpenAI visible',
  analysisNetworkAllowButton: 'Allow network analysis later',
  analysisNetworkBlockButton: 'Keep network blocked',
  architectureTitle: 'Foundation status',
  architectureDescription:
    'Local-first data, feature-based structure, extracted styles, offline transcription, and an AI-ready analysis boundary.',
  plannedTitle: 'Planned controls',
  plannedDescription:
    'Notifications, privacy, export, AI preferences, and Health integrations should live here.',
};

const SETTINGS_COPY_UK: typeof SETTINGS_COPY_EN = {
  ...SETTINGS_COPY_EN,
  title: 'Налаштування',
  subtitle:
    'Локальні керування нагадуваннями, приватністю, копіями й аналізом.',
  sectionTitle: 'Режим',
  sectionGeneral: 'Основне',
  sectionBackup: 'Копії',
  sectionTools: 'Інструменти',
  sectionGeneralHint: 'Мова, нагадування і базова приватність.',
  sectionBackupHint:
    'Експорт копій і перегляд відновлення перед зміною локальних даних.',
  sectionToolsHint: 'Аналіз, транскрипція й дев-інструменти.',
  toggleShow: 'Показати',
  toggleHide: 'Сховати',
  versionTitle: 'Поточний реліз',
  footerBuildLabel: 'Kaleidoskop',
  footerStorageMetaPrefix: 'Схема',
  footerExportMetaPrefix: 'Експорт',
  reminderTitle: 'Нагадування про сон',
  reminderDescription:
    'Одне щоденне нагадування після пробудження, щоб швидше фіксувати сни.',
  reminderStatusLabel: 'Статус',
  reminderPermissionLabel: 'Сповіщення',
  reminderEnabled: 'Увімкнено',
  reminderDisabled: 'Вимкнено',
  reminderPermissionAllowed: 'Дозволені',
  reminderPermissionBlocked: 'Заблоковані',
  reminderEnableButton: 'Увімкнути нагадування',
  reminderDisableButton: 'Вимкнути нагадування',
  reminderTimeLabel: 'Час нагадування',
  reminderTimeHint: 'Натисни, щоб змінити.',
  reminderPreviewWakeAction: 'Переглянути ранковий режим',
  reminderPreviewWakeMeta:
    'Відкрий екран після нагадування без очікування наступного сповіщення.',
  devPreviewMonthlyReport: 'Переглянути місячний звіт',
  actionCancel: 'Скасувати',
  reminderPermissionDeniedTitle: 'Сповіщення вимкнені',
  reminderPermissionDeniedDescription:
    'Дозволь сповіщення в системних налаштуваннях, щоб увімкнути нагадування.',
  reminderSaveErrorTitle: 'Помилка нагадування',
  reminderStateHint:
    'Час зберігається локально. Якщо системні сповіщення заблоковані, нагадування лишається вимкненим, доки дозвіл не повернеться.',
  reminderNotificationTitle: 'Запиши свій сон',
  reminderNotificationBody: 'Зафіксуй його, поки деталі ще свіжі.',
  languageTitle: 'Мова',
  languageDescription: 'Обери мову застосунку.',
  languageEnglish: 'EN',
  languageUkrainian: 'UA',
  architectureTitle: 'Стан фундаменту',
  privacyTitle: 'Приватність і зберігання',
  privacyDescription:
    'Дані про сни лишаються на пристрої за замовчуванням. Хмара лишається опційною і не блокує перший запис.',
  privacyStorageLabel: 'Дані про сни',
  privacyStorageValue: 'Лише на цьому пристрої',
  privacySyncLabel: 'Хмарна синхронізація',
  privacySyncValue: 'Опційно після підключення хмари',
  privacyAccountLabel: 'Акаунт',
  privacyAccountValue: 'Опційна Supabase-сесія',
  privacyReminderLabel: 'Нагадування',
  privacyReminderValue: 'Локальні сповіщення',
  privacyTranscriptionLabel: 'Транскрипція аудіо',
  privacyTranscriptionValue: 'Локально після завантаження моделі',
  privacyFootnote:
    'Якщо видалити застосунок, локальні записи, завантажена модель транскрипції і чернетки можуть зникнути, доки не зʼявиться експорт або синхронізація.',
  cloudTitle: 'Хмарний backup',
  cloudDescription:
    'Тримай один і той самий архів снів на кількох пристроях, але офлайн-запис лишається основним сценарієм.',
  cloudConfigLabel: 'Runtime-конфіг',
  cloudConfigReady: 'Готово',
  cloudConfigMissing: 'Відсутній',
  cloudConfigUrlLabel: 'Supabase URL',
  cloudConfigUrlHint: 'URL проєкту, зазвичай *.supabase.co.',
  cloudConfigAnonKeyLabel: 'Anon key',
  cloudConfigAnonKeyHint: 'Публічний anon key для mobile-клієнта.',
  cloudSessionLabel: 'Backup',
  cloudSessionSignedOut: 'Вимкнено',
  cloudSessionSignedIn: 'Увімкнено',
  cloudAccountLabel: 'Акаунт',
  cloudAccountDisconnected: 'Ще не привʼязано',
  cloudAccountAnonymous: 'Потрібен email-акаунт',
  cloudIdentityTitle: 'Іменний акаунт',
  cloudIdentityDescriptionSignedOut:
    'Увійди з тією ж поштою і паролем на іншому пристрої, щоб відкрити той самий архів.',
  cloudIdentityDescriptionAnonymous:
    'Збережи цей backup під email-акаунтом, щоб інший пристрій міг відкрити його.',
  cloudIdentityEmailLabel: 'Email',
  cloudIdentityEmailHint: 'Використовується для того самого хмарного акаунта на різних пристроях.',
  cloudIdentityPasswordLabel: 'Пароль',
  cloudIdentityPasswordHint: 'Використай щонайменше 6 символів.',
  cloudCredentialsMissingTitle: 'Немає даних для входу',
  cloudCredentialsMissingDescription:
    'Введи email і пароль перед продовженням.',
  cloudSyncToggleLabel: 'Автосинк',
  cloudSyncToggleHint:
    'Автосинк можна увімкнути лише після підключення backup.',
  cloudSyncDisabled: 'Вимкнено',
  cloudSyncEnabled: 'Увімкнено',
  cloudPendingLabel: 'У черзі',
  cloudSyncedLabel: 'Синхронізовано',
  cloudPulledLabel: 'Підтягнуто',
  cloudSkippedLabel: 'Пропущено',
  cloudConflictsLabel: 'Конфлікти',
  cloudLocalWinsLabel: 'Переміг локальний стан',
  cloudRemoteWinsLabel: 'Переміг remote стан',
  cloudErrorsLabel: 'Помилки',
  cloudSaveConfigButton: 'Зберегти конфіг',
  cloudClearConfigButton: 'Очистити конфіг',
  cloudConnectButton: 'Увімкнути backup',
  cloudConnectButtonBusy: 'Підключення...',
  cloudSignInExistingButton: 'Відкрити існуючий backup',
  cloudSignInExistingButtonBusy: 'Вхід...',
  cloudUpgradeAccountButton: 'Зберегти backup-акаунт',
  cloudUpgradeAccountButtonBusy: 'Збереження акаунта...',
  cloudDisconnectButton: 'Вимкнути backup',
  cloudDisconnectButtonBusy: 'Відключення...',
  cloudSyncNowButton: 'Синхронізувати',
  cloudSyncNowButtonBusy: 'Синхронізація...',
  cloudLastSyncLabel: 'Останній синк',
  cloudLastSyncNever: 'Ще не було',
  cloudSyncStateIdle: 'Очікує',
  cloudSyncStateSyncing: 'Синхронізація',
  cloudSyncStateSuccess: 'Синхронізовано',
  cloudSyncStateError: 'Потрібна увага',
  cloudSyncManualErrorTitle: 'Помилка синхронізації backup',
  cloudConfigMissingTitle: 'Немає Supabase-конфігу',
  cloudConfigMissingDescription:
    'Додай валідний URL проєкту та anon key перед підключенням хмари.',
  cloudConfigErrorTitle: 'Помилка cloud-конфігу',
  cloudConnectErrorTitle: 'Не вдалося підключити backup',
  cloudAccountSignInErrorTitle: 'Не вдалося увійти в акаунт',
  cloudAccountUpgradeErrorTitle: 'Не вдалося оновити акаунт',
  cloudDisconnectErrorTitle: 'Не вдалося вимкнути backup',
  cloudFootnote:
    'Твої сни лишаються локальними в першу чергу. Хмарний backup лише додає sync і restore між пристроями, коли ти сам цього хочеш.',
  exportTitle: 'Локальний експорт',
  exportDescription:
    'Створи JSON для відновлення або читабельний PDF-знімок архіву.',
  exportIncludesLabel: 'Що входить',
  exportIncludesValue:
    'Сни, чернетка, мова, нагадування, транскрипти й метадані аналізу',
  exportFormatLabel: 'Формат',
  exportFormatValue: 'JSON v5 + PDF-знімок',
  exportLatestPathLabel: 'Останній файл',
  exportFootnote:
    'JSON підходить для відновлення. PDF є читабельним знімком архіву і не замінює відновлення.',
  exportButton: 'Експортувати JSON',
  exportButtonBusy: 'Експорт...',
  exportPdfButton: 'Експортувати PDF',
  exportPdfButtonBusy: 'Створення PDF...',
  exportSuccessTitle: 'Експорт створено',
  exportSuccessDescription: 'Локальний JSON-файл записано в:',
  exportPdfSuccessTitle: 'PDF створено',
  exportPdfSuccessDescription: 'Локальний PDF-файл записано в:',
  exportErrorTitle: 'Помилка експорту',
  exportPdfErrorTitle: 'Помилка PDF-експорту',
  restoreTitle: 'Локальне відновлення',
  restoreDescription:
    'Переглянь збережену копію перед тим, як замінити локальні дані на цьому пристрої.',
  restoreAvailableLabel: 'Доступні копії',
  restoreLoading: 'Завантаження копій...',
  restoreEmptyTitle: 'Локальних копій ще немає',
  restoreEmptyDescription:
    'Спершу створи експорт, і він з’явиться тут для перегляду та відновлення.',
  restorePreviewTitle: 'Попередній перегляд копії',
  restoreSelectedValue: 'Вибрано',
  restoreModeLabel: 'Режим',
  restoreModeReplace: 'Замінити',
  restoreModeMerge: 'Об’єднати',
  restoreModeReplaceHint: 'Використати копію як нове локальне джерело даних.',
  restoreModeMergeHint:
    'Додати сни з копії і лишити поточні налаштування цього пристрою.',
  restoreFileLabel: 'Файл',
  restoreVersionLabel: 'Копія',
  restoreLocaleLabel: 'Мова',
  restoreDreamCountLabel: 'Снів',
  restoreCurrentCountLabel: 'Зараз',
  restoreIncomingCountLabel: 'З копії',
  restoreNewCountLabel: 'Нових',
  restoreResultCountLabel: 'Результат',
  restoreOverlapCountLabel: 'Збігів',
  restoreDraftLabel: 'Чернетка',
  restoreDraftPresent: 'Є',
  restoreDraftMissing: 'Немає',
  restoreSettingsLabel: 'Налаштування',
  restoreSettingsReplace: 'Налаштування з копії замінять локальні',
  restoreSettingsKeepCurrent: 'Поточні налаштування лишаться як є',
  restoreDraftActionLabel: 'Чернетка',
  restoreDraftActionReplace: 'Чернетка з копії замінить локальну',
  restoreDraftActionImportIfEmpty:
    'Чернетка з копії імпортується, лише якщо локальна порожня',
  restoreExportedAtLabel: 'Експортовано',
  restoreAppVersionLabel: 'Застосунок',
  restoreRestoreButton: 'Замінити цією копією',
  restoreMergeButton: 'Об’єднати з цієї копії',
  restoreRestoreButtonBusy: 'Відновлення...',
  restoreConfirmTitle: 'Замінити локальні дані?',
  restoreConfirmDescription:
    'Це замінить сни, чернетку, мову, налаштування нагадувань і налаштування аналізу вибраною копією.',
  restoreMergeConfirmTitle: 'Об’єднати копію з локальними даними?',
  restoreMergeConfirmDescription:
    'Це додасть сни з копії у поточний архів, лишить поточні налаштування і імпортує чернетку з копії лише якщо локальна порожня.',
  restoreSuccessTitle: 'Копію відновлено',
  restoreSuccessDescription: 'Локальні дані замінено з:',
  restoreSuccessModeLabel: 'Застосований режим',
  restoreSuccessCountLabel: 'Снів тепер на пристрої',
  restoreErrorTitle: 'Помилка відновлення',
  transcriptionTitle: 'Офлайн-транскрипція',
  transcriptionDescription:
    'Голосові нотатки можна транскрибувати на пристрої після одного завантаження моделі.',
  transcriptionStatusLabel: 'Модель',
  transcriptionStatusInstalled: 'Завантажена',
  transcriptionStatusMissing: 'Ще не завантажена',
  transcriptionSizeLabel: 'Розмір',
  transcriptionPathLabel: 'Локальний файл',
  transcriptionDownloadButton: 'Завантажити офлайн-модель',
  transcriptionDownloadButtonBusy: 'Завантаження моделі...',
  transcriptionDownloadSuccessTitle: 'Модель готова',
  transcriptionDownloadSuccessDescription:
    'Офлайн-модель транскрипції тепер збережена локально на цьому пристрої.',
  transcriptionDownloadErrorTitle: 'Не вдалося завантажити модель',
  transcriptionDeleteButton: 'Видалити локальну модель',
  transcriptionDeleteButtonBusy: 'Видалення моделі...',
  transcriptionDeleteSuccessTitle: 'Модель видалено',
  transcriptionDeleteSuccessDescription:
    'Офлайн-модель транскрипції видалено з локального сховища.',
  transcriptionDeleteErrorTitle: 'Не вдалося видалити модель',
  scaleTestTitle: 'Перевірка масштабу',
  scaleTestDescription:
    "Згенеруй тестові сни, щоб прогнати головний екран, Архів і Пам'ять на великому обсязі.",
  scaleTestSeededLabel: 'Тестових снів',
  scaleTestAdd250: 'Додати 250',
  scaleTestAdd1000: 'Додати 1000',
  scaleTestClear: 'Очистити тести',
  scaleTestBusy: 'Працюю...',
  scaleTestClearTitle: 'Очистити тестові сни?',
  scaleTestClearDescription:
    'Це видалить лише згенеровані тестові сни. Твої власні записи лишаться.',
  scaleTestSeededTitle: 'Тестові сни готові',
  scaleTestSeededDescription:
    'Архів заповнено згенерованими снами для перевірки масштабу.',
  scaleTestErrorTitle: 'Не вдалося підготувати тестові сни',
  analysisTitle: 'Аналіз сну',
  analysisDescription:
    'Генеруй локальну рефлексію зі збереженого тексту, транскрипту, тегів і контексту перед сном. Мережевий аналіз лишається опційним і запланованим.',
  analysisEnabledLabel: 'Шар аналізу',
  analysisEnabled: 'Увімкнений',
  analysisDisabled: 'Вимкнений',
  analysisProviderLabel: 'Провайдер',
  analysisProviderManual: 'Локальний',
  analysisProviderOpenAi: 'OpenAI (заплановано)',
  analysisNetworkLabel: 'Мережа',
  analysisNetworkAllowed: 'Дозволена',
  analysisNetworkBlocked: 'Заблокована',
  analysisEnableButton: 'Увімкнути шар аналізу',
  analysisDisableButton: 'Вимкнути шар аналізу',
  analysisUseManualButton: 'Увімкнути локальний аналіз',
  analysisUseOpenAiButton: 'Лишити OpenAI видимим',
  analysisNetworkAllowButton: 'Дозволити мережевий аналіз пізніше',
  analysisNetworkBlockButton: 'Тримати мережу заблокованою',
  architectureDescription:
    'Локальні дані, структура за фічами, винесені стилі, офлайн-транскрипція і готова межа для AI-аналізу.',
  plannedTitle: 'Заплановані розділи',
  plannedDescription:
    'Сповіщення, приватність, експорт, AI-параметри та інтеграції зі Здоров’ям.',
};

export type SettingsCopy = typeof SETTINGS_COPY_EN;

export function getSettingsCopy(locale: AppLocale): SettingsCopy {
  return locale === 'uk' ? SETTINGS_COPY_UK : SETTINGS_COPY_EN;
}
