import { AppLocale } from '../../i18n/types';

const STATS_COPY_EN = {
  title: 'Memory',
  subtitle:
    'Signals, threads, and monthly shapes from your local dream archive.',
  monthLabel: 'Current local snapshot',
  rangeLabel: 'Range',
  rangeAll: 'All time',
  range30Days: '30 days',
  range7Days: '7 days',
  memoryModeLabel: 'Section',
  memoryModeOverview: 'Overview',
  memoryModeThreads: 'Recurring',
  memoryModeMonthly: 'Monthly',
  compareLabel: 'View',
  compareSnapshot: 'Snapshot',
  compareMode: 'Compare',
  compareUnavailable: 'Compare works with 7 or 30 day ranges.',
  compareCurrentPeriod: 'Current period',
  comparePreviousPeriod: 'Previous period',
  compareDeltaLabel: 'vs previous period',
  monthlyReportOpenButton: 'Monthly report',
  monthlyReportBackButton: 'Back',
  monthlyReportEyebrow: 'Monthly reflection',
  monthlyReportTitle: 'Monthly report',
  monthlyReportSubtitle:
    'A calmer revisit of the month, built from your local archive without turning into a dashboard.',
  monthlyReportEmptyTitle: 'No monthly report yet',
  monthlyReportEmptyDescription:
    'Save a few dreams in one month and the first local report will start taking shape.',
  monthlyReportLoadingTitle: 'Building monthly report',
  monthlyReportLoadingDescription:
    'Refreshing the local archive for this month.',
  monthlyReportMonthStripLabel: 'Months',
  monthlyReportSaveAction: 'Save for later',
  monthlyReportSavedAction: 'Saved',
  monthlyReportShareAction: 'Share',
  monthlyReportShareTitle: 'Dream monthly report',
  monthlyReportCoverTitle: 'This month felt like',
  monthlyReportCoverEmpty: 'Still settling into a recognizable shape.',
  monthlyReportHighlightsTitle: 'Month in moments',
  monthlyReportHighlightsDescription:
    'The strongest numbers worth keeping from this month.',
  monthlyReportSignalsTitle: 'What kept returning',
  monthlyReportSignalsDescription:
    'Recurring pieces that gave this month its texture.',
  monthlyReportGentleTitle: 'What deepened the archive',
  monthlyReportGentleDescription:
    'Quiet structure that made this month easier to revisit later.',
  monthlyReportEntriesLabel: 'Entries',
  monthlyReportWordsLabel: 'Words',
  monthlyReportVoiceLabel: 'Voice',
  monthlyReportTranscriptLabel: 'Transcripts',
  monthlyReportTagsLabel: 'Tagged',
  monthlyReportContextLabel: 'Context',
  monthlyReportWakeLabel: 'After waking',
  monthlyReportPreSleepLabel: 'Before sleep',
  monthlyReportThemeLabel: 'Theme',
  monthlyReportSymbolLabel: 'Symbol',
  monthlyReportWordLabel: 'Phrase',
  monthlyReportRevisitTitle: 'Worth reopening',
  monthlyReportRevisitDescription:
    'One dream from this month is landing in a return window right now.',
  monthlyReportOpenThreadAction: 'Open thread',
  monthlyReportSavedThreadsTitle: 'Saved threads',
  monthlyReportSavedThreadsDescription:
    'Threads you pinned earlier that still touch this month.',
  monthlyReportNoSignal: 'Still forming',
  overviewActivityTitle: 'Recent activity',
  overviewActivityDescription: 'How often dreams were saved lately.',
  nightmareFrequencyTitle: 'Nightmare frequency',
  nightmareFrequencyDescription:
    'A gentle read of how often nightmare-pattern dreams appear in this slice.',
  nightmareFrequencyCountLabel: 'Nightmare-pattern entries',
  nightmareFrequencyCountHint:
    'Includes tagged nightmares and entries with stronger distress after waking.',
  nightmareFrequencyCountEmptyHint:
    'No nightmare-pattern entries in this range.',
  nightmareFrequencyShareLabel: 'Share of this range',
  nightmareFrequencyShareHintPrefix: 'About one in ',
  nightmareFrequencyShareHintSuffix: ' dreams in this range.',
  nightmareFrequencyShareEmptyHint: 'Nothing recurring here right now.',
  nightmareFrequencyLatestLabel: 'Most recent',
  nightmareFrequencyLatestHint: 'Latest nightmare-pattern entry in this range.',
  nightmareFrequencyLatestEmptyValue: 'None',
  nightmareFrequencyLatestEmptyHint:
    'No nightmare-pattern entry landed in this range.',
  lucidFrequencyTitle: 'Lucid frequency',
  lucidFrequencyDescription:
    'How often lucidity appears in this slice, plus the recent trail back through it.',
  lucidFrequencyCountLabel: 'Lucid entries',
  lucidFrequencyCountHint:
    'Includes brief awareness, lucid dreams, and lucid entries with control.',
  lucidFrequencyCountEmptyHint: 'No lucid entries in this range.',
  lucidFrequencyShareLabel: 'Share of this range',
  lucidFrequencyShareHintPrefix: 'About one in ',
  lucidFrequencyShareHintSuffix: ' dreams in this range.',
  lucidFrequencyShareEmptyHint: 'No lucid pattern in this range yet.',
  lucidFrequencyLatestLabel: 'Most recent',
  lucidFrequencyLatestHint: 'Latest lucid entry in this range.',
  lucidFrequencyLatestEmptyValue: 'None',
  lucidFrequencyLatestEmptyHint:
    'No lucid entry landed in this range.',
  lucidHistoryTitle: 'Recent lucid history',
  lucidHistoryDescription:
    'Open a lucid entry and revisit what kind of awareness showed up.',
  lucidHistoryEmpty: 'No lucid entries in this slice yet.',
  lucidAwareLabel: 'Aware dreams',
  lucidControlledLabel: 'Controlled dreams',
  lucidTopTechniqueLabel: 'Top technique',
  lucidDreamSignsLabel: 'Top dream sign',
  lucidTechniqueEmptyValue: 'None yet',
  lucidDreamSignsEmptyValue: 'Still forming',
  nightmareRecurringLabel: 'Recurring',
  nightmareHighDistressLabel: 'High distress',
  nightmareRescriptedLabel: 'Rewritten',
  nightmareDerivedLabel: 'Derived signals',
  nightmareDerivedHint: 'Supportive fallback from distress-heavy wake patterns.',
  weeklyPatternsTitle: 'Weekly patterns',
  weeklyPatternsDescription:
    'A calm read of what stood out in the last seven days.',
  overviewTopSignalLabel: 'Top signal',
  overviewTopSignalEmpty: 'Still forming',
  overviewNextStepLabel: 'Next step',
  overviewNextStepEmpty: 'Nothing urgent right now.',
  weeklyPatternRhythmLabel: 'Rhythm',
  weeklyPatternSignalLabel: 'Recent signal',
  weeklyPatternToneLabel: 'Tone',
  weeklyPatternContextLabel: 'Context',
  weeklyPatternCaptureLabel: 'Capture',
  weeklyPatternQuietWeekTitle: 'Quiet week',
  weeklyPatternQuietWeekHint: 'No dreams landed in the last seven days.',
  weeklyPatternStillFormingTitle: 'Still forming',
  weeklyPatternStillFormingHint:
    'One more detailed entry will make the week easier to read.',
  weeklyPatternContextTitle: 'Context showed up',
  weeklyPatternVoiceTitle: 'Voice leaning',
  weeklyPatternThisWeekSuffix: 'this week',
  weeklyPatternVsPreviousLabel: 'vs previous 7 days',
  weeklyPatternVsPreviousFlat: 'Same as previous 7 days',
  fingerprintTitle: 'Dream fingerprint',
  fingerprintDescription:
    'A quick portrait of the signals that keep returning in this slice.',
  fingerprintLeadLabel: 'Main notes',
  fingerprintEmpty: 'Save a few richer dreams to let the fingerprint settle.',
  fingerprintThemeLabel: 'Theme',
  fingerprintSymbolLabel: 'Symbol',
  fingerprintWakeLabel: 'After waking',
  fingerprintPreSleepLabel: 'Before sleep',
  detailsTitle: 'More details',
  detailsDescription: 'Open the deeper numbers only when needed.',
  detailsShow: 'Show details',
  detailsHide: 'Hide details',
  snapshotTitle: 'Archive snapshot',
  snapshotDescription: 'A compact read of this archive slice.',
  spotlightTitle: 'Spotlight',
  spotlightDescription: 'The fastest read on what stands out in this slice.',
  memoryNudgeLabel: 'Reopen now',
  memoryNudgeThemeReasonPrefix: 'Theme still pulling focus: ',
  memoryNudgeThemeReasonSuffix:
    '. Open one dream and see what still feels true.',
  memoryNudgeWordReasonPrefix: 'This word keeps returning: ',
  memoryNudgeWordReasonSuffix:
    '. Reopen one dream and check what changed around it.',
  memoryNudgeSymbolReasonPrefix: 'This symbol keeps resurfacing: ',
  memoryNudgeSymbolReasonSuffix:
    '. Open one dream and see what detail still holds.',
  memoryNudgeTimeReasonPrefix: 'This dream is resurfacing from ',
  memoryNudgeTimeReasonSuffix:
    '. Reopen it and see what detail still holds now.',
  memoryNudgeTranscriptReason:
    'One voice note is still waiting to become usable text while the memory is fresh.',
  memoryNudgeThemeBadge: 'Theme',
  memoryNudgeWordBadge: 'Word',
  memoryNudgeSymbolBadge: 'Symbol',
  memoryNudgeTimeBadge: 'Time',
  memoryNudgeTranscriptBadge: 'Transcript',
  memoryNudgeTimeWeek: 'about a week ago',
  memoryNudgeTimeMonth: 'about a month ago',
  memoryNudgeTimeQuarter: 'about three months ago',
  memoryNudgeTimeHalfYear: 'about six months ago',
  memoryNudgeTimeYear: 'about a year ago',
  memoryNudgeActionReflection: 'Open dream',
  memoryNudgeActionTime: 'Reopen memory',
  memoryNudgeActionTranscript: 'Work on transcript',
  takeawaysTitle: 'Quick takeaways',
  takeawaysDescription:
    'Short reads you can scan without digging through the full archive.',
  coverageTitle: 'Ready to revisit',
  coverageDescription: 'What is already easy to search or revisit later.',
  coverageTranscriptsLabel: 'Searchable text',
  coverageTagsLabel: 'Tags added',
  coverageContextLabel: 'Sleep context added',
  coverageTranscriptsHint: 'dreams already have transcript or written notes',
  coverageTagsHint: 'dreams already have tags attached',
  coverageContextHint: 'dreams already have pre-sleep context',
  attentionTitle: 'Worth adding',
  attentionDescription: 'Small additions that would make this slice richer.',
  attentionAudioLabel: 'Transcribe audio',
  attentionMoodLabel: 'Add mood',
  attentionContextLabel: 'Add context',
  attentionAudioHint: 'voice dreams are still raw',
  attentionMoodHint: 'dreams are missing wake-up mood',
  attentionContextHint: 'dreams are missing pre-sleep context',
  attentionAllSetHint: 'Nothing pressing here right now.',
  workQueueTitle: 'Continue locally',
  workQueueDescription: 'A few concrete follow-ups are ready in this slice.',
  reviewShelfTitle: 'Review shelf',
  reviewShelfDescription:
    'One place to reopen important dreams, saved months, saved threads, and the next local follow-ups.',
  reviewWorkspaceTitle: 'Review workspace',
  reviewWorkspaceSubtitle:
    'Return to the next local follow-up, important dream, saved month, or saved thread from one calmer place.',
  reviewWorkspaceOpenAction: 'Open review',
  reviewWorkspaceContinueTitle: 'Continue locally',
  reviewWorkspaceImportantTitle: 'Important dreams',
  reviewWorkspaceImportantDescription:
    'Starred dreams stay close so they can anchor the next reflection pass.',
  reviewWorkspaceSavedSetsTitle: 'Saved sets',
  reviewWorkspaceSavedSetsDescription:
    'Saved months and threads live together here as one calmer review layer.',
  reviewWorkspaceSavedMonthsTitle: 'Saved months',
  reviewWorkspaceSavedThreadsTitle: 'Saved threads',
  reviewWorkspaceSummaryContinueLabel: 'Local follow-ups',
  reviewWorkspaceSummaryImportantLabel: 'Important dreams',
  reviewWorkspaceSummarySavedSetsLabel: 'Saved sets',
  reviewWorkspaceEmptyTitle: 'Nothing saved for review yet',
  reviewWorkspaceEmptyDescription:
    'Important dreams, saved sets, and local follow-ups will appear here as the archive grows.',
  reviewWorkspaceDreamFallbackTitle: 'Untitled dream',
  reviewShelfImportantDreamEyebrow: 'Important dream',
  reviewShelfContinueEyebrow: 'Continue locally',
  reviewShelfSavedMonthEyebrow: 'Saved month',
  reviewShelfSavedThreadEyebrow: 'Saved thread',
  workQueueTranscriptGenerateReason:
    'This voice note is still waiting to become searchable text.',
  workQueueTranscriptRetryReason:
    'The last transcription attempt did not finish.',
  workQueueTranscriptEditReason:
    'Generated transcript is ready for a quick cleanup pass.',
  workQueueTranscriptActionGenerate: 'Transcribe audio',
  workQueueTranscriptActionRetry: 'Retry transcription',
  workQueueTranscriptActionEdit: 'Edit transcript',
  workQueueAnalysisReason:
    'This dream has enough material for a short local reflection.',
  workQueueAnalysisRetryReason:
    'Local analysis failed last time. Reopen and try again.',
  workQueueAnalysisBadge: 'Analysis',
  workQueueAnalysisActionGenerate: 'Generate analysis',
  workQueueAnalysisActionRetry: 'Regenerate analysis',
  voiceArchiveTitle: 'Voice archive',
  voiceArchiveDescription:
    'How much of the archive is still raw audio vs usable transcript.',
  sleepSignalsTitle: 'Sleep and mood',
  sleepSignalsDescription:
    'Mood, pre-sleep context, and repeated emotions from the same selected period.',
  patternsTitle: 'Recurring signals',
  patternsDescription:
    'Symbols, themes, and repeated phrases ranked by how often they return and where they keep showing up.',
  patternsTrackedLabel: 'tracked',
  memoryThreadTitle: 'Current thread',
  memoryThreadDescription:
    'Stay on this screen and scan the dreams connected to the selected recurring signal.',
  memoryThreadOpenAction: 'Open full thread',
  memoryThreadClearAction: 'Close thread',
  savedThreadsTitle: 'Saved threads',
  savedThreadsDescription:
    'Pinned threads stay here so you can reopen them without hunting through signals again.',
  threadSaveAction: 'Save thread',
  threadSavedAction: 'Saved',
  patternsTopLabel: 'Top signal',
  patternsMoreLabel: 'Also showing up',
  recurringWordsDescription: 'Across titles, notes, and transcripts.',
  recurringThemesDescription: 'From tags and transcript language.',
  recurringSymbolsDescription: 'From transcript language only.',
  preSleepEmotionsDescription: 'The feelings you log before sleep most often.',
  progressOpenButton: 'Open progress',
  progressBackButton: 'Back',
  progressScreenTitle: 'Progress',
  progressScreenSubtitle:
    'See your weekly rhythm, unlocked milestones, and the next recording goal.',
  progressLoadingTitle: 'Loading progress',
  progressLoadingDescription: 'Refreshing local milestones and weekly rhythm.',
  progressFocusTitle: 'Next unlock',
  progressFocusDoneTitle: 'All core milestones unlocked',
  progressFocusDoneDescription:
    'The recording habit is established. New entries now mainly deepen the archive.',
  milestonesToggleShow: 'Show milestones',
  milestonesToggleHide: 'Hide milestones',
  currentStreak: 'Current streak',
  lastSevenDays: 'Last 7 days',
  monthChange: 'Local-first',
  emptyTitle: 'No memory yet',
  emptyDescription:
    'Save a few dreams first. Memory will start connecting recurring signals from your local archive automatically.',
  readinessTitle: 'Insight readiness',
  readinessDescription:
    'The more mood, tags, and pre-sleep context you add, the more useful these patterns become.',
  entriesWithMood: 'Entries with mood',
  entriesWithTags: 'Entries with tags',
  readinessHint:
    'Small sample sizes can swing fast. Treat early patterns as directional, not final.',
  milestonesTitle: 'All milestones',
  milestonesDescription:
    'A simple view of what is already unlocked and what is still building up.',
  milestonesUnlockedLabel: 'Unlocked',
  milestonesCompleteTitle: 'Milestones complete',
  milestonesCompleteDescription:
    'All core recording milestones are unlocked. The archive now has enough volume for richer reflection.',
  milestoneHighlightLabel: 'Highlight',
  milestoneUnlocked: 'Unlocked',
  milestoneInProgress: 'In progress',
  milestoneProgressLabel: 'Done / goal',
  milestoneFirstDreamTitle: 'First dream saved',
  milestoneFirstDreamDescription:
    'Capture the first dream to start building a usable archive.',
  milestoneThreeDayStreakTitle: 'Three days in a row',
  milestoneThreeDayStreakDescription:
    'Log dreams on three consecutive days to prove the habit is taking hold.',
  milestoneTenDreamsTitle: '10 dreams saved',
  milestoneTenDreamsDescription:
    'Reach ten saved dreams so trends and recurring themes start to become clearer.',
  milestoneFirstVoiceDreamTitle: 'First voice dream',
  milestoneFirstVoiceDreamDescription:
    'Save one dream with audio to preserve the original memory before it fades.',
  weeklyGoalTitle: 'Weekly goal',
  weeklyGoalDescription:
    'Aim for three entries in the last seven days to keep the habit warm.',
  weeklyGoalStatusDone: 'On track',
  weeklyGoalStatusPending: 'Keep going',
  weeklyGoalProgressLabel: 'Entries this week',
  weeklyGoalTargetLabel: 'Goal',
  journalVolume: 'Journal volume',
  entries: 'Entries',
  wordsSaved: 'Words saved',
  averageWords: 'Average words',
  averageWordsShort: 'Avg Words',
  entryStructure: 'Entry structure',
  voiceNotes: 'Voice notes',
  transcribedDreams: 'Transcribed dreams',
  generatedTranscripts: 'Generated transcripts',
  editedTranscripts: 'Edited transcripts',
  audioOnlyDreams: 'Audio-only dreams',
  taggedDreams: 'Tagged dreams',
  emotionPatterns: 'Emotion patterns',
  wakeEmotions: 'After waking',
  preSleepEmotions: 'Before sleep',
  emotionPatternsEmpty:
    'Add wake-up and pre-sleep emotions to see which feelings keep repeating.',
  moodBreakdown: 'Mood breakdown',
  moodBreakdownEmpty: 'Add mood after waking to unlock this breakdown.',
  sleepContextBreakdown: 'Pre-sleep factors',
  sleepContextEmpty:
    'Add pre-sleep context to compare stress, caffeine, and other signals here.',
  entriesWithContext: 'Entries with context',
  entriesWithoutMood: 'Entries without mood',
  entriesWithoutContext: 'Entries without context',
  averageStressLevel: 'Average stress',
  alcoholBeforeSleep: 'Alcohol before sleep',
  lateCaffeine: 'Late caffeine',
  medicationsNoted: 'Medications noted',
  importantEventsNoted: 'Important events noted',
  healthNotesNoted: 'Health notes',
  moodSignalTitle: 'Mood signals (experimental)',
  moodSignalEmpty:
    'Negative mood signals appear after you log mood together with pre-sleep context.',
  negativeMoodRate: 'Negative mood rate',
  negativeWithAlcohol: 'Negative after alcohol',
  negativeWithoutAlcohol: 'Negative without alcohol',
  negativeWithLateCaffeine: 'Negative after late caffeine',
  negativeWithoutLateCaffeine: 'Negative without late caffeine',
  negativeWithHighStress: 'Negative with high stress',
  negativeWithLowStress: 'Negative with low stress',
  noData: 'No data',
  recurringThemes: 'Themes',
  recurringThemesEmpty: 'Add tags to surface recurring themes here.',
  recurringWords: 'Words',
  recurringWordsEmpty:
    'Save a few richer notes or transcripts to surface words that keep coming back.',
  recurringSymbols: 'Symbols',
  recurringSymbolsEmpty:
    'Transcribe a few voice dreams to surface repeated symbols from transcript text.',
  patternDetailEyebrow: 'Pattern detail',
  patternDetailMatchesTitle: 'Matching dreams',
  patternDetailMatchesSingle: 'dream',
  patternDetailMatchesPlural: 'dreams',
  patternDetailMatchedIn: 'Matched in',
  patternDetailWordLabel: 'Repeating word',
  patternDetailThemeLabel: 'Recurring theme',
  patternDetailSymbolLabel: 'Recurring symbol',
  patternDetailWordDescription:
    'This word keeps returning across titles, written notes, or transcripts.',
  patternDetailThemeDescription:
    'This signal keeps coming back through tags or transcript language.',
  patternDetailSymbolDescription:
    'This symbol keeps repeating inside saved transcript language.',
  threadDetailEyebrow: 'Dream thread',
  threadDetailCountLabel: 'Matches',
  threadDetailFirstSeenLabel: 'First seen',
  threadDetailLatestSeenLabel: 'Latest',
  threadDetailSourceLabel: 'Strongest source',
  threadDetailTimelineTitle: 'Timeline',
  threadDetailEntryFirst: 'First',
  threadDetailEntryLatest: 'Latest',
  threadDetailEntryOnly: 'Only match',
  threadDetailMentionSingle: 'mention',
  threadDetailMentionPlural: 'mentions',
  threadDetailMentionPluralUkFew: 'mentions',
  patternDetailSourceTag: 'Tag',
  patternDetailSourceTitle: 'Title',
  patternDetailSourceText: 'Notes',
  patternDetailSourceTranscript: 'Transcript',
  patternDetailEmptyTitle: 'No matching dreams',
  patternDetailEmptyDescription:
    'This signal is no longer present in the current archive snapshot.',
  takeawayWordsLabel: 'Words',
  takeawayThemesLabel: 'Themes',
  takeawayGapsLabel: 'Gap to fill',
  takeawayWordsEmpty: 'Not enough repeated words yet.',
  takeawayThemesEmpty: 'Tags are still too sparse for a clear theme.',
  takeawayGapsEmpty: 'This slice is well-covered already.',
  takeawayGapAudioOnly: 'Audio waiting for transcript',
  takeawayGapMood: 'Entries missing mood',
  takeawayGapContext: 'Entries missing context',
  localReflectionTitle: 'Local reflection',
  localReflectionDescription:
    'Recurring signals are extracted only from your saved tags and transcripts on device.',
  reflectionThemeCountLabel: 'dreams',
  reflectionSourceTag: 'Tag',
  reflectionSourceTranscript: 'Transcript',
  reflectionSourceMixed: 'Tag + transcript',
  bright: 'Bright',
  calm: 'Calm',
  heavy: 'Heavy',
  milestoneFiftyDreamsTitle: '50 dreams saved',
  milestoneFiftyDreamsDescription:
    'Fifty entries in the archive. The patterns are deepening.',
  milestoneHundredDreamsTitle: '100 dreams saved',
  milestoneHundredDreamsDescription:
    'A hundred nights remembered. A real archive.',
  streakMilestoneThreeDaysTitle: 'Three days in a row',
  streakMilestoneThreeDaysSubtitle: 'The habit is forming. Keep it warm.',
  streakMilestoneSevenDaysTitle: 'Seven days of dreams',
  streakMilestoneSevenDaysSubtitle:
    'A full week. The archive is starting to remember.',
  streakMilestoneFourteenDaysTitle: 'Two weeks',
  streakMilestoneFourteenDaysSubtitle:
    'Fourteen days. Something real is building here.',
  streakMilestoneThirtyDaysTitle: 'Thirty nights',
  streakMilestoneThirtyDaysSubtitle:
    'A full month of dreams. The patterns are becoming visible.',
  emotionalTrendTitle: 'Emotional arc',
  emotionalTrendDescription:
    'How the mood of your dreams has shifted over time.',
  emotionalTrendEmptyLabel:
    'Add mood to a few dreams to see the arc take shape.',
  emotionalTrendArcPositive: 'Mostly peaceful and bright across this period.',
  emotionalTrendArcNeutral:
    'A steady, balanced drift — not pulling hard in either direction.',
  emotionalTrendArcNegative:
    'A heavier stretch. Worth sitting with for a moment.',
  emotionalTrendArcMixed: 'A mixed arc — shifting between light and heavy.',
  patternGroupHighFrequencyLabel: 'Recurring',
};

const STATS_COPY_UK: typeof STATS_COPY_EN = {
  ...STATS_COPY_EN,
  title: "Пам'ять",
  subtitle: 'Сигнали, нитки й місячні форми з твого локального архіву снів.',
  monthLabel: 'Поточний локальний стан',
  rangeLabel: 'Період',
  rangeAll: 'Увесь час',
  range30Days: '30 днів',
  range7Days: '7 днів',
  memoryModeLabel: 'Розділ',
  memoryModeOverview: 'Огляд',
  memoryModeThreads: 'Повтори',
  memoryModeMonthly: 'Місяць',
  compareLabel: 'Режим',
  compareSnapshot: 'Зріз',
  compareMode: 'Порівняти',
  compareUnavailable: 'Порівняння працює для 7 або 30 днів.',
  compareCurrentPeriod: 'Поточний період',
  comparePreviousPeriod: 'Попередній період',
  compareDeltaLabel: 'до попереднього періоду',
  monthlyReportOpenButton: 'Місячний звіт',
  monthlyReportBackButton: 'Назад',
  monthlyReportEyebrow: 'Місячна рефлексія',
  monthlyReportTitle: 'Місячний звіт',
  monthlyReportSubtitle:
    'Спокійніше повернення до місяця, зібране з локального архіву без відчуття dashboard.',
  monthlyReportEmptyTitle: 'Місячного звіту ще немає',
  monthlyReportEmptyDescription:
    'Збережи кілька снів в одному місяці, і перший локальний звіт почне складатися.',
  monthlyReportLoadingTitle: 'Збираємо місячний звіт',
  monthlyReportLoadingDescription: 'Оновлюємо локальний архів за цей місяць.',
  monthlyReportMonthStripLabel: 'Місяці',
  monthlyReportSaveAction: 'Зберегти на потім',
  monthlyReportSavedAction: 'Збережено',
  monthlyReportShareAction: 'Поділитися',
  monthlyReportShareTitle: 'Місячний звіт про сни',
  monthlyReportCoverTitle: 'Цей місяць відчувався як',
  monthlyReportCoverEmpty: 'Його форма ще не встигла проявитися.',
  monthlyReportHighlightsTitle: 'Місяць у моментах',
  monthlyReportHighlightsDescription:
    'Найсильніші числа, які варто зберегти з цього місяця.',
  monthlyReportSignalsTitle: 'Що поверталося',
  monthlyReportSignalsDescription:
    'Повторювані деталі, які дали цьому місяцю власну текстуру.',
  monthlyReportGentleTitle: 'Що поглибило архів',
  monthlyReportGentleDescription:
    'Тиха структура, яка зробила цей місяць легшим для повернення.',
  monthlyReportEntriesLabel: 'Записи',
  monthlyReportWordsLabel: 'Слова',
  monthlyReportVoiceLabel: 'Голос',
  monthlyReportTranscriptLabel: 'Транскрипти',
  monthlyReportTagsLabel: 'Теги',
  monthlyReportContextLabel: 'Контекст',
  monthlyReportWakeLabel: 'Після пробудження',
  monthlyReportPreSleepLabel: 'Перед сном',
  monthlyReportThemeLabel: 'Тема',
  monthlyReportSymbolLabel: 'Символ',
  monthlyReportWordLabel: 'Фраза',
  monthlyReportRevisitTitle: 'Варто відкрити знову',
  monthlyReportRevisitDescription:
    'Один сон з цього місяця саме зараз потрапляє у вікно повернення.',
  monthlyReportOpenThreadAction: 'Відкрити нитку',
  monthlyReportSavedThreadsTitle: 'Збережені нитки',
  monthlyReportSavedThreadsDescription:
    'Нитки, які ти зберіг раніше і які все ще торкаються цього місяця.',
  monthlyReportNoSignal: 'Ще формується',
  overviewActivityTitle: 'Остання активність',
  overviewActivityDescription: 'Як часто останнім часом зберігалися сни.',
  nightmareFrequencyTitle: 'Частота кошмарів',
  nightmareFrequencyDescription:
    'Мʼякий зріз того, як часто в цьому періоді зʼявляються сни з кошмарним патерном.',
  nightmareFrequencyCountLabel: 'Записи з кошмарним патерном',
  nightmareFrequencyCountHint:
    'Сюди входять позначені кошмари та записи з виразним дистресом після пробудження.',
  nightmareFrequencyCountEmptyHint:
    'У цьому періоді немає записів з кошмарним патерном.',
  nightmareFrequencyShareLabel: 'Частка цього періоду',
  nightmareFrequencyShareHintPrefix: 'Приблизно один із ',
  nightmareFrequencyShareHintSuffix: ' снів у цьому періоді.',
  nightmareFrequencyShareEmptyHint: 'Зараз тут нічого не повторюється.',
  nightmareFrequencyLatestLabel: 'Найсвіжіший',
  nightmareFrequencyLatestHint:
    'Останній запис з кошмарним патерном у цьому періоді.',
  nightmareFrequencyLatestEmptyValue: 'Немає',
  nightmareFrequencyLatestEmptyHint:
    'У цьому періоді не було запису з кошмарним патерном.',
  lucidFrequencyTitle: 'Частота усвідомлених снів',
  lucidFrequencyDescription:
    'Як часто в цьому зрізі зʼявляється усвідомленість і який слід вона лишає в недавній історії.',
  lucidFrequencyCountLabel: 'Усвідомлені записи',
  lucidFrequencyCountHint:
    'Сюди входить коротка ясність, усвідомлені сни та записи з відчуттям контролю.',
  lucidFrequencyCountEmptyHint:
    'У цьому періоді немає усвідомлених записів.',
  lucidFrequencyShareLabel: 'Частка цього періоду',
  lucidFrequencyShareHintPrefix: 'Приблизно один із ',
  lucidFrequencyShareHintSuffix: ' снів у цьому періоді.',
  lucidFrequencyShareEmptyHint:
    'У цьому періоді усвідомленість ще не повторюється.',
  lucidFrequencyLatestLabel: 'Найсвіжіший',
  lucidFrequencyLatestHint: 'Останній усвідомлений запис у цьому періоді.',
  lucidFrequencyLatestEmptyValue: 'Немає',
  lucidFrequencyLatestEmptyHint:
    'У цьому періоді не було усвідомленого запису.',
  lucidHistoryTitle: 'Недавня історія усвідомленості',
  lucidHistoryDescription:
    'Відкрий усвідомлений запис і звір, який рівень ясності там зʼявився.',
  lucidHistoryEmpty: 'У цьому зрізі ще немає усвідомлених записів.',
  lucidAwareLabel: 'Усвідомлені',
  lucidControlledLabel: 'З контролем',
  lucidTopTechniqueLabel: 'Головна техніка',
  lucidDreamSignsLabel: 'Головний dream sign',
  lucidTechniqueEmptyValue: 'Ще немає',
  lucidDreamSignsEmptyValue: 'Ще формується',
  nightmareRecurringLabel: 'Повторювані',
  nightmareHighDistressLabel: 'Високий дистрес',
  nightmareRescriptedLabel: 'Переписані',
  nightmareDerivedLabel: 'Похідні сигнали',
  nightmareDerivedHint: 'Обережне fallback-визначення з дистресу після пробудження.',
  weeklyPatternsTitle: 'Патерни тижня',
  weeklyPatternsDescription:
    'Спокійний зріз того, що виділилося за останні сім днів.',
  overviewTopSignalLabel: 'Головний сигнал',
  overviewTopSignalEmpty: 'Ще формується',
  overviewNextStepLabel: 'Наступний крок',
  overviewNextStepEmpty: 'Нічого термінового зараз немає.',
  weeklyPatternRhythmLabel: 'Ритм',
  weeklyPatternSignalLabel: 'Свіжий сигнал',
  weeklyPatternToneLabel: 'Тон',
  weeklyPatternContextLabel: 'Контекст',
  weeklyPatternCaptureLabel: 'Запис',
  weeklyPatternQuietWeekTitle: 'Тихий тиждень',
  weeklyPatternQuietWeekHint: 'За останні сім днів нових снів не було.',
  weeklyPatternStillFormingTitle: 'Ще формується',
  weeklyPatternStillFormingHint:
    'Ще один детальніший запис зробить тиждень читабельнішим.',
  weeklyPatternContextTitle: 'Контекст зʼявлявся',
  weeklyPatternVoiceTitle: 'Тиждень схилявся до голосу',
  weeklyPatternThisWeekSuffix: 'цього тижня',
  weeklyPatternVsPreviousLabel: 'проти попередніх 7 днів',
  weeklyPatternVsPreviousFlat: 'Так само, як у попередні 7 днів',
  fingerprintTitle: 'Відбиток снів',
  fingerprintDescription:
    'Швидкий портрет сигналів, які знову повертаються в цьому зрізі.',
  fingerprintLeadLabel: 'Головні ноти',
  fingerprintEmpty:
    'Збережи ще кілька змістовніших снів, щоб відбиток усталився.',
  fingerprintThemeLabel: 'Тема',
  fingerprintSymbolLabel: 'Символ',
  fingerprintWakeLabel: 'Після пробудження',
  fingerprintPreSleepLabel: 'Перед сном',
  detailsTitle: 'Більше деталей',
  detailsDescription: 'Відкривай глибші цифри тільки коли це потрібно.',
  detailsShow: 'Показати деталі',
  detailsHide: 'Сховати деталі',
  snapshotTitle: 'Зріз архіву',
  snapshotDescription: 'Компактний зріз цієї частини архіву.',
  spotlightTitle: 'Фокус',
  spotlightDescription:
    'Найшвидший спосіб побачити, що тут найбільше виділяється.',
  memoryNudgeLabel: 'Відкрити зараз',
  memoryNudgeThemeReasonPrefix: 'Тема все ще тягне увагу: ',
  memoryNudgeThemeReasonSuffix:
    '. Відкрий один сон і звір, що досі відчувається правдою.',
  memoryNudgeWordReasonPrefix: 'Це слово знову повертається: ',
  memoryNudgeWordReasonSuffix:
    '. Відкрий один сон і подивись, що навколо нього змінилося.',
  memoryNudgeSymbolReasonPrefix: 'Цей символ знову виринає: ',
  memoryNudgeSymbolReasonSuffix:
    '. Відкрий один сон і перевір, яка деталь досі тримається.',
  memoryNudgeTimeReasonPrefix: 'Цей сон знову виринає з ',
  memoryNudgeTimeReasonSuffix:
    '. Відкрий його ще раз і подивись, яка деталь досі тримається.',
  memoryNudgeTranscriptReason:
    'Одна голосова нотатка ще чекає, щоб стати придатним текстом, поки спогад свіжий.',
  memoryNudgeThemeBadge: 'Тема',
  memoryNudgeWordBadge: 'Слово',
  memoryNudgeSymbolBadge: 'Символ',
  memoryNudgeTimeBadge: 'Час',
  memoryNudgeTranscriptBadge: 'Транскрипт',
  memoryNudgeTimeWeek: 'приблизно тижневої давності',
  memoryNudgeTimeMonth: 'приблизно місячної давності',
  memoryNudgeTimeQuarter: 'приблизно тримісячної давності',
  memoryNudgeTimeHalfYear: 'приблизно піврічної давності',
  memoryNudgeTimeYear: 'приблизно річної давності',
  memoryNudgeActionReflection: 'Відкрити сон',
  memoryNudgeActionTime: 'Повернути спогад',
  memoryNudgeActionTranscript: 'Попрацювати з транскриптом',
  takeawaysTitle: 'Швидкі висновки',
  takeawaysDescription:
    'Короткі сигнали, які можна зчитати без довгого перегляду архіву.',
  coverageTitle: 'Вже добре збережено',
  coverageDescription: 'Що тут уже легко знайти або переглянути пізніше.',
  coverageTranscriptsLabel: 'Є текст для пошуку',
  coverageTagsLabel: 'Додані теги',
  coverageContextLabel: 'Доданий контекст сну',
  coverageTranscriptsHint: 'сни вже мають транскрипт або текст',
  coverageTagsHint: 'сни вже мають прикріплені теги',
  coverageContextHint: 'сни вже мають контекст перед сном',
  attentionTitle: 'Що варто додати',
  attentionDescription: 'Невеликі кроки, які зроблять цей зріз змістовнішим.',
  attentionAudioLabel: 'Транскрибувати аудіо',
  attentionMoodLabel: 'Додати настрій',
  attentionContextLabel: 'Додати контекст',
  attentionAudioHint: 'голосові сни ще сирі',
  attentionMoodHint: 'у снах бракує настрою після пробудження',
  attentionContextHint: 'у снах бракує контексту перед сном',
  attentionAllSetHint: 'Тут зараз усе виглядає добре.',
  workQueueTitle: 'Продовжити локально',
  workQueueDescription:
    'У цьому зрізі вже є кілька конкретних наступних кроків.',
  reviewShelfTitle: 'Полиця для ревʼю',
  reviewShelfDescription:
    'Одне місце, щоб повертатися до важливих снів, збережених місяців, ниток і наступних локальних кроків.',
  reviewWorkspaceTitle: 'Простір ревʼю',
  reviewWorkspaceSubtitle:
    'Повернення до наступного локального кроку, важливого сну, збереженого місяця чи нитки в одному спокійнішому місці.',
  reviewWorkspaceOpenAction: 'Відкрити ревʼю',
  reviewWorkspaceContinueTitle: 'Продовжити локально',
  reviewWorkspaceImportantTitle: 'Важливі сни',
  reviewWorkspaceImportantDescription:
    'Позначені як важливі сни залишаються поруч, щоб задавати тон наступному колу рефлексії.',
  reviewWorkspaceSavedSetsTitle: 'Збережені набори',
  reviewWorkspaceSavedSetsDescription:
    'Збережені місяці й нитки живуть тут разом як один спокійніший шар ревʼю.',
  reviewWorkspaceSavedMonthsTitle: 'Збережені місяці',
  reviewWorkspaceSavedThreadsTitle: 'Збережені нитки',
  reviewWorkspaceSummaryContinueLabel: 'Локальні кроки',
  reviewWorkspaceSummaryImportantLabel: 'Важливі сни',
  reviewWorkspaceSummarySavedSetsLabel: 'Збережені набори',
  reviewWorkspaceEmptyTitle: 'Для ревʼю ще нічого не збережено',
  reviewWorkspaceEmptyDescription:
    'Важливі сни, збережені набори й локальні наступні кроки зʼявляться тут, коли архів трохи виросте.',
  reviewWorkspaceDreamFallbackTitle: 'Сон без назви',
  reviewShelfImportantDreamEyebrow: 'Важливий сон',
  reviewShelfContinueEyebrow: 'Продовжити локально',
  reviewShelfSavedMonthEyebrow: 'Збережений місяць',
  reviewShelfSavedThreadEyebrow: 'Збережена нитка',
  workQueueTranscriptGenerateReason:
    'Ця голосова нотатка ще чекає, щоб стати текстом для пошуку.',
  workQueueTranscriptRetryReason: 'Остання спроба транскрипції не завершилась.',
  workQueueTranscriptEditReason:
    'Згенерований транскрипт уже готовий до швидкої доробки.',
  workQueueTranscriptActionGenerate: 'Транскрибувати аудіо',
  workQueueTranscriptActionRetry: 'Повторити транскрипцію',
  workQueueTranscriptActionEdit: 'Редагувати транскрипт',
  workQueueAnalysisReason:
    'У цьому сні вже достатньо матеріалу для короткої локальної рефлексії.',
  workQueueAnalysisRetryReason:
    'Локальний аналіз минулого разу не вдався. Відкрий і спробуй ще раз.',
  workQueueAnalysisBadge: 'Аналіз',
  workQueueAnalysisActionGenerate: 'Згенерувати аналіз',
  workQueueAnalysisActionRetry: 'Оновити аналіз',
  voiceArchiveTitle: 'Голосовий архів',
  voiceArchiveDescription:
    'Скільки в архіві ще сирого аудіо, а скільки вже стало придатним текстом.',
  sleepSignalsTitle: 'Сон і настрій',
  sleepSignalsDescription:
    'Настрій, контекст перед сном і повторювані емоції в межах вибраного періоду.',
  patternsTitle: 'Повторювані сигнали',
  patternsDescription:
    'Символи, теми й повторювані фрази, відсортовані за тим, як часто вони повертаються і де саме зʼявляються.',
  patternsTrackedLabel: 'відстежуються',
  memoryThreadTitle: 'Поточна нитка',
  memoryThreadDescription:
    'Залишайся на цьому екрані й переглядай сни, пов’язані з вибраним повторюваним сигналом.',
  memoryThreadOpenAction: 'Відкрити всю нитку',
  memoryThreadClearAction: 'Закрити нитку',
  savedThreadsTitle: 'Збережені нитки',
  savedThreadsDescription:
    'Закріплені нитки лишаються тут, щоб їх можна було відкрити знову без пошуку по сигналах.',
  threadSaveAction: 'Зберегти нитку',
  threadSavedAction: 'Збережено',
  patternsTopLabel: 'Головний сигнал',
  patternsMoreLabel: 'Ще повторюються',
  recurringWordsDescription: 'У назвах, нотатках і транскриптах.',
  recurringThemesDescription: 'З тегів і мови транскриптів.',
  recurringSymbolsDescription: 'Лише з мови транскриптів.',
  preSleepEmotionsDescription:
    'Емоції, які ти найчастіше відмічаєш перед сном.',
  progressOpenButton: 'Відкрити прогрес',
  progressBackButton: 'Назад',
  progressScreenTitle: 'Прогрес',
  progressScreenSubtitle:
    'Тут видно тижневий ритм, відкриті майлстоуни і наступну ціль запису.',
  progressLoadingTitle: 'Завантажуємо прогрес',
  progressLoadingDescription: 'Оновлюємо локальні майлстоуни й тижневий ритм.',
  progressFocusTitle: 'Наступне відкриття',
  progressFocusDoneTitle: 'Усі базові майлстоуни відкриті',
  progressFocusDoneDescription:
    'Звичка запису вже зібрана. Тепер нові записи головно поглиблюють архів.',
  milestonesToggleShow: 'Показати майлстоуни',
  milestonesToggleHide: 'Сховати майлстоуни',
  currentStreak: 'Поточний стрік',
  lastSevenDays: 'Останні 7 днів',
  emptyTitle: "Пам'ять ще формується",
  emptyDescription:
    "Спочатку збережи кілька снів. Пам'ять почне автоматично пов'язувати повторювані сигнали з локального архіву.",
  readinessTitle: 'Готовність аналітики',
  readinessDescription:
    'Що більше ти додаєш настрою, тегів і контексту перед сном, то кориснішими стають ці патерни.',
  entriesWithMood: 'Записи з настроєм',
  entriesWithTags: 'Записи з тегами',
  readinessHint:
    'На малому обсязі даних патерни легко коливаються. Сприймай ранні сигнали як орієнтир, а не як висновок.',
  milestonesTitle: 'Усі майлстоуни',
  milestonesDescription:
    'Простий зріз того, що вже відкрито і що ще добудовується.',
  milestonesUnlockedLabel: 'Відкрито',
  milestonesCompleteTitle: 'Майлстоуни закрито',
  milestonesCompleteDescription:
    'Усі базові майлстоуни запису відкриті. Архів уже достатньо насичений для глибшої рефлексії.',
  milestoneHighlightLabel: 'Фокус',
  milestoneUnlocked: 'Відкрито',
  milestoneInProgress: 'У процесі',
  milestoneProgressLabel: 'Виконано / ціль',
  milestoneFirstDreamTitle: 'Перший сон збережено',
  milestoneFirstDreamDescription:
    'Збережи перший сон, щоб почати будувати корисний архів.',
  milestoneThreeDayStreakTitle: 'Три дні поспіль',
  milestoneThreeDayStreakDescription:
    'Записуй сни три дні підряд, щоб закріпити звичку.',
  milestoneTenDreamsTitle: '10 збережених снів',
  milestoneTenDreamsDescription:
    'Дійди до десяти збережених снів, щоб тренди й повторювані теми стали помітнішими.',
  milestoneFirstVoiceDreamTitle: 'Перший голосовий сон',
  milestoneFirstVoiceDreamDescription:
    'Збережи хоча б один сон з аудіо, щоб не втратити оригінальний спогад.',
  weeklyGoalTitle: 'Ціль на тиждень',
  weeklyGoalDescription:
    'Спробуй дійти до трьох записів за останні сім днів, щоб не втрачати ритм.',
  weeklyGoalStatusDone: 'Рух хороший',
  weeklyGoalStatusPending: 'Продовжуй',
  weeklyGoalProgressLabel: 'Записів за тиждень',
  weeklyGoalTargetLabel: 'Ціль',
  journalVolume: 'Обсяг щоденника',
  entries: 'Записи',
  wordsSaved: 'Збережено слів',
  averageWords: 'Середньо слів',
  averageWordsShort: 'Сер. слів',
  entryStructure: 'Структура записів',
  voiceNotes: 'Голосові нотатки',
  transcribedDreams: 'Транскрибовані сни',
  generatedTranscripts: 'Згенеровані транскрипти',
  editedTranscripts: 'Відредаговані транскрипти',
  audioOnlyDreams: 'Сни лише з аудіо',
  taggedDreams: 'Записи з тегами',
  emotionPatterns: 'Патерни емоцій',
  wakeEmotions: 'Після пробудження',
  preSleepEmotions: 'Перед сном',
  emotionPatternsEmpty:
    'Додай емоції після пробудження і перед сном, щоб бачити, які відчуття повторюються.',
  moodBreakdown: 'Розподіл настрою',
  moodBreakdownEmpty:
    'Додай настрій після пробудження, щоб тут зʼявився розподіл.',
  sleepContextBreakdown: 'Фактори перед сном',
  sleepContextEmpty:
    'Додай контекст перед сном, щоб тут порівнювати стрес, кофеїн та інші сигнали.',
  entriesWithContext: 'Записи з контекстом',
  entriesWithoutMood: 'Записи без настрою',
  entriesWithoutContext: 'Записи без контексту',
  averageStressLevel: 'Середній стрес',
  alcoholBeforeSleep: 'Алкоголь перед сном',
  lateCaffeine: 'Пізній кофеїн',
  medicationsNoted: 'Вказані препарати',
  importantEventsNoted: 'Вказані важливі події',
  healthNotesNoted: 'Нотатки про здоровʼя',
  moodSignalTitle: 'Сигнали настрою (експериментально)',
  moodSignalEmpty:
    'Сигнали настрою зʼявляться, коли ти поєднаєш настрій і контекст перед сном у тих самих записах.',
  negativeMoodRate: 'Частка негативного настрою',
  negativeWithAlcohol: 'Негатив після алкоголю',
  negativeWithoutAlcohol: 'Негатив без алкоголю',
  negativeWithLateCaffeine: 'Негатив після пізнього кофеїну',
  negativeWithoutLateCaffeine: 'Негатив без пізнього кофеїну',
  negativeWithHighStress: 'Негатив при високому стресі',
  negativeWithLowStress: 'Негатив при низькому стресі',
  noData: 'Немає даних',
  recurringThemes: 'Теми',
  recurringThemesEmpty: 'Додай теги, щоб тут зʼявлялися повторювані теми.',
  recurringWords: 'Слова',
  recurringWordsEmpty:
    'Збережи кілька змістовніших нотаток або транскриптів, щоб тут зʼявились повторювані слова.',
  recurringSymbols: 'Символи',
  recurringSymbolsEmpty:
    'Транскрибуй кілька голосових снів, щоб тут зʼявилися повторювані символи з тексту транскриптів.',
  patternDetailEyebrow: 'Деталь патерну',
  patternDetailMatchesTitle: 'Сни зі збігом',
  patternDetailMatchesSingle: 'сон',
  patternDetailMatchesPlural: 'снів',
  patternDetailMatchedIn: 'Збіг у',
  patternDetailWordLabel: 'Повторюване слово',
  patternDetailThemeLabel: 'Повторювана тема',
  patternDetailSymbolLabel: 'Повторюваний символ',
  patternDetailWordDescription:
    'Це слово знову зʼявляється в заголовках, нотатках або транскриптах.',
  patternDetailThemeDescription:
    'Цей сигнал повертається через теги або мову транскриптів.',
  patternDetailSymbolDescription:
    'Цей символ повторюється всередині збережених транскриптів.',
  threadDetailEyebrow: 'Нитка сну',
  threadDetailCountLabel: 'Збіги',
  threadDetailFirstSeenLabel: 'Вперше',
  threadDetailLatestSeenLabel: 'Останній',
  threadDetailSourceLabel: 'Головне джерело',
  threadDetailTimelineTitle: 'Послідовність',
  threadDetailEntryFirst: 'Початок',
  threadDetailEntryLatest: 'Останній',
  threadDetailEntryOnly: 'Єдиний збіг',
  threadDetailMentionSingle: 'згадка',
  threadDetailMentionPlural: 'згадок',
  threadDetailMentionPluralUkFew: 'згадки',
  patternDetailSourceTag: 'Тег',
  patternDetailSourceTitle: 'Заголовок',
  patternDetailSourceText: 'Нотатки',
  patternDetailSourceTranscript: 'Транскрипт',
  patternDetailEmptyTitle: 'Збігів не знайдено',
  patternDetailEmptyDescription:
    'Цей сигнал більше не присутній у поточному зрізі архіву.',
  takeawayWordsLabel: 'Слова',
  takeawayThemesLabel: 'Теми',
  takeawayGapsLabel: 'Що ще доповнити',
  takeawayWordsEmpty: 'Поки замало повторюваних слів.',
  takeawayThemesEmpty: 'Тегів ще недостатньо для чіткої теми.',
  takeawayGapsEmpty: 'Цей зріз уже заповнений досить добре.',
  takeawayGapAudioOnly: 'Аудіо без транскрипту',
  takeawayGapMood: 'Записи без настрою',
  takeawayGapContext: 'Записи без контексту',
  localReflectionTitle: 'Локальна рефлексія',
  localReflectionDescription:
    'Повторювані сигнали витягуються лише з твоїх збережених тегів і транскриптів на пристрої.',
  reflectionThemeCountLabel: 'снів',
  reflectionSourceTag: 'Тег',
  reflectionSourceTranscript: 'Транскрипт',
  reflectionSourceMixed: 'Тег + транскрипт',
  bright: 'Світлий',
  calm: 'Спокійний',
  heavy: 'Важкий',
  milestoneFiftyDreamsTitle: '50 збережених снів',
  milestoneFiftyDreamsDescription:
    'Пʼятдесят записів в архіві. Патерни поглиблюються.',
  milestoneHundredDreamsTitle: '100 збережених снів',
  milestoneHundredDreamsDescription:
    'Сотня запамʼятованих ночей. Справжній архів.',
  streakMilestoneThreeDaysTitle: 'Три дні поспіль',
  streakMilestoneThreeDaysSubtitle:
    'Звичка починає формуватися. Підтримуй тепло.',
  streakMilestoneSevenDaysTitle: 'Сім днів снів',
  streakMilestoneSevenDaysSubtitle:
    'Повний тиждень. Архів вже починає памʼятати.',
  streakMilestoneFourteenDaysTitle: 'Два тижні',
  streakMilestoneFourteenDaysSubtitle:
    'Чотирнадцять днів. Щось справжнє будується.',
  streakMilestoneThirtyDaysTitle: 'Тридцять ночей',
  streakMilestoneThirtyDaysSubtitle:
    'Повний місяць снів. Патерни починають проявлятися.',
  emotionalTrendTitle: 'Емоційна дуга',
  emotionalTrendDescription: 'Як настрій твоїх снів змінювався з часом.',
  emotionalTrendEmptyLabel:
    'Додай настрій до кількох снів, щоб дуга почала проявлятися.',
  emotionalTrendArcPositive: 'Переважно спокійний і світлий за цей період.',
  emotionalTrendArcNeutral: 'Рівний, збалансований рух — без різких перепадів.',
  emotionalTrendArcNegative: 'Важчий відрізок. Варто побути з ним трохи довше.',
  emotionalTrendArcMixed: 'Змішана дуга — коливається між світлим і важким.',
  patternGroupHighFrequencyLabel: 'Повторюваний',
};

export type StatsCopy = typeof STATS_COPY_EN;

export function getStatsCopy(locale: AppLocale): StatsCopy {
  return locale === 'uk' ? STATS_COPY_UK : STATS_COPY_EN;
}
