export const STATS_COPY = {
  title: 'Insights',
  subtitle: 'Lightweight analytics from your local dream archive.',
  monthLabel: 'Current local snapshot',
  currentStreak: 'Current streak',
  lastSevenDays: 'Last 7 days',
  monthChange: 'Local-first',
  journalVolume: 'Journal volume',
  entries: 'Entries',
  wordsSaved: 'Words saved',
  averageWords: 'Average words',
  averageWordsShort: 'Avg Words',
  entryStructure: 'Entry structure',
  voiceNotes: 'Voice notes',
  taggedDreams: 'Tagged dreams',
  moodBreakdown: 'Mood breakdown',
  recurringThemes: 'Recurring themes',
  bright: 'Bright',
  calm: 'Calm',
  heavy: 'Heavy',
} as const;
