import { StyleSheet } from 'react-native';
import { Theme } from '../../../theme/theme';
import { createControlPill, createSoftTile } from '../../../theme/surfaces';

export function createArchiveScreenStyles(theme: Theme) {
  return StyleSheet.create({
    content: {
      paddingTop: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
      gap: theme.spacing.sm,
    },
    headerBlock: {
      gap: 12,
    },
    titleBlock: {
      gap: 4,
      paddingHorizontal: 2,
    },
    toolbarCard: {
      gap: 8,
      padding: 12,
      backgroundColor: theme.colors.surface,
      overflow: 'hidden',
      position: 'relative',
      borderColor: `${theme.colors.border}CC`,
    },
    controlsCard: {
      gap: 8,
      padding: 9,
      backgroundColor: theme.colors.surfaceElevated,
      borderColor: `${theme.colors.border}E6`,
    },
    toolbarGlowLarge: {
      position: 'absolute',
      width: 104,
      height: 104,
      borderRadius: 999,
      backgroundColor: theme.colors.auroraMid,
      opacity: 0.035,
      top: -20,
      right: -14,
    },
    toolbarGlowSmall: {
      position: 'absolute',
      width: 54,
      height: 54,
      borderRadius: 999,
      backgroundColor: theme.colors.accent,
      opacity: 0.03,
      bottom: -10,
      left: -8,
    },
    controlsMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    controlsMetaChip: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 4,
        paddingHorizontal: 8,
      }),
    },
    controlsMetaChipText: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'capitalize',
    },
    controlsActionChip: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 4,
        paddingHorizontal: 8,
      }),
      backgroundColor: 'rgba(20, 24, 38, 0.42)',
    },
    controlsActionChipText: {
      color: theme.colors.text,
      fontSize: 9,
      fontWeight: '700',
    },
    searchRow: {
      ...createSoftTile(theme, {
        tone: 'alt',
        radius: 14,
        paddingVertical: 0,
        paddingHorizontal: 0,
      }),
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 8,
      overflow: 'hidden',
      borderColor: `${theme.colors.border}C8`,
      backgroundColor: 'rgba(20, 24, 38, 0.28)',
    },
    searchIconWrap: {
      width: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchFieldContainer: {
      flex: 1,
      gap: 4,
      marginLeft: 3,
    },
    searchInput: {
      backgroundColor: 'transparent',
      borderWidth: 0,
      paddingVertical: 6,
      paddingHorizontal: 0,
      minHeight: 0,
    },
    filtersRail: {
      gap: 5,
      paddingRight: 2,
    },
    filterChip: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 3,
        paddingHorizontal: 9,
      }),
      backgroundColor: 'rgba(20, 24, 38, 0.42)',
    },
    filterChipActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary,
    },
    filterChipText: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
    },
    filterChipTextActive: {
      color: theme.colors.background,
    },
    controlsFooterRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
      minHeight: 20,
    },
    resultsToolbar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
      marginTop: 0,
      flexWrap: 'wrap',
      paddingHorizontal: 2,
    },
    resultsToolbarMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
    },
    resultsToolbarText: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    modeChip: {
      borderRadius: theme.borderRadii.pill,
      paddingVertical: 7,
      paddingHorizontal: 14,
      minWidth: 78,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modeChipActive: {
      backgroundColor: theme.colors.primary,
      shadowColor: theme.colors.glow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.14,
      shadowRadius: 12,
      elevation: 3,
    },
    modeChipText: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '700',
    },
    modeChipTextActive: {
      color: theme.colors.background,
    },
    browseModeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      flexWrap: 'wrap',
    },
    browseModeLabel: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    browseModeChips: {
      borderRadius: theme.borderRadii.pill,
      borderWidth: 1,
      borderColor: `${theme.colors.border}C8`,
      backgroundColor: 'rgba(20, 24, 38, 0.42)',
      flexDirection: 'row',
      gap: 4,
      flexWrap: 'wrap',
      padding: 4,
    },
    revisitInlineCard: {
      ...createSoftTile(theme, {
        tone: 'surface',
        radius: 14,
        paddingVertical: 9,
        paddingHorizontal: 12,
      }),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      borderColor: `${theme.colors.accent}55`,
      backgroundColor: 'rgba(20, 24, 38, 0.26)',
    },
    revisitInlineMain: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    revisitInlineLabel: {
      color: theme.colors.textDim,
      fontSize: 9,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    revisitInlineTitle: {
      color: theme.colors.text,
      fontSize: 13,
      lineHeight: 17,
      fontWeight: '700',
    },
    revisitInlineMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexShrink: 0,
    },
    revisitCard: {
      ...createSoftTile(theme, {
        tone: 'surface',
        radius: 16,
        paddingVertical: 10,
        paddingHorizontal: 12,
      }),
      gap: 4,
      borderColor: `${theme.colors.accent}66`,
    },
    revisitCardPressed: {
      opacity: 0.96,
      transform: [{ scale: 0.992 }],
    },
    revisitHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
      flexWrap: 'wrap',
    },
    revisitBadge: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 5,
        paddingHorizontal: 8,
      }),
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderColor: `${theme.colors.accent}55`,
      backgroundColor: 'rgba(124, 200, 255, 0.08)',
    },
    revisitBadgeText: {
      color: theme.colors.accent,
      fontSize: 10,
      lineHeight: 13,
      fontWeight: '700',
    },
    revisitLabel: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    revisitAction: {
      color: theme.colors.accent,
      fontSize: 11,
      fontWeight: '700',
    },
    revisitActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      marginTop: 4,
    },
    revisitTitle: {
      color: theme.colors.text,
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '700',
    },
    revisitReason: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
    },
    calendarCard: {
      gap: 10,
    },
    calendarTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 8,
    },
    calendarCopy: {
      flex: 1,
      gap: 4,
    },
    calendarTitle: {
      fontWeight: '700',
    },
    calendarSubtitle: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
    },
    calendarToggleButton: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 6,
        paddingHorizontal: 10,
      }),
    },
    calendarToggleButtonText: {
      color: theme.colors.text,
      fontSize: 11,
      fontWeight: '700',
    },
    monthToolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingRight: 0,
    },
    monthPagerSlot: {
      width: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickJumpRow: {
      gap: 5,
      paddingRight: 4,
    },
    quickJumpChip: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 4,
        paddingHorizontal: 8,
      }),
      backgroundColor: 'rgba(20, 24, 38, 0.42)',
    },
    quickJumpChipActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary,
      shadowColor: theme.colors.glow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.14,
      shadowRadius: 12,
      elevation: 3,
    },
    quickJumpChipText: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'capitalize',
    },
    quickJumpChipTextActive: {
      color: theme.colors.background,
    },
    monthPagerButton: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 7,
        paddingHorizontal: 7,
      }),
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(20, 24, 38, 0.42)',
    },
    monthPagerButtonDisabled: {
      opacity: 0.45,
    },
    monthLabelBlock: {
      flex: 1,
      gap: 3,
      alignItems: 'center',
    },
    monthLabel: {
      fontSize: 17,
      lineHeight: 21,
      fontWeight: '700',
      textTransform: 'capitalize',
    },
    monthMetaText: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '600',
      textAlign: 'center',
    },
    monthInlineToggleButton: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 4,
        paddingHorizontal: 10,
      }),
      backgroundColor: 'rgba(20, 24, 38, 0.42)',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    monthInlineToggleButtonText: {
      color: theme.colors.text,
      fontSize: 10,
      fontWeight: '700',
    },
    weekdayRow: {
      flexDirection: 'row',
      gap: 4,
    },
    weekdayLabel: {
      flex: 1,
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    calendarRows: {
      gap: 4,
    },
    calendarDaysWrap: {
      gap: 5,
      paddingTop: 6,
      borderTopWidth: 1,
      borderTopColor: `${theme.colors.border}99`,
    },
    calendarWeekRow: {
      flexDirection: 'row',
      gap: 4,
    },
    calendarCell: {
      ...createSoftTile(theme, {
        tone: 'surface',
        radius: 12,
        paddingVertical: 6,
        paddingHorizontal: 4,
      }),
      flex: 1,
      minHeight: 46,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
    },
    calendarCellPlaceholder: {
      opacity: 0,
    },
    calendarCellActive: {
      backgroundColor: theme.colors.surface,
    },
    calendarCellToday: {
      borderColor: `${theme.colors.primary}66`,
      borderWidth: 1.5,
    },
    calendarCellSelected: {
      borderColor: theme.colors.primary,
      borderWidth: 2,
      backgroundColor: theme.colors.surface,
    },
    calendarCellDay: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    calendarCellDaySelected: {
      color: theme.colors.primary,
    },
    calendarCellDayMuted: {
      color: `${theme.colors.textDim}88`,
      fontWeight: '500',
    },
    calendarMoodDot: {
      width: 5,
      height: 5,
      borderRadius: 3,
      opacity: 0.85,
    },
    calendarMoodDotNeutral: {
      backgroundColor: theme.colors.textDim,
      opacity: 0.5,
    },
    selectedDateRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    selectedDateChip: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 6,
        paddingHorizontal: 10,
      }),
      backgroundColor: 'rgba(20, 24, 38, 0.42)',
    },
    selectedDateText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: '600',
    },
    clearDateChip: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 6,
        paddingHorizontal: 10,
      }),
      backgroundColor: 'rgba(20, 24, 38, 0.42)',
    },
    clearDateChipText: {
      color: theme.colors.textDim,
      fontSize: 12,
      fontWeight: '700',
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      paddingTop: theme.spacing.xs,
      paddingBottom: 4,
      paddingHorizontal: 2,
    },
    sectionTitle: {
      color: theme.colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    sectionMeta: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '600',
    },
    listRowPressable: {
      borderRadius: theme.borderRadii.xl,
    },
    listRowPressed: {
      opacity: 0.96,
      transform: [{ scale: 0.994 }],
    },
    listRowCard: {
      paddingVertical: 13,
      paddingHorizontal: 14,
      gap: 9,
      backgroundColor: theme.colors.surfaceElevated,
      borderColor: `${theme.colors.border}D9`,
    },
    listRowCardVisual: {
      overflow: 'hidden',
      position: 'relative',
    },
    listRowGlow: {
      position: 'absolute',
      width: 112,
      height: 112,
      borderRadius: 999,
      top: -26,
      right: -20,
      opacity: 0.9,
    },
    listRowAccentBar: {
      position: 'absolute',
      left: 14,
      right: 22,
      top: 0,
      height: 3,
      borderRadius: 999,
      opacity: 0.95,
    },
    listRowCardCompact: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 12,
      gap: 12,
      backgroundColor: theme.colors.surface,
    },
    comfortableTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 10,
    },
    comfortableDateWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
    },
    rowTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
    },
    rowCopy: {
      flex: 1,
      gap: 7,
    },
    rowTitle: {
      fontSize: 18,
      lineHeight: 23,
      fontWeight: '700',
    },
    rowTitleCompact: {
      flex: 1,
      fontSize: 15,
      lineHeight: 19,
      fontWeight: '700',
    },
    rowDateChip: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 4,
        paddingHorizontal: 8,
      }),
    },
    rowDateChipText: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '700',
    },
    rowDateChipTextStrong: {
      color: theme.colors.text,
    },
    rowDateChipTextCompact: {
      fontSize: 9,
    },
    signalRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    signalChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: theme.borderRadii.pill,
      borderWidth: 1,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    signalChipText: {
      fontSize: 10,
      fontWeight: '700',
    },
    rowPreview: {
      flex: 1,
      color: theme.colors.textDim,
      fontSize: 13,
      lineHeight: 19,
    },
    rowPreviewPanel: {
      ...createSoftTile(theme, {
        tone: 'surface',
        radius: 16,
        paddingVertical: 11,
        paddingHorizontal: 12,
      }),
      backgroundColor: 'rgba(20, 24, 38, 0.38)',
      borderColor: `${theme.colors.border}CC`,
      flexDirection: 'row',
      gap: 10,
    },
    rowPreviewAccent: {
      width: 4,
      borderRadius: 999,
    },
    rowPreviewContent: {
      flex: 1,
      gap: 7,
      minWidth: 0,
    },
    rowPreviewHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      flexWrap: 'wrap',
    },
    rowPreviewTypePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: theme.borderRadii.pill,
      borderWidth: 1,
      paddingVertical: 4,
      paddingHorizontal: 8,
      alignSelf: 'flex-start',
    },
    rowPreviewTypeText: {
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    rowPreviewCompact: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 16,
    },
    matchReasonsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 4,
    },
    matchReasonPill: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 3,
        paddingHorizontal: 7,
      }),
      borderColor: theme.colors.accent,
    },
    matchReasonPillText: {
      color: theme.colors.text,
      fontSize: 9,
      fontWeight: '700',
    },
    rowChevron: {
      marginRight: -2,
      paddingTop: 2,
    },
    pillsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    pill: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 4,
        paddingHorizontal: 8,
      }),
      backgroundColor: 'rgba(20, 24, 38, 0.34)',
    },
    pillText: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
    },
    compactDateBlock: {
      width: 52,
      minHeight: 52,
      borderRadius: 16,
      backgroundColor: 'rgba(20, 24, 38, 0.52)',
      borderWidth: 1,
      borderColor: `${theme.colors.border}CC`,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 1,
    },
    compactDayLabel: {
      color: theme.colors.text,
      fontSize: 20,
      lineHeight: 22,
      fontWeight: '800',
    },
    compactMonthLabel: {
      color: theme.colors.textDim,
      fontSize: 10,
      lineHeight: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    compactContent: {
      flex: 1,
      gap: 3,
      minWidth: 0,
    },
    compactSignalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
      minHeight: 22,
    },
    compactSignalChip: {
      width: 22,
      height: 22,
      borderRadius: 999,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    compactMatchText: {
      color: theme.colors.textDim,
      fontSize: 10,
      lineHeight: 13,
      fontWeight: '700',
    },
    compactTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    compactDateMeta: {
      color: theme.colors.textDim,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '600',
    },
    compactStatusText: {
      color: theme.colors.textDim,
      fontSize: 11,
      lineHeight: 14,
    },
    compactTagRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 1,
    },
    compactTagPill: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 3,
        paddingHorizontal: 7,
      }),
      backgroundColor: 'rgba(20, 24, 38, 0.3)',
    },
    compactTagText: {
      color: theme.colors.textDim,
      fontSize: 9,
      fontWeight: '700',
    },
    emptyWrap: {
      paddingTop: theme.spacing.md,
    },
    tagRailRow: {
      gap: 5,
    },
    tagRailLabel: {
      color: theme.colors.textDim,
      fontSize: 9,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    tagRail: {
      gap: 5,
      paddingRight: 2,
    },
    tagChip: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 4,
        paddingHorizontal: 9,
      }),
      backgroundColor: 'rgba(20, 24, 38, 0.42)',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    tagChipActive: {
      borderColor: theme.colors.auroraMid,
      backgroundColor: theme.colors.auroraMid,
    },
    tagChipText: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
    },
    tagChipTextActive: {
      color: theme.colors.background,
    },
    tagChipCount: {
      color: theme.colors.textDim,
      fontSize: 9,
      fontWeight: '700',
      opacity: 0.7,
    },
    tagChipCountActive: {
      color: theme.colors.background,
      opacity: 0.8,
    },
  });
}
