import { StyleSheet } from 'react-native';
import { createControlPill, createSoftTile } from '../../../theme/surfaces';
import { Theme } from '../../../theme/theme';

export function createDreamDetailScreenStyles(theme: Theme) {
  return StyleSheet.create({
    heroShell: {
      gap: 12,
      paddingHorizontal: 4,
      paddingTop: 2,
      paddingBottom: 6,
    },
    heroTopBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
    },
    backButton: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 10,
        paddingHorizontal: 10,
      }),
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroIconActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    heroIconButton: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 9,
        paddingHorizontal: 9,
      }),
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroIconButtonActive: {
      borderColor: `${theme.colors.accent}44`,
      backgroundColor: theme.colors.surfaceAlt,
    },
    heroIconButtonDanger: {
      borderColor: `${theme.colors.danger}44`,
    },
    heroIconButtonPressed: {
      opacity: 0.92,
    },
    heroHeader: {
      gap: 4,
    },
    heroTitle: {
      color: theme.colors.text,
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '700',
      includeFontPadding: false,
    },
    heroSubtitle: {
      color: theme.colors.textDim,
      fontSize: 15,
      lineHeight: 21,
    },
    heroMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 10,
      minHeight: 22,
    },
    statusChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    heroMoodPill: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 5,
        paddingHorizontal: 10,
      }),
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    statusChipLabel: {
      color: theme.colors.textDim,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '600',
    },
    statusDot: {
      width: 8,
      height: 8,
      borderRadius: 999,
    },
    heroMetaText: {
      color: theme.colors.textDim,
      fontSize: 13,
      lineHeight: 18,
    },
    heroMetaChip: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 4,
        paddingHorizontal: 9,
      }),
    },
    heroMetaChipLabel: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '600',
    },
    savedCard: {
      paddingVertical: 12,
      paddingHorizontal: 14,
      gap: 8,
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.surface,
    },
    savedHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
    },
    savedLead: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    savedIconShell: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 6,
        paddingHorizontal: 6,
      }),
      width: 28,
      height: 28,
      borderColor: `${theme.colors.accent}33`,
      alignItems: 'center',
      justifyContent: 'center',
    },
    savedCopy: {
      flex: 1,
      gap: 2,
    },
    savedTitle: {
      fontWeight: '700',
      fontSize: 13,
    },
    savedDescription: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 16,
    },
    savedDismiss: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 6,
        paddingHorizontal: 6,
      }),
      width: 30,
      height: 30,
      alignItems: 'center',
      justifyContent: 'center',
    },
    savedMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 8,
    },
    savedMetaPill: {
      minWidth: 120,
      gap: 3,
      ...createSoftTile(theme, {
        tone: 'alt',
        radius: 12,
        paddingVertical: 6,
        paddingHorizontal: 8,
      }),
    },
    savedMetaLabel: {
      color: theme.colors.textDim,
      fontSize: 9,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    savedMetaValue: {
      fontWeight: '700',
      fontSize: 13,
      lineHeight: 16,
    },
    savedMetaInline: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 16,
    },
    detailSheet: {
      padding: 0,
      gap: 0,
      overflow: 'hidden',
      backgroundColor: theme.colors.surfaceElevated,
      borderColor: `${theme.colors.border}CC`,
      shadowOpacity: 0.04,
    },
    sheetSection: {
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 12,
    },
    sheetDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: `${theme.colors.border}88`,
      marginHorizontal: 16,
    },
    sheetHeading: {
      color: theme.colors.text,
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '700',
    },
    glanceGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    glanceCell: {
      minWidth: 120,
      flexBasis: '47%',
      flexGrow: 1,
      gap: 4,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 14,
      backgroundColor: theme.colors.surface,
    },
    glanceLabel: {
      color: theme.colors.textDim,
      fontSize: 11,
      lineHeight: 16,
    },
    glanceValue: {
      color: theme.colors.text,
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '700',
    },
    featuredPanel: {
      gap: 10,
      paddingVertical: 14,
      paddingHorizontal: 14,
      borderRadius: 18,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}AA`,
    },
    revisitPanel: {
      gap: 10,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 16,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}66`,
    },
    featuredEyebrow: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '700',
    },
    featuredTitle: {
      color: theme.colors.text,
      fontSize: 20,
      lineHeight: 26,
      fontWeight: '700',
    },
    featuredBody: {
      color: theme.colors.text,
      fontSize: 16,
      lineHeight: 24,
    },
    featuredMutedBody: {
      color: theme.colors.textDim,
      fontSize: 16,
      lineHeight: 24,
    },
    featuredAction: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 8,
        paddingHorizontal: 12,
      }),
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    featuredActionPressed: {
      opacity: 0.94,
    },
    featuredActionText: {
      color: theme.colors.text,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '700',
    },
    utilityRows: {
      gap: 8,
      paddingVertical: 2,
    },
    contextFactsCard: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 16,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}88`,
    },
    supportBlock: {
      gap: 8,
    },
    settingsNotice: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 14,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}88`,
    },
    settingsNoticePressed: {
      opacity: 0.94,
    },
    settingsNoticeCopy: {
      flex: 1,
      gap: 3,
    },
    settingsNoticeTitle: {
      color: theme.colors.text,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
    },
    settingsNoticeBody: {
      color: theme.colors.textDim,
      fontSize: 13,
      lineHeight: 19,
    },
    supportHeading: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '700',
    },
    supportText: {
      color: theme.colors.textDim,
      fontSize: 14,
      lineHeight: 21,
    },
    syncNoteCard: {
      paddingVertical: 9,
      paddingHorizontal: 11,
      borderRadius: 14,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}66`,
    },
    syncNoteText: {
      color: theme.colors.textDim,
      fontSize: 13,
      lineHeight: 19,
    },
    contextNoteCard: {
      gap: 8,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 16,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.accent}22`,
    },
    contextNoteText: {
      color: theme.colors.text,
      fontSize: 15,
      lineHeight: 22,
    },
    statusErrorText: {
      color: theme.colors.danger,
      fontSize: 14,
      lineHeight: 21,
    },
    actionGroup: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    audioPlayer: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: `${theme.colors.border}99`,
      backgroundColor: theme.colors.surface,
      paddingVertical: 12,
      paddingHorizontal: 14,
      gap: 10,
    },
    audioPlayerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    audioPlayButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    audioPlayButtonPressed: {
      opacity: 0.85,
    },
    audioProgressShell: {
      flex: 1,
      gap: 5,
    },
    audioProgressTrack: {
      height: 3,
      borderRadius: 2,
      backgroundColor: `${theme.colors.border}`,
      overflow: 'hidden',
    },
    audioProgressFill: {
      height: 3,
      borderRadius: 2,
      backgroundColor: theme.colors.accent,
    },
    audioTimeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    audioTimeLabel: {
      color: theme.colors.textDim,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '600',
      letterSpacing: 0.3,
    },
    tagsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    relatedList: {
      gap: 8,
    },
    relatedRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 14,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}88`,
    },
    relatedRowPressed: {
      opacity: 0.95,
    },
    relatedCopy: {
      flex: 1,
      gap: 3,
    },
    relatedTitle: {
      color: theme.colors.text,
      fontSize: 15,
      lineHeight: 21,
      fontWeight: '700',
    },
    relatedMeta: {
      color: theme.colors.textDim,
      fontSize: 13,
      lineHeight: 18,
    },
    transcriptEditorInput: {
      minHeight: 150,
    },
    supportingPromptList: {
      gap: 10,
    },
    supportingPromptRow: {
      gap: 4,
      paddingTop: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: `${theme.colors.border}66`,
    },
    supportingPromptTitle: {
      color: theme.colors.text,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    supportingPromptBody: {
      color: theme.colors.textDim,
      fontSize: 14,
      lineHeight: 20,
    },
  });
}

export type DreamDetailScreenStyles = ReturnType<typeof createDreamDetailScreenStyles>;
