import { StyleSheet } from 'react-native';
import { Theme } from '../../../theme/theme';
import { getDreamLayout } from '../constants/layout';

export function createHomeScreenStyles(theme: Theme) {
  const layout = getDreamLayout(theme);

  return StyleSheet.create({
    emptyContainer: {
      justifyContent: 'center',
    },
    emptyCard: {
      gap: 10,
    },
    dreamCard: {
      gap: 12,
      padding: 12,
    },
    dreamPressable: {
      borderRadius: theme.borderRadii.xl,
    },
    dreamPressablePressed: {
      transform: [{ scale: 0.992 }],
      opacity: 0.96,
    },
    swipeableContainer: {
      borderRadius: theme.borderRadii.xl,
      overflow: 'hidden',
    },
    swipeActionsContainer: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 8,
    },
    swipeRightActionsContainer: {
      paddingLeft: 8,
    },
    swipeLeftActionsContainer: {
      paddingRight: 8,
    },
    swipeAction: {
      width: layout.swipeActionWidth,
      minHeight: layout.swipeActionHeight,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 10,
      borderRadius: theme.borderRadii.md,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
    },
    swipeEditAction: {
      backgroundColor: theme.colors.surfaceAlt,
    },
    swipeDeleteAction: {
      backgroundColor: theme.colors.primaryAlt,
      borderColor: theme.colors.primaryAlt,
    },
    swipeArchiveAction: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },
    swipeUnarchiveAction: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    swipeActionText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.text,
      textAlign: 'center',
    },
    swipeActionTextInverted: {
      color: theme.colors.background,
    },
    heroCard: {
      gap: 10,
      overflow: 'hidden',
      padding: 14,
      position: 'relative',
    },
    heroGlowLarge: {
      position: 'absolute',
      width: 172,
      height: 172,
      borderRadius: 999,
      backgroundColor: theme.colors.auroraMid,
      opacity: 0.08,
      top: -48,
      right: -40,
    },
    heroGlowSmall: {
      position: 'absolute',
      width: 124,
      height: 124,
      borderRadius: 999,
      backgroundColor: theme.colors.accent,
      opacity: 0.08,
      bottom: -34,
      left: -20,
    },
    heroTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 12,
    },
    heroCopy: {
      flex: 1,
      gap: layout.rowGap,
    },
    heroEyebrow: {
      color: theme.colors.accent,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.7,
      textTransform: 'uppercase',
    },
    heroTitle: {
      fontSize: 21,
      lineHeight: 26,
      fontWeight: '700',
      flexShrink: 1,
      includeFontPadding: false,
    },
    heroSubtitle: {
      color: theme.colors.textDim,
      lineHeight: 18,
      fontSize: 13,
      flexShrink: 1,
    },
    heroVisualShell: {
      width: 68,
      height: 68,
      borderRadius: 22,
      backgroundColor: theme.colors.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.colors.primaryAlt,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.18,
      shadowRadius: 14,
      elevation: 4,
    },
    heroFacet: {
      position: 'absolute',
      width: 20,
      height: 20,
      borderRadius: 8,
      transform: [{ rotate: '45deg' }],
    },
    heroFacetPrimary: {
      top: 14,
      backgroundColor: theme.colors.primary,
    },
    heroFacetAccent: {
      left: 15,
      bottom: 16,
      backgroundColor: theme.colors.accent,
    },
    heroFacetAlt: {
      right: 15,
      bottom: 16,
      backgroundColor: theme.colors.auroraMid,
    },
    heroFooter: {
      gap: 10,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
      padding: 10,
    },
    statsRow: {
      flexDirection: 'row',
      gap: 8,
    },
    heroActionsRow: {
      flexDirection: 'row',
      gap: 8,
      flexWrap: 'wrap',
    },
    heroPrimaryAction: {
      flexGrow: 1,
      minWidth: 124,
    },
    heroSecondaryAction: {
      flexGrow: 1,
      minWidth: 124,
    },
    heroActionHint: {
      color: theme.colors.textDim,
      lineHeight: 18,
      fontSize: 12,
    },
    timelineHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-end',
      gap: 12,
    },
    timelineHeaderCopy: {
      flex: 1,
    },
    timelineHeaderActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    timelineCountPill: {
      borderRadius: theme.borderRadii.pill,
      paddingHorizontal: 9,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
      alignSelf: 'flex-start',
    },
    timelineCountLabel: {
      color: theme.colors.text,
      fontSize: 11,
      fontWeight: '700',
    },
    recentLimitHint: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
      marginTop: -4,
    },
    spotlightCard: {
      gap: 12,
      overflow: 'hidden',
    },
    spotlightHeader: {
      gap: 4,
    },
    spotlightSubtitle: {
      color: theme.colors.textDim,
      fontSize: 13,
      lineHeight: 18,
    },
    spotlightRow: {
      flexDirection: 'row',
      gap: 8,
      flexWrap: 'wrap',
    },
    spotlightTile: {
      flex: 1,
      minWidth: 96,
      gap: 4,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
      paddingVertical: 10,
      paddingHorizontal: 10,
    },
    spotlightTileFeatured: {
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.surface,
    },
    spotlightTilePressed: {
      opacity: 0.96,
      transform: [{ scale: 0.992 }],
    },
    spotlightLabel: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    spotlightValue: {
      color: theme.colors.text,
      fontSize: 16,
      lineHeight: 20,
      fontWeight: '700',
    },
    spotlightHint: {
      color: theme.colors.textDim,
      fontSize: 11,
      lineHeight: 15,
    },
    statChip: {
      flex: 1,
      gap: 2,
      borderRadius: 12,
      paddingVertical: 8,
      paddingHorizontal: 9,
      backgroundColor: theme.colors.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    statLabel: {
      color: theme.colors.textDim,
      fontSize: 10,
      lineHeight: 13,
    },
    statValue: {
      fontSize: 15,
      lineHeight: 18,
      fontWeight: '700',
    },
    sectionLabel: {
      color: theme.colors.textDim,
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    sectionHint: {
      color: theme.colors.textDim,
      marginTop: -2,
    },
    filterRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    searchCard: {
      gap: 12,
      backgroundColor: theme.colors.surface,
    },
    primaryControlsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 12,
      flexWrap: 'wrap',
    },
    primaryActionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    resultCount: {
      color: theme.colors.textDim,
      fontSize: 12,
      fontWeight: '600',
    },
    inlineActionButton: {
      borderRadius: theme.borderRadii.pill,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
    },
    inlineActionButtonActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary,
    },
    inlineActionButtonText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    inlineActionButtonTextActive: {
      color: theme.colors.background,
    },
    activeFiltersRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 8,
    },
    filterGroup: {
      gap: 8,
    },
    filterGroupLabel: {
      color: theme.colors.textDim,
      fontSize: 12,
      fontWeight: '600',
    },
    filterButton: {
      borderRadius: theme.borderRadii.pill,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
    },
    filterButtonActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary,
    },
    filterButtonLabel: {
      color: theme.colors.textDim,
      fontSize: 12,
      fontWeight: '600',
    },
    filterButtonLabelActive: {
      color: theme.colors.background,
    },
    clearFiltersButton: {
      alignSelf: 'flex-start',
      borderRadius: theme.borderRadii.pill,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
    },
    clearFiltersButtonText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    filterSheetRoot: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(7, 11, 28, 0.35)',
    },
    filterSheetBackdrop: {
      flex: 1,
    },
    filterSheetCard: {
      gap: 14,
      borderTopLeftRadius: theme.borderRadii.xl,
      borderTopRightRadius: theme.borderRadii.xl,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderBottomWidth: 0,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 28,
    },
    filterSheetHeader: {
      gap: 10,
    },
    filterSheetHandle: {
      alignSelf: 'center',
      width: 42,
      height: 5,
      borderRadius: 999,
      backgroundColor: theme.colors.border,
    },
    filterSheetBody: {
      gap: 14,
      paddingBottom: 8,
    },
    filterSheetScroll: {
      maxHeight: 460,
    },
    dreamHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    dateBadge: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 50,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
      paddingVertical: 7,
      paddingHorizontal: 8,
    },
    dateBadgeFeatured: {
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.surface,
    },
    weekday: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    dayNumber: {
      fontSize: 18,
      lineHeight: 21,
      fontWeight: '700',
    },
    month: {
      color: theme.colors.textDim,
      fontSize: 11,
    },
    dreamHeaderCopy: {
      flex: 1,
      gap: 5,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    title: {
      fontSize: 17,
      lineHeight: 22,
      fontWeight: '700',
      flex: 1,
      includeFontPadding: false,
    },
    moodDot: {
      width: 10,
      height: 10,
      borderRadius: 999,
    },
    timestampRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 6,
    },
    timestamp: {
      color: theme.colors.textDim,
      fontSize: 11,
    },
    moodPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: theme.borderRadii.pill,
      paddingVertical: 3,
      paddingHorizontal: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
    },
    moodPillText: {
      color: theme.colors.text,
      fontSize: 11,
      fontWeight: '600',
    },
    previewPanel: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
      paddingVertical: 9,
      paddingHorizontal: 10,
    },
    previewAccent: {
      width: 3,
      borderRadius: 999,
    },
    preview: {
      color: theme.colors.textDim,
      flex: 1,
      lineHeight: 18,
      fontSize: 13,
    },
    dreamFooterRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 10,
      flexWrap: 'wrap',
    },
    statePills: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      flex: 1,
    },
    statePill: {
      borderRadius: theme.borderRadii.pill,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    statePillText: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
    },
    tags: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      justifyContent: 'flex-end',
    },
    tagPill: {
      borderRadius: theme.borderRadii.pill,
      paddingVertical: 4,
      paddingHorizontal: 8,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    tagOverflowPill: {
      backgroundColor: theme.colors.surfaceAlt,
    },
    tagPillText: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '600',
    },
  });
}
