import { StyleSheet } from 'react-native';
import { fontFamilies } from '../../../theme/fonts';
import { Theme } from '../../../theme/theme';
import { createControlPill, createSoftTile } from '../../../theme/surfaces';
import { getDreamLayout } from '../constants/layout';

export function createHomeScreenStyles(theme: Theme) {
  const layout = getDreamLayout(theme);

  return StyleSheet.create({
    emptyContainer: {
      justifyContent: 'center',
    },
    listContent: {
      padding: theme.spacing.md,
      gap: theme.spacing.sm,
    },
    listHeaderContent: {
      gap: theme.spacing.xs,
    },
    emptyCard: {
      gap: 10,
    },
    skeletonCard: {
      gap: 12,
      padding: 12,
    },
    skeletonHeaderRow: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
    },
    skeletonDateBadge: {
      width: 52,
      height: 56,
      borderRadius: theme.borderRadii.lg,
    },
    skeletonHeaderCopy: {
      flex: 1,
      gap: 8,
    },
    skeletonPreviewBlock: {
      ...createSoftTile(theme),
      gap: 8,
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 10,
    },
    skeletonFooterRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
    },
    dreamCard: {
      gap: 10,
      padding: 12,
    },
    dreamCardVisual: {
      overflow: 'hidden',
      position: 'relative',
    },
    dreamCardStarred: {
      borderColor: `${theme.colors.accent}55`,
    },
    dreamCardGlowLarge: {
      position: 'absolute',
      width: 108,
      height: 108,
      borderRadius: 999,
      top: -26,
      right: -18,
      opacity: 0.9,
    },
    dreamCardGlowSmall: {
      position: 'absolute',
      width: 76,
      height: 76,
      borderRadius: 999,
      bottom: -26,
      left: 26,
      opacity: 0.7,
    },
    dreamCardAccentBar: {
      position: 'absolute',
      left: 12,
      right: 18,
      top: 0,
      height: 3,
      borderRadius: 999,
      opacity: 0.95,
    },
    dreamPressable: {
      borderRadius: theme.borderRadii.xl,
    },
    dreamPressablePressed: {
      transform: [{ scale: 0.992 }],
      opacity: 0.96,
    },
    swipeableContainer: {
      borderRadius: theme.borderRadii.xl,
      overflow: 'hidden',
    },
    swipeActionsContainer: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 8,
    },
    swipeRightActionsContainer: {
      paddingLeft: 8,
    },
    swipeLeftActionsContainer: {
      paddingRight: 8,
    },
    swipeAction: {
      ...createSoftTile(theme),
      width: layout.swipeActionWidth,
      minHeight: layout.swipeActionHeight,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 10,
      borderRadius: theme.borderRadii.md,
    },
    swipeEditAction: {
      backgroundColor: theme.colors.surfaceAlt,
    },
    swipeDeleteAction: {
      backgroundColor: theme.colors.primaryAlt,
      borderColor: theme.colors.primaryAlt,
    },
    swipeArchiveAction: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },
    swipeUnarchiveAction: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    swipeActionText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.text,
      textAlign: 'center',
    },
    swipeActionTextInverted: {
      color: theme.colors.background,
    },
    heroCard: {
      gap: 8,
      overflow: 'hidden',
      padding: 14,
      position: 'relative',
      marginBottom: 2,
    },
    heroFrame: {
      justifyContent: 'flex-start',
      gap: 10,
      position: 'relative',
      zIndex: 1,
      paddingBottom: 2,
    },
    heroGlowLarge: {
      position: 'absolute',
      width: 104,
      height: 104,
      borderRadius: 999,
      backgroundColor: theme.colors.auroraMid,
      opacity: 0.1,
      top: -4,
      right: -10,
      zIndex: 0,
    },
    heroGlowSmall: {
      position: 'absolute',
      width: 72,
      height: 72,
      borderRadius: 999,
      backgroundColor: theme.colors.accent,
      opacity: 0.08,
      bottom: 8,
      left: -12,
      zIndex: 0,
    },
    heroTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 18,
      position: 'relative',
      zIndex: 1,
    },
    heroCopy: {
      flex: 1,
      gap: layout.rowGap,
      paddingRight: 10,
      minWidth: 0,
      zIndex: 2,
    },
    heroMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    heroDateRow: {
      marginTop: 2,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    heroPromptCard: {
      ...createSoftTile(theme, {
        tone: 'surface',
        radius: 16,
        paddingVertical: 10,
        paddingHorizontal: 10,
      }),
      marginTop: 4,
      gap: 10,
      position: 'relative',
      zIndex: 3,
      elevation: 2,
    },
    heroPromptHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    heroPromptIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${theme.colors.primary}24`,
      borderWidth: 1,
      borderColor: `${theme.colors.primary}2E`,
    },
    heroPromptCopy: {
      flex: 1,
      gap: 3,
      minWidth: 0,
    },
    heroPromptTitle: {
      color: theme.colors.text,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '700',
    },
    heroPromptDescription: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
    },
    heroPromptActions: {
      gap: 8,
    },
    heroPromptPrimaryAction: {
      width: '100%',
    },
    heroPromptSecondaryAction: {
      width: '100%',
    },
    heroShortcutButton: {
      ...createSoftTile(theme, {
        tone: 'surface',
        radius: 14,
        paddingVertical: 8,
        paddingHorizontal: 10,
      }),
      marginTop: 2,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      maxWidth: '100%',
      position: 'relative',
      zIndex: 3,
      elevation: 2,
    },
    heroShortcutButtonPressed: {
      opacity: 0.94,
      transform: [{ scale: 0.992 }],
    },
    heroShortcutIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${theme.colors.primary}24`,
      borderWidth: 1,
      borderColor: `${theme.colors.primary}2E`,
    },
    heroShortcutCopy: {
      flex: 1,
      gap: 1,
      minWidth: 0,
    },
    heroShortcutLabel: {
      color: theme.colors.textDim,
      fontSize: 10,
      lineHeight: 13,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.45,
    },
    heroShortcutTitle: {
      color: theme.colors.text,
      fontSize: 13,
      lineHeight: 17,
      fontWeight: '700',
    },
    heroShortcutMeta: {
      color: theme.colors.textDim,
      fontSize: 11,
      lineHeight: 15,
    },
    heroShortcutIcon: {
      color: theme.colors.accent,
    },
    heroEyebrow: {
      color: theme.colors.accent,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.7,
      textTransform: 'uppercase',
    },
    heroDateChip: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingHorizontal: 9,
        paddingVertical: 5,
      }),
    },
    heroDateChipLabel: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    heroStreakChip: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingHorizontal: 9,
        paddingVertical: 5,
      }),
    },
    heroStreakChipMilestone: {
      backgroundColor: `${theme.colors.auroraMid}22`,
      borderColor: `${theme.colors.auroraMid}44`,
    },
    heroStreakChipText: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    heroStreakChipTextMilestone: {
      color: theme.colors.auroraMid,
    },
    heroTitle: {
      fontFamily: fontFamilies.display,
      fontSize: 24,
      lineHeight: 28,
      fontWeight: '700',
      flexShrink: 1,
      includeFontPadding: false,
    },
    heroSubtitle: {
      color: theme.colors.textDim,
      lineHeight: 18,
      fontSize: 13,
      flexShrink: 1,
      maxWidth: '100%',
    },
    heroVisualShell: {
      width: 44,
      height: 44,
      borderRadius: 13,
      backgroundColor: 'rgba(28, 34, 53, 0.82)',
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.colors.primaryAlt,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 3,
      marginTop: 4,
      marginRight: 4,
      zIndex: 1,
    },
    heroFacet: {
      position: 'absolute',
      width: 16,
      height: 16,
      borderRadius: 6,
      transform: [{ rotate: '45deg' }],
    },
    heroFacetPrimary: {
      top: 10,
      backgroundColor: theme.colors.primary,
    },
    heroFacetAccent: {
      left: 11,
      bottom: 12,
      backgroundColor: theme.colors.accent,
    },
    heroFacetAlt: {
      right: 11,
      bottom: 12,
      backgroundColor: theme.colors.auroraMid,
    },
    heroFooter: {
      gap: 8,
    },
    timelineHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
    },
    timelineHeaderCopy: {
      flex: 1,
    },
    timelineHeaderActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 0,
    },
    timelineCountPill: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingHorizontal: 9,
        paddingVertical: 5,
      }),
      alignSelf: 'flex-start',
    },
    timelineCountLabel: {
      color: theme.colors.text,
      fontSize: 11,
      fontWeight: '700',
    },
    recentLimitHint: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
      marginTop: -4,
    },
    spotlightCard: {
      gap: 7,
      overflow: 'hidden',
    },
    spotlightHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    spotlightHeaderCopy: {
      flex: 1,
      gap: 3,
    },
    spotlightHeaderHint: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
    },
    spotlightLeadRow: {
      gap: 6,
    },
    spotlightSupportRow: {
      flexDirection: 'row',
      gap: 7,
      flexWrap: 'wrap',
    },
    spotlightTile: {
      ...createSoftTile(theme),
      gap: 3,
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    spotlightTileLead: {
      minWidth: '100%',
      paddingVertical: 10,
      paddingHorizontal: 12,
    },
    spotlightCompactTile: {
      flex: 1,
      minWidth: 132,
      gap: 3,
    },
    spotlightTileFeatured: {
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.surface,
    },
    spotlightTilePressed: {
      opacity: 0.96,
      transform: [{ scale: 0.992 }],
    },
    spotlightCueHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
      flexWrap: 'wrap',
    },
    spotlightCueBadge: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 5,
        paddingHorizontal: 8,
      }),
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderColor: `${theme.colors.accent}55`,
      backgroundColor: `${theme.colors.accent}14`,
    },
    spotlightCueBadgeText: {
      color: theme.colors.accent,
      fontSize: 10,
      lineHeight: 13,
      fontWeight: '700',
    },
    spotlightLabel: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    spotlightValue: {
      color: theme.colors.text,
      fontSize: 18,
      lineHeight: 22,
      fontWeight: '700',
    },
    spotlightCompactValue: {
      color: theme.colors.text,
      fontSize: 16,
      lineHeight: 20,
      fontWeight: '700',
    },
    spotlightHint: {
      color: theme.colors.textDim,
      fontSize: 11,
      lineHeight: 15,
    },
    weeklyPatternsSection: {
      gap: 8,
    },
    weeklyPatternsHeader: {
      gap: 3,
    },
    weeklyPatternsSubtitle: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
    },
    weeklyPatternsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
    },
    weeklyPatternCard: {
      ...createSoftTile(theme),
      flexGrow: 1,
      flexBasis: '47%',
      minWidth: 146,
      gap: 4,
      paddingVertical: 10,
      paddingHorizontal: 11,
    },
    weeklyPatternCardAccent: {
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.surfaceAlt,
    },
    weeklyPatternLabel: {
      color: theme.colors.textDim,
      fontSize: 10,
      lineHeight: 13,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    weeklyPatternTitle: {
      color: theme.colors.text,
      fontSize: 16,
      lineHeight: 20,
      fontWeight: '700',
    },
    weeklyPatternHint: {
      color: theme.colors.textDim,
      fontSize: 11,
      lineHeight: 15,
    },
    spotlightActionHint: {
      color: theme.colors.accent,
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '700',
      marginTop: 2,
    },
    spotlightCueActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      marginTop: 3,
    },
    sectionLabel: {
      color: theme.colors.textDim,
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    sectionHint: {
      color: theme.colors.textDim,
      marginTop: -2,
    },
    filterRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    searchCard: {
      gap: 8,
      paddingVertical: 10,
      paddingHorizontal: 12,
    },
    searchBarRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
    },
    searchCardHeaderRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    searchFieldContainer: {
      flex: 1,
      gap: 4,
    },
    searchFieldInput: {
      paddingVertical: 10,
      minHeight: 0,
    },
    controlSection: {
      gap: 8,
    },
    controlCard: {
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
    },
    controlSectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
      flexWrap: 'wrap',
    },
    searchDetailsToggleRow: {
      alignItems: 'flex-start',
      marginTop: -2,
    },
    searchDetailsToggleButton: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 6,
        paddingHorizontal: 10,
      }),
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    primaryControlsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 10,
      flexWrap: 'wrap',
    },
    primaryActionsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
      marginTop: -2,
    },
    controlSectionDivider: {
      height: 1,
      backgroundColor: theme.colors.border,
      opacity: 0.65,
    },
    sortControlBlock: {
      gap: 8,
    },
    resultCount: {
      color: theme.colors.textDim,
      fontSize: 12,
      fontWeight: '600',
    },
    inlineActionButton: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 6,
        paddingHorizontal: 10,
      }),
    },
    inlineActionButtonActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary,
    },
    inlineActionButtonText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    inlineActionButtonTextActive: {
      color: theme.colors.background,
    },
    activeFiltersRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 8,
    },
    emptyActionsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 8,
    },
    searchPresetHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
      flexWrap: 'wrap',
    },
    searchPresetLabel: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    searchPresetSaveButton: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 5,
        paddingHorizontal: 9,
      }),
    },
    searchPresetSaveButtonText: {
      color: theme.colors.text,
      fontSize: 11,
      fontWeight: '700',
    },
    searchPresetRow: {
      flexDirection: 'row',
      gap: 8,
      paddingRight: 4,
    },
    filterGroup: {
      gap: 6,
    },
    filterGroupGrid: {
      flexDirection: 'row',
      gap: 10,
      flexWrap: 'wrap',
    },
    filterGroupGridItem: {
      flex: 1,
      minWidth: 148,
    },
    filterGroupLabel: {
      color: theme.colors.textDim,
      fontSize: 12,
      fontWeight: '600',
    },
    filterGroupMetaLabel: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '600',
    },
    filterSelectionBlock: {
      gap: 8,
    },
    filterButton: {
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 6,
        paddingHorizontal: 10,
      }),
    },
    filterButtonActive: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.primary,
    },
    filterButtonLabel: {
      color: theme.colors.textDim,
      fontSize: 12,
      fontWeight: '600',
    },
    filterButtonLabelActive: {
      color: theme.colors.background,
    },
    clearFiltersButton: {
      alignSelf: 'flex-start',
      ...createControlPill(theme, {
        tone: 'surface',
        paddingVertical: 6,
        paddingHorizontal: 10,
      }),
    },
    clearFiltersButtonText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    filterEmptyText: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
    },
    filterMoreButton: {
      alignSelf: 'flex-start',
      paddingVertical: 4,
    },
    filterMoreButtonText: {
      color: theme.colors.accent,
      fontSize: 12,
      fontWeight: '700',
    },
    filterSheetRoot: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: `${theme.colors.ink}59`,
    },
    filterSheetBackdrop: {
      flex: 1,
    },
    filterSheetCard: {
      gap: 10,
      borderTopLeftRadius: theme.borderRadii.xl,
      borderTopRightRadius: theme.borderRadii.xl,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderBottomWidth: 0,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 24,
    },
    filterSheetHeader: {
      gap: 8,
    },
    filterSheetHeaderActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    filterSheetHandle: {
      alignSelf: 'center',
      width: 42,
      height: 5,
      borderRadius: 999,
      backgroundColor: theme.colors.border,
    },
    filterSheetBody: {
      gap: 12,
      paddingBottom: 8,
    },
    filterSheetScroll: {
      maxHeight: 460,
    },
    filterAdvancedMeta: {
      color: theme.colors.textDim,
      fontSize: 11,
      fontWeight: '600',
    },
    dreamHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    dateBadge: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 50,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
      paddingVertical: 7,
      paddingHorizontal: 8,
    },
    dateBadgeFeatured: {
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.surface,
    },
    weekday: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    dayNumber: {
      fontSize: 18,
      lineHeight: 21,
      fontWeight: '700',
    },
    month: {
      color: theme.colors.textDim,
      fontSize: 11,
    },
    dreamHeaderCopy: {
      gap: 4,
    },
    dreamHeaderCopyExpanded: {
      flex: 1,
      minWidth: 0,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    title: {
      fontSize: 17,
      lineHeight: 22,
      fontWeight: '700',
      flex: 1,
      includeFontPadding: false,
    },
    moodDot: {
      width: 10,
      height: 10,
      borderRadius: 999,
    },
    lucidityGlyph: {
      color: theme.colors.accent,
      fontSize: 10,
      lineHeight: 14,
      includeFontPadding: false,
    },
    headerMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
      minHeight: 24,
    },
    headerMetaHint: {
      color: `${theme.colors.textDim}CC`,
      fontSize: 11,
      lineHeight: 15,
    },
    timestampRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 6,
    },
    timestamp: {
      color: theme.colors.textDim,
      fontSize: 11,
    },
    moodPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: theme.borderRadii.pill,
      paddingVertical: 3,
      paddingHorizontal: 8,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
    },
    moodPillText: {
      color: theme.colors.text,
      fontSize: 11,
      fontWeight: '600',
    },
    signalRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    signalChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: theme.borderRadii.pill,
      borderWidth: 1,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    signalChipText: {
      fontSize: 10,
      fontWeight: '700',
    },
    previewPanel: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 10,
      borderRadius: 18,
      borderWidth: 1,
      paddingVertical: 10,
      paddingHorizontal: 10,
    },
    previewAccent: {
      width: 4,
      borderRadius: 999,
    },
    previewContent: {
      flex: 1,
      gap: 7,
      minWidth: 0,
    },
    previewHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      flexWrap: 'wrap',
    },
    previewLabelPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: theme.borderRadii.pill,
      borderWidth: 1,
      paddingVertical: 4,
      paddingHorizontal: 8,
      alignSelf: 'flex-start',
    },
    previewLabelText: {
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    previewAudioIcon: {
      alignSelf: 'flex-start',
      marginTop: 2,
    },
    previewAccentPrimary: {
      backgroundColor: theme.colors.primary,
    },
    preview: {
      color: theme.colors.textDim,
      flex: 1,
      lineHeight: 18,
      fontSize: 13,
    },
    previewTranscript: {
      fontStyle: 'italic',
    },
    dreamFooterRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      flexWrap: 'wrap',
    },
    statePills: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      flex: 1,
    },
    matchReasonsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    matchReasonPill: {
      ...createControlPill(theme, {
        tone: 'background',
        paddingVertical: 4,
        paddingHorizontal: 8,
      }),
      borderColor: theme.colors.accent,
    },
    matchReasonPillText: {
      color: theme.colors.text,
      fontSize: 10,
      fontWeight: '700',
    },
    statePill: {
      borderRadius: theme.borderRadii.pill,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceAlt,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    statePillText: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '700',
    },
    tags: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      justifyContent: 'flex-end',
    },
    tagPill: {
      borderRadius: theme.borderRadii.pill,
      paddingVertical: 4,
      paddingHorizontal: 8,
      backgroundColor: `${theme.colors.primary}10`,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    tagOverflowPill: {
      backgroundColor: theme.colors.surfaceAlt,
    },
    tagPillText: {
      color: theme.colors.textDim,
      fontSize: 10,
      fontWeight: '600',
    },
  });
}
