import { StyleSheet } from 'react-native';
import { fontFamilies } from '../../../theme/fonts';
import { Theme } from '../../../theme/theme';
import { hexToRgba } from '../../../theme/color';

export function createWakeEntryScreenStyles(theme: Theme) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: theme.colors.background,
      overflow: 'hidden',
    },
    glowTop: {
      position: 'absolute',
      width: 320,
      height: 320,
      borderRadius: 999,
      top: -112,
      right: -84,
      backgroundColor: theme.colors.auroraMid,
      opacity: 0.16,
    },
    glowLeft: {
      position: 'absolute',
      width: 240,
      height: 240,
      borderRadius: 999,
      left: -72,
      bottom: 140,
      backgroundColor: theme.colors.accent,
      opacity: 0.14,
    },
    glowBottom: {
      position: 'absolute',
      width: 260,
      height: 260,
      borderRadius: 999,
      right: -64,
      bottom: -48,
      backgroundColor: theme.colors.primaryAlt,
      opacity: 0.12,
    },
    content: {
      flex: 1,
      paddingHorizontal: theme.spacing.xl,
      paddingTop: theme.spacing.lg,
      paddingBottom: theme.spacing.xl,
      justifyContent: 'space-between',
      gap: theme.spacing.xl,
    },
    topBar: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    closeButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: hexToRgba(theme.colors.surfaceElevated, 0.92),
      borderWidth: 1,
      borderColor: hexToRgba('#FFFFFF', 0.08),
    },
    closeButtonPressed: {
      opacity: 0.78,
      transform: [{ scale: 0.98 }],
    },
    main: {
      flex: 1,
      justifyContent: 'space-between',
      gap: theme.spacing.xl,
    },
    hero: {
      gap: theme.spacing.md,
      paddingTop: theme.spacing.lg,
    },
    eyebrow: {
      color: theme.colors.accent,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1.1,
      textTransform: 'uppercase',
    },
    title: {
      fontFamily: fontFamilies.display,
      fontSize: 38,
      lineHeight: 44,
      letterSpacing: -0.7,
      fontWeight: '700',
      maxWidth: 280,
    },
    description: {
      color: theme.colors.textDim,
      fontSize: 18,
      lineHeight: 27,
      maxWidth: 320,
    },
    actionDeck: {
      gap: theme.spacing.md,
      paddingBottom: theme.spacing.sm,
    },
    primaryActionCard: {
      gap: theme.spacing.md,
      borderRadius: 28,
      paddingVertical: 18,
      paddingHorizontal: 18,
      backgroundColor: theme.colors.primary,
      borderWidth: 1,
      borderColor: hexToRgba('#FFFFFF', 0.08),
      shadowColor: theme.colors.glow,
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.2,
      shadowRadius: 30,
      elevation: 8,
    },
    primaryActionCardPressed: {
      opacity: 0.92,
      transform: [{ scale: 0.992 }],
    },
    primaryActionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.md,
    },
    primaryActionIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: hexToRgba(theme.colors.ink, 0.12),
    },
    primaryActionCopy: {
      flex: 1,
      gap: 2,
    },
    primaryActionTitle: {
      color: theme.colors.ink,
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '800',
    },
    primaryActionHint: {
      color: hexToRgba(theme.colors.ink, 0.72),
      fontSize: 14,
      lineHeight: 20,
    },
    primaryActionMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.xs,
    },
    primaryActionMetaChip: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: hexToRgba(theme.colors.ink, 0.12),
    },
    primaryActionMetaLabel: {
      color: theme.colors.ink,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700',
    },
    secondaryActions: {
      gap: theme.spacing.sm,
    },
    actionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.md,
      borderRadius: 18,
      paddingVertical: 12,
      paddingHorizontal: 14,
      backgroundColor: hexToRgba(theme.colors.surfaceElevated, 0.92),
      borderWidth: 1,
      borderColor: hexToRgba('#FFFFFF', 0.08),
    },
    actionCardPressed: {
      opacity: 0.86,
      transform: [{ scale: 0.992 }],
    },
    actionCardIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: hexToRgba(theme.colors.accent, 0.12),
      borderWidth: 1,
      borderColor: hexToRgba(theme.colors.primary, 0.12),
    },
    actionCardCopy: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    actionCardTitle: {
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '700',
      color: theme.colors.text,
    },
    actionCardHint: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
    },
  });
}
