import { StyleSheet } from 'react-native';
import { fontFamilies } from '../../../theme/fonts';
import { Theme } from '../../../theme/theme';
import { hexToRgba } from '../../../theme/color';

export function createWakeEntryScreenStyles(theme: Theme) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: theme.colors.background,
      overflow: 'hidden',
    },
    glowTop: {
      position: 'absolute',
      width: 320,
      height: 320,
      borderRadius: 999,
      top: -112,
      right: -84,
      backgroundColor: theme.colors.auroraMid,
      opacity: 0.16,
    },
    glowLeft: {
      position: 'absolute',
      width: 240,
      height: 240,
      borderRadius: 999,
      left: -72,
      bottom: 140,
      backgroundColor: theme.colors.accent,
      opacity: 0.14,
    },
    glowBottom: {
      position: 'absolute',
      width: 260,
      height: 260,
      borderRadius: 999,
      right: -64,
      bottom: -48,
      backgroundColor: theme.colors.primaryAlt,
      opacity: 0.12,
    },
    content: {
      flex: 1,
      paddingHorizontal: theme.spacing.xl,
      paddingTop: theme.spacing.lg,
      paddingBottom: theme.spacing.xl,
      justifyContent: 'space-between',
      gap: theme.spacing.xl,
    },
    topBar: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    closeButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: hexToRgba(theme.colors.surfaceElevated, 0.92),
      borderWidth: 1,
      borderColor: hexToRgba('#FFFFFF', 0.08),
    },
    closeButtonPressed: {
      opacity: 0.78,
      transform: [{ scale: 0.98 }],
    },
    main: {
      flex: 1,
      justifyContent: 'center',
      gap: theme.spacing.xxl,
    },
    hero: {
      gap: theme.spacing.sm,
      alignItems: 'center',
    },
    eyebrow: {
      color: theme.colors.accent,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1.1,
      textTransform: 'uppercase',
      textAlign: 'center',
    },
    title: {
      fontFamily: fontFamilies.display,
      textAlign: 'center',
      fontSize: 34,
      lineHeight: 40,
      letterSpacing: -0.7,
      fontWeight: '700',
    },
    description: {
      textAlign: 'center',
      color: theme.colors.textDim,
      fontSize: 17,
      lineHeight: 24,
      maxWidth: 320,
    },
    stage: {
      alignItems: 'center',
      gap: theme.spacing.lg,
    },
    orbStage: {
      width: 252,
      height: 252,
      alignItems: 'center',
      justifyContent: 'center',
    },
    haloOuter: {
      position: 'absolute',
      width: 244,
      height: 244,
      borderRadius: 122,
      backgroundColor: hexToRgba(theme.colors.auroraMid, 0.16),
      borderWidth: 1,
      borderColor: hexToRgba('#FFFFFF', 0.05),
    },
    haloInner: {
      position: 'absolute',
      width: 206,
      height: 206,
      borderRadius: 103,
      backgroundColor: hexToRgba(theme.colors.accent, 0.12),
      borderWidth: 1,
      borderColor: hexToRgba('#FFFFFF', 0.06),
    },
    orbPressable: {
      width: 176,
      height: 176,
      borderRadius: 88,
      alignItems: 'center',
      justifyContent: 'center',
    },
    orbSurface: {
      width: 176,
      height: 176,
      borderRadius: 88,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: hexToRgba('#FFFFFF', 0.09),
      backgroundColor: hexToRgba(theme.colors.surfaceElevated, 0.96),
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.colors.glow,
      shadowOffset: { width: 0, height: 20 },
      shadowOpacity: 0.22,
      shadowRadius: 30,
      elevation: 9,
    },
    orbPressablePressed: {
      opacity: 0.92,
      transform: [{ scale: 0.985 }],
    },
    orbAura: {
      position: 'absolute',
      width: 134,
      height: 134,
      borderRadius: 67,
      backgroundColor: hexToRgba(theme.colors.auroraMid, 0.16),
      top: -16,
      right: -6,
    },
    orbAuraSecondary: {
      position: 'absolute',
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: hexToRgba(theme.colors.accent, 0.14),
      left: -20,
      bottom: -16,
    },
    kaleidoscopeCluster: {
      width: 92,
      height: 92,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: theme.spacing.sm,
    },
    kaleidoscopeFacet: {
      position: 'absolute',
      width: 34,
      height: 34,
      borderRadius: 12,
      transform: [{ rotate: '45deg' }],
    },
    kaleidoscopeFacetPrimary: {
      top: 12,
      backgroundColor: theme.colors.primary,
    },
    kaleidoscopeFacetAccent: {
      left: 16,
      bottom: 16,
      backgroundColor: theme.colors.accent,
    },
    kaleidoscopeFacetAlt: {
      right: 16,
      bottom: 16,
      backgroundColor: theme.colors.auroraMid,
    },
    orbLabel: {
      fontSize: 15,
      fontWeight: '700',
      letterSpacing: 0.1,
    },
    orbHint: {
      color: theme.colors.textDim,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
      maxWidth: 260,
    },
    actions: {
      gap: theme.spacing.md,
    },
    alternateLabel: {
      color: theme.colors.textDim,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      textAlign: 'center',
    },
    actionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.md,
      borderRadius: 18,
      paddingVertical: 12,
      paddingHorizontal: 14,
      backgroundColor: hexToRgba(theme.colors.surfaceElevated, 0.92),
      borderWidth: 1,
      borderColor: hexToRgba('#FFFFFF', 0.08),
    },
    actionCardPressed: {
      opacity: 0.86,
      transform: [{ scale: 0.992 }],
    },
    actionCardIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: hexToRgba(theme.colors.accent, 0.12),
      borderWidth: 1,
      borderColor: hexToRgba(theme.colors.primary, 0.12),
    },
    actionCardCopy: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    actionCardTitle: {
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '700',
      color: theme.colors.text,
    },
    actionCardHint: {
      color: theme.colors.textDim,
      fontSize: 12,
      lineHeight: 17,
    },
  });
}
