# R8 rules for release builds.
#
# Deliberately short. React Native, Sentry and the other libraries ship their own
# consumer rules inside their AARs, so repeating them here would only create a
# second copy to go stale. Anything added below has to earn its place by being
# something that demonstrably broke, with a note saying what.

# Keep stack traces readable after shrinking.
#
# R8 renames classes and drops line numbers, which turns every Sentry report into
# a list of `a.b.c` frames with no line to point at. These two attributes cost a
# small amount of size and are the difference between a crash report that can be
# acted on and one that cannot. `renamesourcefileattribute` collapses the
# original file names to a single token, so keeping the line table does not hand
# the source layout back out.
#
# Symbolication also needs the mapping file R8 writes to
# `app/build/outputs/mapping/release/mapping.txt`. It is regenerated by every
# build and has to be uploaded with the release, or these attributes buy nothing.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
